### ISSUE TITLE
Add reviewers

### ISSUE THREAD

**Issue by mkj28** [dependabot/feedback#10]
Would be nice to be able to specify default reviewers for each repo.

**Comment by greysteil** [comment]
Sounds sensible to me - I've done the groundwork [here](https://github.com/dependabot/dependabot-core/commit/678a042e1b97abcb280818791bc4c78ee61bd1eb) and will add a command to Dependabot this evening. Thanks for the feedback!

**Comment by greysteil** [comment]
Deployed and documented in the `Dependabot commands and options` details object that is included on all new PRs. Thanks for the feedback!

**Comment by mkj28** [comment]
Thanks @greysteil !! As far as process works - when / how does it show up on https://app.dependabot.com/accounts/ourcompany/repos ?

**Comment by greysteil** [comment]
I opted for making it a comment option on PRs instead - it won't show up in the Dependabot dashboard for now, but hopefully that's OK as it will be pretty obvious from the PRs what it's doing.

The process is:
- Tag a reviewer in a PR
- Comment `@dependabot use these reviewers` on that PR
- Dependabot will comment in confirming that from now on it will tag those reviewers

Does the above work for you?

**Comment by mkj28** [comment]
YEAH!
