### ISSUE TITLE
Add 'monthly' option to scheduler

### ISSUE THREAD

**Issue by olimart** [dependabot/feedback#10]
Some projects are less active than others. In this case, 'monthly refresh' is enough.

**Comment by greysteil** [comment]
Is there are downside to these projects using `weekly` instead?

**Comment by olimart** [comment]
Not really, just too much noise, especially for gems defined in non-production groups

**Comment by Shuunen** [comment]
Yep please add monthly :)

**Comment by greysteil** [comment]
Done!

**Comment by Shuunen** [comment]
Great thx ! :+1:
