### ISSUE TITLE
Open source plans ?

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#101]
Hi, it seems like for open source plans, we are limited to a single project : am i right ?

Thank you in advance for your feedback.

**Comment by greysteil** [comment]
You should be able to add as many repos as you like - ping me more details if there’s something I’m missing!

**Comment by adriens** [comment]
Thanks a lot, hence i'll let you know if i do encounter any issue on limitation.
Thanks a lot for these great news.

**Comment by mike-north** [comment]
@greysteil what about open-source orgs? I've set up dependabot for personal repos, but can't seem to find where I'd update the bot's github access so it can see OSS repos in orgs I'm an admin of

**Comment by greysteil** [comment]
@mike-north to give Dependabot access to OSS repos in a org you're and admin of you'll need to install it on that org (for free, of course). You can do so from the "add account" link in the Dependabot menu (drop-down in the top-right of your Dependabot dashboard), or alternatively can do so directly from https://github.com/apps/dependabot/installations/new.

(We don't control GitHub's UI on this one, and it can be really confusing - sorry about that. It looks like they've recently changed things and made them even more confusing - I'll get in touch with them and try to make this clearer.)

**Comment by mike-north** [comment]
@greysteil this totally solved my problem. Thanks! FWIW I wasn't able to find my way to this screen through either Github or Dependabot's UI. The "add account" link in the Dependabot UI takes me to

https://github.com/marketplace/dependabot which is less helpful than the link you provided

**Comment by greysteil** [comment]
Awesome! Yeah, unfortunately the /apps like is only really relevant for free accounts, as it bypasses the marketplace. I’m trying to work with GitHub on improving the main flow - we’ll get there!
