### ISSUE TITLE
Batch add project

### ISSUE THREAD

**Issue by tristanbes** [dependabot/feedback#101]
Hello,

I got 200 private repository, and 180 of them has the same pattern (= they are js project).

I don't want to spend 2 days manually enable dependabot for each repositories. Would you please provide an UI option to batch enable dependabot for multiple repositories please ?

**Comment by greysteil** [comment]
Super up for this, but it'll take me a while. In the meantime, if you email me the repo names I’ll add them from a console on my side.

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#424
