### ISSUE TITLE
Custom label

### ISSUE THREAD

**Issue by geonu** [dependabot/feedback#102]
We want adding our custom label by rule. like [this](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

**Comment by greysteil** [comment]
No problem! If you comment `@dependabot use this label` or `@dependabot use these labels` on a Dependabot PR that's labeled the way you want it, Dependabot will start using those labels for PRs of that type. Will that do what you need?

**Comment by greysteil** [comment]
Or are you saying you'd like Dependabot to automatically label the status of it's PRs? I'm not sure we've got enough information to do that, but if you can give me some examples I'll have a think about it.

**Comment by geonu** [comment]
@greysteil oh.. thank you ! :) 👍
