### ISSUE TITLE
Escape @-mentions in release notes and commit summaries

### ISSUE THREAD

**Issue by novemberborn** [dependabot/feedback#104]
Many projects mention contributors in their release notes, some even in commit summaries. Since they're included in the pull requests this means these contributors are notified by GitHub, which is rather annoying. Could you escape these so they do link to the GitHub profile, but GitHub won't send notifications?

Example: https://github.com/y1ngyang/bigfive-web/pull/10

It doesn't look like `bot` users can be blocked, except maybe if I report abuse, which seems unfair but might be necessary.

Thanks!

**Comment by greysteil** [comment]
Good shout - will do!

**Comment by greysteil** [comment]
Just pushed [this fix](https://github.com/dependabot/dependabot-core/commit/875f481c41086634d93b7585ca383ed4c58b1182). Sorry about that!

**Comment by novemberborn** [comment]
Wow, thanks for the rapid turnaround @greysteil!
