### ISSUE TITLE
Support for non-standard Dockerfile names

### ISSUE THREAD

**Issue by bsedat** [dependabot/feedback#105]
We build a few flavors of a docker image from a single repository using multiple Dockerfiles, so it would be nice to be able to customize the name of the Dockerfile that should be updated.

**Comment by greysteil** [comment]
Definitely :+1: on this - I’ll have a look at adding an option to specify the filename in the next couple of days.

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#428
