### ISSUE TITLE
Auto-merge minor and Patch

### ISSUE THREAD

**Issue by Incognito** [dependabot/feedback#106]
For some know stable and commonly used projects we merge once it's green in ci.

For example, typescript types, lodash, awssdk, etc...

However I run dependant on nearly 20 repos and my day usually includes a stage where I just merge all of these things because they updated so often 

Can I whitelist deps that can auto-merge? Not sure what to do with regards to the approval process but at least that gives me an option.

**Comment by greysteil** [comment]
Thanks for the feedback! Have you seen the auto-merge options I added last week? There's a blog post [here](https://dependabot.com/blog/automatic-pull-request-merging).

In future I'd like to expand this to allow you to specify particular dependencies for automerging, but perhaps not for a little while.

**Comment by Incognito** [comment]
Thanks @greysteil great feature, I didn't see it but I'm going to turn it on.

Thanks from me and my team!
