### ISSUE TITLE
Support for Hex.pm private packages 

### ISSUE THREAD

**Issue by fertapric** [dependabot/feedback#107]
Dependabot seems to not work when the `mix.exs` file of an Elixir project contains private packages (i.e. `{:my_private_package, "~> 1.0", organization: "acme"}`). [Private packages have been officially released quite recently (after some months of beta)](https://hex.pm/blog/organizations-going-live). It would be nice if an organization key could be configured in the "Config variables" settings.

Here is more information on private packages: https://hex.pm/docs/private

**Comment by greysteil** [comment]
Totally 👍 on adding this, and it looks pretty straightforward. I'll have a go now and get back to you.

**Comment by greysteil** [comment]
@stevedomin can I get your help with this one? It looks to me like the hex method we want to piggy-back off of is [here](https://github.com/hexpm/hex/blob/f778cf542135bad733b9a964c67f1fd0cabb7216/lib/mix/tasks/hex.ex#L142-L155) and I've created a starter branch [here](https://github.com/dependabot/dependabot-core/pull/311).

**Comment by greysteil** [comment]
I've added a backend and frontend to the Dependabot app, so it's just the PR mentioned above that needs finishing for this to all work. Let me know if/when you have a chance to look at it @stevedomin.

Thanks for the feedback @fertapric.

**Comment by greysteil** [comment]
FYI, this will ship today. Sorry for the delay!

**Comment by greysteil** [comment]
Shipped! :shipit:

**Comment by fertapric** [comment]
Awesome! Thanks @greysteil!

**Comment by greysteil** [comment]
You're welcome - keen to see Dependabot's Elixir support continue to improve. 🙂

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#430
