### ISSUE TITLE
Allow selecting merge strategy in auto-merge

### ISSUE THREAD

**Issue by dmitry-timofeev** [dependabot/feedback#107]
## Overview
It would be great to be able to set up a merge strategy for the auto-merge feature, so that the merge strategy that the bot uses matches the one that is normally used in the repository.

I'd like to be able to set up this option for the whole repository, so that any automatic merges use the same strategy.

**Comment by greysteil** [comment]
Hey @dmitry-timofeev, thanks for giving Dependabot a try.

We already adjust to any setting you've made disallowing certain merge styles in GitHub, but you can also set it at the account level from your dashboard - it's in the dropdown menu at the top right under settings.

This is definitely one we could move down to the per-repo level if it would make a difference to people, but so far everyone's been pretty happy having it at the top level.

Hopefully that solves this one?

**Comment by dmitry-timofeev** [comment]
I see, found it, thank you!

We have several projects in the organization, each uses its own merge strategy (depending on the team working on it). The ones that are enabled in the bot use the same though, so the setting at the account level will work for us unless some repository requires distinct merging strategy.

**Comment by greysteil** [comment]
Awesome. Get back to me if/when you need this setting at the repo level - I'm not opposed to it, just don't want to add it until there's an actual need. 🙂
