### ISSUE TITLE
Feature Request: Set target branch

### ISSUE THREAD

**Issue by simlu** [dependabot/feedback#110]
Would be great if we could specify the merge target branch. Right now I'm assuming it's the default branch configured in github.

Use case here is that we have staging. The master branch is still our default that displays on the github page. However merges happen into a staging branch first and are then propagated using git-ally (gally) and ci.

**Comment by greysteil** [comment]
You can! 🎉

Annoyingly, you have to specify it when you add an update config - you can't edit it later. It's in the "advanced options" in the "add language" dialogue.

**Comment by simlu** [comment]
Sweet! Another reason why a config file would be super handy (all config in one place). Thank you very much! Really love this project!

**Comment by RichardDavies** [comment]
@greysteil 	It's not obvious that the target branch can only be set upon creation because when you edit an existing language/directory the setting appears to be editable, but any changes are not saved to it. At first I thought this was a bug until I stumbled upon your comment above.

**Comment by greysteil** [comment]
That comment is old  - editing it should be working. Can you give me the URL of the screen it's not working on?

**Comment by RichardDavies** [comment]
https://app.dependabot.com/accounts/eGovPDX/projects/81291

**Comment by greysteil** [comment]
Sorry for the delay digging into this - I was on holiday the last few days.

I've checked that update config in our backend and there's nothing invalid about it, so my hunch is that this is connected to the CORS issue you opened at https://github.com/dependabot/feedback/issues/646. Can you confirm that you're seeing a CORS error for this request?
