### ISSUE TITLE
Add ability to scan dev-requirements.txt for python project

### ISSUE THREAD

**Issue by liiight** [dependabot/feedback#111]
A common pattern for python projects is to hold dev-requirements.txt for dev dependencies. It would be great to support this file as well.

**Comment by greysteil** [comment]
Dependably should be automatically picking up any file with `requitements` in its name, or in a directory with that name - is it not?

**Comment by liiight** [comment]
Oops, my bad. It's working as expected. Sorry for the false report...

**Comment by greysteil** [comment]
No worries! Always feel free to get in touch!
