### ISSUE TITLE
Bug: Automatic merge after adding a commit fails

### ISSUE THREAD

**Issue by sloria** [dependabot/feedback#114]
I added a commit to a dependabot branch to fix a compatibility issue then added the `@dependabot merge` comment so that it would get automatically merged after tests passed.

https://github.com/sloria/jrnl-parse/pull/5

However, the PR did not automatically get merged--I had to manually merge the PR.

Not a huge deal--just thought I'd report the bug.

**Comment by greysteil** [comment]
Ah, good catch. Dependabot is listening for webhooks from GitHub telling it when CI passes, but it's only listening for hooks which reference the original commit SHAs 🤦‍♂️. I'll get that fixed.

**Comment by greysteil** [comment]
Now fixed - thanks for the bug report!
