### ISSUE TITLE
Python: scan for requirements in setup.py

### ISSUE THREAD

**Issue by sloria** [dependabot/feedback#116]
It would be great if Dependabot were able to bump dependencies declared in setup.py, i.e. `setup_requires` and `extras_require`.

**Comment by greysteil** [comment]
Dependabot *should* be doing this already - the relevant parsing code is [here](https://github.com/dependabot/dependabot-core/blob/master/helpers/python/lib/parser.py#L53-L125) (and yes, OMG it's ugly). Is there a repo you're running it on where they're not being picked up?

**Comment by greysteil** [comment]
(Sometimes we fail at the parsing stage here, or for Pipenv at the updating stage. I've got a plan to fix that at the updating stage, and am happy to keep whacking moles at the parsing stage if/when they come up.)

**Comment by sloria** [comment]
Ah, my bad. I thought I had enabled Dependabot on a project using setup.py with pinned requirements but I hadn't. After I enabled, it does seem to be working.

Sorry for the noise.

**Comment by greysteil** [comment]
No worries - these are my favourite bug reports! 😉
