### ISSUE TITLE
Support for HCL (Terraform Modules and Providers)

### ISSUE THREAD

**Issue by osterman** [dependabot/feedback#118]
## what
* Open PRs against terraform repos when terraform modules have new releases
* Open PRs against terraform repos when terraform providers have new releases

## why
* It's an extremely diverse ecosystem with many modules
* We have [100+ terraform modules](https://github.com/cloudposse/?q=terraform-) and keeping them up to date is a nightmare. Anyone doing a lot with Terraform will have the same problem.

## examples
* https://github.com/cloudposse/terraform-aws-cloudfront-cdn/blob/master/main.tf#L2
* https://www.terraform.io/docs/configuration/providers.html#provider-versions

**Comment by greysteil** [comment]
Interesting, and looks like this wouldn't be too difficult. I'm crunching through a bunch of maintenance tasks this week and next, have shipped Go last week, but will take a look at this once that's done.

Is there any concept of version resolution for terraform files (like in Bundler)?

**Comment by osterman** [comment]
@greysteil not that I've been able to find so far. It's a big gap in the terraform ecosystem. 

One of our [community members](https://slack.cloudposse.com) created [this script](https://gist.github.com/mike-zipit/fa936438c1edbb5f26ba68eec1cffaf8), but it's in bash. It does more than just update versions, but perhaps serves as a starting point to see how to do it.

**Comment by osterman** [comment]
Also, there's an official registry site now for Terraform: https://registry.terraform.io, but don't know if it will be of much help.

There are a few ways to specify versions in terraform which may complicate it. 

I think you could roll this out in phases. 

1. First support git remotes (biased as this is most important to us and possibly the easiest to implement)
2. Support `version` parameter

I'll happily provide all the technical guidance, so don't hesitate to ask questions. 

## method 1

This is the original method. It uses git URIs. 

```
module "rds_cluster_aurora_postgres" {
  source             = "git::https://github.com/cloudposse/terraform-aws-rds-cluster.git?ref=master"
}
```

I think you would check if `ref` looks like a semver, you would update it.

## method 2

This method uses the terraform registry. This method is perhaps more straight forward, but not universally used since it was only recently introduced.

```
module "consul" {
  source  = "hashicorp/consul/aws"
  version = "0.0.5"
}
```

## references
- <https://www.terraform.io/docs/modules/usage.html#module-versions>

**Comment by osterman** [comment]
This feature was discussed today in our "Town Hall" meeting (slack.cloudposse.com). Concensus was "gimme"! =)

https://cloudposse.com/meetup/sweetops-town-hall-meeting/

**Comment by greysteil** [comment]
Haha, OK, I've got a relatively clear day today - let's do this!

**Comment by greysteil** [comment]
Moving discussion to https://github.com/dependabot/dependabot-core/pull/648
