### ISSUE TITLE
Configurable mix.exs and lock files

### ISSUE THREAD

**Issue by ConnorRigby** [dependabot/feedback#119]
Projects using [Nerves Framework](https://nerves-project.org/) or possibly [any project](https://hexdocs.pm/mix/Mix.Project.html#module-configuration) aren't able to use dependabot because they expect project file to be `mix.exs` and `mix.lock`

**Comment by greysteil** [comment]
Thanks for the feedback Connor - should be relatively easy for me to fix today.

Would love your advice on a couple of things:
1) Dependabot has a [`required files` check](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_fetchers/elixir/hex.rb#L9-L11) that it does when someone adds a project. It's meant to be a very quick check that this project could possible support the chosen language. Given the configurability of the `mix.exs` and `mix.lock` names, presumably you'd recommend changing that to match any file ending in `.exs`?

2) Currently the [actual fetching](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_fetchers/elixir/hex.rb#L19-L25) requires both a `mix.exs` and a `mix.lock`. Presumably you'd recommend changing that to
  - handle the case when there isn't a lockfile (I noticed that [these examples](https://github.com/nerves-project/nerves_examples/tree/master/hello_leds) don't commit one, for example)
  - look for a file that calls `use Mix.Project` and treat that as the `mix.exs` is currently treated. Is there some way of knowing what the lockfile will be called given the name of the project file?

**Comment by greysteil** [comment]
cc @stevedomin

**Comment by greysteil** [comment]
Update: I've just relaxed the requirement that a lockfile is present for Dependabot to work, as I'm pretty sure that's a requirement here.

**Comment by greysteil** [comment]
@ConnorRigby - would love your feedback on the comments above. I'd really like to make Dependabot work for projects using Nerves.

**Comment by ConnorRigby** [comment]
Thanks for the quick turnaround! I'll give this a try again today

**Comment by greysteil** [comment]
No worries. Happy to keep iterating to get support as close to perfect as possible.
