### ISSUE TITLE
Ruby versions not being taken into account correctly?

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#12]
I've just had a few updates opened up that introduce a dependency on `public_suffix` as part of the update. This is in old Ruby 1.9.3 projects, but this gem requires Ruby 2. This should be blocking the update, but it seems not.

See https://github.com/theodi/panopticon/pull/261 for an example. If I run `bundle update capybara` on the command line, it says:

```
Gem::InstallError: public_suffix requires Ruby version >= 2.0.
An error occurred while installing public_suffix (2.0.5), and Bundler cannot continue.
Make sure that `gem install public_suffix -v '2.0.5'` succeeds before bundling.
```

That's not exactly a great error message, but bundler doesn't perform the update, unlike dependabot. The ruby version is specified in the project Gemfile.

**Comment by greysteil** [comment]
Interesting, thanks. This one requires a bit of thought on our side, but shouldn't be too tough, and it's definitely a bug.

**Comment by greysteil** [comment]
Quick update: we're working on this, but there's an underlying bug in Bundler. We should have it patched in the next day or so.

**Comment by greysteil** [comment]
This should be fixed now - [this PR](https://github.com/theodi/panopticon/pull/266) is proof (the buggy old version generated [this one](https://github.com/theodi/panopticon/pull/249)).

🎉

**Comment by Floppy** [comment]
Brilliant, thanks :)
