### ISSUE TITLE
Adding new dependencies to PR for Major version bump [PHP]

### ISSUE THREAD

**Issue by tobybellwood** [dependabot/feedback#120]
Hi - thanks for the work on Dependabot, we've been putting it through it's paces over the last couple of weeks.

One behaviour I'm keen to understand is how a new Major version that introduces a brand new dependency would get PR'd

in https://github.com/tobybellwood/govcms-composer-test/blob/master/composer.json I currently have

> "drupal/workbench_moderation": "1.4",

The 3.0 release of this library introduced a brand-new dependency on "drupal/drafty".  How would Dependabot handle that situation - would it

a) update the lockfile with both new packages, or 
b) would it not submit a PR, because it can't update two packages at once?

If b, would this behaviour be similar for dependencies that can be updated alongside a version bump?  Will Dependabot always only update one package at a time?

**Comment by greysteil** [comment]
Thanks for getting in touch.

Dependabot will update the sub-dependencies of a dependency when it makes updates - it's only top-level dependencies that it creates separate PRs for. As such, the behaviour is (a), which I think is what you'd want?

**Comment by tobybellwood** [comment]
Wow - quick on the reply! I've tried bumping the repo (sorry!!), but can't get it to generate a PR for that module to demo.  This could be because b) is happening, or because I used ignore major on another version of the repo in my account - and the ignore has persisted for my username, not the repo? (https://github.com/tobybellwood/govcms-composer/pull/5)

**Comment by greysteil** [comment]
It won't be the other ignore condition, but it could be that the new version won't resolve for some reason. Does the update work locally? If so I'll need to take a look at Dependabot's PHP resolution logic and check if it's missing something...

**Comment by tobybellwood** [comment]
Thanks, it looks like the PRs have started flowing again. I'll keep an eye out, and try a dry-run in the morning.

**Comment by greysteil** [comment]
👍 

FYI, Dependbot is a bit slow at generating PHP pull requests (from clicking bump now to first PR) because resolution requires that it clones down all the dependencies. (Other package managers do the resolution based solely on metadata from the registry, but Composer doesn't work that way.)

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#443
