### ISSUE TITLE
Add support for monorepos such as DefinitelyTyped

### ISSUE THREAD

**Issue by styfle** [dependabot/feedback#121]
Some projects are published to npm as multiple packages but use a single github repository.

I didn't dig into details to see npm has a way to detect this, but I can tell you how it works for DefinitelyTyped 😄 

Basically, if the package `@types/node` is bumped, I would expect to see a link to commits pointing to [/commits/master/types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/node)

Currently, it links to all commits in the entire repo which is huge as you can see here: [/commits/master](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master)

Is this possible?

**Comment by greysteil** [comment]
This has been sitting in my inbox as a "good question, needs thought" issue for the last week. Finally getting to it now!

**Comment by styfle** [comment]
Thanks for the response!

I see now how tricky this is to make a pattern that will work for any arbitrary monorepo since they all handle publishing differently.

DefinitelyTyped is kind of the exception to most npm packages because they don't deal with JS source code so they don't bother maintaining a bunch of `package.json` files in a `packages` directory.

Maybe you can look at how often Dependabot is updating `@types/*` packages because if it is often, then its probably worth it to add a special case to check the `README.md` for the magic string "Files were exported from".

**Comment by greysteil** [comment]
Yeah, this one is definitely tricky, but I'm not giving up on it yet.

I think there's a bigger problem here that there's currently no way for monorepos to specify the directory that their code lives in in their `package.json`. That affects `react`, `angular`, etc., and is a bit sad. I'm chatting with the npm folks to make sure I'm not missing anything, and will make a proposal to fix it if need be.

**Comment by styfle** [comment]
Yeah I could see that being part of the [repository](https://docs.npmjs.com/files/package.json#repository) field. Something like:

```json
"repository" : {
  "type": "git",
  "url": "https://github.com/DefinitelyTyped/DefinitelyTyped.git",
  "path": "/types/node"
}
```

I found the npm team is pretty good at entertaining ideas.
Did you create an idea on their community page? https://npm.community/c/ideas
Or just tweet at them?

**Comment by greysteil** [comment]
Asked in the discord app ([here](https://discordapp.com/channels/317475976369930241/317477684999487489)). I'll create an idea on the community page if I don't hear back.

**Comment by greysteil** [comment]
FYI, I've created an RFC for npm on this - it's [here](https://github.com/npm/rfcs/pull/19).

**Comment by styfle** [comment]
@greysteil  The RFC has been accepted! Great job! 🎉 🎉 🎉 

Are you able to move forward with implementing this feature in Dependabot?

**Comment by greysteil** [comment]
Yes! Just implemented in [this commit](https://github.com/dependabot/dependabot-core/commit/a22235d399ae95c67903ce294576c95a2928b582). Will need to get each monorepo to convert to the new format, but that should be doable. 🎉
