### ISSUE TITLE
Handle parent version in pom.xml

### ISSUE THREAD

**Issue by mbarre** [dependabot/feedback#122]
Dependabot doesn't check parent version in pom.xml

We use Spring Boot, so the pom.xml is written this way :

```
<project>
...
   <parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.0.3.RELEASE</version>
	<relativePath/> <!-- lookup parent from repository -->
   </parent>
...
</project>
```
Spring Boot just released the 2.0.4.RELEASE, I didn't received any PR.

It should be nice, if you could do it.
Thanks

**Comment by adriens** [comment]
This could be very useful as Spring Boot is widely used....

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/e7de4d5bba558ce4fe7232f10955dceffa11979c.

**Comment by mbarre** [comment]
Great ! I received the PR for spring-boot-starter-parent.
Thanks

**Comment by adriens** [comment]
awesome @greysteil !!! ...and released so fast !!! :clap:

**Comment by adriens** [comment]
Don't forget to add this feature to your feature list, it's really great !!!
