### ISSUE TITLE
PHP composer: dependabot wrongly proposed a downgrade

### ISSUE THREAD

**Issue by tsufeki** [dependabot/feedback#122]
Hi, I've got this PR: https://github.com/tsufeki/kayo-json-mapper/pull/1/files where dependabot suggests I should *downgrade* a requirement `^4.3 -> ^2.0`. I don't think this should happen.

Thank you.

**Comment by greysteil** [comment]
It definitely shouldn't be doing that!

Dependabot finds things a bit harder when you don't have a lockfile committed, as it's trickier for it to figure out what versions you're using. It can definitely do better than this, though - I'll take a look

**Comment by greysteil** [comment]
Thanks for this feedback. I've just pushed [this fix](https://github.com/dependabot/dependabot-core/commit/f4f217023f07177b3f28c3c902c3a201b4701c37), which uses your `composer.json` as a test fixture. I'll run it against your repo to ensure it works as soon as it's deployed, but I'm feeling confident enough to mark this is resolved.

Thanks again for the feedback!

**Comment by tsufeki** [comment]
Thank you.
