### ISSUE TITLE
add an "Only security updates" option for Python

### ISSUE THREAD

**Issue by afeld** [dependabot/feedback#123]
Hello! Interested in adding dependabot to a Python project, but only looking for security updates. [This blog post](https://dependabot.com/blog/automatically-respond-to-security-advisories) indicates that dependabot now "pull[s] security advisory data...for Python", but I'm not seeing the corresponding "Only security updates" filter option when adding a Python project. Thanks!

**Comment by greysteil** [comment]
Ooh, I forgot I needed to flick the switch on that. Done!
