### ISSUE TITLE
Use of composer outdated to shortlist packages for update?

### ISSUE THREAD

**Issue by tobybellwood** [dependabot/feedback#124]
I've been double checking how good dependabot has been at identifying our dependencies over at https://github.com/tobybellwood/govcms-composer-test and tracking it against what I was expecting on my local install using `composer outdated -D`(https://getcomposer.org/doc/03-cli.md#outdated).

For the record:

module|installed|latest|description
-----|-----|-----|-----
drupal/accessible\_forms|1.0.0-alpha1|1.0.0-alpha2|This is a simple Drupal 7 module for adding form attributes for improved accessibility.
drupal/ctools|1.12.0|1.14.0|A library of helpful tools by Merlin of Chaos.
drupal/date|2.9.0|2.10.0|Makes date/time fields available.
drupal/defaultconfig|1.0.0-alpha9|1.0.0-alpha11|Use features as default configuration without having to deal with overriden features.
drupal/linkchecker|1.2.0|1.3.0|Periodically checks for broken links in node types, blocks and fields and reports the results.
drupal/media|2.13.0|2.16.0|Provides the core Media API
drupal/metatag|1.21.0|1.25.0|Adds support and an API to implement meta tags.
drupal/workbench\_moderation|1.4.0|3.0.0|Provides content moderation services
drupal/zen|5.5.0|6.4.0|Zen sub-themes are the ultimate starting themes for Drupal 7. Read the <a href="https://drupal.org/node/873778">online docs</a> or the included README-...
drush/drush|8.1.16|9.2.3|Drush is a command line shell and scripting interface for Drupal, a veritable Swiss Army knife designed to make life easier for those of us who spend s...

This brought me back to a comment from #120 (and subsequently digging a bit through the code)

> (Other package managers do the resolution based solely on metadata from the registry, but Composer doesn't work that way.)

I just assumed you were running composer outdated at some point to get the shortlist of potential updates to iterate through - but it looks like you're grabbing the list another way?

Also - is there a way to report what versions we currently have asked Dependabot to ignore (and potentially un-ignore them?)

**Comment by greysteil** [comment]
OK, I've just had a dig into this and I think Dependabot is doing the right thing here:
- By default, Dependabot doesn't try to update subdependencies (I can turn that on for you if you'd like, though)
- The other dependencies on that list don't appear to be resolvable at their latest version. Try running `composer update drupal/date`, for example, and you'll find that composer can't install the 2.10 version.

Given the above I'm going to close this, but let me know if I'm missing anything!

**Comment by tobybellwood** [comment]
FYI - I tracked down the problem with drupal/date - it requires drupal/date_api (one of the modules that it packages as a submodule, so updates automatically)...
https://cgit.drupalcode.org/date/tree/date.info?id=7.x-2.10#n3
```
name = Date
description = Makes date/time fields available.
dependencies[] = date_api
```
Which means they both need to be updated separately at the same time, despite being packaged together 🤦‍♂️

**Comment by greysteil** [comment]
Ack, that's a pain. It's the one thing Dependabot find really tough - situations where two dependencies have to be updated at the same time are fortunately quite rare, but when they do occur Dependabot gets stuck.

We've solved the above problem for Ruby by listening for resolution conflict errors and using them to guide what other dependencies to unlock, but it's *very* involved. I'm not up to doing it for PHP, I don't think!
