### ISSUE TITLE
Scan files for fixme's and notify inside PR

### ISSUE THREAD

**Issue by rolandasb** [dependabot/feedback#124]
There are cases when I have to implement workarounds before new version of a libraries get released. To annotate these, I add comments like this:

```js
// FIXME: Remove event listener after Stimulus 1.1 release.
addEventListener("DOMContentLoaded", () => {
  application.load(definitionsFromContext(context))
})
```

What if dependabot could notify me about this after Stimulus update? For example, I could write something like this...
```js
// @dependabot notify stimulus@1.1.0
addEventListener("DOMContentLoaded", () => {
  application.load(definitionsFromContext(context))
})
```
... and dependabot would add a note inside a PR, that in `app/javascript/packs/application.js#L18` there are code that needs updating.

**Comment by greysteil** [comment]
That would be really cool. It's a little out of reach for Dependabot just yet, and I want to make sure we've got our core functionality nailed before expanding to use cases like the above, but I can see the value of us adding it at some point.

I'm going to close this for now as I can't put the above on the short-term roadmap for Dependabot, but will keep it in mind. Thanks for the feedback!
