### ISSUE TITLE
Did dependabot recently change the email under which it commits?

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#125]
I thought dependabout used to commit as `support@dependabot.com`, e.g:

<img width="436" alt="screen shot 2018-08-02 at 09 36 10" src="https://user-images.githubusercontent.com/8789912/43572474-8fbec908-9637-11e8-9bde-51524a7753d0.png">

Now I think it's changed to `dependabot[bot]@users.noreply.github.com`, e.g:

<img width="1069" alt="screen shot 2018-08-02 at 09 37 04" src="https://user-images.githubusercontent.com/8789912/43572527-b239069c-9637-11e8-825c-485e1e0fa420.png">

Unfortunately this is causing me some issues. We use a tool called [codacy](https://www.codacy.com/) which analyses commits based on the committers email. I had previously added `support@dependabot.com` to our organisation so that codacy was able to analyse the commits. It seems I can no longer do that as codacy won't accept `dependabot[bot]@users.noreply.github.com` as it deems it an invalid address.

As for why I was analysing dependabot commits, well, it came down mostly to workflow. We use github protected branches that require status checks to pass on the PR before it can be merged. We enforced previously that Codacy checks must be green before a merge - in order for the checks to pass on dependabot PR's the commits need to be analysed (which means that dependabot need to be part of our codacy members).

The only workaround I see right now is to turn off the github protected branch setting for enforcing that the checks pass. 

Is there anyway that dependabot can use a valid email address to commit under or am I looking at this the wrong way?

**Comment by greysteil** [comment]
That shouldn't have happened - let me take a look.

**Comment by greysteil** [comment]
Do you have a PR I can look at that's got this issue?

Nothing related to this has changed on our side, so I'm wondering if it's a GitHub issue.

**Comment by davidgoate** [comment]
@greysteil I'm actually wondering if this is a false alarm (sorry).

I see one from today that worked: https://github.com/marshmallow-insurance/uk-auto-quoting/pull/312
And one from today that did not: https://github.com/marshmallow-insurance/uk-auto-quoting/pull/313

The difference between the two is that the latter I think was updated via the GitHub UI's `Update Branch` button and merged via a squash merge (as it has 2 commits) whereas the former was a `merge and rebase` via the GitHub UI. 

I guess therefore this is not dependabot's issue - but I'm still not clear exactly why this happened (e.g. why updating the branch would change what codacy sees as the committers email address) Here's a link to the commit: https://github.com/marshmallow-insurance/uk-auto-quoting/commit/fe44211fecaf0a7601e3dc4c6316e8afafbc482b

**Comment by greysteil** [comment]
I'm not sure what could have happened there either.

One thing worth mentioning is that Dependabot supplies GitHub with the author details to use for its commits (we tell it to use `{ name: "dependabot[bot]", email: "support@dependabot.com" }`), BUT the default email address associated with our bot account, which I believe we're unable to change, is `dependabot[bot]@users.noreply.github.com`. Hence, when Dependabot performs merges for you (if you have automerge switched on) that later email address might show up.

I'll email GitHub and see if it's possible to change  that.

**Comment by msaspence** [comment]
@greysteil did you get any info from GitHub on this, I am also running into this

**Comment by greysteil** [comment]
Sorry, this is quite old now and I'm no longer a developer! Would recommend contacting them directly.
