### ISSUE TITLE
dependabot trying to downgrade gemspec dependency

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#126]
Hi there. Looks like I've got a similar issue to #122 but for a Ruby gem—see [this dependabot PR](https://github.com/JacobEvelyn/friends/pull/195/files). Let me know what I can do to help!

**Comment by greysteil** [comment]
Uh oh, I'll take a look. Since the repo's open source it should be really easy for me to replicate, but I'll let you know if I have any trouble.

Thanks for reporting, and for giving Dependabot a try.

**Comment by JacobEvelyn** [comment]
Thanks!

**Comment by greysteil** [comment]
Should be fixed by https://github.com/dependabot/dependabot-core/commit/8ee9aae4e9dd03d8216899846030d7494ee7e752, which is deploying now.

**Comment by greysteil** [comment]
Fix confirmed. Sorry about that, and thanks for adding Dependabot to friends. I remember reading about it on HackerNews month ago - great project!

**Comment by JacobEvelyn** [comment]
Thanks, I appreciate it @greysteil!
