### ISSUE TITLE
[Bug] Wrong title on PR

### ISSUE THREAD

**Issue by georgemcg** [dependabot/feedback#127]
Recently I got a PR to update a dependency, where the title of the PR was different to the actual dependency being updated.

The title claimed to be updating react from `16.4.1 to 16.4.2`, but was in fact updating from `16.3.1 to 16.4.2`.

As well as being a bit misleading, this spooked me a bit, as not sure if dependabot knows it's not just a patch version for the purposes of automatic PR merging.

<img width="1245" alt="screen shot 2018-08-02 at 12 45 16" src="https://user-images.githubusercontent.com/28559436/43581830-3683fa5a-9652-11e8-87db-8b88e556b9dc.png">

**Comment by greysteil** [comment]
Would you mind just checking what the version is in your lockfile for this update? That's where Dependabot will have been reading the current version from, and whilst it looks from your `package.json` that it should be `16.3.1` I'd like to be sure. Better yet, if you email me a link to the PR then I can dig into it from my side.

**Comment by georgemcg** [comment]
I think as it's a private repo I can't email a link, sorry about that.

Here's another screenshot showing the yarn.lock file, looks like it is 16.3.1 as well.

<img width="1241" alt="screen shot 2018-08-02 at 12 57 11" src="https://user-images.githubusercontent.com/28559436/43582246-af53b032-9653-11e8-84b9-00e6491e4d13.png">

**Comment by greysteil** [comment]
Ah man, that's definitely a bug. Looking at the `yarn.lock` I can see how Dependabot has got confused - you *did* already have React 16.4.1 in the lockfile, but it wasn't the version that corresponded to the requirement in your `package.json`. I'll put together a failing test for this case now, and get it fixed.

**Comment by georgemcg** [comment]
Awesome, thanks!

**Comment by georgemcg** [comment]
Sure sent 😄

**Comment by greysteil** [comment]
Got it. Please leave that PR open whilst I diagnose and fix. 🙂

**Comment by greysteil** [comment]
Ah, I see what's going on here:
- The repo being updated is a monorepo, containing a bunch of different packages
- The repo uses Yarn workspaces, and some of the packages have React at `16.4.1`. The top-level `package.json`, however, has a requirement that pins its version of React to `16.3.1`
- Dependabot is creating a PR to update the top-level package and all sub-level packages to `16.4.2`. In doing so, it's reducing the number of installed React versions from 2 (`16.3.1` and `16.4.1`) to 1 (`16.4.2`)

In the above setup, I think it's right to prioritise whatever version relates to the main `package.json` requirement. I've implemented that [here](https://github.com/dependabot/dependabot-core/commit/df15ca600d7d401e631889b5f07d0892569ad637).

Thanks for the bug report!

**Comment by georgemcg** [comment]
Thanks for the speedy resolution!
