### ISSUE TITLE
Integration with Azure DevOps (previously Visual Studio Team Services)

### ISSUE THREAD

**Issue by gauravhub** [dependabot/feedback#128]
We use Microsoft VSTS Git repositories in our organization. Does dependabot support VSTS or is there any future plans?

**Comment by adriens** [comment]
I don't see the link between IDE and dependabot. I would say that if the IDE has git support, then it supports dependabot. :smile_cat:

**Comment by greysteil** [comment]
VSTS is more than an IDE - it's a source code hosting provider, too.

We do have plans to support more source code hosting providers, starting with GitLab. I hope to have support by the end of the year, although can't promise anything on this one.

**Comment by gauravhub** [comment]
Thanks @greysteil for quick response. Looking forward to support for VSTS Git repositories. Will check again at the end of year.

**Comment by greysteil** [comment]
Awesome - sorry I can't offer support sooner.

**Comment by chris5287** [comment]
@greysteil is there any way that “we” (ie: open source community) could speed up the implementation of other hosting providers? I would love to have VSTS and Bitbucket Server support (both of which have marketplaces), but it looks like the open source community cannot help as the code isn’t in the core repo :(

**Comment by greysteil** [comment]
Thanks for the offer @chris5287.

There's open-source work to be done for both VSTS and Bitbucket - Dependabot Core doesn't work fully with either yet.
- For Bitbucket, what's needed is extension of [this method](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator.rb#L47-L53) and [this method](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_updater.rb#L22-L27). I'm happy to provide guidance on either
- VSTS needs the same as the above, but additionally needs work at the [FileFetcher](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_fetchers/base.rb) and [source](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/source.rb) level. That's likely to be a little tricker to bite off (more touch points), so perhaps best left to me.

Once that's done there's a significant piece of work to be done on the main Dependabot backend, which isn't open source. I think that's a week of my time to add GitLab and then a couple of days for Bitbucket and VSTS. The work I'm doing now on bug fixing and polish should help buy me the time to get to that soon.

**Comment by greysteil** [comment]
There's no reason Dependabot shouldn't be able to support on-prem - Dependabot Core can already do it for GHE 🙂. If you take a look at the `Dependabot::Source` class, basically it works by providing a custom `api_endpoint` and/or `hostname`.

**Comment by greysteil** [comment]
And thanks! 🙏

**Comment by mbernard** [comment]
Can't wait for that feature :D

**Comment by chris5287** [comment]
Example script to run using azure pipelines: https://github.com/chris5287/dependabot-for-azuredevops
