### ISSUE TITLE
Update to the latest minor / patch release if a major bump isn't desired

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#13]
would be good to be able to configure a version constraint as one suggest right now with maven is to update

e.g. Bump org.springframework.boot:spring-boot-starter-parent from 1.5.12.RELEASE to 2.0.2.RELEASE for us would have been great if it was able to suggest `1.5.13` as our code can't support `2.x` yet but `1.x` is fine and desirable.

Should we change our POM syntax from:

```xml
<parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.12.RELEASE</version>
         <relativePath/> <!-- lookup parent from repository -->
     </parent>
```

to use https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN402

```xml
<parent>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-starter-parent</artifactId>
        <version>[1.5.12,2.0)</version>
         <relativePath/> <!-- lookup parent from repository -->
     </parent>
```

I wasn't sure whether I should ignore the `.RELEASE` suffix.

**Comment by greysteil** [comment]
👍 , and thanks for the ping on the PR, too.

You shouldn't need to change your POM syntax for this - it would be better if Dependabot would figure it out automatically if you `@dependabot ignore this major version`, or if it tried to update you to the latest minor before jumping a major. I'll have a look at getting one of those set up, although it's not trivial so might not happen immediately.

Thanks for the feedback!

**Comment by davidgoate** [comment]
@greysteil thanks for the advice, I used `@dependabot ignore this major version` and dependabot closed the PR. However, I then triggered a rebump and it has not suggested an upgrade to the latest version of 1.x. Currently we have `1.5.12.RELEASE` and I was hoping after ignoring the major version it would then suggest on the next rebump the `1.5.13.RELEASE` but this doesn't seem to be the case.

**Comment by davidgoate** [comment]
@greysteil is this on the roadmap. I know maven support is beta. It'd be super useful for us in particular - most of our projects are maven based and there are quite a few alternatives for our JS based projects some of which are free. But this seems to be one of the few that look good with maven support so having this type of support would be really valuable for us. We're about 1/2 way though our trial and so far this is the only real negative for us.

**Comment by greysteil** [comment]
It's absolutely on the roadmap. Which languages are you most interested in it for? For Java I ought to be able to get it done tomorrow. (It's *much* harder for some languages than others.)

**Comment by davidgoate** [comment]
@greysteil just java for us!

**Comment by greysteil** [comment]
OK, this is done and deployed for Java. (I tested it against one of your repos, noticed a bug, and fixed it - sorry for the incorrect 2.0.0.RELEASE pull request generated.)

Please do let me know how you get on with this. I'm going to keep it Java-only initially to check the flow doesn't confuse anyone, but assuming it doesn't I'll roll it out to other languages.

Thanks for the feedback!

**Comment by davidgoate** [comment]
@greysteil thanks, we will give it a try. I forced a bump just now on 5 repos and on one of those it was worked while the others continue to show the 2.x version. How should this work, should I go to each PR and ask `@dependabot to ignore the major version` and then ask for a re-bump manually at which point it'll suggest the latest 1.x version?

**Comment by greysteil** [comment]
Yes exactly - once Dependabot knows you’re avoiding a version it will generate PRs for lower ones
