### ISSUE TITLE
Add option for minor/major updates

### ISSUE THREAD

**Issue by Shuunen** [dependabot/feedback#13]
It could be nice to have less notifications like "hey update xyz from 1.12.1 to 1.12.2" and another one after with "ok I closed  1.12.1 to 1.12.2 but now you can 1.12.1 to 1.12.3" ... etc and this for each dependancy...

It would be nice to set what kind of update we want. 

According to http://semver.org/ we could specify to update on MAJOR, MINOR or PATCH

**Comment by greysteil** [comment]
Would the approach in https://github.com/dependabot/feedback/issues/11#issuecomment-310036053 work for you?

**Comment by Shuunen** [comment]
Yes totally :)

**Comment by greysteil** [comment]
Perfect - I'm going to close this as a duplicate. I'm really keen to get #11 working at some point.
