### ISSUE TITLE
Feature Request: Auto Merge Upon Approval

### ISSUE THREAD

**Issue by osterman** [dependabot/feedback#130]
## what
* Merge after PR approval

## why
* We require an approval on all PRs

**Comment by greysteil** [comment]
Interesting. Is there a reason the person giving the approval wouldn't click merge?

You've probably seen that at the moment Dependabot comments on the PR if it's been asked to auto-merge but GitHub permissions prevent it from doing so. I think doing this would mean losing that comment, which might make the auto-merge behaviour unclear for some folks (I think most people expect it to not require approval).

**Comment by osterman** [comment]
>  Is there a reason the person giving the approval wouldn't click merge?

We usually have the person opening the PR, merge the PR. 

This leads to my follow up request, to have dependabot merge and tag a new patch release. =)

e.g. https://github.com/cloudposse/testing.cloudposse.co/releases

**Comment by greysteil** [comment]
Sorry for the slow reply - got dragged into another couple of things.

I've just shipped a solution to https://github.com/dependabot/feedback/issues/138, which I think fixes this, too. If you comment `@dependabot merge` when approving a pull request the bot will get it done for you.

One tagging a new patch release, I'm afraid that's a little beyond humble Dependabot for now! I'd suggest having a look at probot or similar to build a bespoke automation bot to do that.

Thanks again for the feedback - hopefully the change to listen for messages in approval commands gives you what you need?

**Comment by osterman** [comment]
@greysteil I will check it out. Thanks!
