### ISSUE TITLE
Markdown formatting breaking

### ISSUE THREAD

**Issue by davidwessman** [dependabot/feedback#130]
Hello, thank you for a great project!

When Bulma was update to 0.7.0 the release notes broke Dependabots own text.
Might be because Bulma did some bad things with their table and perhaps there is no way for Dependabot to handle that.

https://github.com/pensionsupplysning/web/pull/213

<img width="810" alt="screen shot 2018-04-16 at 07 28 11" src="https://user-images.githubusercontent.com/6763624/38791404-c314cb3a-4147-11e8-9de8-6216a9f49ab8.png">

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/571ed0152813af8f7241409ee47b5655276222b7, which is deploying now. Thanks again - this one's a big like whack-a-mole, so if you see anything similar again please do let me know!

**Comment by davidwessman** [comment]
Amazing response time :+1:
I'll definitely get back to you if I find anything else :)
