### ISSUE TITLE
Dependabot automerge doesn't work for some updates

### ISSUE THREAD

**Issue by drewpterry** [dependabot/feedback#131]
I enabled auto-merge functionality on all of my repos with the "all patches" or "minor updates" option selected.

Currently, it works some updates are merged automatically but some that I think should be merged automatically are not.

For example Dependabot threw a PR for:
`Bumps pry-doc from 0.13.3 to 0.13.4.`
with 100% compatibility and all tests passing.

Given my settings I would expect this to be auto-merged. Could I get some clarification why this isn't merged?

**Comment by greysteil** [comment]
FYI, I've just shipped an update to the frontend so that it reads `PRs to merge automatically (post 1.0.0)` when you enable automerging. I'll look at adding a note to the PR description, too.

Thanks for reporting this, and for using Dependabot!

**Comment by drewpterry** [comment]
Got it! Thanks for the super quick response. I actually think I remember reading that note and I just forgot about it. Thanks for the clarification.

However, since we are generally using passing tests as the criteria for merging, it seems like that would extend to pre 1.0.0 versions as well (as long as your tests pass, it should be assumed safe to merge). You could probably make the same argument even for major updates potentially. I think it would be interesting to have the option at least.

**Comment by greysteil** [comment]
Agreed, and I'm going to add a lot more options around automerging in the near future. A couple of people have suggested they'd only like the automerges to happen during working hours, for example.

Watch this space!
