### ISSUE TITLE
Composer: changed ssh github URLs to https

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#131]
Bit of a strange one. We had a composer update a few days ago  that changed the github URLs of unrelated packages from `git@github.com:` style to `https://github.com/` style. The ssh urls were still the same in the composer.json file. Any ideas why that might have happened?

**Comment by greysteil** [comment]
Ah, that does sound like something we'd do. It's related to how Composer deals with credentials for git repos, but I *think* we might be able to avoid the change now. Let me test and get back to you. Nudge me if I don't get to in this week.

**Comment by greysteil** [comment]
@Floppy - any chance you could ping me the URL of the PR? You can email support@dependabot.com if you don't want to put it here.

**Comment by greysteil** [comment]
Now fixed - sorry about this one!
