### ISSUE TITLE
Can't get it to work because of private repo

### ISSUE THREAD

**Issue by cabello** [dependabot/feedback#132]
Hi 👋 , I just started a trial and I am trying to get Dependabot to work with a Ruby/Rails project, we use Sidekiq pro. I configured the Config Variables to the same setup I have in my local and production but it did not work.

> Dependabot couldn't authenticate with gems.contribsys.com.
> You can provide authentication details in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'.

What else can I do to debug, understand what's going on?

Thanks

**Comment by greysteil** [comment]
Oh, sorry about that. We dont offer much self serve debugging for config variables, but I’ll take a look when I’m at my computer and get this fixed for you

**Comment by cabello** [comment]
Just a moment... I may have a typo in the address.

**Comment by cabello** [comment]
🤦‍♂️ it was my mistake, all good for now, thanks for the prompt reply ❤️

**Comment by greysteil** [comment]
Haha, perfect - had just got to my computer!
