### ISSUE TITLE
[question] ignore package names or wildcards

### ISSUE THREAD

**Issue by christopherthielen** [dependabot/feedback#133]
Some packages I want to keep at a specific version. I'd rather not receive PRs for these packages. Is it currently possible?

**Comment by greysteil** [comment]
Absolutely - if you comment @dependabot ignore this dependency then Dependabot will close the PR and not bother you about that dependency again (unless you update it yourself). Will that work for you?

**Comment by christopherthielen** [comment]
Answered: https://github.com/dependabot/dependabot-core/issues/353#issuecomment-382803114
