### ISSUE TITLE
Add labels for major, minor and patch bumps for better filtering

### ISSUE THREAD

**Issue by caiofbpa** [dependabot/feedback#134]
Scenario: We have lots of (50+) dependency updates.

Given that:
- A patch bump is non-brainer merge if all tests pass.
- A minor bump is easy to merge given all tests pass and a quick check on the release notes.
- A major bump is very likely to break tests or require changes in client code.

It would be really handy if we could filter the bumps by `major`, `minor` and `patch`, which would be possible if they were labeled as so.

This way we could merge first the easy patch bumps, then the minor ones, and leave the major bumps to when we have time to update our client code.

This could also be a nice addition for auto-merge, as most people would want to auto-merge patch or minor bumps but never a major bump (even if all tests pass).

**Comment by greysteil** [comment]
Sorry for the slow reply on this. I think it makes a tonne of sense, I'm just thinking through the best way to do it.

I'm not sure everyone would want `minor`, `major` and `patch` labels applied to their PRs (mainly because those labels don't make sense stand-alone). However, it would be pretty straightforward for me to check if you've got those labels declared on your side and use them if you do. What do you reckon?

**Comment by caiofbpa** [comment]
I would be happy with creating the labels and dependabot using them if they exist.

But I also have some suggestions for alternatives:

1. Make the labels be `patch-dependency-bump`, `minor-dependency-bump` and `major-dependency-bump`, so they make sense standalone, and maybe they can be the default for everyone.

2. Make this labelling optional in dependabot settings page.

3. Add an option to `@dependabot use these labels` command. Something like: `@dependabot use these labels for patch bumps`, so you don't have to guess the appropriate label names for each bump level.

**Comment by greysteil** [comment]
OK, to get things started I've just shipped https://github.com/dependabot/dependabot-core/commit/fb3d263054ecf4bf0602968f4c3526453c1fbe98, which will use the `major`, `minor`, `patch` labels if all three already exist on a repo. If you create the labels in your repo then Dependabot should start including them on PRs. 🎉

I'm going to mark this as resolved given the above, but wouldn't be too surprised if we revisit later.

**Comment by greysteil** [comment]
Out of interest, are you planning to automate something based on this? Looking at the work I had to do to add it I'm slightly wondering whether it is, in fact, more complicated than it needs to be. Dependabot already puts the updated and previous versions into the PR title - is a quick scan of those not enough? I'm tempted to remove this if so - feels kinda imperfect and I don't like that. 🤔

**Comment by caiofbpa** [comment]
Thanks @greysteil! 🌷

I don't plan on doing any automation for the foreseeable future, our use case is really being able to filter out PRs based on the semver change level so we can manually merge first the easy ones.

We were doing the "filtering" manually, going through all PRs and spotting the patch and minor ones, and giving preference to those, which is quite tedious work when you have 50+ dependency PRs (which I think is quite common in modern React apps). I've added the labels to our main repos and will be using this feature for the next couple of weeks. I can provide feedback on that later.

Keep up the good work! 💪

**Comment by greysteil** [comment]
👍 - let me know how you get on, and I'll keep thinking on whether there's something better we could do.

**Comment by oliikit** [comment]
👋 resurfacing this conversation... from a visualization standpoint, this feature would still be helpful for us. We had some PRs not properly tested from going to a major version, didn't look closely enough at the changes, and we had some things break. So this visual cue will hopefully aid in that.

If we were to do any automation, we'd probably have patch (possibly minor) versions automatically merged if it passed tests.

**Comment by greysteil** [comment]
Are you using the feature? It’s still in the product as described above

**Comment by hipstersmoothie** [comment]
Is there any option to configure the patch, minor, and major labels? i use those labels for calculating semver bumps on my projects

**Comment by RohanNagar** [comment]
From above:

> I've just shipped dependabot/dependabot-core@fb3d263, which will use the major, minor, patch labels if all three already exist on a repo. If you create the labels in your repo then Dependabot should start including them on PRs. 🎉

**Comment by hipstersmoothie** [comment]
I understand that. I have want to be able to configure them.

I use [auto](https://github.com/intuit/auto) to release my projects. It uses the semver labels to calculate a version bump. I'm trying to set auto up with dependabot for all it's dep management, but need to be able to configure this.

It's also a problem for people who use auto:

1. security vuln reported GitHub wide
2. dependabot makes PR with `major` label
3. Person running project with auto hits "merge" and accidently causes a major release of their project.

**Comment by caiofbpa** [comment]
@greysteil I'm using this feature for months now and it's very useful for us. Being able to filter which bumps are `patch` and `minor` is very useful in figuring out an update plan when there are lots of bumps.

**Comment by oliikit** [comment]
@greysteil - I was going to open up an issue about how dependabot could make major versions more prominent to avoid an accidental major version merged without proper testing. But I found this issue and noticed you had some concerns about additional complexity, so I just wanted to know I'm going to implement it at my organization. I can report back if you'd like further user feedback.

**Comment by greysteil** [comment]
@oliikit sounds good, let me know. Have you already seen Dependabot's own automerge logic?

@hipstersmoothie we don't have plans to make those labels configurable. I'd recommend adding the `skip-release` label to Dependabot PRs if you're using it with `auto` (you probably don't want releases for most version bumps anyway).

@caiofbpa good to hear the effort implementing was worth it! 😄

**Comment by hipstersmoothie** [comment]
The `major` label will still effect the release once a pr without the `skip-release` label is merged. Good idea though!

How about instead the labels being configurable a user could just opt out of those labels all together? That might be easier to implement/maintain. Would you be open to a contribution for such a feature? IDK ruby but I could give it a swing

**Comment by greysteil** [comment]
@hipstersmoothie I'm releasing https://github.com/dependabot/dependabot-core/commit/0ae7e2f18e5b6cbb52ce02c3d1a4b59f722d22de now which will stop Dependabot from using `patch`/`minor`/`major` labels for repos using `auto`.

**Comment by oliikit** [comment]
> Have you already seen Dependabot's own automerge logic?

@greysteil - yup! I think we'll poke about it here soon, but we wanted to vet the PRs coming in first and have a good workflow at handling them. I think we'll probably enable that feature for some repos within the upcoming weeks. We can provide feedback if we run into anything. 😃

**Comment by hipstersmoothie** [comment]
@greysteil thank you so much! <3
