### ISSUE TITLE
Allow to customize a name of branches

### ISSUE THREAD

**Issue by avokhmin** [dependabot/feedback#135]
Hello.

Is possible to add an extra config for project and allow to customize the name of branches?

See: [gcloud functions deploy](
https://cloud.google.com/sdk/gcloud/reference/functions/deploy)

![screen shot 2018-08-14 at 17 14 43](https://user-images.githubusercontent.com/422109/44097093-9e638946-9fe5-11e8-8546-b04cfbc61a7c.PNG)

They forbid to use `/` char in the branches name.

Best regards,
Aleksei

**Comment by greysteil** [comment]
Ah man, that is really annoying. Why would they do that?!?!

I'm sure I can fix that. What an annoying setting to need, though!

**Comment by greysteil** [comment]
Just deployed the backend - if you give me the name of the account you want the prefix changing on then I can do that for you manually in console.

Working on the frontend now.

**Comment by greysteil** [comment]
Front end deployed! Second setting under "Pull request options".

![image](https://user-images.githubusercontent.com/1144873/44107055-183a24ca-9fee-11e8-97e0-266070eefef4.png)

**Comment by avokhmin** [comment]
Wow, so fast, thanks @greysteil !

**Comment by avokhmin** [comment]
@greysteil , is possible to do it per project? Not per account?

![screen shot 2018-08-15 at 10 13 32](https://user-images.githubusercontent.com/422109/44136038-f3268f3a-a073-11e8-98a2-5e0ee8303cae.PNG)

**Comment by greysteil** [comment]
Not for now - is there a particular downside to having it at the account level? I'm all for increased granularity in general, but I thought this one was the least likely to receive requests to move - I've never though the separator mattered to people very much unless it blocked other tools.

**Comment by greysteil** [comment]
And you're welcome! Always looking to improve the product so feedback like this, particularly when it's blocking you using Dependabot, is always welcome 🙂

**Comment by avokhmin** [comment]
Thanks @greysteil 

Yeah, we deploy only few projects to Google cloud. This `/` issue is really strange. I wrote to Google about it, but 0 response 😕 
For all other projects we like to use `/` char in the name, because it helps to use other tools and etc.

**Comment by greysteil** [comment]
My guess is that it just makes their life a little easier with URLs. If others can manage it I don't see why they can't though, and like you said, using a `/` is preferred for other tools.

I'll have a think about moving down to the repo level, but can't promise that in the short term. Longer term I want to introduce an (optional) config file, at which point there'll be no downside to pushing this kind of stuff down to the repo level.

**Comment by mkorszun** [comment]
@greysteil having possibility to configure branch names per project rather than per account has one huge benefit: **you are de-risking breaking other people / teams builds**

Imagine some teams have certain conditional logic based on branch names in their CI/CD pipeline - you do not want break it.

**Comment by pacarvalho** [comment]
Is this setting is still possible now that Dependabot is part of Github?

**Comment by greysteil** [comment]
Sure is, but currently only for Dependabot Preview. We'll add support for it to the GitHub-integrated bot soon, too.

**Comment by pacarvalho** [comment]
That is awesome! We currently use Dependabot through Github (https://help.github.com/en/articles/configuring-automated-security-fixes).

Thank you for the quick reply.

**Comment by phantomwhale** [comment]
Hit this problem with dependabot using `/` in the github branch name, which we then use as part of a docker tag during the build step (and docker tags don't support `/` characters).

Is there any way to override this setting in the Github integrated dependabot? I can't find a setting, but perhaps I'm lacking privileges in my companies set up?
