### ISSUE TITLE
Python: unrecognised options in requirements.txt cause unknown error

### ISSUE THREAD

**Issue by wajeeha-khalid** [dependabot/feedback#135]
Bumping on dependabot does not create Pull Request for my repo.
How to i check status and also reason for why it is happening?

**Comment by greysteil** [comment]
I'm taking a look now. We massively expanded our Java support yesterday, so that kept me a little busy!

**Comment by wajeeha-khalid** [comment]
Sure; no problem :)
I will be waiting.

**Comment by greysteil** [comment]
Could you let me know which version of `pip` are you using locally with this `requirements.txt` file? It looks like `--allow-external` might no longer a valid option in pip 10.

**Comment by greysteil** [comment]
FYI, my code to improve the error is [here](https://github.com/dependabot/dependabot-core/commit/cdd7706e6092b5f3885dadc65a6cee071e0901f1) and is deploying now. It will mean Dependabot creates an issue on your repo when this happens, rather than internally erroring.

Can you let me know whether removing those lines is possible? Don't want to close this until I know it's resolved!

**Comment by wajeeha-khalid** [comment]
Thanks @greysteil  for looking into it.
I have to see thoroughly to confirm if we can remove those lines.
I will have a look and then confirm.
Meanwhile, i have updated my repo with latest code (many new commits) since my last run was on older code.

I am going to run bump again with latest code and meanwhile i will be looking into Pillow library to resolve this run issue.

Will your fix for error reporting be available with my next bump try?

**Comment by greysteil** [comment]
Should be, but the error message won't be hugely inspiring - we don't give details of the exact error that happened on the Dependabot side at the moment. (Although for Python we should - in other languages there are potential credential-sanitization issues, but not Python.)

**Comment by wajeeha-khalid** [comment]
ah! ok and do you know if detailed error reporting for python is in your plan?

FYI i am using `pip 9.0.1`

**Comment by greysteil** [comment]
It certainly is - just a case of when we can get to it. I'll take a quick scan of all errors of this type (requirement file parsing or evaluation) and see if there's any reason we can't start putting the detail in for that category now, at least.

**Comment by wajeeha-khalid** [comment]
That would be great! thanks @greysteil 
FYI, i am looking into if we can update `pip` to `version 10` and then remove those lines for `pillow`.
Will keep you posted too.

**Comment by greysteil** [comment]
Took a look through and discovered there was nothing stopping us adding error details when it's resolvability that Dependabot struggled with. That change is deploying now and will be live in ~ 5 minutes.

Thanks for the push on this one!

**Comment by greysteil** [comment]
Error details should be coming through now, so I'm going to close this. Were you able to upgrade to pip 10?
