### ISSUE TITLE
Listen to approval messages for bot commands

### ISSUE THREAD

**Issue by marcotc** [dependabot/feedback#138]
My current usage pattern for @dependabot-bot is:
```
Inspect PR.
If it looks good, approve it in GitHub.
Ask Dependabot to merge it.
```

It would be great if either of these two things were true:
* Dependabot interprets approved PRs as "ready to merge".
* Dependabot listens to the message inside the approval event, so that we can write `@dependabot merge` in the approval message itself.

**Comment by greysteil** [comment]
(2) is deploying now. Thanks again for the suggestion!
