### ISSUE TITLE
Allow adding custom labels

### ISSUE THREAD

**Issue by asherf** [dependabot/feedback#139]
When we have multiple languages in the same repo (python & JS for example)
it will be useful to customize those in Depandabot so it will add custom labels.
this way we can filter by the dependencies and by the language (custom) label.
also allows adding other tags (team association, for example) across multiple repos.

**Comment by RohanNagar** [comment]
You can add labels to a Dependabot PR, then comment `@dependabot use these labels` on a PR and it will use those labels in the future for that repo and language.

**Comment by asherf** [comment]
ah. good to know.

**Comment by greysteil** [comment]
Thanks @RohanNagar! ❤️
