### ISSUE TITLE
A wrong label is assigned

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#140]
The issues created by Dependabot has a wrong label -- `dependency/spring`. I'm using this label for marking issues that are related to Spring Framework. If Dependabot need some particular label, it should be stated as a requirement in the installation manual. Also, it should be configurable in UI.

Examples:
https://github.com/php-coder/mystamps/pull/936
https://github.com/php-coder/mystamps/pull/937
https://github.com/php-coder/mystamps/pull/938
https://github.com/php-coder/mystamps/pull/939
https://github.com/php-coder/mystamps/pull/940

Thank you!

**Comment by greysteil** [comment]
Ah, oops! Dependabot looks for labels in your repo that includes `dependency` and uses them in place of its own `dependencies` label if they exist, in an attempt to match your style. Obviously its made the wrong decision here! I'll get that fixed.

**Comment by php-coder** [comment]
@greysteil Thank you for the fast reply! How it will work after fix? Do I need to create a dedicated label myself or Dependabot will create it? Or it will create issues without label if it doesn't exist in a repo?

**Comment by greysteil** [comment]
I think the fix here is for Dependabot to explicitly ignore that label when looking at labels users might prefer to Dependabot's default `dependencies` label. Once I've deployed that Dependabot will correctly create a `dependencies` label and start labelling its PRs with that. If you'd prefer it use a different label, or no label at all, you can just label up a Dependabot PR how you'd like it and then comment `@dependabot use these labels`.

**Comment by greysteil** [comment]
The code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/labeler.rb) btw.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/063f67f53be5f2875801edfa19561870de0ca1c4. Thanks for reporting!
