### ISSUE TITLE
Q: How to exclude some dependency from update?

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#141]
I'd like to exclude Spring Boot from automatic updates as I'm updating it manually. Is there a way to get such behavior? Thanks!

**Comment by greysteil** [comment]
Yep! Just comment `@dependabot ignore this dependency` on the relevant Dependabot PR. (There are details of all the commands you can use included in the footer of each PR.)

**Comment by php-coder** [comment]
Yeah, I already found it. Thank you!
