### ISSUE TITLE
Custom Dockerfile name / multiple Dockerfiles per repo

### ISSUE THREAD

**Issue by danmaas** [dependabot/feedback#145]
Hi - I have a repo with a couple of Dockerfiles named something other than "`Dockerfile`", e.g.

```
./Dockerfile-manager
./Dockerfile-webserver
./Dockerfile-backup-agent
```

I would like there to be an option in Dependabot's Docker configuration to specify a custom Dockerfile name.

Also, it would be nice to handle multiple Dockerfiles within a single repo, either by registering them as separate "languages", or by managing them as a group.

**Comment by nesl247** [comment]
I too have multiple in almost all of my repos. We have one for ngoni, pho-fpm, etc.

**Comment by greysteil** [comment]
On easy start here would be for Dependabot to fetch and update all files with the word `dockerfile` in them. I'll implement that now and have it deployed in the next couple of hours.

After that adding support for arbitrary names shouldn't be too tricky. I'll try to get to that today, too.

**Comment by greysteil** [comment]
OK, Dependabot will now update all files with the word `dockerfile` in them (commits are [here](https://github.com/dependabot/dependabot-core/compare/v0.67.1...v0.67.2)).

Are either of you using names that it would miss, given the above? I'll close this if not.

**Comment by nesl247** [comment]
I just use `Dockerfile` in different directories.

**Comment by greysteil** [comment]
Ah cool - Dependabot should already be able to handle that if you just add multiple update configs, one for each language. I *think* that's probably the best long-term solution there - I could set Dependabot up to trawl your repo for any files called Dockerfile, but can see that being the wrong behaviour for some people.

**Comment by nesl247** [comment]
I actually didn't know we could add the same language multiple times. That works for me.

**Comment by greysteil** [comment]
Yeah, I could definitely clean up the UI on that...

@danmaas - does the current change work for you, too?

**Comment by danmaas** [comment]
Yes, a case-insensitive match against `dockerfile` in the filename should work fine.

**Comment by greysteil** [comment]
Awesome - going to close for now, and will revisit if other need even more custom names. Thanks for the feedback!

**Comment by connorshea** [comment]
@greysteil this'd be nice to have documented somewhere :) I almost opened an issue about how to go about setting multiple Dockerfiles in the `config.yml` (I have two Dockerfiles, called `Dockerfile` and `Dockerfile.ci`).

**Comment by greysteil** [comment]
Agreed. I'll have think on where we can put it.

**Comment by hawksight** [comment]
Not sure this is documented [here](), has anyone got an example config, or is it just a case of naming the dockerfiles with the string `dockerfile` in them?
Is it also case sensitive?, so `app.Dockerfile` would not work?
