### ISSUE TITLE
Reduce duplication in a commit message

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#146]
Commit that has been created by Dependabot could have duplicated lines (example: https://github.com/php-coder/mystamps/pull/936/commits/35d9046d39c54ffcf73add5f6b70af60ff16f081):

> Bump maven-failsafe-plugin from 2.19.1 to 2.22.0
> Bumps maven-failsafe-plugin from 2.19.1 to 2.22.0.

I don't see how the 2nd line is useful in this case. Could commit message be improved?

**Comment by greysteil** [comment]
I can see where you're coming from on that one!

Currently the commit message mirrors the GitHub PR title, and then also the first line of the PR (roughly). The relevant code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/message_builder.rb#L154-L175), and it's not *always* a straight duplication, so I'm inclined to keep it how it is...

**Comment by greysteil** [comment]
Closing - I've recently updated the logic to change that first line in cases where it would be longer than 72 characters, so there's less duplication now.
