### ISSUE TITLE
Idea: teach bot about changelogs

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#147]
When bot don't have links to the changelogs, users could teach a bot with a special command. WDYT?

**Comment by php-coder** [comment]
Perhaps, users can also teach a bot that some additional changes is required for update. For example: https://github.com/php-coder/mystamps/pull/944 -- native2ascii plugin was fully-rewritten and configuration has been changed, so it's impossible to just update its version.

**Comment by greysteil** [comment]
Learning how to apply additional changes is on my "very long term" plan for Dependabot. I think it could be awesome, and with enough users I don't see why it shouldn't be possible.

Learning about links to changelogs might be a bit simpler, but often there's something rules-based that Dependabot could be doing better. What repos has it missed?
