### ISSUE TITLE
More error output when a project fails

### ISSUE THREAD

**Issue by TorrentKatten** [dependabot/feedback#149]
When we added a few of our ruby projects they failed, and dependabot gave some useful error output so we could fix it. But one of our Docker builds fails and all we get is:

"
Error bumping dependencies

Dependabot encountered an unknown error.

We've been notified of the problem, and are working to fix it.
"

Sure the error is unknown, but there must be something? 
Or are you that sure that the issue is at your end?

**Comment by greysteil** [comment]
Error message should be a lot clearer now - this was a permissions issue and you can enter credentials in your dashboard. Let me know if you have any trouble!
