### ISSUE TITLE
Support vendoring for Ruby

### ISSUE THREAD

**Issue by biow0lf** [dependabot/feedback#15]
Hello,

I am using vendored gems in vendor/cache/. So, dependabot update gem in Gemfile.lock, but leave old gem file in vendor/cache/. Plus, not put new gem to vendor/cache/.

So, I think, run `bundle pack` and add changed files will enough.

**Comment by greysteil** [comment]
Hmmm, at the moment Dependabot doesn't support vendoring. It would be nice to add it, but I think it's going to be hard to do so performantly - downloading all those dependencies using `bundle package` would take a lot of time on our end. We currently avoid actually doing any installs for Ruby, which keeps things fast (take a look at [dependabot/dependabot-core](https://github.com/dependabot/dependabot-core) for all the gory details), and whilst Dependabot is free that's essential.

One hacky solution would be to append something to your CI run that does the vendoring and commits the change, but that's pretty grim...

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#370
