### ISSUE TITLE
Label Change today

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#151]
Today I got 3 PRs using a new label scheme. Before today, I got PRs from dependabot using the label `Type: Dependencies`, which is the label I would like to be used.

Ex: RohanNagar/thunder#251

Today, I got PRs using the label `dependencies`. It looks like this label was just created.

Ex: RohanNagar/thunder#255, RohanNagar/thunder#256, RohanNagar/thunder#257

Can Dependabot continue to use the custom label I had set?

Also, another (slightly less important) question is can I disable the per-language label? I don't necessarily need it for my workflow.

Thanks!

**Comment by greysteil** [comment]
Ah crap, sorry about that.

On using the incorrect `dependencies` tag, I've just fixed that in https://github.com/dependabot/dependabot-core/commit/69c0ec6a11eccbf6bceab00a5d07adfc0ff6cb68, but you'll also need to delete the `dependencies` label that Dependabot has created for you.

On not using a `js` / other language tag - yes, if you comment `@dependabot use these labels` on a PR having removed that tag then Dependabot won't try to use it for future PRs of that language.

I've been experimenting with the labels that we use, as I think for most users with Dependabot being used for multiple languages tagging them as such makes sense. I didn't mean to affect setups like yours on the `dependencies` label, though - sorry about that!

**Comment by RohanNagar** [comment]
No worries, I really appreciate the quick fix!
