### ISSUE TITLE
Configuring dependabot to rebase smarter?

### ISSUE THREAD

**Issue by peol** [dependabot/feedback#152]
Hi!

Thanks for this project, it has been working great for us in our open source efforts. We are currently running dependabot on 18 repositories in our organization. So now to my thinking:

Right now, when there are multiple pull requests in one repository dependabot rebases _all_ PRs after one has been merged. This triggers _a lot_ of CI builds, increasing the time it takes to get PRs merged.

My thinking was, perhaps it could be an idea for dependabot to target one PR that it rebases first and merges it, picks the next PR and rebases that, and so forth. That would decrease the number of builds needed, and unnecessary rebases on PRs that would need rebasing again.

Perhaps this is possible today, if so, sorry for this issue :)

**Comment by greysteil** [comment]
Hi!

Interesting! I like that idea, but think it might be harder for Dependabot to figure out which PR to target after a merge, and could be noisy for it to communicate it.

Have you seen the option to turn off auto-rebases in your settings? It's here:

![image](https://user-images.githubusercontent.com/1144873/44425613-406dbd80-a584-11e8-9f04-a05ae0e038fb.png)

Would switching the auto-rebases off, and then manually asking for rebases using `@dependabot rebase` work for you?

**Comment by greysteil** [comment]
And finally, thanks for using Dependabot, and particularly for using it on open source repos! :octocat:

**Comment by peol** [comment]
Thanks for the quick reply :)

I saw the settings, but unfortunately turning off auto-rebase would instead introduce _a lot_ of manual overhead but it's certainly an option we might consider. Another "workaround" would be to be allowed to adjust how many open PR:s there can be per repository, so if we could set that to 1, it would probably work as expected as well (unfortunately, the option is hard-coded to either off or 10 open PR:s at a time).

**Comment by greysteil** [comment]
Just had a play around with adding a UI for the number of open PRs allowed and finding it slightly tricky to implement something nice. I've also just implemented the suggestion in #153, which should make working with auto-rebasing switched off less painful.

Would you mind giving things a try with auto-rebase turned off, and report back on how you find it? If it introduces a lot of manual work then I'm more than happy to revisit it, but I think it would be better to wait until you've tried that. Hopefully you shouldn't need too many `@dependabot rebase` commands, but if it gets tedious please do let me know!

**Comment by peol** [comment]
Sorry for the late reply. That sounds like it could work! We'll give that a try and I'll get back to you if we're still getting stuck in a tedious workflow. Thanks again for this project, it's a lifesaver :)

**Comment by gingerlime** [comment]
I bumped into this as well, and somehow it seems like dependabot rebases always, even when there's no conflict?
