### ISSUE TITLE
Create a "rebase on bump" option

### ISSUE THREAD

**Issue by caiofbpa** [dependabot/feedback#153]
Scenario: We have lots of (50+) dependencies, and we have disabled auto-rebase because our CI would be flooded with builds on every bump merge. We have also configured dependabot to run daily bumps at night (3AM) so all builds get plenty of time to run before we get back to work the next day.

Problem: New bumps work great, but old ones that got conflicts need to be rebased manually (by asking dependabot) and we can only do that during business hours.

Solution suggestion: Make a new option `Rebase on bump` that makes dependabot go through all open PRs and rebase them when it's time to bump. In our case, when it runs in the middle of the night, it would not only open new bumps but also rebase the conflicting ones, so when we get back to work the next day, all bump PRs are mergeable.

**Comment by greysteil** [comment]
That's a really great idea. I'm not sure it even needs to be an option - I'm not sure why anyone *wouldn't* want that.

**Comment by caiofbpa** [comment]
I suggested as an option because I'm not sure about other people's use cases, but indeed it makes sense to be the default. If I can also add one more thing: when going through all the PRs, dependabot should relabel them. This would make a `@dependabot use these labels` be applied to old PRs overnight, which is very nice for organising a repo with a lot of dependencies and old PRs.

**Comment by greysteil** [comment]
I'm totally 👍 on that. Pretty easy to implement, so I should have it done in the next day or so.

**Comment by greysteil** [comment]
OK, the `@dependabot use these labels` change is live - it applies immediately to all open PRs when you make a label change.

Working on rebasing open PRs as part of the Dependabot overnight job now.

**Comment by greysteil** [comment]
Overnight rebases are now implemented too, and will happen automatically for any accounts that have automatic rebases disabled - thanks for the feedback!
