### ISSUE TITLE
Allow Custom Regex Patterns and Rules

### ISSUE THREAD

**Issue by matfax** [dependabot/feedback#154]
### Problem
There are various scenarios in which you specify dependency versions in **variables** that are passed over. For instance, Docker meanwhile allows you to reference ARGs in FROMs so that you can pass the dependency versions to the Dockerfile. As another example, there are dependencies that you may define as environment variables in Dockerfiles or shell scripts. Such versions are currently not covered by Dependabot.
### Suggested Approach
1. Allow user-defined file names so that shell scripts and other text-based configs (e.g., config yamls) can be referenced.
2. Allow user-defined semver patterns so that any version can be matched wherever and however they may be defined. Regular Expressions appear convenient for that.
3. Add an optional validator to check if any version bump (i.e., any digit x's increase in x.x.x) is a valid dependency. If it is valid, the pull request can be opened, otherwise discarded.#
3.1 Add an HTTP status validator. This validator calls a user-given URL with the replaced version to check, and if the URL exists, the PR is to be opened. For instance, the bumping version to check is 1.0.1 (i.e., derived from the current version 1.0.0), then this version is replaced in the user URL https://api.github.com/repos/dependabot/feedback/releases/tags/{version}. If it returns code 200, it is a valid dependency.
3.2 There might also be use cases, in which validation is not possible but still, you want to have an automated version bump, or in which the validation can only be done by GitHub's enabled third-party status checks by any CI of your choosing. There, it would be appropriate to always open a pull request for a version bump of the (security) PATCH, or in general, the last digit of the version. First, the status checks will block the PR, but once the specified version becomes available, they will pass it, and the admin knows when to merge. That would also require an additional comment command to change the PR's version, allowing MINOR or MAJOR semver bumps to a specific version.

**Comment by greysteil** [comment]
Sounds like the way to go about this would be to add a new "language" to Dependabot Core ([code here](https://github.com/dependabot/dependabot-core)) that allowed highly configurable input.

Whilst I like this idea, I think it would be a *lot* of work - it's not the way that Dependabot is set up at the moment, and likely to require a lot of changes to the architecture of Dependabot Core (to allow you to pass in all of that use input).

Do you want to have a play with Dependabot Core and see if you can get something working? I'm not going to be able to prioritise this one myself for some time, so am going to close this here - I think it's a good idea, but I don't want to set expectations I can't match.
