### ISSUE TITLE
Auto add repositories for an organization

### ISSUE THREAD

**Issue by yoshuawuyts** [dependabot/feedback#155]
It'd be great if new repositories could automatically be added for any organization. I would love it if dependabot only required setting up once, and then it just works.

Similarly I still haven't been able to figure out how to batch import projects (even with https://github.com/dependabot/feedback/issues/4). It'd be great if that was possible in the UI.

Thanks heaps!

**Comment by greysteil** [comment]
Thanks for the feedback @yoshuawuyts. I'd love to add a UI for this, and the ability to auto-add projects, and will in future.

In the meantime, the API endpoint you want for setup is [this one](https://github.com/dependabot/api-docs#create-an-update-config-for-a-repo), with the `repo-id` and `account-id` being IDs from GitHub (you can get them by hitting `https://api.github.com/repos/your/repo`).

**Comment by yoshuawuyts** [comment]
@greysteil thanks heaps for the quick reply! - that should def do the trick for me  for now :sparkles: :grin:

**Comment by yoshuawuyts** [comment]
@feelepxyz that's fantastic to hear! -- excited for more automation on this front! :D

**Comment by greysteil** [comment]
Closing as stale now that Dependabot is part of GitHub and automated security fixes will soon be on for everyone by default. I'll keep this in mind as we continue to integrate Dependabot, though!

**Comment by yoshuawuyts** [comment]
@greysteil much appreciated!
