### ISSUE TITLE
Label description

### ISSUE THREAD

**Issue by yoshuawuyts** [dependabot/feedback#156]
I noticed dependabot adds labels to my project -- I like it a lot!

A small nit however is that the label doesn't have a description, which kind of gives away it was added later (see below). I reckon it'd be cool if it could come with a description. Perhaps something like:

> About project dependencies

---

Thanks!

## Screenshot

![screenshot_2018-08-25 update sparse-bitfield requirement from 0 4 0 to 0 8 0 by dependabot pull request 20 datrs hyper](https://user-images.githubusercontent.com/2467194/44617080-20c4e680-a85d-11e8-8dd6-1e9ca1ba82e6.png)

**Comment by greysteil** [comment]
Oh, that is weird! Definitely a bug. The code is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/labeler.rb#L232-L241) - it should be adding a description. I'll dig into it.

**Comment by greysteil** [comment]
I think this might be a bug on GitHub's side - we've got tests that we're passing through the description correctly. I'll test end-to-end and get in touch with them if it is.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/0be3cd07fa3008cc240c47df3ff3aa67fec5f116.

**Comment by yoshuawuyts** [comment]
@greysteil awesome thanks for fixing! Glad I could be of help! :sparkles:
