### ISSUE TITLE
Rails app: Does not run an update on dependent gems?

### ISSUE THREAD

**Issue by kapso** [dependabot/feedback#157]
My daily bump ran, after which I did `bundle update` I noticed - that updated some of the dependent gems. Why did dependabot miss them?

**Comment by kapso** [comment]
Yea lets try that, thanks @greysteil

**Comment by greysteil** [comment]
Awesome - one your `kapso` account, or a different one?

**Comment by kapso** [comment]
Its my github user, but on my company a/c - boxbotinc

**Comment by greysteil** [comment]
Done. Let me know if you have any trouble with it - I'm planning to make the option available to everyone, but am waiting to hear feedback from people who have it switched on first.

**Comment by kapso** [comment]
Sounds good, thanks.

**Comment by mreinsch** [comment]
@greysteil I'd be interested in this as well - also for our javascript app.

**Comment by greysteil** [comment]
Ah, the one language it doesn't work for yet is JavaScript. I need to do a bit more thinking about how sub-dependency updating should work there (given nested resolution). Sorry!

**Comment by mreinsch** [comment]
@greysteil we also have Ruby projects, would love to see how it works for that!

**Comment by greysteil** [comment]
👍 - I've set all of the Ruby configs for xapix-io to update sub-dependencies, too.

Getting to the point where enough people are using this, and none of them finding any issue with it, that I'll make it configurable in the dashboard.
