### ISSUE TITLE
Cannot bump dependencies in a public repo that's dependent on a private repo

### ISSUE THREAD

**Issue by StuartMorrisAU** [dependabot/feedback#158]
Hi there,

I have a public repo that's dependent on another private repo, for which I have a read-only ssh key but I'm not a member of. If I create a personal access token (per #35) using the `repo` scope and add it to the Dependabot dashboard variables using Git source, host `github.com`, username `x-access-token`, I get an error back when I bump the repo that states:

> Dependabot couldn't resolve your project's dependencies as it couldn't access hydejack-pro.

After I get this error, the personal access token shows it's never been used. Am I missing something?

Thanks for your help.

**Comment by greysteil** [comment]
Hmmm, let me look into that for you.

**Comment by greysteil** [comment]
Oh huh, this looks like a tricky one.

I've just taken a look at https://hydejack.com/docs/install/#pro-version and it looks like it only works with ssh - giving Dependabot a GitHub access token won't help here. I'll ping the author and see if we can work out a solution.

**Comment by greysteil** [comment]
OK, the only workaround that I can think of here is for you to push the repo that you're pulling down from hydejack to a (private) GitHub repo of your own, and then use that as your source instead of the hydejack URL. Would that work?
