### ISSUE TITLE
Specify day of week for "Bump weekly" option

### ISSUE THREAD

**Issue by eitoball** [dependabot/feedback#16]
Hi

It would be nice to specify day of week for "Bump weekly" option because you would get lots of PRs when you setup multiple languages on a project.

Thank you for considering.

**Comment by greysteil** [comment]
Thanks for the feedback! I'll have a think about how we can fit this into the UI - I don't want it to end up too busy.

**Comment by greysteil** [comment]
This has been open for a while and hasn't got a lot of traction, so I'm going to close. I'll keep it in mind, though.

**Comment by greysteil** [comment]
This is now an option! You can choose the day of the week that weekly updates happen on from the setting tab in your Dependabot dashboard. Use the menu in the top right to get there.

Thanks for your patience on this one!
