### ISSUE TITLE
Support for multiple composer.json-files [PHP]

### ISSUE THREAD

**Issue by torkiljohnsen** [dependabot/feedback#160]
I have a repo, which holds multiple PHP packages. Structured something like this:

```
composer.json
packages/
    foopackage/composer.json
    barpackage/composer.json
```

The root `composer.json` uses `packages` as a repository, so when I `composer require foopackage`, the files from `packages/foopackage` are just symlinked to the vendor folder by Composer.

So basically a monorepo.

The issue is that only the dependencies in the root composer.json file are kept up to date by dependabot. None of the dependencies in the packages folder are managed at all.

Dependabot does not support adding multiple projects per repo either, so I have no way of adding multiple composer.json files to the mix here.

Or could it be better if dependabot would look at outdated packages the same way composer does, by `composer outdated`? I guess by using `composer.lock` as a source of package info, instead of looking only at `composer.json`, but I'm not sure if that is perhaps a lot harder to pull off?

**Comment by greysteil** [comment]
Ah, interesting - let me take a look. Can you ping the repo to support@dependabot.com

Dependabot *does* support adding multiple projects per repo, as long as you select a different directory for each one when you add it (in the advanced settings section of the add language dialog). I'm going to work on making the UI around that clearer, too.

**Comment by torkiljohnsen** [comment]
Yeah, on the project overview though, you only see the directory if you mouseover the info icon, so the overview page would be a bit hard to read, since it would just see 20 identical repo names when scrolling down.

Also I think you are mistaken…? I have granted access to two repos from our github org, and added one dependabot project for each of those two repos. When I try to add a new project now, it just says "No repos found", so I can't add any more projects it seems. I have double checked that Dependabot still has access to those two repos just now.

**Comment by torkiljohnsen** [comment]
I have sent you an e-mail 👍

**Comment by greysteil** [comment]
New dashboard makes this *much* clearer by showing the names of all of the files covered in each update config 🎉
