### ISSUE TITLE
Python: pbr is removed from Pipfile.lock when upgrading other dependency

### ISSUE THREAD

**Issue by dpursehouse** [dependabot/feedback#162]
See for example https://github.com/dpursehouse/pygerrit2/pull/33 where `pytest` is upgraded.  This in itself is a welcome update, but the same change also seems to be removing the `pbr` dependency from the `Pipfile.lock`.  If I run `pipenv upgrade` manually, it does not remove `pbr.` 

I've previously also seen this problem on https://github.com/dpursehouse/pygerrit2/pull/30 and https://github.com/dpursehouse/pygerrit2/pull/32, and also https://github.com/dpursehouse/pygerrit2/pull/31 which was actually supposed to be an upgrade of `pbr` (but removed it instead).  For those latter three PRs I ended up squashing them all into a single commit that I generated with `pipenv upgrade` manually.

**Comment by greysteil** [comment]
Taking a look now - thanks for flagging this.

**Comment by greysteil** [comment]
Ah, this is going to be due to https://github.com/dependabot/dependabot-core/commit/e114262cbd31a65d67fdb13037a588aaabe594ba. That's *definitely* a bug on my side - fixing now.

**Comment by greysteil** [comment]
Fixed! Took a few hours to get to the bottom of, but Dependabot's setup.py sanitization is a lot better now. Thanks so much for flagging this.

**Comment by dpursehouse** [comment]
Thanks for the quick fix 🍺
