### ISSUE TITLE
Terraform doesn't detect tf files in folders

### ISSUE THREAD

**Issue by Isaacpm** [dependabot/feedback#164]
The terraform option doesn't detect terraform configuration files in folders, just in the root directory.
Given how Terraform is usually used, configurations in different folders, it would be very useful if dependabot would recursively looked for terraform files.

**Comment by greysteil** [comment]
Interesting, thanks for the feedback. Would you then want Dependabot to create a single PR that updated the version of a particular module everywhere, or want one PR per file?

**Comment by Isaacpm** [comment]
good question, I guess a PR per file would be better as it follows the isolation philosophy in which the initial split in folders is based on.
Does that make sense?

**Comment by greysteil** [comment]
👍 - OK, in that case I'm going to close this as a dup of https://github.com/dependabot/dependabot-core/issues/649. We'll get to this in the next few weeks, and the fix is likely to be an improved frontend.

Thanks again for the feedback.
