### ISSUE TITLE
Some dependabot commit messages violate @commitlint/config-conventional length rules

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#165]
`@commitlint/config-conventional` specifies a maximum line length of 72 characters. The following commit message is 74 characters.

```
build(deps-dev): update postcss-import requirement from ^11.1.0 to ^12.0.0
```

It seems to me that "requirement" is extraneous, but for even more safety, perhaps something like the following might work?

```
build(deps-dev): update <%= packagename %>

Previous Version: <%= oldversion %>
New Version: <%= newversion %>
```

**Comment by greysteil** [comment]
Interesting. We can definitely do better here - taking a look now.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/6eb9d546265a4243c9d4dd7b64342c906bd0711a.

Long names will now be truncated at the `from` point, so this would become

```
build(deps-dev): update postcss-import
```

I think that's a nice improvement, and for version updates the new version is included in the next line anyway (for requirement updates it says that it's updating to allow the latest version, which I also think is fine).

Thanks for the feedback!

**Comment by ianwremmel** [comment]
Awesome, thanks!

**Comment by jbinto** [comment]
We recently turned commit-lint and were stunned to see that Dependabot adapted to this. Amazing work.

**Comment by pellizzetti** [comment]
I tried to use `dependabot` automated pull requests (using GitHub UI) but it fails to follow our `commitlint` rules.

- [PR](https://github.com/Rocketseat/unform/pull/138)
- [Travis Status Check](https://travis-ci.org/Rocketseat/unform/builds/590129601#L227)
- [Commitlint rules](https://github.com/Rocketseat/commitlint-config-rocketseat/blob/master/index.js)

It seems that the first line of the commit body is 84 characters long:
`Bumps [mixin-deep](https://github.com/jonschlinkert/mixin-deep) from 1.3.1 to 1.3.2.`

Does the bot only check/trim the subject of the commit?

I tried to look at the bot configs but found nothing about specifying commit rules.

Am i missing something?

How can I fix this? Thank you!

**Comment by feelepxyz** [comment]
@pellizzetti only the first subject is truncated and don't have any configuration to fix this for the body at the moment 😢we support the conventional config which only limits the subject/header to 72 characters. It would be quite a bit of work on our side to add configuration to specify a max length on header and body.

**Comment by greysteil** [comment]
Yeah, we’d need to use a dependency that did something clever with wrapping. I feel like it should be possible, but it’s a whole domain...

**Comment by TimoGlastra** [comment]
I'm running into an issue with this when merging pull requests from dependabot.

Dependabot creates a pr with the following commit: 
`chore(deps-dev): bump @typescript-eslint/parser from 2.11.0 to 2.14.0`. 

I then choose to squash and the merge the pr with `@dependabot squash and merge`.  The problem however is that github adds the pr number to the commit message which adds some characters to the header. The above commit message with a header-length of below 72 becomes 74 characters long:
`chore(deps-dev): bump @typescript-eslint/parser from 2.11.0 to 2.14.0 (#6)`

[Commit](https://github.com/ula-aca/aries-cloudagent-interface-javascript/commit/748901b79daac39daba21948f6c84e153798f2b9)
[Github action run that fails](https://github.com/ula-aca/aries-cloudagent-interface-javascript/runs/369153055)
[PR](https://github.com/ula-aca/aries-cloudagent-interface-javascript/pull/6)

Is there anything I can do to fix this?

**Comment by feelepxyz** [comment]
@TimoGlastra not aware of any workaround for this as it's added by GitHub. Not sure it makes sense to trim all titles by five characters to accommodate this possibility.

**Comment by TimoGlastra** [comment]
Yeah this is not really a problem of dependabot and more the combination of commitlint + dependabot + github. However as dependabot creates the commit messages it is the only of the three that can solve the problem (besides disabling the commitlint rule).

I see two possible solutions to this:

1. Commit messages already get trimmed to 72 characters. Maybe there could be a setting to make the 72 characters max length adjustable?
1. Make a setting that will remove dependency versions from the commit header completely? So only the `bump @typescript/eslint-parser` would be in the commit header and the exact dependency update would be placed in the body.

I now have to manually rewrite some of the commit messages that dependabot creates, which is not a good solution. 

Thank you!

**Comment by feelepxyz** [comment]
@TimoGlastra yeah making the length configurable would make sense and possibly dropping versions as an automatic strategy if it doesn't fit under the limit. Could you open this suggestion up as a new issue? We're unfortunately super stretched so don't have much spare capacity to work on this in the near term. If you're super keen we would also accept a PR to https://github.com/dependabot/dependabot-core implementing this ([relevant code](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/message_builder.rb#L103-L111)).

**Comment by TimoGlastra** [comment]
Issue: https://github.com/dependabot/feedback/issues/817

I would like to submit a pull request, but having not a lot of spare time and no experience in ruby I'm not going to dive into it at the moment. If I have the time I'm definitely going to take a look.
