### ISSUE TITLE
dependabot cannot automerge in repos configured to require code reviews

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#166]
Is there a way around this with just github settings? or does some kind of automation need to be setup to auto approve dependabot PRs? If the latter, would you consider operating a second dependabot user with that ability?

**Comment by greysteil** [comment]
This is a frustrating one. There's a long running thread of people asking GitHub to add a way to approve bots to work with protected branches [here](https://platform.github.community/t/repositories-which-have-protected-branches-with-push-restrictions-have-no-ability-to-grant-push-rights-to-integrations/1376/53), and it would be great if you could add your voice to it.

In the meantime, an approval bot is the way to go. We haven't built one yet, and have a couple of other priorities to get to before we do (GitLab, Go modules, a dashboard overhaul). If GitHub don't fix things then we will eventually get to it, though!

**Comment by josesimoes** [comment]
Just added my comment and up vote [there](https://platform.github.community/t/repositories-which-have-protected-branches-with-push-restrictions-have-no-ability-to-grant-push-rights-to-integrations/1376/56?u=josesimoes)
