### ISSUE TITLE
[Ruby] AWS SDK gem custom directory structure

### ISSUE THREAD

**Issue by marcotc** [dependabot/feedback#167]
Since version 3.0, the [AWS SDK for Ruby](https://github.com/aws/aws-sdk-ruby) has been broken down into smaller gems.
The problem here is that they all live under the same repository, under different directories.

This causes @dependabot-bot to not be able to provide meaningful Changelogs.
Here's an example I got recently:

> Bumps [aws-sdk-s3](https://github.com/aws/aws-sdk-ruby) from 1.9.1 to 1.17.1.
> <details>
> <summary>Commits</summary>
> 
> - See full diff in [compare view](https://github.com/aws/aws-sdk-ruby/commits)
> </details>

Amazon does provide [information on how to find the specific changelog for each gem](https://github.com/aws/aws-sdk-ruby#change-log), but it seems like a very bespoke case.

**Comment by greysteil** [comment]
Ah, oops, we can totally do better here. I was the one that got Amazon to link up their changelogs on Rubygems, but a change to Dependabot means we're not using that information 🤦‍♂️.

I'll get this fixed tomorrow. Thanks for flagging it!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/a6ea7a5d8757ce4d02d9bbf9e26f55e63721e4e2. 🎉
