### ISSUE TITLE
Can't login to dashboard in mobile

### ISSUE THREAD

**Issue by kemitix** [dependabot/feedback#168]
When figuring the website on a mobile browser there is no login option, only a signup link. The signup link only leads, after a Signup with Github, to a page showing just "Authentication failure".

**Comment by greysteil** [comment]
Good spot! I've added a login button for small screens at the bottom of the menu (which is where you'd expect it, I think).

On the authentication failure, I'm not sure what could have caused that. I'll dig into it separately.

Thanks for the feedback.
