### ISSUE TITLE
Github personal access token permissions

### ISSUE THREAD

**Issue by paddycarey** [dependabot/feedback#169]
Hey,

I'm creating a new personal access token so that dependabot can pull dependencies from private Github sources (`dep` in this case) but I'm unsure what the minimal set of permissions i need to give the token is.

Is this documented anywhere or does anyone know the answer? I'd like to give the token as few permissions as possible to allow dependabot to operate.

**Comment by paddycarey** [comment]
That did the trick, thank you! Is is worth documenting somewhere?

**Comment by greysteil** [comment]
Yes! Hopefully folks will find this issue, but I'll append the text in the dashboard with `(which needs read permission to your private repos)`.

Thanks for giving Dependabot a try!
