### ISSUE TITLE
Option to choose branch

### ISSUE THREAD

**Issue by mkody** [dependabot/feedback#17]
Hi and thanks for your work.

Currently, Dependabot makes PRs to the master branch. Would it be possible to make it work with other branches?
Like we might want to use a develop, dev, testing (etc.) branch instead.

And thanks again!

**Comment by greysteil** [comment]
Hey, thanks for the feedback!

We've had this request once before - currently Dependabot opens PRs against whatever your default branch is, but in some (rare) cases that's not the branch people want.

Given the above, I think it makes sense for us to add it. I'll do it sometime this week.

Cc-ing @NicolasCARPi as he's the one who asked for this last time, and @hmarr as I'll need his help on the front-end.

**Comment by greysteil** [comment]
Done and deployed - it's in the `Advanced options` section when you add a new language / repo.

Thanks for bearing with us on this one!

🎉
