### ISSUE TITLE
.NET dependecy check PR missing project file contents

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#170]
Hi,

I've just setup dependabot in one of our repos to give it a try. It's a .NET solution.
It seems that it updates the contents of the packages.config file, but it misses the references in the csproj files.

**Comment by greysteil** [comment]
Hey @josesimoes,

Hmmm, it should be picking those up. Can you give me the name of the repo (or email it to support@dependabot.com if it's private)?

**Comment by josesimoes** [comment]
Here's the [PR](https://github.com/nanoframework/lib-Windows.Devices.Gpio/pull/25)

Actually I just realize that there was nothing to bump, because there was no new package... still dependabot has created this PR bumping to a non-existing package....

Looking at the PR comment I can see that it's picking up and linking to another unrelated repo: nf-class-libraries.... I don't know from here that comes from....

**Comment by josesimoes** [comment]
On the wrong bump and and repo link: I think I've found the reason.
There is a package in nuget for [version 1.0.0](https://www.nuget.org/packages/nanoFramework.CoreLibrary/1.0.0) _but_ it's unlisted so it's supposed to be _hidden_. Guess it's showing on the collection that dependabot receives from nuget API and it's considering that as a new version.

I would suggest that if a package is hidden then it should not be considered for evaluating if it's a valid new version.

**Comment by greysteil** [comment]
Awesome - I'll make that improvement tonight. It's a little late on a Friday evening here so I won't be responsive for the next couple of hours, but I'll get this fixed up when I'm back.

Thanks for giving Dependabot a try!

**Comment by greysteil** [comment]
OK, https://github.com/dependabot/dependabot-core/commit/24f3458b9bb5a62e61adfcc355a11465cd1af346 and https://github.com/dependabot/dependabot-core/commit/93ab6693696fc3e2b53b5d3971d804458a956790 are deploying now, which will fix the unlisted version problem. 🎉 

Thanks for flagging this!

**Comment by josesimoes** [comment]
Thank YOU for the quick fix!

**Comment by josesimoes** [comment]
This is not a _standard_ .NET extension (being standard something coming from Microsoft). It's part of a .NET project system that, despite being C#, it's derived from the regular CPS.

I guess this can happen with other folks using their own project systems/extensions...
Maybe if there was a new setting on the dependabot project on which one could enter the file extension(s) to the processed as the regular .csproj.....
Or maybe dependabot could "smartly" pick up those from the solution file that is next to the packages.config...

**Comment by greysteil** [comment]
I think Dependabot ought to be able to figure it out by parsing your `.sln` file better - at the moment it just looks for `.(cs|fs|vb)proj` files in there, but it should be taking the filename of anything that's declared as a project.

**Comment by josesimoes** [comment]
Makes sense!

**Comment by greysteil** [comment]
Deploying the fix now - should be live in about 10 mins.

**Comment by josesimoes** [comment]
That was fast! 👏 

For some reason that is not working... You can use [this PR](https://github.com/nanoframework/lib-Windows.Storage.Streams/pull/24) for debugging if you want.

**Comment by greysteil** [comment]
Ah, it looks like this is a separate issues. Dependabot expects packages to be declared using `PackageReference` tags, but you're using a `Dependency` tag. Can you point me to any information about the difference?

**Comment by josesimoes** [comment]
Understood!

I was looking into this early today. The "new and shiny" version relies on [packagereferences](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files).
Those have been added very recently as you can read from there.
They don't cover all .NET projects (see the all list of exceptions). I would dare to say that at this point in time, very few projects are using them. 

Technically projects with the new PackageReference tag do not have packages.config file...

If you ask my opinion dependabot should support both models.

Surprisingly I couldn't find official documentation on this.... The best one on a quick search is [this](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) blog post.
When you get to "NuGet: imports and references" you'll see that the previous formats relie on the `Reference` tag _but_ there are more to it, as a Nuget package could also bring along targets and props files.
My suggestion would be that you add a few regex rules or similar to find+replace these.

Using the example on that blog post, it would be something like:
1. packages\MySql.Data.6.9.9 ->  packages\MySql.Data.7.0.0 (this will pick all the `hints`, `imports` and other tags in the project file that rely on the package path) (don't forget and preview/alpha/etc suffix there) (do a wide search on the project file not only inside those tags, because these could be used/referenced elsewhere)

2. MySql.Data, Version=6.9.9.0  -> MySql.Data, Version=7.0.0.0 (this will pick all the `reference` tags) mind the 4 version numbers and that no preview/alpha/etc suffix exists on these tags)

**Comment by greysteil** [comment]
Makes sense.

I'll take a look at supporting NuGet 2 syntax when I have a moment, but in the meantime I've added support for the `Dependency` tag, which appears to be bespoke to `.nuproj` files, because I think even those using the latest version of VS might have those!
