### ISSUE TITLE
Development dependency is ignored while peer dependency is bumped

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#173]
I have faced this situation. I have the following `package.json`:

```json
...
"peerDependencies": {
    "babel-eslint": "^8.2.3"
  },
 "devDependencies": {
    "babel-eslint": "^8.2.3"
}
```

After dependabot bumped my dependencies it became:

```json
...
"peerDependencies": {
    "babel-eslint": "^9.0.0"
  },
 "devDependencies": {
    "babel-eslint": "^8.2.3"
}
```

But that's not what I expect. These versions should be in sync.
Related PR: https://github.com/wemake-services/eslint-config-flowtype-essential/pull/57

Thanks!

**Comment by greysteil** [comment]
Sorry for the slow reply on this one. That's a bug, and I'll take a look!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/de53ec1a3a17685f46d9c13e0fb3d703a087d8cd, which is something of a hack but a better stopgap than the current behaviour. Thanks for flagging.
