### ISSUE TITLE
[.NET] Specifying option to include preview packages

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#175]
It's common to have Nuget feeds with preview packages along with official versions.
It would be great to have the ability to specify in the project settings if preview packages should be included when evaluating if there is a new version.

(I'm assuming that currently, the default follows the default Nuget behaviour of _not_ including preview packages)

**Comment by josesimoes** [comment]
This seems to be working out of the box. Closing now.

**Comment by greysteil** [comment]
Yep! We include pre-releases, and will update you to them if you're already using one (i.e., `4.2.3-alpha.1` will happily update to `4.2.3-alpha.2`) but not if you're not (so `4.2.3` won't update to `4.2.4-alpha.1`).

**Comment by robertcoltheart** [comment]
@greysteil Is it possible to opt-in to updates from stable to non-stable (eg `4.2.3` to `4.3.0-beta.1`)? I'd like to be able to use this as a canary for upcoming package updates (.net) that we can use to develop against before a stable release drops.

**Comment by greysteil** [comment]
Not currently, but we're thinking about adding an option to opt-in to exactly that. Let me have a think and get back to you.

Related to https://github.com/dependabot/feedback/issues/356.

**Comment by robertcoltheart** [comment]
Any update on this? This is still a feature that would be super useful to flag incompatibilities with upcoming major releases of packages that we depend on (ie Resharper SDK).
