### ISSUE TITLE
add the option to squash+merge 

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#178]
This is useful when there are several commits in the PR (because of fixes, manual edits, etc) and it's intended that the repo history is kept "clean".

**Comment by greysteil** [comment]
Are you thinking this should be a new Dependabot comment command - something like `@dependabot squash and merge`? I think in most cases the GitHub UI has what you need here, so I'm slightly reticent to add it.

**Comment by josesimoes** [comment]
That is correct! In the same spirit of `@dependabot merge` which is already there.
In the end it's a command to dependabot with the GitHub option one wishes to use to merge the PR just like the merge. Actually a variation of merge 😉 .

(and yes, of course it's there on the UI, again, like merge)

**Comment by greysteil** [comment]
Cool - shouldn't be too hard to implement. I might not document it at first, as I don't want to overwhelm folks with too many commands, but I'll let you know here if/when it's implemented :-)

**Comment by Rsl1122** [comment]
How is the implementation going? :)
As a new user, I would love this feature.

**Comment by greysteil** [comment]
Deploying now! If you commend `@dependabot squash and merge` then that's what Dependabot will do.

(Give it 5-10 minutes to deploy first, though).

Thanks for the feedback!

**Comment by kiview** [comment]
I tried this command in this PR and it didn't seem to work:
https://github.com/testcontainers/testcontainers-java/pull/1227

Has this feature been rolled back?

**Comment by Rsl1122** [comment]
You did a merge command right after @kiview

It only needs the single command `@dependabot squash and merge` to work.

**Comment by kiview** [comment]
I just did the other command, because it seemed I didn't get feedback, but
maybe I was just impatient, thanks :)

Am Fr., 8. Feb. 2019 um 09:15 Uhr schrieb Risto Lahtela <
notifications@github.com>:

**Comment by ybiquitous** [comment]
`squash and merge` is a very nice feature! I have wanted a long time! 😊 

So, would you please add this `squash and merge` command to the `Dependabot commands and options` section? 🙏 🙏 🙏 
I have been assumed it as unsupported until I noticed this issue. 😅 

The following is an example screenshot on my repository: https://github.com/ybiquitous/eslint-config-ybiquitous/pull/343

![image](https://user-images.githubusercontent.com/473530/52602117-bfdda900-2ea4-11e9-908a-e846a4e13a48.png)

**Comment by greysteil** [comment]
Documented! 🎉

**Comment by ybiquitous** [comment]
Thank you very very much!!! 🎉 🎉 🎉

**Comment by douglasrlee** [comment]
Can we also get this as an option for auto-merging PRs? Unless I just missed it somewhere..

**Comment by Rsl1122** [comment]
@douglasrlee 
Uncheck this box in the account settings
![kuva](https://user-images.githubusercontent.com/24460436/79565767-07b81b80-80ba-11ea-9940-58e39590938f.png)

**Comment by douglasrlee** [comment]
@Rsl1122 thanks! I figured I missed it somewhere.

**Comment by kuoruan** [comment]
I unchecked `Create a merge commit if a PR is merged by Dependabot` but there is still a merge commit.

```
Merge pull request #** from XXXXX
```

Does anyone know why?

Maybe we need to add a new option in config files to set automerge use `default merge`, `squash merge` or `rebase merge`.

**Comment by dannyphillips** [comment]
Is there a way to disable `

> @douglasrlee
> Uncheck this box in the account settings
> ![kuva](https://user-images.githubusercontent.com/24460436/79565767-07b81b80-80ba-11ea-9940-58e39590938f.png)

Is there a way to disable this via config file, instead of unchecking a checkbox in the UI?
