### ISSUE TITLE
.NET package update is not checking dependencies

### ISSUE THREAD

**Issue by josesimoes** [dependabot/feedback#181]
Just noticed that the version update on Nugets is not checking the dependencies of the updated package, which will result inevitably on a build failure.

Example: 
[This repo/project](https://github.com/nanoframework/lib-Windows.Devices.Gpio/blob/develop/source/packages.config) depends on `nanoFramework.CoreLibrary` and `nanoFramework.Runtime.Events`. 

After triggering a bump I've received 2 PRs updating both packages (which is correct, in principle, because both were updated). nanoFramework.CoreLibrary is now on 1.0.0-preview073 and nanoFramework.Runtime.Events is now on 1.0.0-preview188.

The fact is that nanoFramework.Runtime.Events depends on nanoFramework.CoreLibrary _AND_ the current version (188) requires nanoFramework.CoreLibrary-1.0.0-preview073.

Any of this PRs fails the build because of wrong dependencies on the other referenced package.

**Comment by greysteil** [comment]
Interesting. Can you move the discussion of this one over to https://github.com/dependabot/dependabot-core/issues/541, please? I'd love to add proper resolution to Dependabot's .NET support.
