### ISSUE TITLE
dependabot does not update `npm-shrinkwrap.json`?

### ISSUE THREAD

**Issue by jandockx** [dependabot/feedback#183]
Node projects that support both Node 6 / npm 3 and Node 8 or later (npm 5 or later), call `package-lock.json` the old name, `npm-shrinkwrap.json`. That way, both `npm install` on Node 6, and `npm ci` on Node 8 and later work. Travis uses this, e.g.

It seems dependabot does not update `npm-shrinkwrap.json` though. Or am I missing something?

See , e.g., https://travis-ci.org/Toryt/dns-sd-lookup/jobs/429303535

**Comment by greysteil** [comment]
Sadly that's right - Dependabot doesn't have support for `npm-shrinkwrap.json` at the moment.

I hadn't realised that the format was identical, though - should be relatively straightforward for me to add support. I'll take a look tomorrow.

Thanks for the feedback!

**Comment by greysteil** [comment]
FYI, I've started a PR for this [here](https://github.com/dependabot/dependabot-core/pull/669).

**Comment by greysteil** [comment]
Fixed! 🎉
