### ISSUE TITLE
PR isn't merged after CI finishes

### ISSUE THREAD

**Issue by niels-s** [dependabot/feedback#184]
I tried to use the `@dependabot merge` command to get a PR merged while CI was still running. 
Dependabot notifies us that it will merge the PR once CI has finished but after almost waiting a day the PR is still not merged. I watched this behaviour before that's why I waited a day this time around to see if I wasn't too eager after all which doesn't seem to be the case.

I'm also sure all other checks like reviews are applied. All checks where green, expect CI runs.
We do use a PR based ci run and a pr-merged ci run perhaps that could potentially be an issue?
It's hard to show an example since it's in a private repo and we also use a private jenkins instance but it does report properly to Github.

Let me know if you need anymore information, would be great to get this solved 👍

**Comment by greysteil** [comment]
Merging should be pretty quick, so something's definitely gone wrong here. Can you email the URL of the PR to support@dependabot.com? I can use that to find it in our backend and see what's happened.

Sorry about this one!

**Comment by niels-s** [comment]
Thanks for fast response, I've mailed you the PR and a screenshot

**Comment by greysteil** [comment]
Looks almost certain that this was due to GitHub's downtime this morning. Have followed up over email, and added some additional retry logic to Dependabot so it *should* be able to handle GitHub issues more gracefully if/when they occur again.
