### ISSUE TITLE
update vendored Go code

### ISSUE THREAD

**Issue by ryanking** [dependabot/feedback#187]
For Go projects that use vendoring, the vendored code should be updated in addition to the Gopkg.toml.

Example PR where it doesn't get updated https://github.com/chanzuckerberg/czecs/pull/8/files

**Comment by greysteil** [comment]
Thanks for the feedback @ryanking. I totally agree on this, and adding support for vendoring to Dependabot is the next big project on my list. I've moved this issue to the [dependabot-core](http://github.com/dependabot/dependabot-core) repo and will pick it up there.

(Out Go support is still pretty new - we added support for Go modules on Saturday - so please bear with us on this one.)
