### ISSUE TITLE
Changed default branch - PRs still hanging around on old one

### ISSUE THREAD

**Issue by kierenj** [dependabot/feedback#189]
I have a `release/2.0.0` branch which was the default branch, and set up dependabot to scan the default repo (left the box blank).

The default repo has now changed to `develop`, but the PRs are hanging around on the old one, and no new PRs are raised.

(P.S. I found another issue - if you type in the repo box then clear it out, it doesn't pick up the default one anymore.  I don't remember what happened - maybe a client-side validation error?)

**Comment by greysteil** [comment]
Thanks for the feedback @kierenj.

Looks like our backend wasn't treating empty string branch names correctly, which probably explains the second issue you mentioned. I've just pushed a fix for that.

On the first issue, I'm going to do some work to fix this today. Basically, you *should* be able to say `@dependabot rebase` to those PRs and have it have the correct result (i.e., realise the base branch needs to change), but right now you can't. Give me a couple of hours...

**Comment by greysteil** [comment]
OK, fix is deployed - you should now be able to ask those PRs for a rebase and they'll switch to the correct branch. 🤖
