### ISSUE TITLE
Is there a list of the comment commands @dependabot can interpret?

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#19]

**Comment by greysteil** [comment]
Yes - it’s in the `Dependabot commands and options` details tag on each Dependabot PR 🎉

**Comment by ianwremmel** [comment]
Oh, nice. Thanks! Honestly, that's the last place I would think to look; I expect automated posts to have very little useful detail and lots of cruft :)

Maybe these commands could also go on the website somewhere?

**Comment by ianwremmel** [comment]
no problem, thanks for the great tool!

**Comment by pankajagrawal16** [comment]
@dependabot help

**Comment by miikamakiOC** [comment]
@dependabot help
