### ISSUE TITLE
Auto-merge on PR approval

### ISSUE THREAD

**Issue by lucas-nelson** [dependabot/feedback#190]
Our workflow is for developers to create a PR, then seek approval using the built-in github review / approval feature. Once approved, the developer is free to merge and delete the branch.

Would be nice if this could be automated for dependabot.

As it is now, because I can never remember the command, I need to move from the `Files changed` tab to the `Conversation` tab; expand the `Dependabot commands and options` section, copy the `@dependabot merge` command; back to the `Files changed` tab; paste it into the approval command; and hit approve.

It's not the end of the world doing that, though it does get old when many PRs come in across our repos in a batch. But, if a PR gets a github `approval`, why *wouldn't* I want the PR merged immediately? Feel like a step that could be automated.

PS: this is an awesome product with so much care and attention in the little details, thanks!

**Comment by greysteil** [comment]
Interesting feedback. I can definitely see how for your flow an automatic merge would be great, but for other users, who like to have multiple approvals on a single PR (we see this quite often) the above would cause problems.

I think the ideal solution here would be to make the above configurable, but it got me thinking that you presumably have the same issue (having to hit "approve" and then later "merge") for PRs created by individuals in your organisation. Would it perhaps be better to have a separate bot that merges all PRs once they're approved (perhaps through something like probot)?

**Comment by lucas-nelson** [comment]
> it got me thinking that you presumably have the same issue (having to hit "approve" and then later "merge") for PRs created by individuals in your organisation

For us, the merge is the responsibility of the author of the PR, not the reviewer. The reviewer just needs to hit the approval button and move on.

Thank you for the tip about the github bot. I'll look into it!

**Comment by greysteil** [comment]
OK, I've added a setting for the behaviour described above. From now on, when you approve a Dependabot PR it will work the same as saying `@dependabot merge` to it. I've only enabled it for @blake-education, and haven't added it to the frontend yet, but assuming everything goes well I'll make it generally available.

Can you let me know how you get on? And thanks for using Dependabot!

**Comment by lucas-nelson** [comment]
@greysteil - tried it just now, worked flawlessly, thanks!

**Comment by thomaseizinger** [comment]
@greysteil Did you ever get around to adding this setting to the frontend? I can't seem to find it ...

I would really like to activate this feature to avoid some redundancy in my workflow.

At the moment, I have to approve (so that GitHub allows dependabot to merge) and write `@dependabot-bot merge` into the feedback.

**Comment by greysteil** [comment]
We didn't, but happy to enable it for you on my side. Why accounts do you want it on?

**Comment by thomaseizinger** [comment]
`nobt-io/frontend` would be great, thank you! :)

Are you still evaluating to make this a first-class feature?
I'd hate to bother you with further requests in the future :)

**Comment by greysteil** [comment]
Yep! We're planning to move all of the account-level features (this is one of them) down to the repo level and expose them in config files, but before we do so I don't want to add anything else to the UI.

**Comment by thomaseizinger** [comment]
Awesome, thank you! :)

**Comment by zachmccormick** [comment]
Oh this feature is awesome - I would love this too for @ColossusInnovation !!

**Comment by greysteil** [comment]
@zachmccormick no problem - I've enabled it on your account. 🎉

**Comment by artfwo** [comment]
Very nice feature. @greysteil can you please enable it for @freight-hub as well?

**Comment by greysteil** [comment]
Sure thing - done!

**Comment by Naveg** [comment]
would love this for @alloytech :)

**Comment by greysteil** [comment]
Done!

**Comment by Naveg** [comment]
Hmm - can't seem to get this working. When we approve dependabot PRs, nothing happens, but `dependabot merge` works as expected.

**Comment by greysteil** [comment]
Can you tag `@dependabot` in the next PR that happens in (and not merge it)?

**Comment by bobvanderlinden** [comment]
Is there already a way to configure this for dependabot? I'd like to enable this for a whole repo (so that the whole team is included). Is that a possibility?

**Comment by greysteil** [comment]
Yes - you can configure this in your account settings from your [dashboard](https://app.dependabot.com).

**Comment by bevanloon** [comment]
Hi - this is a fantastic feature - quick question:

Is this available on a per repo basis or is it only at the org level?

I assume this will also respect any protection we have against merging should tests fail? (Just in case someone is a little too quick on approving).

**Comment by feelepxyz** [comment]
> I assume this will also respect any protection we have against merging should tests fail? (Just in case someone is a little too quick on approving).

@bevanloon yup! You can set up branch protection to require status checks to pass before merging. The setting is only org level at the moment. You could use a GitHub Action to have more fine grained control per repo, here's one example (haven't tried it): https://github.com/pascalgn/automerge-action
