### ISSUE TITLE
Dependabot runs updates any time it wants

### ISSUE THREAD

**Issue by dekode-deployment** [dependabot/feedback#192]
Hi!
User: DekodeInteraktiv
We have specified that Dependabot run updates at 5 CEST. However just now it started a whole bunch of updates. (It is now 10:00 CEST). Why doesn't it adhere to our rules?

![image](https://user-images.githubusercontent.com/24959526/45804810-68ecf280-bcbd-11e8-8141-1db89243d719.png)

**Comment by greysteil** [comment]
Thanks for getting in touch. I've just taken a look through all of the update runs Dependabot created for your account today and they all ran at 3am UTC (5am CEST). It looks like that's also when your last batch of pull requests were created.

Can you link me to a PR that Dependabot created today when it shouldn't have done (if it's private you can email me on support@dependabot.com)? According to our database they were all created at 3am.

**Comment by dekode-deployment** [comment]
Yeah, sorry. My fault. These were PRs that were just then approved by a colleague. I am so sorry for blaming Dependabot. Hope he doesn't bear a grudge!

**Comment by greysteil** [comment]
Haha, no worries, he's a friendly sort and knows full well that he makes his own mistakes, too! 🤖
