### ISSUE TITLE
Is there a known reason why sometimes the automatic merging doesn't happen

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#195]
Sometimes, we have a PR like this: https://github.com/marshmallow-insurance/uk-auto-quoting/pull/421 which doesn't get auto merged. The PR was created and review checks passed within the time window that PR auto-merging is enabled for.

![screen shot 2018-09-25 at 12 30 51](https://user-images.githubusercontent.com/8789912/46011891-36793600-c0bf-11e8-91b2-96e5c2fb5be5.png)
![screen shot 2018-09-25 at 12 30 41](https://user-images.githubusercontent.com/8789912/46011892-36793600-c0bf-11e8-9ef3-10c21f362da8.png)

**Comment by davidgoate** [comment]
Ignore me, that's a major update and our config is for minor. Sorry - my mistake.

**Comment by greysteil** [comment]
Haha, phew - thanks for the feedback all the same 🙂
