### ISSUE TITLE
git target branch name is neither viewable nor editable after Add Project

### ISSUE THREAD

**Issue by joma74** [dependabot/feedback#199]
E.g. https://app.dependabot.com/accounts/joma74/repos with ts-in-js-1 gives list of two "projects" aka master and one branch. Guess which list item is which branch? From the interface onyl i may only guess which is which (because of the timestamp?). May have forgotten tomorrow :sleepy:

![selection_008](https://user-images.githubusercontent.com/5314859/46233831-8b91a200-c374-11e8-833a-98f899b644a4.png)

P.S. love the yarnlock only update feature, as it provides in-range semver compatible updates.

**Comment by joma74** [comment]
Uh, missed that it is on (i). Thanks,  should I close this issue?

**Comment by greysteil** [comment]
Let's close because Phil's aware, and because we have a couple of other issues for the (badly needed) dashboard v2, but this is still really valid feedback - thanks for it, and thanks for using Dependabot!
