### ISSUE TITLE
Allow weekly updates

### ISSUE THREAD

**Issue by pezholio** [dependabot/feedback#2]
For some, a daily update might be a bit too noisy and distracting. It might be nice to offer a weekly update frequency, then users can schedule a time every week to check over and merge dependency updates.

**Comment by hmarr** [comment]
Agreed - we'll get this implemented and update this ticket once it's shipped!

**Comment by hmarr** [comment]
Done. You can now select daily or weekly bumping. Weekly bumping occurs on Monday mornings (and no, that is not configurable 😉).

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#361
