### ISSUE TITLE
Check also plugins version for java gradle projects.

### ISSUE THREAD

**Issue by rosolko** [dependabot/feedback#20]
For example I'm adding versioned plugin to project:
```
plugins {
    id 'com.github.spotbugs' version '1.6.1'
}
```
And I will be nice if bot can check this version also.
Like [gradle versions plugin](https://github.com/ben-manes/gradle-versions-plugin) does.

**Comment by greysteil** [comment]
Thanks for the feedback. Our Gradle support is pretty rough at the moment, but getting it perfect is my next big priority. 🙂

**Comment by bsideup** [comment]
Hi @greysteil! The Gradle support got improved a lot since May, but the plugins are still not supported.

There are strict limitations on the format of `plugins {}` block ( https://docs.gradle.org/4.9/userguide/plugins.html#sec:plugins_block ), and it is not really a code (e.g. values can't be dynamic, only static constant strings are accepted).

Maybe you could have another look?
(given that you started using Regexp for parsing, it should be trivial)

Thanks! 👍

**Comment by greysteil** [comment]
This should be pretty straightforward - sorry for letting it drop! I'll try to get it shipped today.

**Comment by bsideup** [comment]
@greysteil OMG! What are you?! A magician?! 😂 💯

**Comment by greysteil** [comment]
Haha, hmm, well I might have spoken slightly too soon - didn't realise plugins have a different format to dependencies (i.e., they don't have a group). Will require a bit more work, but still totally doable. Give me a few days, as am at GitHub Universe at the moment without much time to code.

**Comment by bsideup** [comment]
@greysteil ofc, take your time (and enjoy the Universe) 👍 
Thanks for prioritizing it anyway, really happy to hear :)

Let me know if I can help somehow!

**Comment by kaidowei** [comment]
@greysteil is there any progress for this one? :)

**Comment by greysteil** [comment]
Not yet, sorry! Things have been a little crazy. I'll try to get to it in the next couple of weeks. :-)

**Comment by quittle** [comment]
Hi, just checking in as another interested party.  Do you think this might be doable soon?

**Comment by greysteil** [comment]
Sorry for the delay on this one y'all. It's implemented now, and will be released in the next 15 minutes 🎉

**Comment by 1951FDG** [comment]
I had to resort to the legacy plugin application format, the current implementation may not be working as it should and could use some testing.
