### ISSUE TITLE
Support for Docker images

### ISSUE THREAD

**Issue by dalberto** [dependabot/feedback#20]
Knowing when new Docker images are published would be helpful.

One issue I can see arising is that repositories may have multiple Dockerfiles.

**Comment by doismellburning** [comment]
This would be excellent please! I want to use [digests](https://medium.com/@RemindEng/docker-image-digests-be8b6b348efb) so our builds are more [reproducible](https://reproducible-builds.org/) but I like hand-updating hashes even less than hand-updating version numbers...

**Comment by greysteil** [comment]
I've made a start on this over at https://github.com/dependabot/dependabot-core/pull/95. I don't speak Docker, so can I get your review on it when it's ready @doismellburning? Should be pretty straightforward, and I'll flag the areas that need thinking about.

**Comment by doismellburning** [comment]
The more I look at this the more it feels like actually identifying the update could be a nightmare. My internal repos all use the convention "tags follow semver, variants are a different repo" which made this easier, but that's not the general / Hub convention cf. `python:3.6.2-onbuild` and `python:3.6.3-slim` (heck I don't even know why they're both not 3.6.3...)

It feels like at the moment, the main convention is "tags are opaque strings" and thus the best I've got right now is "track https://hub.docker.com/r/chauffer/docker-hub-rss/ and try to do some kind of hey-this-looks-like-a-version-number"... 💩

**Comment by greysteil** [comment]
Yeah, I think "looks like a version number" is going to be the way to go here, but that's fine. Dependabot is already going to need to handle that for git tag updating (which I'm going to release for Ruby this evening / early next week), so I'm comfortable with it trying to handle the 💩  for you...

**Comment by greysteil** [comment]
Dockers support is live! Quite a few caveats for the first version, as detailed in https://github.com/dependabot/dependabot-core/pull/95, but we'll keep improving it from here.

**Comment by dalberto** [comment]
Awesome! Thanks, @greysteil. Will be sure to try it out soon.
