### ISSUE TITLE
GitHub PR language labels (php, javascript, ...)

### ISSUE THREAD

**Issue by jbelien** [dependabot/feedback#200]
Hello,

On new(?) repositories, everytime @dependabot-bot makes a Pull Request, I have a label with the language ( `php`, `javascript`, ...) (see https://github.com/geo6/upload-geojson/pulls) but I don't have these labels on old(?) repositories (see https://github.com/jbelien/MapFile-Generator/pulls).

Is there a way to enable those language labels on all my repositories ?

Thanks a lot :)

**Comment by greysteil** [comment]
The difference here is whether a repo has Dependabot enabled for multiple languages or not
- If you're using Dependabot for multiple languages on a single repo then it will label each PR with the language
- If you're only using it for one language, it won't label the PRs with the language

If you want the language label then for now the easiest ways to get it on that repo would be either
- Get Dependabot to update your JS dependencies on that repo, too
- OR, create the label your self, label a Dependabot PR with it, and comment `@dependabot use these labels`

Hope that helps?

**Comment by jbelien** [comment]
That makes **complete** sense !
I didn't realised that only one language was enabled 😝 

Thanks a lot :)
