### ISSUE TITLE
[Feature request] Define pattern, list allowing dependency updates

### ISSUE THREAD

**Issue by cabello** [dependabot/feedback#201]
We use a micro-app architecture, so one main Javascript project depends on many other internal Javascript projects, at this moment we don't want the main Javascript project to update dependencies at will.

It would be nice to be able to define a pattern for which dependencies are allowed to be updated.

For example: "Include only: `@megacorp/*`" would update `@megacorp/foo` but it would not update `babel-core` nor `@types/react`.

It's likely that this feature would be useful in negate form as well, e.g "Exclude: `@types/*`"

Somewhat similar to: https://github.com/dependabot/feedback/issues/150

**Comment by benjyblack** [comment]
If the pattern solution is difficult to achieve, an alternative would be the ability to whitelist specific dependencies that Dependabot will look for. For instance:

```
@megacorp/banking-components
@megacorp/address-components
```

etc.

**Comment by greysteil** [comment]
Interesting, thanks for the feedback. I'm cc-ing @feelepxyz who's doing a redesign of our dashboards right now which should make specifying ignores a bunch easier.

**Comment by feelepxyz** [comment]
Yes thanks for the feedback! Planning on adding a page on the dashboard showing a list of all dependencies for a project, from which you would be able to select which ones to ignore. We have some loose future plans on adding a config file which could make specifying these a bit easier, but can't promise anything on this yet.

@cabello how have you architected your setup? Separate repos for each micro app that get published under a namespace? And whats your process for updating external libs like `babel-core`? Wondering if there's another way for us to help you keep these up to date too.

**Comment by greysteil** [comment]
Not perfect yet, but some level of whitelisting is now possible! 🎉 

It has to be done through a config file rather than your dashboard (we'll probably extend it to the dashboard in future), and the docs are [here](https://github.com/dependabot/feedback/issues/70#issuecomment-449377695).

Config files are brand new, so if anything's unclear just let us know. We're working to improve them, and to add more documentation and linting for them. We'll also be having a think about adding support for globs (it's not there yet) in future, too.

**Comment by greysteil** [comment]
New location for docs: https://dependabot.com/blog/introducing-config-files/

I'll keep this open until we support pattern matching.

**Comment by greysteil** [comment]
Basic pattern matching is now supported! If you use a `*` character in the `dependency_name` field for `automerged_updates`, `allowed_updates` or `ignored_updates` then it will match an unlimited number of arbitrary characters (or none). So specifying `@megacorp/*` is now possible. I've updated the config file docs accordingly.

Thanks for the feedback, and for your patience on this one.
