### ISSUE TITLE
Some Languages not showing dependency file paths

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#203]
Hi - I noticed this morning that the dashboard now shows which dependency files it is monitoring which is awesome! Just wanted to report what appears to be a bug - not all languages in a repo that I have set up multiple languages are showing the files that it is monitoring:

![](https://i.imgur.com/gy4xRm9.png)

Java and Javascript are not showing the dependency files that it is monitoring, but in other repos it appears to be fine.

**Comment by feelepxyz** [comment]
@RohanNagar great that you're enjoying the feature! The dependency file path gets set from the last update run, since we just added this feature and those two projects are on a weekly schedule we haven't set those files yet. They should show up once the updater runs!

**Comment by RohanNagar** [comment]
Got it, thanks!

**Comment by feelepxyz** [comment]
Oops, just fixed that weird display bug where the last bracket around `(Maven)` shows up front 🐛
