### ISSUE TITLE
Multi-language projects

### ISSUE THREAD

**Issue by madoar** [dependabot/feedback#208]
I have a project, where I'm combining multiple programming languages (https://github.com/Spielekreis-Darmstadt/lending).
In my case, I combine scala, maven (which both use maven for dependency management) and javascript (which uses npm for dependency management).
As far as I know, it is currently only possible for dependabot to create PRs, containing either maven or npm dependency updates and not both.

Therefore my question/suggestion:
Do you plan to support projects containing multiple programming languages and multiple dependency management systems?

**Comment by greysteil** [comment]
Hi @madoar,

Thanks for getting in touch, and apologies for the confusion. Dependabot can already support multi-language projects - all you have to do is click the "add project" button for an existing repo to add an additional language. Here's what the update configs for Dependabot Core look like, for example:

![image](https://user-images.githubusercontent.com/1144873/46766171-18275300-ccd9-11e8-9be0-167df3e22af4.png)

More generally, I'm sorry the dashboard doesn't make this as clear as it could do. We're going through a major overhaul of it right now, which should make it a lot more obvious!
