### ISSUE TITLE
Limit monitored subprojects/submodules

### ISSUE THREAD

**Issue by madoar** [dependabot/feedback#209]
Some project managements tools, like maven and gradle, allow for subprojects/submodules.
As far as I understand dependabot it is currently only possible to either have dependabot monitor a project including all its subprojects or none.
In some cases it may be useful to have dependabot monitor only a subset of the subprojects contained in a project.

Therefore my question/suggestion:
Is it possible to limit the monitored subprojects to a given set?

**Comment by greysteil** [comment]
@madoar - yes! You can specify a `directory` when adding a project (it's in the advanced options). If you do so, Dependabot will only update the project at that directory, rather than the whole thing.

**Comment by madoar** [comment]
Thanks for your answer, but this doesn't fully solve my issue.
My suggestion requires a more detailed adjustability, where you can select one or multiple projects/folders which you want to have monitored or excluded from monitoring.

Let's assume you have a project consisting of multiple subprojects which you currently want/need to overhaul by replacing certain modules, with new modules you're currently implementing.
In such cases, where you're currently implementing new modules, it may be obstructive if dependabot wants to update the dependencies of the submodule(s) you're currently working on, therefore it would be useful to exclude it for the moment until the overhauled modules are stable.

**Comment by madoar** [comment]
You're right I've forgotten, that you can add a project multiple times (like you have commented in #208).
Still it would be nice if you had a list of directories, which you can edit for a single project, instead of a list of projects, which each allow for a single directory.
I don't have a project yet, where I need this, it's just a thought I had, which I wanted to share.

**Comment by greysteil** [comment]
👍 awesome, well thanks for the feedback - always useful to hear user opinions, and makes it clear to me what is/isn't obvious about the dashboard!
