### ISSUE TITLE
trackable configs?

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#21]
The controls available via comment commands are pretty great, but once I set a particular option (e.g. label ruby deps with `backend`), I'm not aware of that decision being retrievable. I'd love to be able to set assignees, labels, etc via e.g. `.config/dependabot.yml` (yml because json doesn't support comments in general).

**Comment by ianwremmel** [comment]
As an additional enhancement, it might be handy if dependabot could manipulate that config file.

**Comment by greysteil** [comment]
I'm up for this in the long term, but in the short term I want to keep iterating the UI and setting for Dependabot, and committing to a `dependabot.yml` would slow down the iteration cycle.

I'm going to close this for now, but I'll keep it in mind - I can totally see the use case. Thanks for the feedback all the same. ❤️

**Comment by ianwremmel** [comment]
no problem, makes sense. maybe in the shorter term: can there be a comment command for request that config?

**Comment by feelepxyz** [comment]
@ianwremmel we launched config files recently - https://dependabot.com/blog/introducing-config-files/

**Comment by ianwremmel** [comment]
🙌
