### ISSUE TITLE
yarn.lock gets updated incorrectly

### ISSUE THREAD

**Issue by Hypnosphi** [dependabot/feedback#213]
After running `yarn install` on a dependabot's PR branch, `yarn.lock` gets changed, which shouldn't be the case

E.g. https://github.com/storybooks/storybook/pull/4391

This commit shows the diff that I get when running `yarn install`:
https://github.com/storybooks/storybook/pull/4391/commits/0809ec3ada32a741bc01df8b2d4876c9d5f34264#diff-8ee2343978836a779dc9f8d6b794c3b2

**Comment by greysteil** [comment]
That's definitely a bug! Thanks for flagging it - I'll look into it and get it fixed ASAP.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/0e923f172f97b7159c53e3de548ec327d0eccc69, which is deploying now. Thanks again for reporting this, and for using Dependabot!
