### ISSUE TITLE
Dependabot new Poetry lock file support

### ISSUE THREAD

**Issue by pythoninja** [dependabot/feedback#218]
As it was in #57, Poetry has been added but now they are changing pyproject.lock to poetry.lock.

More information about these changes is available here: sdispater/poetry#444 (not in the master atm but will be soon)

Do you have any plans to support it?

**Comment by greysteil** [comment]
Thanks for the heads up! I've just pushed https://github.com/dependabot/dependabot-core/pull/704, which will add support.
