### ISSUE TITLE
[python]: Missed update

### ISSUE THREAD

**Issue by JayH5** [dependabot/feedback#220]
Hi again 👋,

I have a missing update for a dependency and I'm not sure why. In [this file](https://github.com/praekeltfoundation/debian-wheel-mirror/blob/develop/requirements.txt) the dependency `Twisted==18.7.0` is listed, but version `18.9.0` was released on October 15th. I have this repo set to live updates and even pressed the "Bump Now" button, but there has been no Dependabot PR. Any idea what's going on?

Thanks 🙏

**Comment by greysteil** [comment]
Ooh, that is weird! Takinga  look now.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/4aeb19824beb2a79dbf11eee84b869a600371361. Thanks for the heads up @JayH5!
