### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by leogiertz** [dependabot/feedback#221]
We ❤️ Dependabot and it would be great if we could also let it update our iOS dependencies.

**Comment by RohanNagar** [comment]
There is also some discussion about CocoaPods over at dependabot/dependabot-core#416

**Comment by feelepxyz** [comment]
@RohanNagar nice one!
@leogiertz The main blocker on this is that Cocoapods still relies on activesupport 4.x to support Ruby 2.0 (we're on Rails 5 which requires activesupport 5.x). I've raised this issue again (hopefully time to move on soon) https://github.com/CocoaPods/CocoaPods/issues/7885

**Comment by leogiertz** [comment]
Great! I'm closing this one.
