### ISSUE TITLE
New `poetry` version now uses `poetry.lock`

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#222]
Hi! 

Just to be sure you have not missed this important update: https://poetry.eustace.io/blog/poetry-0-12-0-is-out.html

And it will still work with new `poetry` versions.
It now uses `poetry.lock` file instead of `pyproject.lock`.

**Comment by feelepxyz** [comment]
@sobolevn yes! @greysteil just added support https://github.com/dependabot/dependabot-core/pull/704 ✌️

**Comment by greysteil** [comment]
I do need to get https://github.com/dependabot/dependabot-core/pull/705 over the line, though. That's on my list for today 🙂
