### ISSUE TITLE
Error bumping dependencies

### ISSUE THREAD

**Issue by pythoninja** [dependabot/feedback#223]
```
Dependabot encountered an unknown error.

We've been notified of the problem, and are working to fix it.
```

This project is managed by Poetry, so dependabot look into pyproject.toml. Could you look at that error?

**Dependabot url:**  https://app.dependabot.com/accounts/pythoninja/repos
**Repo url:** https://github.com/pythoninja/adarklib

**Comment by greysteil** [comment]
I've seen it and it's on my list - should have it fixed by the end of today :octocat:

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/752f729107cb5fa326cbb700db6649ba4760dced.
