### ISSUE TITLE
Would dependabot keep working with yarn's "frozen-lockfile" option on?

### ISSUE THREAD

**Issue by jraoult** [dependabot/feedback#227]
I want to run `yarn install --frozen-lockfile` by default to make sure no-one is messing with the lockfile when installing. After all, this is one of the reason for having dependabot :) I'm about to follow the advice here https://github.com/yarnpkg/yarn/issues/4147#issuecomment-420769373: adding `--install.frozen-lockfile true` in my `.yarnrc.

I was wondering if dependabot would still work or will that prevent it from updating the lockfile as well?

**Comment by greysteil** [comment]
Good question. If it doesn't then it definitely should. I'll double check for you, but will have it working either way within the hour.

**Comment by greysteil** [comment]
Can confirm that Dependabot will continue to work just fine with that setup. ✌️

**Comment by greysteil** [comment]
(And for good measure, I've just added a test, so you can be sure this won't break in future. https://github.com/dependabot/dependabot-core/commit/6573b80880677acdba15cb3c9c6a17956461782b.)
