### ISSUE TITLE
Detect higher released versions when pointing to master

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/feedback#23]
Sometimes one has to specify things like

```ruby
gem "pry", git: "https://github.com/pry/pry"
```

You normally do this when you need to pick up not yet released bug fixes or features.

It'd be nice if dependabot could create a PR when a released version higher than the commit sha1 the gem is pointing to is made available.

**Comment by greysteil** [comment]
I've actually got a branch working on this right now. Working assumption is that you always want the latest commit sha (for the specified branch). Should be working in the next few days.

**Comment by deivid-rodriguez** [comment]
> Working assumption is that you always want the latest commit sha (for the specified branch).

What do you mean? That dependabot will also send updates when newer commit sha1's are released? I'm not sure people will like that? Normally master branches are considered unstable...

What I mean is that dependabot could update my Gemfile along the lines of:

```diff
- gem "pry", git: "https://github.com/pry/pry"
+ gem "pry", "= 0.11.0"
```

**Comment by greysteil** [comment]
Ah, interesting.

I'm thinking if you pin to `master` without specifying a commit SHA you probably want the latest commit - if you specify a reference we'd leave it be.

I like the latest version idea, though - I'll have a think how we could implement that.

**Comment by deivid-rodriguez** [comment]
> I'm thinking if you pin to master without specifying a commit SHA you probably want the latest commit - if you specify a reference we'd leave it be.

After a second thought, that'd be the perfect behavior for me indeed! :heart: 

When I want a specific fix or feature, I lock the ref

```ruby
gem "pry", git: "https://github.com/pry/pry", ref: "<commit_sha1_that_I_want>"
```

and I would only expect dependabot to update it when there's a released version containing the ref.

When instead I want to be a beta tester of the gem, I don't specify a `ref` and I would expect dependabot to always update the locked commit sha1.

**Comment by greysteil** [comment]
Just deployed this - check out https://github.com/greysteil/dependabot-test/pull/1 for an example. 🎉 

Thanks masses for the suggestion - I think this is a really great new feature.

**Comment by deivid-rodriguez** [comment]
It's so great @greysteil, fantastic job!
