### ISSUE TITLE
Maven Wrapper Feature Suggestion

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#23]
Some projects in the java maven world make use of the maven wrapper: https://github.com/takari/maven-wrapper

which lets a developer set the version of maven and have the build more consistently.

Updating the version requires automatic updating of the folder `.mvn/wrapper/maven-wrapper.properties`

e.g. `distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.2/apache-maven-3.5.2-bin.zip` -> `distributionUrl=https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.3/apache-maven-3.5.3-bin.zip` 

See: https://maven.apache.org/docs/history.html

Would be cool to have these being auto bumped.

**Comment by greysteil** [comment]
Interesting. Looks like this would be similar to the vendoring requests for Ruby, PHP, and pretty much every other language 😓. It's another reason for me to add vendoring support to Dependabot in general - I'll definitely get to it.

**Comment by greysteil** [comment]
Closed in favour of https://github.com/dependabot/dependabot-core/issues/485 (because this is a Dependabot Core issue).
