### ISSUE TITLE
Feature Request: Blacklist Dependencies

### ISSUE THREAD

**Issue by wvh-shanee** [dependabot/feedback#233]
It would be great if we could list (simple string or REGEX) dependencies that dependabot should ignore when checking for updates.  This would allow us to intentionally ignore specific fast moving dependencies that are causing us to have daily PRs that aren't useful.

**Comment by greysteil** [comment]
Thanks @wvh-shanee. @feelepxyz is actually working on the beginning of a dashboard view that will make this easier right now, but in the meantime I presume you've already seen that you can use `@dependabot ignore this dependency` to ignore a single dependency?

**Comment by wvh-shanee** [comment]
I had not seen that, but I'll go have a look now and set that up on our repos.  Thanks!

**Comment by greysteil** [comment]
Update: with config files you can now add a blacklist (`ignored_updates`) and a whitelist (`allowed_updates`) of dependencies. 🎉 

https://dependabot.com/blog/introducing-config-files/

**Comment by bjeanes** [comment]
Can the config file also be stored in `.github` as is conventional for many apps to do (including Renovate). This feels particularly suitable now that Dependabot is part of GitHub...

**Comment by greysteil** [comment]
Not at the moment, but once we're fully integrated with GitHub it will be. 🙂
