### ISSUE TITLE
Feature Request: dependabot.yml configuration

### ISSUE THREAD

**Issue by wvh-shanee** [dependabot/feedback#234]
Please consider implementing a configuration parser that looks for a dependabot.yml file inside the repo that we can use to specify settings, whitelists, blacklists, project users to be requested on PRs, etc.  This would make it very easy to set up multiple projects that have similar requirements by copying the YML file between projects.  It may also make it faster to develop new features since a UI change wouldn't be required in the early development of new settings.

**Comment by greysteil** [comment]
Thanks for the feedback @wvh-shanee! We've got an issue tracking this one at https://github.com/dependabot/feedback/issues/70.
