### ISSUE TITLE
Unable to add a project

### ISSUE THREAD

**Issue by mynkow** [dependabot/feedback#236]
https://gyazo.com/b5e7e29d0fe92eb725b7815923a649ce

The screenshot show the error. Here is the project. There is a csproj file inside

https://github.com/mynkow/DotNetCore.WindowsService

What am I missing?

**Comment by feelepxyz** [comment]
Ah looks your file isn’t in the root folder. You’ll need to change the directory to ‘/src/WindowsServiceHost’ for that repo by clicking the cog icon.

Thanks for getting in touch and sorry for the not so helpful error message! We have some improvements planned for this page.
