### ISSUE TITLE
Feature Suggestion OWASP Scan

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#24]
dependabot could perhaps provide reports on java maven projects after analysing the dependencies in `pom.xml` with the OWASP scanner https://www.owasp.org/index.php/OWASP_Dependency_Check and provide badges or PR status checks for PR's being created by developers in their normal workflow

**Comment by greysteil** [comment]
Thanks @davidgoate. I'm really keen to add security checking for Java - will take a look at this in the next couple of weeks.

**Comment by davidgoate** [comment]
@greysteil not indeed not! I think our card fraud system kicked in a didn't like the sudden payment so it failed! We will contact the card company today and see if we can resolve. I'm hoping all of our repos are still configured in dependabot and I don't have to start from scratch again adding them all and configuring reviewers and assignees and ignored major versions etc. Love the product and will try to get it sorted in next day

**Comment by greysteil** [comment]
That’s great news.

Dependabot will continue to work as normal in the meantime - you’ll just get a note on any PRs that it creates warning you that your private repos would be deactivated in a week or so if payment wasn’t set up again.

Thanks for all your feedback over the last couple of weeks!

**Comment by davidgoate** [comment]
@greysteil on that note it would be awesome to be able to configure a team or people as reviewers and assignees globally for the organisation per technology, e.g. java pulls, docker pulls, JS pulls for ALL repos in the org. I really love the innovative chat bot nature of just tagging `@dependabot` in the PR but the downside is for each repo i need to first wait for the first PR to arrive, manually assign reviewers and assignees and then type two things to dependabot. Great for one or two repos, less cool for 10+. Also easy to forget on new repos we set up which would mean that if we are filtering on PR's assigned to us or marked for review they get missed. Just a suggestion ;)

**Comment by greysteil** [comment]
Interesting. I'm planning to release an API today or tomorrow that would make that possible, but having a "defaults" section at the account level sounds sensible, too. I'll have a think about how to implement it.

**Comment by greysteil** [comment]
We're integrated with Sonatype's OSS Index now, which provides Java vulnerability data 🎉
