### ISSUE TITLE
Unable to scroll immediately after adding a new project

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#24]
on `https://app.dependabot.com/accounts/<account>/repos`

I used "Add project" to add a project.
I then wanted to scroll to the "Add Project" button again...but I could not scroll until the alert message disappeared.

Expected behavior:
- Scroll should be possible even while the alert message was visible.

note: this only became a problem once I had added > 6 projects... and I was trying to add 3 more.

I suspect that if I had clicked "x" on the message, I would have been able to scroll...I don't have another project to add right now, so I cannot confirm.

**Comment by greysteil** [comment]
@hmarr - can you take a look at this one?

**Comment by greysteil** [comment]
FYI, @hmarr dug into this and it's a bug in blueprint. We've put in a [PR](https://github.com/palantir/blueprint/pull/1684) to fix it, and will have scrolling fixed as soon as it's released.

Thanks for the feedback!

**Comment by greysteil** [comment]
Fixed! Thanks again for the feedback @rdunlop.
