### ISSUE TITLE
Creation of security PRs for sub-dependencies is only attempted once

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#240]
For [this repo](https://github.com/panorama-ed/rainbow-backend), we've noticed that Dependabot only ever seems to have one PR open for security fixes, despite GitHub telling us that there are multiple vulnerabilities. This might be related to the fact that when we initially added Dependabot for that repo, the first "scan" resulted in an error message in the Dependabot UI.

**Comment by greysteil** [comment]
That's odd. Looking through our logs I can see that Dependabot is occasionally timing out when trying to update that repo, which might lead to some security fix PRs not being created (for sub-dependencies, Dependabot will only attempt to create the PR once and if it fails to do so won't try again).

Let me see what I can do about fixing that. For vulnerable dependencies Dependabot should repeatedly try to create the PR if it fails.

**Comment by greysteil** [comment]
Fix deployed - Dependabot will check for insecure sub-dependencies every time it does an update run, so it won't matter (as much) if it encounters an error during the initial check. Thanks for reporting this!

**Comment by JacobEvelyn** [comment]
Thanks!
