### ISSUE TITLE
Support gems.rb

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#241]
I've just added a couple of repos that use `gems.rb` instead of `Gemfile`, expecting it to work (as it does in bundler 1.17.1 on the command line), but it didn't like it :(

Is this something you're intending to add in future, or should I stick to `Gemfile` for now?

**Comment by greysteil** [comment]
Oh, I didn't realise we'd shipped that with 1.17.0 - is it not still behind a feature switch?

We're absolutely planning to support it, but you'd the first to need it!

**Comment by greysteil** [comment]
Support added in https://github.com/dependabot/dependabot-core/pull/747. Do you have a repo to test it on? I'll deploy the change now.

**Comment by Floppy** [comment]
Hey @greysteil, sorry, I missed the notification on this one. It looks like it's working fine, thank you!
