### ISSUE TITLE
Additional labels

### ISSUE THREAD

**Issue by edahlseng** [dependabot/feedback#242]
In addition to the `dependencies` label that dependabot adds, it would be awesome if other labels (`patch`, `minor`, `major`, etc.) were added! Our team would like to use this information to trigger other pieces of our workflow, which differ based on the type of dependency update.

**Comment by greysteil** [comment]
On `patch`, `minor`, `major` you're in luck - if you've already got those labels (all three of them) then Dependabot will use them. Logic is [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/labeler.rb#L177-L179).

Any others you'd like to see?

**Comment by edahlseng** [comment]
Ah, that's awesome! We didn't have the labels created ahead of time – will try that out now, thanks!

Those are the only three that we're looking for right now!
