### ISSUE TITLE
yarn.lock breaks for github commits updates

### ISSUE THREAD

**Issue by iCrawl** [dependabot/feedback#243]
At a glance this looks very similar to #213

But I am a bit unsure since this was supposed to be fixed almost 20 days ago and deployed too (regarding the last comment)

As you can see here:
https://github.com/Naval-Base/yukikaze/commit/f0c2348800fe28e93ab990c0557531c6f2e74d74#diff-8ee2343978836a779dc9f8d6b794c3b2R484

I had to delete my yarn.lock file and reinstall deps listed in the package.json so it reverts to the correct syntax, which seems to be this:
https://github.com/Naval-Base/yukikaze/commit/e655739c78c248a091264dec5ad4a0b568701cd3#diff-8ee2343978836a779dc9f8d6b794c3b2R481

**Comment by feelepxyz** [comment]
@iCrawl thanks for reporting this! Looks like we're not dealing with installs using the github shorthand, e.g. `yarn add discord.js@discordjs/discord.js` - looking into it now.

A current workaround is to install from the git url, e.g. `yarn add https://github.com/discordjs/discord.js`

**Comment by iCrawl** [comment]
I get by just ignoring the dependencies for now (it's not a lot, actually just 2 where I should, like a good developer does, pin the commits anyway 😄 ), thanks for the fast answer!

**Comment by feelepxyz** [comment]
@iCrawl just got this fixed, the lockfile should update correctly on the next run. Should I unignore the deps for you?

The fix for reference: https://github.com/dependabot/dependabot-core/pull/735/commits/32f68c8745c756fbe77cd4a650bd0331c162b7dc

**Comment by iCrawl** [comment]
Damn you guys work fast 👍 

@feelepxyz if thats a possbility yes, that would be very nice!

**Comment by feelepxyz** [comment]
@iCrawl removed the ignores for `discord-akairo` and `discord.js` ✌️
