### ISSUE TITLE
Close PR if the Gem is yanked

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#244]
This morning, I had a dependabot PR opened for concurrent-ruby 1.1.0.
I merged it, and my build failed, because concurrent-ruby 1.1.0 doesn't exist in rubygems.

It appears that the gem was yanked.

Would it be possible to update the PR (maybe even close it) if the gem is yanked from the rubygems repo?

**Comment by rdunlop** [comment]
Thanks Grey

**Comment by rdunlop** [comment]
@greysteil looks like they want more changes on your PR.

**Comment by greysteil** [comment]
PR is merged and Dependabot is now received yanked webhooks. We'll close any open PRs when we receive them. 🎉
