### ISSUE TITLE
Typo in the app overview

### ISSUE THREAD

**Issue by ffflorian** [dependabot/feedback#249]
Hi there,

in the [app overview](https://app.dependabot.com) it says "Add Langauge" instead of "Add Language".
In the modal it also says "Add a **langauge** to `<repo name>`".

**Comment by greysteil** [comment]
Nice catch, thanks! @feelepxyz I’m on the road, can you push a fix?

**Comment by feelepxyz** [comment]
@ffflorian yes nice catch, fixed!

**Comment by ffflorian** [comment]
That was quick, thanks :slightly_smiling_face:
