### ISSUE TITLE
Update shown on wrong account page

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#25]
I have multiple accounts set up.
One for my OpenSource stuff, one for my work stuff.

I was on my OpenSource one (rdunlop), and I did a "Bump Now". I then opened another browser tab...and was doing other stuff on github (unrelated).

When I returned to the dependabot page (https://app.dependabot.com/accounts/rdunlop/repos) it showed me a repo which is in a different account.

It showed me "Hang on, bumping now" status update for a `tablexi` repo.

Expected behavior: it should not show updates if I have browsed to a different account.

**Comment by greysteil** [comment]
Thanks @rdunlop.

@hmarr - looks like a redux issue?

**Comment by hmarr** [comment]
Sorry for the delay, @rdunlop, and thanks for reporting this! I think I've figured out what caused this, and I'll have it fixed in the next day or so.

**Comment by hmarr** [comment]
This should now be fixed - please let us know if you spot any other funky behaviour!

Thanks again for reporting this.
