### ISSUE TITLE
Wrong versions shown in PR title

### ISSUE THREAD

**Issue by idris** [dependabot/feedback#250]
See screenshot below.  It updated `cryptiles` from `3.1.2` to `3.1.3`, but the PR title says "from 2.0.5 to 4.1.3".  _Neither the "from" nor the "to" are correct!_

<img width="1642" alt="screen shot 2018-11-05 at 1 46 12 pm" src="https://user-images.githubusercontent.com/13989/48019317-2d897480-e101-11e8-81b2-48dfb3c19e49.png">

**Comment by greysteil** [comment]
That doesn’t look right! Can you link to the PR, or email it’s address to support@dependabot.com, so I can debug? Thanks!

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/b917ac195748f2d2812071c3cffaf7b77b6b5489 - thanks for reporting this!
