### ISSUE TITLE
Auto-merge with approving reviews required

### ISSUE THREAD

**Issue by marcotc** [dependabot/feedback#253]
For our `master` branch, we have "Require pull request reviews before merging", with "Require review from Code Owners" and "Required approving reviews: 1".
These settings have been working pretty well for our organization.

At the same time, we'd like Dependabot to be able to auto-merge (in our case only "Patch updates").
But because of these restrictions, we get this error in our repositories:

````
Dependabot tried to automerge this PR, but received the following error from GitHub:

```
You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.
```

As a result, we've disabled automerging on this repo (you can re-enable it in your Dependabot settings).
````

Is there any suggestion on how to allow Dependabot to auto-merge in such a scenario?

**Comment by tuky** [comment]
Could we reopen this @greysteil ? https://github.com/dependabot/feedback/issues/86 is now closed, but the issue here is still a problem.

**Comment by greysteil** [comment]
I don't work on Dependabot anymore - @feelepxyz may be able to help, though 🙂

**Comment by feelepxyz** [comment]
@tuky which branch protection setting are you having issues with? If you require reviewers to approve you can't use Dependabot's automerging, you can instead enable "Treat PR approval as a request to merge" in the [Dependabot Dashboard](https://app.dependabot.com/) under your account settings.

The other option is to use something like https://github.com/palantir/bulldozer which can be configured with policies.

**Comment by tuky** [comment]
> If you require reviewers to approve

Yes, exactly. Just like OP. It would be super helpful, if that was possible out of box. Having to use other 3rd party integrations would over kill considering this seems like a common issue. Especially with many repos to manage.

**Comment by feelepxyz** [comment]
@tuky great, that should work if you toggle that setting from your dashboard and disable automerging.

**Comment by tuky** [comment]
> and disable automerging.

But automerging is what we want: (humans') PRs have to be reviewed, but the bot shall still automerge e.g. patch versions without a human's review.

**Comment by feelepxyz** [comment]
@tuky ah I see. If you enable GitHub branch protection with required reviewers there's no way for Dependabot to merge them based on the auto-merge settings (e.g. only patch releases). You could still set up a GitHub action to auto-approve any Dependabot PRs and enable the toggle I suggested to achieve something similar but this would merge all PRs from Dependabot.

What you are suggestion sounds like a super useful product feature. We've previously heard feedback on different notification settings for human PRs vs bot PRs. We'll keep it in mind when figuring out what to prioritise.
