### ISSUE TITLE
.NET dependency not checked

### ISSUE THREAD

**Issue by pascalberger** [dependabot/feedback#254]
I setup dependabot to monitor https://github.com/bbtsoftware/TfsUrlParser/tree/develop/src. The `packages.config` in both projects contain several outdated dependencies (e.g. XUnit), but dependabot doesn't create PRs for them.

**Comment by greysteil** [comment]
Looks like Dependabot isn't finding those files for some reason - let me dig into what's going on there. Thanks for reporting it!

**Comment by greysteil** [comment]
Ah, I see what the issue is here. Will have a fix deployed today.

**Comment by greysteil** [comment]
Fixed! Thanks for your patience.

**Comment by pascalberger** [comment]
@greysteil That was fast! Thanks 👍
