### ISSUE TITLE
Can't add new repositories to dependabot for large GitHub orgs

### ISSUE THREAD

**Issue by SteveMarshall** [dependabot/feedback#257]
It doesn't appear to be possible to add new repositories to dependabot for users in the @ministryofjustice GitHub org. When we try to do so, we are met by the error `GET https://api.dependabot.com/repos`. I *assume* this is because we have ~770 public repos (and ~1300 repos total) and something is timing out? Is there any way we could get this fixed: we'd really like to use dependabot more widely, but this is something of a blocker…

**Comment by SteveMarshall** [comment]
Oh, I've just managed to get to the “add repo” page… But it seems inconsistently accessible. How odd.

**Comment by hmarr** [comment]
You're right - we did just get alerted about a timeout. We'll get it fixed
ASAP. Sorry about that!

**Comment by SteveMarshall** [comment]
That’s great, thanks! 🎉🎉🎉

**Comment by hmarr** [comment]
We just deployed this change, so you should be able to see all your repos now :-)

Thanks for bearing with us! And please let us know if you spot anything else acting up.

**Comment by hmarr** [comment]
I noticed the request to view currently _active_ repos (as opposed to repos that haven't yet been activated) was also looking a little slow for large organisations. So, apologies if you've had any issues with that. I've just rewritten the endpoint to make it a fair bit quicker and I'll continue to keep an eye on the metrics to make sure we avoid hitting any timeouts.

**Comment by greysteil** [comment]
Just found another place in our codebase (on bulk create) that was paging through all repos and caused a timeout when someone from MoJ tried to add a couple of repos today. I've moved that endpoint across to the new strategy and you shouldn't see timeouts there (or anywhere else) anymore.

**Comment by SteveMarshall** [comment]
Wow, thanks gang! This is great!
