### ISSUE TITLE
Configuration of private gemservers without hardcoding credentials

### ISSUE THREAD

**Issue by BRMatt** [dependabot/feedback#26]
We use a private gemserver hosted by packagecloud.io. We configure our development/CI environments to pass the packagecloud credentials to bundler using environment variables or `bundle config`. 

We don't really want to hardcode the credentials for this server in our Gemfile. Would it be possible to configure the API key within dependabot's UI (preferably at the organization level), or at the very least, disable the checking of private gem servers? Our repos use the following setup to selectively pull gems from the private server:

```ruby
source 'https://packagecloud.io/geckoboard/internal-ruby-gems' do
  gem 'private-gem-here', "~> 9.17"
end
```

**Comment by greysteil** [comment]
Hey @BRMatt,

Sounds sensible. We're running into the same issue for Dockerfile updates, too, so I'm keen to look at it over the next few days.

In the meantime, unfortunately we can't disable checking of private servers - Dependabot needs to be able to resolve your Gemfile to figure out what versions to update you to (we update you to the latest resolvable version, *not* the latest version, although over time it amounts to the same thing).

Let me take this one away and I'll get back to you in the next few days. I can't promise we'll have a solution today, but we should do in the next few days.

**Comment by BRMatt** [comment]
No worries, thanks for the prompt reply! 😃

**Comment by greysteil** [comment]
OK, I've got a solution for this on the backend. It's too beta to put into the frontend just yet (we need to lock down the security on exactly what people can pass us, because Bundler handles it very liberally), but if you encrypt your packagecloud credentials and ping them over to support@dependabot.com then I'll get you set up manually. I'm `greysteil` on keybase.

**Comment by BRMatt** [comment]
Thanks @greysteil! I'm happy to wait until this is in the frontend, no rush!

**Comment by greysteil** [comment]
Backend is done, and the frontend will be shipped tomorrow, as soon as @hmarr gets a chance to finish it. 😄

**Comment by shaneog** [comment]
Thank you both!! _(I need it for Ruby right now, and for Yarn later)_

**Comment by hmarr** [comment]
@shaneog @BRMatt - config variables are now live. From within your Dependabot account click the account dropdown (top right) and select "Config variables". From there you can enter Ruby config variables, which are passed to Bundler. The flow should be self-explanatory, but if it isn't, let me know!

**Comment by BRMatt** [comment]
Thanks, that was pretty straightforward!

**Comment by greysteil** [comment]
You're welcome! Now, if you fancied updating Geckoboard's account to a paid plan we'd be forever grateful 😉 . (You signed up just before we went live in the [marketplace](https://github.com/marketplace/dependabot), so are currently getting everything for free.)

**Comment by BRMatt** [comment]
Sure! FYI clicking "manage plan" in dependabot really freaked me out because it linked to an order page on my personal account, setup to pay $180/year. It'd be great if it could include `?account={org name}` so that it links to the plan my org has.

**Comment by greysteil** [comment]
Interesting - looks like that's a bug on the GitHub side, since we tell them the target organisation when we send people across to upgrade. I'll get in touch with them and hopefully they can fix it quickly (the marketplace stuff is so new that they're still working out a bunch of issues with it).

**Comment by shaneog** [comment]
Thank you @hmarr and @greysteil!
