### ISSUE TITLE
Possible production issue?

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#261]
Is Dependabot down? I get asked to install dependabot again and if i click that it says that my account is already on the unlimited plan. If i try to navigate to my repo list I see:

![screenshot 2018-11-09 at 15 12 57](https://user-images.githubusercontent.com/8789912/48270484-1ebcfd80-e432-11e8-9300-3ad39f86f85d.png)

**Comment by greysteil** [comment]
Yes, sorry, we're working to bring it back up right now. We've been down for around 5 minutes.

**Comment by greysteil** [comment]
We're back up. Sorry about that!
