### ISSUE TITLE
Misformatting of --hash in requirements.txt

### ISSUE THREAD

**Issue by jklukas** [dependabot/feedback#265]
We have pip requirements files that include hashes like:

```
flake8==3.5.0 \
    --hash=sha256:c7841163e2b576d435799169b78703ad6ac1bbb0f199994fc05f700b2a90ea37 
```

But Dependabot seems to be getting tripped up ~~by whitespace~~ and is issuing PRs where 
~~a blank line is inserted, and then~~ the new hash ends up concatenated with the old hash:

```
flake8==3.6.0 \
    --hash=sha256:6a35f5b8761f45c5513e3405f110a86bea57982c3b75b766ce7b65217abe1670--hash=sha256:c01f8a3963b3571a8e6bd7a4063359aff90749e160778e03817cd9b71c9e07d2 
```

Example: https://github.com/mozilla/gcp-ingestion/pull/177/files

**Comment by jklukas** [comment]
We're moving hashes to the same line, which will likely cause a rebase. Here's the specific commit:

https://github.com/mozilla/gcp-ingestion/pull/177/commits/01e7df3f9861f041bbfc9fccd1a921bc2efaa42d

**Comment by jklukas** [comment]
Looks like this was not a whitespace issue as I originally thought. We moved hashes to the same line as dependency declarations, but are still seeing multiple `--hash=` entries being concatenated together without whitespace separating them. See updated https://github.com/mozilla/gcp-ingestion/pull/177

**Comment by greysteil** [comment]
Taking a look into this now - thanks for flagging it.

**Comment by greysteil** [comment]
OK, I've just pushed https://github.com/dependabot/dependabot-core/commit/9c275b2dd3577e2b711d2d8ee28626ad6dc9e758 which I think is the right solution here.

However, with the new logic Dependabot will continue to add multiple hashes to your requirements.txt file if multiple hashes are available. I can see that you're using a single hash for each dependency - how are you choosing which to use?

**Comment by jklukas** [comment]
Adding multiple hashes sounds reasonable.

cc @relud who may be able to add more context on our existing strategy for choosing hashes

**Comment by relud** [comment]
> I can see that you're using a single hash for each dependency - how are you choosing which to use?

I was choosing the hash that pip reported as missing. That worked because our docker image is consistent enough for pip to choose the same hash every time, and docker is our only supported environment. I'm not attached to that process, adding multiple hashes is also fine with me.

**Comment by greysteil** [comment]
I'll wait for your decision on https://github.com/mozilla/gcp-ingestion/pull/174 before closing this. If having a single hash is important to you I should be able to add some logic to
1) Detect that you're using single hashes
2) Figure out details of the hash that you were using before
3) Use that to pick a hash from the range returned by hashin

It'll be quite a bit of work on my side, but if it's important to you then it's worth doing.

**Comment by jklukas** [comment]
We're fine with the multiple hashes.

Thanks for the quick response on fixing this!

**Comment by greysteil** [comment]
My pleasure - thanks for using Dependabot :octocat:
