### ISSUE TITLE
Wildcards for auto-merge in Java

### ISSUE THREAD

**Issue by jodastephen** [dependabot/feedback#267]
I'd like to have dependabot automatically merge all version updates from the AWS Java SDK, but that consists of many separate jar files. These jar files are all released together, so there is actually only one version number to be updated in the Maven `pom.xml`. The closest I can get at present is to navigate the UI and add each one separately:

![dependabot1](https://user-images.githubusercontent.com/213212/48484916-61564f80-e80f-11e8-9ada-dddcab80aba2.png)

Doing the above is slow and error-prone. It also doesn't handle all the jar files in the AWS SDK, just the ones we currently depend on, thus if we depend on another jar file in the future it wouldn't be covered.

A more convenient approach would be to add `com.amazonaws:aws-java-sdk*`. I'd hope such a wildcard approach wouldn't be too hard to implement.

While I'm here, I think #70 (a yaml config file) should also be a top priority as I really shouldn't be using a UI for any of this - infrastructure as code.

**Comment by greysteil** [comment]
Thanks for the feedback @jodastephen. We're planning to work on config files over the next week, so should at least have an easier interface for this soon.

**Comment by greysteil** [comment]
Just added support for wildcards! If you're using config files, using a `*` anywhere in a dependency name will match an unlimited (or zero) arbitrary characters.

Thanks for the feedback!
