### ISSUE TITLE
Not picking up updates for setuptools

### ISSUE THREAD

**Issue by dstufft** [dependabot/feedback#269]
It appears that Dependabot does not notice updates for setuptools, even if setuptools is currently being pinned as pypa/warehouse has it.

**Comment by greysteil** [comment]
Looks that way - I had no idea. Will dig into it now.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/5aaca13ac45472a83002a77e60a105b739f05877, which is deploying now. Thanks for reporting this one!
