### ISSUE TITLE
Custom Requirements File for Python Dependencies

### ISSUE THREAD

**Issue by joelbcastillo** [dependabot/feedback#27]
We use multiple requirements files stored in a `/requirements` folder in our projects to manage dependencies for specific environments (such as debug packages for our development environment). 

Pip allows us to install these dependencies as needed by just specifying the filename e.g. `pip install -r requirements/dev.txt`.

Is it possible to allow us to specify the Python requirements file if it the standard `requirement.txt` file is not found.

For an example of this, see [CityOfNewYork/NYCOpenRecords](https://github.com/CityOfNewYork/NYCOpenRecords)

**Comment by greysteil** [comment]
Interesting. Would be nice to support specifying a specific file, and I think we're going to need that for other languages anyway (I'm thinking of Dockerfiles in particular). I'll have a think and see what we can do.

In the meantime, if you were to place a `requirements.txt` file in the requirements folder of https://github.com/CityOfNewYork/NYCOpenRecords, which required in all of the other requirements files in there, then you could give Dependabot that directory and it would update all the files in there for you. A bit of a hack, though...!

**Comment by joelbcastillo** [comment]
That makes a lot of sense. We'll try out the hack for now. 

Thanks!

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/pull/166 (which detects a much broader group of requirement.txt files). 🎉
