### ISSUE TITLE
Any plans for Shellcheck integration

### ISSUE THREAD

**Issue by thcp** [dependabot/feedback#271]
Any plans for integrating this awesome product with https://www.shellcheck.net/ ?

**Comment by greysteil** [comment]
None for the moment - what kind of an integration would you want there? PRs for spellcheck fixes?

**Comment by thcp** [comment]
From [ShellCheck github](https://github.com/koalaman/shellcheck) page:

**The goals of ShellCheck are**

- To point out and clarify typical beginner's syntax issues that cause a shell to give cryptic error messages.

- To point out and clarify typical intermediate level semantic problems that cause a shell to behave strangely and counter-intuitively.

- To point out subtle caveats, corner cases and pitfalls that may cause an advanced user's otherwise working script to fail under future circumstances.

Currently we are using shellcheck directly on our Jenkins builds due the large rotation/issues that my company is facing with offshore developers, and by that we are looking to some options.

**Comment by greysteil** [comment]
Thanks for the feedback. I don't think this is something we'll integrate into Dependabot - if we go into the CI space more broadly I'll definitely keep it in mind, though.
