### ISSUE TITLE
Failing with `uninitialized constant` in vendored gem

### ISSUE THREAD

**Issue by kitop** [dependabot/feedback#273]
We're trying dependabot, and can't get it to run because of the following error:
```
Bundler::GemspecError with message:  (Dependabot::DependencyFileNotEvaluatable)
[!] There was an error while loading `my_gem.gemspec`: uninitialized constant MyGem. Bundler cannot continue.

 #  from /home/dependabot/dependabot-updater/tmp/vendor/gems/my_gem-1.0.0.c5f320cd44/my_gem.gemspec:7
 #  -------------------------------------------
 #    spec.name          = "my_gem"
 >    spec.version       = MyGem::VERSION
 #    spec.authors       = []
 #  -------------------------------------------
```

At the top of the `gemspec` file, there's a
```ruby
require File.expand_path("lib/my_gem/version.rb", __dir__)
```
that defines
```ruby
class MyGem
  VERSION = "1.0.0.c5f320cd44"
end
```

I can reproduce the error locally when cloning `dependabot-scritps` and running it against the  repo, but wasn't able to figure out exactly why it happened. In that script, it happens when calling `checker.can_update?(requirements_to_unlock: :own)` even when I'm targeting another gem.

Is this expected? Is there a trick to make dependabot work with vendored gems? 

Found https://github.com/steakknife/svg-flags-rails/issues/13 as a similar issue, but no other references.

**Comment by greysteil** [comment]
Ah, this is going to be a problem with sanitization. Let me take a look.

**Comment by kitop** [comment]
Thanks!! Let me know if you need any other information, happy to help. 
We really want to use dependabot, but this is currently blocking us 😞

**Comment by greysteil** [comment]
This should be fixed by https://github.com/dependabot/dependabot-core/commit/1b22e5661343a30eae5583cf1e807945b8451133, which is deploying now. I'll re-run Dependabot on the affected repos as soon as it's out.

**Comment by kitop** [comment]
That was fast! Thanks @greysteil!!
