### ISSUE TITLE
Email Reply Runs all Commands

### ISSUE THREAD

**Issue by dav-is** [dependabot/feedback#277]
If I directly reply to an email it appends the dependabot message to the bottom of it automatically. For some reason it will run all the commands that were listed in the Commands section. 

This is where it happened to me: https://github.com/dav-is/connordav.is/pull/34

**Comment by greysteil** [comment]
Woah, that's the first time I've ever seen that. I'll get it fixed right away.

Out of interest what email client are you using?

**Comment by dav-is** [comment]
Zoho but this behavior is common in any email client I've used. It's easier to just reply to a notification email than to open GitHub.

Thanks again!

**Comment by greysteil** [comment]
Thanks. GitHub has logic that removes the previous email bodies from the comment, but it looks like it's not being applied for some reason, so Dependabot is getting the full previous email text back. I'm guessing that's due to a transformation that Zoho applies, but Dependabot should be more robust to this regardless!

**Comment by greysteil** [comment]
It definitely looks different to me coming from your email - the email notification I got for you last comment, for example, included the full text of my previous post. That doesn’t normally happen (probably isn’t happening for you for this email reply, for example.).

Either way, Dependabot needs fixing here!

**Comment by greysteil** [comment]
I mean, unless GitHub just changed something and broke this, which is also possible.

**Comment by greysteil** [comment]
FYI, you can see the difference in comment style between our two email clients by looking at the API response [here](https://api.github.com/repos/dependabot/feedback/issues/277/comments). It looks like Zoho doesn't insert `>` characters, which is what's tripping Dependabot up.

**Comment by dav-is** [comment]
It looks like your email client revealed your mute thread link 🤔 looks like GitHub has some work to do

**Comment by greysteil** [comment]
Indeed! In the meantime I've added some sanitization logic on our side that should ensure this doesn't happen again. Thanks for reporting this, and apologies for the bug!
