### ISSUE TITLE
Using Google Container Registry

### ISSUE THREAD

**Issue by niels-s** [dependabot/feedback#279]
Hey,

I noticed support was added to use private docker registries and I was giving it a try with the [Google Container Registry](https://cloud.google.com/container-registry) we use in our company.
I tried the approach explained in the documentation here: https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file. That means adding the service account as password but when I tried to add this config in Dependabot I ran into an issue that the secret password was too long over 2000 chars. Is there a possible way to fix this or another approach to get the Google Registry working?

**Comment by hmarr** [comment]
Sorry about this - we'll bump the limit for you :-)

Could you run a `wc -c` on the file to give us a rough sense of what limit you'd need?

**Comment by niels-s** [comment]
I examined a couple service account secrets they are around 2344 - 2346 characters. So 2350 would be sufficient for us right now.

**Comment by hmarr** [comment]
Thanks – I've bumped the limit to 3000. It'll be out in 10-15 mins once it's made its way through the CI & deploy pipeline.

**Comment by niels-s** [comment]
@hmarr I've been testing several different approaches to get a Private GCP Container Registry working without any luck so far. Putting the service account json file in as password like mentioned here https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file didn't really work. I've also tried another approach by using the password secret generated by `gcloud auth configure-docker`.
Unfortunately debugging isn't really possible since the error message we see only mentions it can't authenticate.

Perhaps you have any tips how we could debug this? Or you find the time yourself to take a further look at it?

**Comment by greysteil** [comment]
Hey @niels-s,

Huh, sounds like there's some more work to be done on our side on this one then.

For testing, check out https://github.com/dependabot/dependabot-script/blob/master/update-script.rb. You'll need to add your credentials to the credentials array at the top - they'll look something like:

```
credentials = [
  {
    "type" => "git_source",
    "host" => "github.com",
    "username" => "x-access-token",
    "password" => "a-github-access-token"
  },
  {"type"=>"docker_registry", "password"=>"your password", "username"=>"your username"}
]
```

The code that Dependabot is running to do the lookup is all at https://github.com/dependabot/dependabot-core. I'll also take a look from my side.

**Comment by greysteil** [comment]
Digging into this, I'm pretty use that all that's required is for you to change the username on your credentials to `_json_key`, as described at https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file. Everything should work perfectly then.
