### ISSUE TITLE
PHP Library support

### ISSUE THREAD

**Issue by aensley** [dependabot/feedback#28]
I just setup a free Dependabot account to check my PHP projects on GitHub.

I've tried both:

* https://github.com/aensley/file
* https://github.com/aensley/media-organizer

Both projects have `composer.json` and `composer.lock` files in the root directory.

I get this error message when trying to add them:

> Dependabot is designed for applications, and doesn't support Php libraries as their dependency management needs are very different.

I don't understand either what this means or why it is that way. Could you clarify this error for me?

**Comment by greysteil** [comment]
Hi @aensley,

Sorry about this one. The thinking is that the kind of dependency bumps you want for a library are different to the kind you want for an application. Specifically, for a library you want your `composer.json` to admit as large a range of dependency versions as possible, to help avoid conflicts with other libraries when your users install. You want Dependabot to check whether the latest version of a dependency in your `composer.json` is included in the range you have specified, and extend that range if not (in contrast, for an app, people typically keep the range quite tight, dropping support for older versions as soon as a new one is released.)

In addition, there's some extra complexity about supporting libraries that don't commit a `composer.lock`, but that's a separate issue (and not relevant here).

At the moment, Dependabot just throws up its hands and gives up when a `composer.json` says it's a library. That's pretty sad, and I'd like to improve it - having it as an issue in this repo will make sure I get to it.

**Comment by aensley** [comment]
Thank you for the explanation. That makes perfect sense!

**Comment by greysteil** [comment]
FYI, I'm working on this now over at https://github.com/dependabot/dependabot-core/pull/174.
