### ISSUE TITLE
Display forked projects differently

### ISSUE THREAD

**Issue by Turbo87** [dependabot/feedback#281]
When I open the "Add Repos" page I see a lot of projects, but most of them are personal forks of other projects where I would want dependabot on the upstream project, but not my personal repo. I would prefer it if the list would show the forks in a separate list so that I could focus on enabling dependabot on the non-forked repos.

**Comment by greysteil** [comment]
Thanks for the feedback @Turbo87. We're planning to show an icon for forked projects on that screen imminently, which will help a little, at least.

@feelepxyz - one for you!

**Comment by feelepxyz** [comment]
@Turbo87 I've just added an icon to indicate which repos are forked, hopefully makes it a bit easier to scan the list!

**Comment by Turbo87** [comment]
hmm, it's a little better yeah, though the grey icon kinda fades away in the background, especially because of the "external link" icons right next to them. maybe a different color might highlight the non-forks better?

**Comment by feelepxyz** [comment]
@Turbo87 good point, will make it stand out a bit more!
