### ISSUE TITLE
Respond differently if dependabot is told to do something it can't do

### ISSUE THREAD

**Issue by mattr-** [dependabot/feedback#282]
Dependabot opened https://github.com/TracksApp/tracks/pull/2155 which I approved and merged roughly five hours after opening. When checking email, I told dependabot to merge it because I had forgotten I'd done it myself the previous day and I don't have GitHub set to send me notifications for my own actions, and dependabot happily told me it would merge the PR after it passed CI again.  Of course, since the PR was already merged, that didn't happen. :smile:

It would be great if dependabot would notice that it can't take an action and respond appropriately.

Thanks! :heart:

**Comment by feelepxyz** [comment]
@mattr- thanks for reporting this! You're right, this is definitely what should happen! Looking into it 👌
