### ISSUE TITLE
Auto-merge after review

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#283]
I *think* this is a little different to #253 and #86, but if I'm repeating stuff please close this.

I'd like to be able to have dependabot automerge PRs after we've done a human review, much like it auto-deletes the branch after merging.

I know Dependabot can auto-merge when status checks pass, but the "requires review before merge" option doesn't seem to work quite the same. Would it be possible to make auto merge trigger after reviews happen?

**Comment by greysteil** [comment]
I quite like this, and now that Dependabot adds details of its automerge strategy to the PR body I don't see why we shouldn't make it an option. No promises, but I'll have a look at implementing :-)

**Comment by Floppy** [comment]
Fantastic @greysteil, thanks for the positive feedback :)

I guess ideally it should be able to automerge whenever the github button goes green - so if reviews or status checks are required, it should wait for them but then do so.

**Comment by pascalberger** [comment]
@Floppy In the meantime [mergify](https://mergify.io) can help you. An example how to auto merge PRs created by dependabot is available [here](https://doc.mergify.io/examples.html#automatic-merge-for-automatic-pull-requests).

**Comment by Floppy** [comment]
Oh, superb @greysteil! I love it when past-me has already done things, so I know the feeling. Happy to test it out for you if you want to turn it on, yeah - can you enable it on the 'apolitical' organisation please?

**Comment by greysteil** [comment]
Sure thing - done!

**Comment by Floppy** [comment]
@greysteil this seems to be working nicely, great stuff!

**Comment by greysteil** [comment]
Ah yeah, that's a bugger.

Dependabot uses the `dependabot[bot]` account, which is attached to our app, to perform merges. Whilst that accounts has push access (because those are the permissions you grant it when you authorize Dependabot), it *can't* be specified as an admin user in the GitHub protected branches UI 🙁

**Comment by Floppy** [comment]
Interesting - the bot should be able to merge as long as the review is passed, it shouldn't need to be an admin... I'll have a look at the settings with that in mind.

**Comment by osman** [comment]
This sounds like a great feature, could we get this enabled too?

**Comment by greysteil** [comment]
@osman so sorry for not getting back to you on the above! Not sure how that got stuck in my inbox. Do you still want this enabled?

**Comment by alexceder** [comment]
Is there anything keeping this from general availability? This would be a great feature for my team's workflow as well.

**Comment by greysteil** [comment]
Just added as an option in your account settings. Thanks for the feedback everyone!

**Comment by tooomm** [comment]
Will this trigger on every approve? @greysteil 
Or only approves from members of the repo for example?
I mean... everybody could approve a PR. :)

**Comment by greysteil** [comment]
It will bounce out folks who don't have write permission, but at the moment it would comment saying so. I'll disable that comment, because they wouldn't be expecting it.

**Comment by greysteil** [comment]
Done 🙂

**Comment by mxschmitt** [comment]
@greysteil could you enable it on our @react-bootstrap organization too? Best regards

**Comment by feelepxyz** [comment]
@mxschmitt done! It's now configurable in the dashboard account settings: https://app.dependabot.com/
