### ISSUE TITLE
Ability to prevent to auto-update temporarily

### ISSUE THREAD

**Issue by shimbaco** [dependabot/feedback#289]
Hi, can I disable to auto-update temporarily? My team reviews PR by 2 people. Even if first reviewer approves PR, we can't merge PR until second reviewer reviews it. If PR is auto-updated before second reviewer reviews, first reviewer needs to review again. So we would like to prevent to auto-update in that case.

Thanks!

**Comment by feelepxyz** [comment]
@shimbaco thanks for getting in touch! Want to make I get this right, are you currently requiring 2 pull request reviews and dismissing stale pull request approvals when new commits are pushed?
How would you want to tell Dependabot to temporarily disable auto-rebases?

Not ideal but you could work around this by disabling automatic PR rebases on the account level (under account/settings in the dashboard nav) and then manually running `@dependabot rebase` when you've done reviewing to work around this. Could this work?

**Comment by shimbaco** [comment]
Thank you for your reply! And sorry for delayed response.

> are you currently requiring 2 pull request reviews and dismissing stale pull request approvals when new commits are pushed?

Yes!

> you could work around this by disabling automatic PR rebases on the account level

I don't want to disable automatic PR rebases on the account level if it's possible. I want to disable it each PRs because I want other PRs to rebase automatically.
But if it's difficult, I'll do the workaround you taught me. So I'll close this issue for now. 😃 

Thanks!

**Comment by feelepxyz** [comment]
@shimbaco great! I'm stil going to add this to our config wishlist. We're currently working on config files and this could be a candidate for a future advanced option.
