### ISSUE TITLE
Be able to mute dependencies upgrades

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#29]
As it was possible on versioneye, be able to mute dependencies upgrade.

**Comment by greysteil** [comment]
Thanks for the feedback @adriens. You can mute dependencies by commenting `@dependabot ignore this dependency`, and there are details of all of the Dependabot commands possible in the "Dependabot commands and options" section included on each PR. Does that cover your use case?

**Comment by adriens** [comment]
Hi @greysteil , thanks for very quick answer. you mean that i should comment 

```@dependabot ignore this dependency```

directly in the PR ?...and it will do the job ?

**Comment by greysteil** [comment]
Yes, exactly!

**Comment by adriens** [comment]
LOL, this is excellent, i trully <3 the code based approach :+1: 

Thanks a lot for answer :pray:

**Comment by adriens** [comment]
Sorry for last minute question : how do you ```un-ignore``` dependency please ?

**Comment by greysteil** [comment]
If you re-open the PR, or make a change to it yourself, then Dependabot will unignore it. 😄

**Comment by greysteil** [comment]
Good shout - I need to get around to writing an FAQ for Dependabot!
