### ISSUE TITLE
Rails 5.2.1.1 and Rails 5.2.2 not suggested as an update

### ISSUE THREAD

**Issue by shepmaster** [dependabot/feedback#294]
The [Rails gem](https://rubygems.org/gems/rails) has a few recent releases:

> - 5.2.1.1 - November 27, 2018 (6.5 KB)
> - 5.2.2 - December 04, 2018 (6.5 KB)

Our Gemfile allows these newer versions:

```
gem 'rails', '~> 5.2.1'
```

But we are still at version 5.2.1:

```
    rails (5.2.1)
      actioncable (= 5.2.1)
      actionmailer (= 5.2.1)
      actionpack (= 5.2.1)
      actionview (= 5.2.1)
      activejob (= 5.2.1)
      activemodel (= 5.2.1)
      activerecord (= 5.2.1)
      activestorage (= 5.2.1)
      activesupport (= 5.2.1)
      bundler (>= 1.3.0)
      railties (= 5.2.1)
      sprockets-rails (>= 2.0.0)
```

A `bundle update rails` does perform the upgrade, so it doesn't seem like there are other gems preventing the update:

```
$ bundle update rails
Fetching gem metadata from https://rubygems.org/......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies.........
... snipped other gems
Using activesupport 5.2.2 (was 5.2.1)
Using actionview 5.2.2 (was 5.2.1)
Using actionpack 5.2.2 (was 5.2.1)
Using actioncable 5.2.2 (was 5.2.1)
Using activejob 5.2.2 (was 5.2.1)
Using actionmailer 5.2.2 (was 5.2.1)
Using activemodel 5.2.2 (was 5.2.1)
Using activerecord 5.2.2 (was 5.2.1)
Using activestorage 5.2.2 (was 5.2.1)
Using railties 5.2.2 (was 5.2.1)
Using rails 5.2.2 (was 5.2.1)
... snipped other gems
Bundle updated!
```

**Comment by greysteil** [comment]
Thanks for the feedback @shepmaster. Can you link to your repo? Dependabot has generated a few thousand updates for that Rails version, so it's not a general problem, but I'd like to debug whatever's happening here specifically!

**Comment by shepmaster** [comment]
> Can you link to your repo

Oh yes, that would be important, wouldn't it?

https://github.com/jetpackworkflow/checklistpro

**Comment by greysteil** [comment]
👌 I'll dig into this in the next couple of hours.

**Comment by greysteil** [comment]
Looks like the cause of this was that you asked for an ignore of Rails on this PR https://github.com/jetpackworkflow/checklistpro/pull/6627. However, Dependabot should have picked up that you'd updated it yourself and started creating PRs again - let me dig into why that didn't happen here...

**Comment by greysteil** [comment]
FYI, the eventual bug in this want that after I moved the logic for honouring ignore conditions into Dependabot Core, the old logic for deleting outdated ignores was no longer being called. I've just fixed that, and Dependabot will now kick back into life when you update a dependency yourself (as it says it will do in the PR comments it generates).

Thanks for flagging this!

**Comment by shepmaster** [comment]
Thank you for the quick resolution!
