### ISSUE TITLE
Dependabot on a nodejs monorepo adds packages to root package-lock that should not be there

### ISSUE THREAD

**Issue by alferpal** [dependabot/feedback#296]
Hello everyone.

Yesterday I got this PR from dependabot: https://github.com/alferpal/calcifer/commit/78b321e2d9326baafbb5169d620767536e02ef49 

The problem with this is that it has added pino to the root package-lock.json, even when pino is not on the root package.json. This pino dependency is only on packages/calcifer-utils/package.json

**Comment by alferpal** [comment]
Happened again here:
https://github.com/alferpal/calcifer/pull/63/files

**Comment by greysteil** [comment]
Thanks for reporting this, and for the linked PRs. If you could leave https://github.com/alferpal/calcifer/pull/63/files open while I look into it that would be 👌.

**Comment by alferpal** [comment]
Sure, I'll keep it open as long as you need

**Comment by feelepxyz** [comment]
@alferpal sorry for the slow response on this one! I've just deployed the fix and added a test case to prevent this from happening in future.

If you're curious, here's [the code](https://github.com/dependabot/dependabot-core/pull/854/commits/3918fd6c821c88d475f0435ee4f95b83cc0704ff).
