### ISSUE TITLE
Certain caret ^ and tilde ~ versions according to semver npmjs do not get bumped

### ISSUE THREAD

**Issue by joma74** [dependabot/feedback#297]
As of https://github.com/joma74/tailwind-spa-ws/commit/f3c9efded259a1e0557d093cfc4bdd9332959ad8 i am of the opinion that that some dependencies did not recieve an expected depdendebot bump/pull request.

On checkout you will see
```
joma@edison:~/entwicklung/nodews/tailwind-spa-ws$ yarn upgrade-interactive
yarn upgrade-interactive v1.12.1
info Color legend :
 "<red>"    : Major Update backward-incompatible updates
 "<yellow>" : Minor Update backward-compatible features
 "<green>"  : Patch Update backward-compatible bug fixes
? Choose which packages to update. (Press <space> to select, <a> to toggle all, <i> to inverse selection)
 resolutionDependencies
   name                   range    from       to      url
❯◯ @types/webpack         ~3       3.8.14  ❯  3.8.17  https://github.com/DefinitelyTyped/DefinitelyTyped.git

 devDependencies
   name                   range    from       to      url
 ◯ tailwindcss            ^0       0.7.2   ❯  0.7.3   https://tailwindcss.com
 ◯ vue-template-compiler  ^2.5.16  2.5.20  ❯  2.5.21  https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#readme

 dependencies
   name                   range    from       to      url
 ◯ vue                    ^2       2.5.20  ❯  2.5.21  https://github.com/vuejs/vue#readme
```
Upon these i recieved bumps/pull requests for vue and vue-template-compiler. 

But for tailwindcss and @types/webpack i did not, what this issue is about. I checked both deps and version specifiers with https://semver.npmjs.com/ and saw that they would be also eligible for bumping. 

I assume that this might has something to do with caret and tilde syombols combined with single numbers of the version specifiers.

_P.S. I remember that the same goes for dep testcafe a few days ago, where i did a manual bumping myself_

_P.S.2 Totally :heart: dependebot esp it's workflow_

**Comment by joma74** [comment]
On your agreement i would like to retract only @types/webpack from this issue.  
yarn itself seems to mix resolutions version of `~3` with hard coded dev dep of `3.8.16`. :open_mouth:

**Comment by greysteil** [comment]
Sorry for the slow reply on this one - got swamped last week. I'm going to try to dig into it tomorrow (and definitely next week).

**Comment by feelepxyz** [comment]
@joma74 sorry for the slow response on this! Just fixed this issue and getting it deployed now.
