### ISSUE TITLE
on ruby gems inspect gemspec required ruby versions before suggesting an upgrade

### ISSUE THREAD

**Issue by majormoses** [dependabot/feedback#299]
In https://github.com/sensu-plugins/sensu-plugins-chef/pull/47 it suggests bumping versions to a version 14 which requires dropping support for ruby 2.3 which is a supported version of ruby, rather than creating an ignore rule for the version which someone may forget about later it would be better if dependabot instead inspected and only proposed changes that are safe based on the ruby version. I get that this could be a rabbithole and leading to expectations that applying is always safe which is often not the case as dependencies cross major thresholds. Open to other ideas/suggestions but I think this makes a lot of sense.

**Comment by greysteil** [comment]
I'm looking into this now. Dependabot already has a bunch of logic that should have stopped it trying to create an update that would require you to drop Ruby support for old versions, given that you already specify a `required_ruby_version` in your gemspec. I'll try to reproduce and get this fixed.
