### ISSUE TITLE
Limit number of open PRs

### ISSUE THREAD

**Issue by greysteil** [dependabot/feedback#3]
Currently we rate-limit to 5 PRs an update run. It would be better to limit the number of open PRs.

**Comment by greysteil** [comment]
Initial design: 
![image](https://user-images.githubusercontent.com/1144873/40117016-9019a61e-590d-11e8-9c26-c6105231d66d.png)

**Comment by greysteil** [comment]
Shipped! cc @bustikiller @chrvadala

**Comment by bustikiller** [comment]
Thanks @greysteil !
