### ISSUE TITLE
Personal account + org account doesn't seem to work

### ISSUE THREAD

**Issue by bfirsh** [dependabot/feedback#30]
I had dependabot installed for my personal repos. In quite a roundabout way, which I forgot, I managed to install it for the arxiv-vanity organisation too. I think it was by adding the application again on GitHub, then selecting arxiv-vanity as the org to install it on.

Anyway - your web UI now seems very confused. The URL is https://app.dependabot.com/accounts/arxiv-vanity/repos but it is showing my repos. Selecting arxiv-vanity from the top-right dropdown shows the same page. I can't seem to get it to show arxiv-vanity's repos.

**Comment by greysteil** [comment]
Ack, sorry about that. If you need a brute-force reset you can clear your local storage (the redux key is the one that needs deleting). We'll also have a look into what caused this.

**Comment by hmarr** [comment]
Hey Ben, thanks for reporting this! It actually looks like a backend glitch, so don't worry about resetting your localstorage. I think I've fixed up the bad data, so this should be resolved now, but let us know if you spot any other peculiar behaviour.

**Comment by bfirsh** [comment]
Nice thanks!

Still seems a bit confused, though. I can view the arxiv-vanity org now:

<img width="1280" alt="screenshot 2017-10-24 12 07 33" src="https://user-images.githubusercontent.com/40906/31934148-023ce7f6-b8b4-11e7-8427-ee279188c3e1.png">

But when I try to add a repo I get this error:

<img width="574" alt="screenshot 2017-10-24 12 07 15" src="https://user-images.githubusercontent.com/40906/31934168-0ee31d68-b8b4-11e7-9f5e-30596eb04430.png">

Which is a bit confusing, because the page before was blank.

This might be because I moved the repo from my personal account to the org, so perhaps it still already exists somehow under my personal account. It isn't listed under there, though.

**Comment by greysteil** [comment]
Ah-ha! It's the move that's messed things up - we weren't handling that quite right, which is what messed up the data on the backend.

I've manually moved that repo across, so it should be showing up now. Did you move any others? I'll update our backend so it handles this properly now, too.

**Comment by bfirsh** [comment]
bfirsh/ass (a sillier time) -> arxiv-vanity/arxiv-vanity
bfirsh/engrafo -> arxiv-vanity/engrafo

Thank you! :)

**Comment by greysteil** [comment]
Great, those should both be fixed up. Sorry about that one!

**Comment by bfirsh** [comment]
No sweat! It's a brilliant service, so thank you!

**Comment by bfirsh** [comment]
Okay nearly! 

<img width="750" alt="screenshot 2017-10-24 12 35 06" src="https://user-images.githubusercontent.com/40906/31935557-d816f0f8-b8b7-11e7-9eb0-46077d7b4dc9.png">

<img width="565" alt="screenshot 2017-10-24 12 35 10" src="https://user-images.githubusercontent.com/40906/31935576-e2bdc6da-b8b7-11e7-9931-21996cad4597.png">

I fixed engrafo by removing it and recreating, but that doesn't seem to have fixed arxiv-vanity...

**Comment by greysteil** [comment]
That's actually a separate error, and one that I was looking into last night. The cause is that the [`requirements.txt`](https://github.com/arxiv-vanity/arxiv-vanity/blob/master/requirements.txt) for arxiv-vanity specifies the version of `django-basicauth` at minor precision (rather than patch). That's causing Dependabot to:
1. think there's an update available (0.4.1)
2. generate a requirements file for the update that is identical to the old one

Hence the explosion. Updating for other dependencies should be working fine.

I think the right fix for the above is for Dependabot to quietly ignore that dependency update, under the assumption that you know what you're doing when you specify the version to minor precision. Does that make sense to you?

**Comment by bfirsh** [comment]
Ah, that's interesting, I don't think it's possible to specify fuzzy versions like that with requirements.txt is it? I am actually specifying the exact version "0.4".

I think this is the package author's fault. They released 0.4.0 without a patch version: 

https://pypi.python.org/pypi/django-basicauth/0.4
https://pypi.python.org/pypi/django-basicauth/0.4.0

So I think 0.4 is installed, not 0.4.1. So in this case, I would like a bump to 0.4.1.

**Comment by greysteil** [comment]
👍 I’ll update the Python logic to do that.
