### ISSUE TITLE
Request: stop asking about labels

### ISSUE THREAD

**Issue by kmoe** [dependabot/feedback#30]
Whenever the label of a dependabot PR changes, dependabot posts two comments on the PR reminding me how to set a default label.

![dependabot_label](https://user-images.githubusercontent.com/5575356/40664918-e7642804-6353-11e8-8041-724476296572.png)

Is there a way to stop it from doing this?

**Comment by greysteil** [comment]
Ack, that's an annoying race condition. I reckon we can probably do away with that comment entirely now that Dependabot lists its help commands in the PR text, though - I'll do that now.

**Comment by greysteil** [comment]
Change deploying now. Thanks for the feedback!

**Comment by kmoe** [comment]
Thanks for the quick response!
