### ISSUE TITLE
Java dependencies are not updating since beginning of the December 2018

### ISSUE THREAD

**Issue by lanwen** [dependabot/feedback#302]
We use dependabot for bunch of private repos and didn't get the latest updates of the `com.amazonaws:aws-java-sdk-bom` for 2 weeks already.

Current version is `1.11.470` when the latest update was `1.11.461`. 

Actually we didn't get any java updates for last 2 weeks.

**Comment by greysteil** [comment]
Huh, that's no good. Can you ping me a repo name to support@dependabot.com so I can debug?

**Comment by greysteil** [comment]
Debugging over email.
