### ISSUE TITLE
[python]: `install -e .` in requirements.txt fails

### ISSUE THREAD

**Issue by amureki** [dependabot/feedback#305]
Hi,

thank you for the great project!

I am currently testing it with pipenv (works great) and with old-fashioned requirements files:

So, I have a package repository. My `requirements_test.txt` that is being used by CI includes this line:
`-e .`

which in Travis install the package itself from the given repository.
Dependabot proposes to replace this line with some temporary dependabot folder like 
`file:///home/dependabot/...`

Could we check this problem? It currently blocks me from setting up dependabot on my projects.

Best,
Rustem

**Comment by greysteil** [comment]
I’ll take a look. What’s the URL of the repo? (You can email support@dependabot.com if it’s private.)

The code for this is all at https://github.com/dependabot/dependabot-core btw.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/1c630f0e6453fe5943995979fb5dde1378910791, which is deploying now. Thanks for flagging this!

**Comment by amureki** [comment]
@greysteil thank you, mate, that was quick! 🥇
