### ISSUE TITLE
Dependabot does not want to add a repo

### ISSUE THREAD

**Issue by L1ghtn1ng** [dependabot/feedback#307]
I am trying to import the following

![image](https://user-images.githubusercontent.com/3628354/50499716-b9ee4e80-0a43-11e9-8545-dd1ff936bc43.png)

But I keep getting Repo must contain a requirements.txt, setup.py, pyproject.toml, or a Pipfile. even though it does and dependabot auto-detects it as javascript so I have to change it to python

**Comment by greysteil** [comment]
That definitely looks like a bug. Thanks for reporting - looking into it now.

**Comment by greysteil** [comment]
Just dug into this and it looks like you've got a unicode blankspace at the end of the filename for `requirements.txt`. As a result Dependabot isn't recognising that as a `.txt` file.

I don't think the above is a Dependabot bug so I'm not going to make any changes on our side, but I will put in a PR to your repo to fix the file for you 🙂.
