### ISSUE TITLE
Couldn't convince dbot to close an obsolete PR

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#309]
As far as I can tell, there's no longer any need for [https://github.com/ianwremmel/http-server-exceptions/pull/98](this pr), but dbot didn't autoclose it and didn't produce a version that didn't have conflicts. I closed the PR manually.

**Comment by greysteil** [comment]
Ah, it's sometimes tricky to tell with sub-dependency updates like this one, but I *think* dependabot is still making an update there. [This line](https://github.com/ianwremmel/http-server-exceptions/pull/98/files#diff-32607347f8126e6534ebc7ebaec4853dL8335) looks like it's updating the version of `sshpk` that's being pulled in as a sub-dependency.

**Comment by greysteil** [comment]
Oh, hang on, it looks like it never got back to you on those rebases, though. Let me take a look into that...

**Comment by greysteil** [comment]
Hmmm, I'm not sure what's happened here and it's tricky to reproduce because the PR is closed - if you see this behaviour again can you ping me with the PR still open and I'll dig into it? Keen to get to the bottom of it!

**Comment by ianwremmel** [comment]
Ah, gotcha. Didn't think to open this issue til after I closed the PR. Will send you more details if I see it again. Thanks for looking!
