### ISSUE TITLE
Versions not respecting maven release version schema

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#31]
Hi,

some deps do not respect the release schema like ```xstream``` :

```Bump xstream from 1.4.10 to 1.4.10-java7```

See, the one without ```1.4.10-java7``` is the old one while the ```1.4.10``` is the good one.

On the dependabot, would it possible, on you side (versioneye was doing the job), not to report this dependency upgrade ?

Use case : see https://github.com/adriens/schemacrawler-deb/pull/17

**Comment by greysteil** [comment]
Ah, interesting, I've been wondering about these for a while.

In theory (according to Maven's version number progression details) the `-java7` release is a higher number, but I can full see why we'd want to treat it specially. Perhaps I could put together an exhaustive list of such suffixes to handle specially? I've seen `-android` and `-jre` - what other ones should I be aware of?

**Comment by adriens** [comment]
Hmmm, i saw some some few other one i think. Let me search for them. I'll let you know ASAP. :+1:

**Comment by adriens** [comment]
I got a new one : see https://github.com/adriens/schemacrawler-deb/pull/19

```Bump mssql-jdbc from 6.4.0.jre8 to 6.5.2.jre9-preview```

see https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc :

```xml
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.1.0.jre8</version>
    <scope>test</scope>
</dependency>
```

you get these ones :

- `6.5.2.jre9-preview`
- `6.5.2.jre8-preview`
- `6.3.6.jre7-preview`

**Comment by greysteil** [comment]
I'll add special casing for all of these tomorrow. Thanks for the feedback, and hunting some down!

**Comment by adriens** [comment]
I love :gun:  :duck: :rofl:

**Comment by greysteil** [comment]
First version of a fix is https://github.com/dependabot/dependabot-core/commit/ecc5c86892b54d9f9869418e8b83054699ea9784. I'll deploy that tomorrow (internet isn't good enough where I am right now).

**Comment by adriens** [comment]
Great news ! Thanks a lot !

**Comment by greysteil** [comment]
Deployed!

**Comment by adriens** [comment]
Thanks a lot !
