### ISSUE TITLE
GET https://api.dependabot.com/active_repos

### ISSUE THREAD

**Issue by yildiz-online** [dependabot/feedback#310]
Displayed on the dashboard instead of the repositories

**Comment by greysteil** [comment]
I'm just looking into that error on our side - it looks like a change we made to the repos endpoint means it's not working for those who have more that 100 repos active - yours is the first account that's run into that since it was deployed two days ago.

I'll have a fix out in the next hour.

**Comment by yildiz-online** [comment]
Thank you for the quick reply.

**Comment by greysteil** [comment]
I've just deployed the fix - everything should be working normally now. Apologies for the bug!

**Comment by yildiz-online** [comment]
Working as expected, thank you very much for reactiveness

Have a happy 2019 year

**Comment by greysteil** [comment]
Good to hear, and happy new year!
