### ISSUE TITLE
configurable commit messages

### ISSUE THREAD

**Issue by jcjones1515** [dependabot/feedback#312]
Most of the time using `chore(...): ...` for commit messages is what we want but there are some dependencies/repos where I would like to be able to use `fix(...): ...` to trigger a semantic release in a downstream dependency too.  

Is there some way to configure commit messages used?

Thanks!

**Comment by greysteil** [comment]
Thanks for the question. The honest answer is "not at the moment".

In the long term I can see this being something we potentially add support for in config files, but we're a way away from that just yet. Before doing so we'd probably want to add support for custom commit messages, and then make this a special case of those.

In the meantime, you might want to take a look at [Renovate](https://renovatebot.com/). They're a copycat of Dependabot, but have the philosophy that "everything should be configurable to a ridiculous extent". (We're more focussed on ease of use, with configurability coming second.)

**Comment by zypA13510** [comment]
greenkeeper also has this, you provide a string with placeholders, they replace the placeholders to generate commit messages and PR titles. Like this:

```JS
{
  initialBadge: 'docs(readme): add Greenkeeper badge',
  initialDependencies: 'chore(package): update dependencies',
  dependencyUpdate: 'fix(package): update ${dependency} to version ${version}',
  devDependencyUpdate: 'chore(package): update ${dependency} to version ${version}',
  lockfileUpdate: 'chore(package): update lockfile ${lockfilePath}',
  closes: '\n\nCloses #${number}'
}
```

And now that #443 and #551 have been closed, is there any plan to revisit this?
