### ISSUE TITLE
PR not created

### ISSUE THREAD

**Issue by guillaumechervetaxa** [dependabot/feedback#315]
Hi,

I do not know why, but PR are not created by dependabot on this repository :
https://github.com/AxaGuilDEv/react-toolkit

PR are well created on this one with exactly the same configuration :
https://github.com/AxaGuilDEv/react-oidc

![image](https://user-images.githubusercontent.com/43414465/50681500-06212c00-100c-11e9-8361-4e9913b1b3a9.png)

Do you have an idea why?

Regards,

Guillaume.

**Comment by feelepxyz** [comment]
@guillaumechervetaxa ouch looked into this and the update timed out due to the large number of package files being checked (trying to check 99 package json files).
Sorry for not handling this better! Looking into a solution.

**Comment by feelepxyz** [comment]
@guillaumechervetaxa going to take some time to get this properly fixed so will tackle this from Monday and start by adding better caching around npm installs. Will keep you posted on progress ✌️

**Comment by Aedius** [comment]
i got the same issue with php, it take a while on my computer, so i assume it's the same issue. 
any notification about error would be great

**Comment by feelepxyz** [comment]
Hey, sorry for the super slow progress on this! Been a busy couple of weeks. Did a bunch of work to speed up our JS jobs which didn't end up fixing the issue for https://github.com/AxaGuilDEv/react-toolkit, hoping to get some time to work on this next week.

@Aedius we have a bunch of issues with php jobs timing out as the php package manager is quite slow and resource intensive. Do you have an example repo you are having issues with?

**Comment by guillaumechervetaxa** [comment]
Thank you very much for your attention :)

I think that dependabot is awesome :p

**Comment by Aedius** [comment]
@feelepxyz as example i have : https://github.com/Aedius/crowfall-royaumes-eternel
my point is that it ok to fail, but it is far less to not mention it on the dashboard

**Comment by feelepxyz** [comment]
@Aedius agreed! We really need to fix up these time out issues and figure out what actionable info we can give to fix it. Unfortunately PHP needs some serious speedup work so will continue to not perform very well until we get this fixed.

We are hoping to get some more people involved soon so should be able to tackle these issues.

**Comment by feelepxyz** [comment]
@guillaumechervetaxa 👋 just deployed a change in how we process sub-dependency updates that  fixed the issue of no updates for your repo: https://github.com/AxaGuilDEv/react-toolkit/pulls

Looks like a few of your scoped packages are now being resolved from the npm registry instead of your private npm feed (afa-nrepo.azure-paas.intraxa) - should we be making this change?

Sorry it took so long to fix! The commit fixing this is here if you're curious: [97713a3](https://github.com/dependabot/dependabot-core/commit/97713a341085d05e63b089226adfa235b65b4b87)

**Comment by guillaumechervetaxa** [comment]
Thank you very much, it is awesome ! Very nice work !

Thank for the feedback, I have fixed the package.lock, it was an old one :
https://github.com/AxaGuilDEv/react-toolkit/pull/84
