### ISSUE TITLE
github-pages gem not being bumped

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#32]
I've got a couple of repositories that aren't being updated for some reason. They're shown as recently bumped, but the dependencies are still way out of date and no PRs are being sent. The same gems are being updated in other similar repositories.

Two examples:

* https://github.com/Floppy/cv
* https://github.com/Floppy/floppy.github.io

Can anyone shed any light on why this might be?

**Comment by Floppy** [comment]
Ah, this isn't quite true, I was mistaken. It seems to be just the `github-pages` gem that's not being bumped. I'll update the title.

**Comment by Floppy** [comment]
I'm wondering if this is related to #5. I'll see if I can bump one gem at a time manually.

**Comment by Floppy** [comment]
Hm, no, a manual `bundle update github-pages` has worked OK.

**Comment by greysteil** [comment]
Hmmm, that's strange. I'm not at my computer right now, but will take a look this evening / tomorrow morning.

**Comment by greysteil** [comment]
Just dug into this. It looks like there's a conflict here between the latest version of `rake` and the latest version of `github-pages`, which is what's blocking this update. `github-pages` relies on `liquid`, which specifies an outdated version of `rake` in it's latest version. That's a pity - I'll put in a PR to liquid now.

**Comment by greysteil** [comment]
So it turns out this is a resolution problem in Bundler. I'll have a PR to fix it in tonight / tomorrow, and it should be released as part of Bundler 1.16.0. Thanks for raising it @Floppy! I'll keep this open until the PR is accepted.

**Comment by greysteil** [comment]
FYI, the issue to fix this in Bundler is [here](https://github.com/bundler/bundler/pull/6128).

**Comment by Floppy** [comment]
❤️ @greysteil you guys are awesome!

**Comment by gerrywastaken** [comment]
@greysteil wow, that's quite a find. Do you know if the problem was only only recent?

**Comment by greysteil** [comment]
OK, https://github.com/bundler/bundler/pull/6128 has been merged and I've pulled in the update into Dependabot. I just triggered an update on https://github.com/Floppy/cv and the relevant update PR is https://github.com/Floppy/cv/pull/8. Given all of that, I'm closing this.

@gerrywastaken - this will have been surfaced by the work we did to improve Bundler's resolution logic. There's a blog post on it [here](https://dependabot.com/blog/improving-dependency-resolution-in-bundler) linking to some of the relevant PRs, if you're curious.

Thanks again for the feedback @Floppy!

**Comment by gerrywastaken** [comment]
@greysteil Wow, thank you so much for all your work on Bundler and Molinillo! That was a fantastic read.
