### ISSUE TITLE
Maven bill of materials in milestore repo question.

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#32]
In my pom.xml i have 

```xml
<properties>
        <spring-cloud.version>Finchley.RC1</spring-cloud.version>
</properties>

<dependencyManagement>
      <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

<repositories>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>
```

2 days ago `Finchley.RC2` was released but dependabot hasn't suggested the upgrade. I was wondering whether this was because it's not yet on maven central or is there another reason this didn't get bumped?

**Comment by greysteil** [comment]
Hmmm, that sounds like a bug - Dependabot should have found that. Let me take a look.

**Comment by davidgoate** [comment]
Ok thanks! Let me know if it's something wrong we have done in our POM!

**Comment by greysteil** [comment]
Update: I don't think Dependabot can handle non-numeric versions like this at all. I'll have a look at fixing that.

**Comment by davidgoate** [comment]
Thanks, would be a great feature. In the spring cloud ecosystem this is really common 🎉

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/9c86c57088b428cb8ced4834c8f9f8f4643563fe, which will be deployed tomorrow (evening). 🎉

**Comment by davidgoate** [comment]
@greysteil awesome thanks!
