### ISSUE TITLE
Workflow

### ISSUE THREAD

**Issue by tielur** [dependabot/feedback#321]
We have a git workflow where we merge branches into a QA and Staging pre-prod environment for testing before we merge to master.

What would be the appropriate workflow to bring that into dependabot? I basically want to merge dependabot branches into our QA branch, test it, merge it into our staging branch, test it, then eventually just merge the branch into master.

**Comment by greysteil** [comment]
Would just changing the branch that Dependabot targets to whatever you use for staging work? That's possible from the dashboard (under advanced settings when adding a repo) or via a config file.

**Comment by tielur** [comment]
I'd have to constantly change it through right? I don't merge the QA or Staging environment into master.

My initial thinking was just to keep it opening PRs against master, then just manually merge the dependabot branches into the other two branches. Once testing is all done then go back to the PR and merge it into master.

**Comment by tielur** [comment]
I wasn't sure if dependabot had a better workflow for such things though

**Comment by greysteil** [comment]
Ah, OK, I see what you mean now.

I guess one option would be to run Dependabot on all three branches?

**Comment by tielur** [comment]
Yea I think that may turn into a mess though. I think for now I'll leave the PR's open on master, and manually merge the dependabot branches into our QA environments for testing.

Then once everything is good just merge the dependabot PR

**Comment by greysteil** [comment]
Sounds sensible!
