### ISSUE TITLE
Commits Wrong Author

### ISSUE THREAD

**Issue by dav-is** [dependabot/feedback#327]
The author of commits is set to `dependabot[bot]` which does not exist. If you go to commits and click on the dependabot logo next to one of it's commits, it links to https://github.com/dependabot%5Bbot%5D which is a 404. Shouldn't the author be listed as `dependabot-bot`?

**Comment by greysteil** [comment]
It looks like this only applies to the merge commits when Dependabot auto-merges a PR. The commits in the PR are already authored by dependabot-bot.

Unfortunately there's no way we can change the account that merges the PRs - when you grant Dependabot permission over your repo you're granting the `dependabot[bot]` account permission to take action, *not* the `dependabot-bot` account. The later only exists as a user in GitHub, with no permission over you account (that doesn't stop us using its details in the commit metadata, but it can't actually take any action on your account).

I'll ping the folks at GitHub to see if they can come up with a better link for `[bot]` users.
