### ISSUE TITLE
Support repositories other than Git

### ISSUE THREAD

**Issue by cowwoc** [dependabot/feedback#328]
The implementation is currently coupled with Git. Not everyone wants to use Git. Are you able to isolate the source-code portion of the code so we can provide different implementations?

I'm personally angling for Mercurial support, possibly via BitBucket.

**Comment by greysteil** [comment]
Yes, although I imagine this is likely to be a big project! The core of Dependabot is source accessible over at https://github.com/dependabot/dependabot-core - contributions welcome, and feel free to hack it into whatever shape you need to run it locally via a script (reference implementation at https://github.com/dependabot/dependabot-script).
