### ISSUE TITLE
Config directory for Maven Project

### ISSUE THREAD

**Issue by broder** [dependabot/feedback#329]
We've defined a maven project using a [config file](https://github.com/UKGovernmentBEIS/beis-mspsds/blob/master/.dependabot/config.yml#L9). We're seeing an error on the dependabot dashboard  though:
```
Dependabot couldn't find a pom.xml for this project.

Dependabot requires a pom.xml to evaluate your project's current Java dependencies. It had expected to find one at the path: /‎/keycloak/providers/rest-api/pom.xml.

If this isn't a Java project, or if it is a library, you may wish to disable updates for it in the .dependabot/config.yml file in this repo.
```

Is the double slash at the start of the path the issue or is it a red herring?

Let me know if you need anymore information!

**Comment by greysteil** [comment]
Hmmm, that does look suspicious. Let me dig into it.

**Comment by greysteil** [comment]
Elected not to bad as technically a zero-width character is legal in a directory name. Have put a PR in to your repo to clean them out of your config file, though 🙂

**Comment by broder** [comment]
Ah, that's irritating - thanks for looking into it!
