### ISSUE TITLE
Add support for C#

### ISSUE THREAD

**Issue by evenh** [dependabot/feedback#33]
This seems like a great product for the company I work at, but almost all our projects are written in Java (Maven) or C#/.NET. Is there any plans to support this? :-)

**Comment by evenh** [comment]
I just realized that [dependabot/dependabot-core](https://github.com/dependabot/dependabot-core) is a thing. I'm not a Rubyist, but I might try to add some Java + Maven support.

**Comment by greysteil** [comment]
That would be amazing! Happy to help guide you through it. There is a readme for each of the different helper classes that should help, too.

(And yes, we'd absolutely love to have support for Java and C#/.NET, but I don't know enough of either to add it myself and there's some polish we want to add to Python and PHP before I can spend my time digging into a new language.)

Cc @hmarr, who knows enough Java to be dangerous.

**Comment by greysteil** [comment]
Added a starter PR for you: https://github.com/dependabot/dependabot-core/pull/116

**Comment by evenh** [comment]
@asbjornu Are you up for trying to add C#/.NET support? :)

**Comment by asbjornu** [comment]
@evenh: Sure! I just don't know where to start. If @greysteil could kickstart the process with a template of some sort (as he did for Maven), that would be awesome!

**Comment by greysteil** [comment]
Very, very initial starter kit [here](https://github.com/dependabot/dependabot-core/pull/212). I can do a bit more on it, but the first decision is already clear: what package manager should we be supporting here...

(Let's move the discussion over to that PR.)

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#372
