### ISSUE TITLE
[Feature Request] remove old branches not tied to a PR

### ISSUE THREAD

**Issue by jonathan-irvin** [dependabot/feedback#332]
Sometimes as CI cycles and time goes on, there are some dependency branches that get left behind by dependabot.

These are leftover branches without a PR tied to them.
![screen shot 2019-01-17 at 9 24 20 am](https://user-images.githubusercontent.com/2481437/51328756-b09c4480-1a39-11e9-96d8-851242b9da30.png)

Here are some ideas
1. Run a job to remove any straggling branches
2. Scan for branches and reopen PRs for them, optionally checking for updates and nixing the branch if a higher version is available, unless user is opting out of a major/minor/patch.
3. Scan for branches and allow the user to remove old branches that are left behind.

**Comment by feelepxyz** [comment]
@jonathan-irvin are you seeing these branches on GitHub or locally?

**Comment by feelepxyz** [comment]
Going to close this - let us know if you're still seeing this issue!
