### ISSUE TITLE
Sign up error

### ISSUE THREAD

**Issue by ghostslayer989** [dependabot/feedback#335]
I get a "something went wrong" error when trying to sign up.

**Comment by greysteil** [comment]
That's definitely not good! Are you seeing the error on Dependabot's side or on GitHub's?

**Comment by ghostslayer989** [comment]
Dependabots. Now I get "GET https://api.dependabot.com/repos"

**Comment by greysteil** [comment]
Hmmm, I'm not seeing any errors on our backend except a rate-limiting issue for a different account. Is it the `ghostslayer989` account you're trying to install on / access?

**Comment by ghostslayer989** [comment]
Going to the api gives` {"errors":[{"status":403,"title":"Forbidden","detail":"No access token provided in 'Authorization' header"}]}` and I'm doing a fresh install. I did it through the github Marketplace.

**Comment by greysteil** [comment]
That explains the lack of backend errors - for some reason it sounds like the Dependabot frontend isn't including your GitHub OAuth token when it makes requests to the backend.

Can you try clearing your cookies and revoking the Dependabot authorization at https://github.com/settings/apps/authorizations (assuming it's there)?

**Comment by ghostslayer989** [comment]
@greysteil It doesn't have an "Authorized github app" showing.

**Comment by greysteil** [comment]
I guess that's why it's not passing down a token! Can you try visiting https://app.dependabot.com/auth/sign-in?

**Comment by ghostslayer989** [comment]
Thx. It works!
