### ISSUE TITLE
Close (update?) old PRs after target_branch change

### ISSUE THREAD

**Issue by szpak** [dependabot/feedback#337]
Due to some initial issues with `.dependabot/config.yml` (Dependabot didn't find that file when I was adding a new repository and applied the default configuration) I've got 5 PRs against the master branch. After I convinced Depndabot to read the configuration file it created another 5 PRs against the devel branch (10 in total).

Target branch is not changed very often, so it's a minor enhancements, but Dependabot could check if there is no identical branch against the other branch (created by it) and update the old PR (if feasible using the GitHub API) or at least closed the old one before creating the new one.

Btw, in the https://dependabot.com/blog/introducing-config-files/ article there is `default_branch` used in the example for `target_branch`:

```
target_branch

Branch to create pull requests against.

By default your repository's default branch is used.
Example: target branch

version: 1
update_configs:
  # required properties omitted ...
  default_branch: "develop"      <---- here
```

**Comment by greysteil** [comment]
Thanks for the feedback! I've updated the blog post and changed the config file processing logic so it will update the existing update config for a change in the target branch (if there's only one existing update config for that package manager and directory).
