### ISSUE TITLE
Golang [deps]: .toml file constraint not updated.

### ISSUE THREAD

**Issue by bwplotka** [dependabot/feedback#347]
Hi :wave: 

We use `deps` and `toml`  `constraint` entries for a reason: To have my dependencies pinned for CI and reproducible builds. I do not vendor deps in a repo (and I don't want to). 

For example:
```
[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.1"
```

I got a nice PR from dependabot that updates it to `6.0.15` which is legit. The only problem is that `.toml` constrant is not updated: https://github.com/improbable-eng/thanos/pull/787

This is bad as we have drift between `.lock` file and toml causing `.lock` file to be overriden on every `make deps` anyway.. Is dependant bot forgetting to commit toml changes?  Is there something wrong with our `dep` setup?

Thanks!

**Comment by bwplotka** [comment]
Maybe it is similar to https://github.com/dependabot/feedback/issues/177 ? 

Trying `Increase Versions` for toml file option on dashboard

**Comment by bwplotka** [comment]
That worked! https://github.com/improbable-eng/thanos/pull/792/files

So.... can we remove `Auto` option as it clearly does not work to stop confusion? (: Or fix it? Is there any pending issue on Dependabot-core?

**Comment by greysteil** [comment]
That's awesome. I pride myself on being quick to reply to issues, but you fixed this one before I could help out!

**Comment by bwplotka** [comment]
Yea, sorry for using your board as a rubber duck... whatever works I guess  (: 

> So.... can we remove Auto option as it clearly does not work to stop confusion? (: Or fix it? Is there any pending issue on Dependabot-core?

Any action item for this?
