### ISSUE TITLE
PHP Version configured in composer.json is not respected

### ISSUE THREAD

**Issue by jeromegamez** [dependabot/feedback#348]
Dependabot suggests updates that are not compatible to the configured PHP version.

### Example

https://github.com/jeromegamez/duration-php/pull/4

- The configured PHP-Version in the `composer.json` file is `"php": "^7.1"`
- The suggested bump is `"phpunit/phpunit"` from `^7.0` to `^8.0`
- PHPUnit 8.0 requires `"php": "^7.2"` (https://github.com/sebastianbergmann/phpunit/blob/8.0.0/composer.json#L24)

:octocat:

**Comment by greysteil** [comment]
Sadly, the way Composer works is limiting us here. If you specify your PHP version in the `platform` section of your `composer.json` Dependabot will do the right thing, though.

c/r: https://github.com/dependabot/dependabot-core/issues/394
