### ISSUE TITLE
registry.npmjs.org authentication issue when we only use npm for public packages

### ISSUE THREAD

**Issue by cchawn** [dependabot/feedback#349]
This morning Dependabot opened several issues on different repositories within our organization. The issue was:

>Dependabot couldn't authenticate with registry.npmjs.org.
>
>You can provide authentication details in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'.
>
>You can mention @dependabot in the comments below to contact the Dependabot team.

This is misleading for a few reasons:
1. we only use the npm registry for public packages (so we don't require authentication nor is it set up)
2. we've also had Dependabot successfully open and update PRs while this "issue" was open

I believe that what is happening is that Dependabot couldn't connect to npm (perhaps due to an npm outage) but it is surfacing this as an authentication issue. 

I've seen this related issue: https://github.com/dependabot/feedback/issues/11

And it seems like this messaging, `"Dependabot couldn't authenticate with registry.npmjs.org"`, is commonly used for many kinds of issues when trying to connect to npm. Hopefully there is a way to determine if the issue is on npm's side vs. our project, and surface a more clear error message.

**Comment by greysteil** [comment]
Thanks for the heads up! This should be fixed by https://github.com/dependabot/dependabot-core/commit/ed5de2d9971dbeb74803a24348eda9559205d72c, which is deploying now. Will help us detect npm blips better.
