### ISSUE TITLE
Add support for Elixir

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#35]
Thanks for the awesome project!

I know, that `elixir` is not as popular as `python`, `php`, or `js`. But I really use it a lot.
Maybe there are other developers who are interested in supporting `elixir`?

**Comment by greysteil** [comment]
You're going to really like https://github.com/dependabot/dependabot-core/pull/10...

@stevedomin is working on some driverless cars stuff for the next couple of weeks, but is planning to pick it up and finish it after the 20th. 🎉

**Comment by sobolevn** [comment]
@greysteil you are truly awesome!

**Comment by stevedomin** [comment]
@sobolevn it's coming, stay tuned :)

**Comment by greysteil** [comment]
This is live! Would love your feedback if you give it a try @sobolevn

**Comment by sobolevn** [comment]
Right now I can say just one thing: it works! 

<img width="755" alt="2018-01-17 16 50 26" src="https://user-images.githubusercontent.com/4660275/35045963-9e62ae06-fba6-11e7-9266-e1d64294588c.png">
