### ISSUE TITLE
Unable to add github repo which is dependent upon private gem in another organization

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#35]
On SuperBetterLabs/SuperBetter-iPhone we are dependent upon tablexi/mobile-deploy (a private repo), but we are unable to grant access via the marketplace configuration (apparently because it's a different organization?).

Is there a way to resolve this?

**Comment by mmizutani** [comment]
As per greysteil's instruction, adding a GitHub personal access token with repo scope to the "Config variables" section using the https-style access
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'xxxxxx', git: 'https://github.com/xxxxxx/xxxxxx.git', branch: 'master'
```
worked for our repos which are dependent on RubyGems in our private repository.
