### ISSUE TITLE
dependabot not detecting package.json in the case of full stack JS web apps

### ISSUE THREAD

**Issue by open-source-explorer** [dependabot/feedback#350]
Currently, `depedabot` just checks whether the corresponding dependency configuration file is being listed within the root directory of the repo which is not always the case.
> For instance, take the case of JS. Most full stack web apps have a project hierarchy with `client` and `server` directories with the `package.json` files keeping track of the specific dependencies.

Dependabot fails to address those repositories as mentioned above which is a good feature to have :thinking:

**Comment by greysteil** [comment]
Thanks for the feedback. You can specify a directory for each Dependabot update config, which allows you to update nested `package.json` files. Dependabot will also automatically find all of them if you're using Lerna or Yarn workspaces.

We're working on adding automatic detection of all projects within a repo, even when it's not using Lerna or Yarn workspaces, but it's obviously something we have to be careful with - in some cases folks wouldn't want Dependabot to run on all the directories within a monorepo.

Is the above clear, and does it allow you to get set up?
