### ISSUE TITLE
How to provide multiple directories in the case of full stack JS web apps

### ISSUE THREAD

**Issue by coder9604** [dependabot/feedback#352]
Currently there is a provision to provide a single directory where `Dependabot` is required to search for package config files relative to the root path. Consider the case of a Full Stack JS web app where the project structure includes `client` and `server` directories which ensures sufficient abstraction between the UI components and business logic.

> How can  I make Dependabot to check for `package.json`  files within both `client` and `server` directories?
Also, what I'm having a `package.json` file in the root path as well another one within a directory :thinking:

**Comment by greysteil** [comment]
Hmmm, sounds like we're doing a bad job of communicating this, but you can add multiple directories to Dependabot - you just have to add them one-by-one as separate update configs for that repo. I'll have a think about how we can improve the UI, but Dependabot already supports multiple directories 🙂

**Comment by greysteil** [comment]
FYI, I've just changed the button text to "add a language / directory", which should make things clearer!
