### ISSUE TITLE
Removing a project

### ISSUE THREAD

**Issue by kirkkala** [dependabot/feedback#354]
We recently archived a project in Github hence I was looking to delete that project from Dependabot and found deleting happens by removing all languages one by one. It did work but felt a bit quirky - maybe add a "delete from dependabot" option to project settings at `https://app.dependabot.com/accounts/[ACCOUNT]/repos/[ID]`.

**Comment by greysteil** [comment]
Good shout - one for you @feelepxyz.

I'll also see if we can automatically disable Dependabot when a repo is archived.

**Comment by greysteil** [comment]
Since the dashboard is now on borrowed time (we'll be moving configuration to be directly within GitHub) I'm closing this.
