### ISSUE TITLE
ignored_updates not working for Python repository

### ISSUE THREAD

**Issue by edmorley** [dependabot/feedback#359]
Hi!

I just activated Dependabot on our repository (replacing pyup), with a number of Python packages listed under `ignored_updates`. When I first added the config file, I used the same version specifier as I had for pyup, eg `<2` to mean "please limit PRs to versions that are less than 2".

However after merging the config to `master` a number of unwanted PRs were opened - at which point I realised that the version range should probably be eg `>=2`, to mean instead "these are the versions that should be ignored":
https://github.com/mozilla/treeherder/blob/9d0c77620f8b5ea77f2acb84e66bd499c7551c5d/.dependabot/config.yml

However even after fixing the version ranges, the existing unwanted PRs have not been closed, and additional PRs opened (presumably these additional PRs were not opened prior, due to the initial 5 PR limit?):
https://github.com/mozilla/treeherder/pulls/app%2Fdependabot

Am I still specifying the version incorectly, or is there a bug in Dependabot's version matching for Python?

Many thanks :-)

**Comment by greysteil** [comment]
Let me take a look into this one. That `django` match could be to do with capitalisation, but I'm not sure and want to dig in properly (and it's a bug either way).

**Comment by greysteil** [comment]
Digging in to this, it's definitely a bug caused by capitalisation. I'll get that fixed.

**Comment by greysteil** [comment]
Fixed. Sorry about that one!

**Comment by greysteil** [comment]
Also, we didn't have logic to automatically close PRs when an ignore condition was added for them in a config file. We have that now. (Config files are new so little oversights like that might exist - it's the same reason the capitalisation bug was present.) Thanks again.

**Comment by edmorley** [comment]
Hi :-)

I was wondering if the fix for the ignore logic might now be preventing the latest Django update from being picked up?

The ignore entry is here:
https://github.com/mozilla/treeherder/blob/7060eef00763e1690879461e9929886375988497/.dependabot/config.yml#L27-L30

This in-range version was released today:
https://pypi.org/project/Django/1.11.20/

**Comment by greysteil** [comment]
You're totally right - I applied the fix to our main backend, which meant ignores were working, but not to our update script. As a result, the update script wasn't adapting to find the latest version *given the ignored versions*. I've just shipped a fix for that, and will re-run now.

**Comment by edmorley** [comment]
Many thanks :-)
