### ISSUE TITLE
Pipfile support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#36]
Right now almost every `python` package uses `requirements.txt`. But, recently created `pipenv` with `Pipfile` is way better than using raw `requirements.txt`.

Do you plan to support `Pipfile` and `Pipfile.lock`? Here's a sample repo: https://github.com/wemake-services/wemake-django-template

**Comment by greysteil** [comment]
Check out https://github.com/dependabot/dependabot-core/pull/15!

I want to get Python support out of beta with `requirements.txt` first (there are still a few tweaks to library support to be made, but it should be done in the next week), but after that I'm super keen for Pipfile support.

**Comment by greysteil** [comment]
OK, I've got a very first version of this working, and the initial PRs are [here](https://github.com/greysteil/wemake-django-template/pulls).

Would love some feedback. For starters I'm guessing we shouldn't be updating the `host-environment-markers`?

**Comment by greysteil** [comment]
OK, I'm relatively happy with how this is working, so am going to announce the beta. Would love to hear your feedback if you give it a try!

**Comment by sobolevn** [comment]
@greysteil this is awesome. 

Activated https://github.com/wemake-services/wemake-django-template
