### ISSUE TITLE
Change From name

### ISSUE THREAD

**Issue by rogerhu** [dependabot/feedback#36]
The brackets in "dependabot[bot]" can't be filtered by Gmail.  Is there a way to provide an option to change the From name?

**Comment by greysteil** [comment]
I think we *might* be able to change this to `dependabot-bot` without too much trouble - would that make gmail filtering easier?

**Comment by rogerhu** [comment]
Yes assuming the filters are ok with the dashes! (Which I think they are)

**Comment by greysteil** [comment]
👍 - do you want to check, before I try to make the change?

**Comment by rogerhu** [comment]
Tested by sending myself emails with dashes.  It appears to work fine.

**Comment by greysteil** [comment]
Frustratingly, on closer inspection it looks like there's no way for us to change the From name in the emails you get from GitHub - it's determined by the user who creates the PR, and for GitHub integrations is always suffixed with `[bot]`. All I can suggest is speaking to GitHub themselves 😞
