### ISSUE TITLE
Dependabot downgrading Python package to an older version due to post-release suffix

### ISSUE THREAD

**Issue by edmorley** [dependabot/feedback#360]
Hi!

Dependabot has opened this PR, which changes the version of `djangorestframework-filters` from `0.10.2.post0` to `0.10.2`:
https://github.com/mozilla/treeherder/pull/4580

This change is actually downgrading the package version, since `0.10.2.post0` is the most recent:
https://pypi.org/project/djangorestframework-filters/#history

The "post version" identifiers are listed in the Python versioning spec, here:
https://www.python.org/dev/peps/pep-0440/#post-releases

Many thanks :-)

**Comment by greysteil** [comment]
Thanks for the extremely clear issue @edmorley. Fixed in https://github.com/dependabot/dependabot-core/commit/87bbbcf21d02b7e2f0dea833e5a442f3b8813576.

**Comment by edmorley** [comment]
Many thanks for the quick fix!

Will Dependabot close the PR once this is deployed, or will I need do so manually? :-)

**Comment by greysteil** [comment]
It should close it next time it tries to rebase it (and I've just triggered a rebase of it manually from my side).
