### ISSUE TITLE
github-redirect.dependabot.com URLs not clickable in PR comment

### ISSUE THREAD

**Issue by edmorley** [dependabot/feedback#364]
Hi

In mozilla/treeherder/pull/4635 the changelog section in the description looks like:

> pytest 4.2.1 (2019-02-12)
> =========================
> 
> Bug Fixes
> ---------
> 
> - `#2895 <https://github-redirect.dependabot.com/pytest-dev/pytest/issues/2895>`_: The ``pytest_report_collectionfinish`` hook now is also called with ``--collect-only``.

It would be good to adjust the URL replacement such that the `#2895` was a markdown link using the redirector URL, rather than both being a code comment.

Many thanks :-)

**Comment by edmorley** [comment]
Similarly with mozilla/treeherder/pull/4634

**Comment by greysteil** [comment]
Thanks Ed. These ones are a real case of whack-a-mole - we need to sanitize the content so that we don't accidentally spam GitHub PRs with links / contributors with emails, but it's complicated! I'll have a look at fixing those, though.

**Comment by greysteil** [comment]
OK, this should be fixed. Before inserting the text in the PR description Dependabot will now run any changelogs that have a `.rst` suffix through Pandoc to covert them to markdown.

Relevant commit is [here](https://github.com/dependabot/dependabot-core/commit/92f474c26248ca6c3a7d65382f9d4a66a7a672f2). I think it's quite a clean solution, so 🤞.

**Comment by greysteil** [comment]
Just verified that it's fixed: https://github.com/greysteil/treeherder/pull/4.

Thanks again for the heads up on this one! 🙂

**Comment by edmorley** [comment]
The test PR looks great - elegant fix! Many thanks :-)
