### ISSUE TITLE
Will the command @dependabot merge rebase the PR is necessary?

### ISSUE THREAD

**Issue by thomaseizinger** [dependabot/feedback#365]
Assuming you have

1. auto-rebase disabled
2. 3 open dependabot PRs
3. GitHub branch protection that needs up-to-date branches

If I issue `@dependabot merge` on all three PRs, will dependabot go ahead and rebase all three of them in some order so they are merged one after the other?

The idea would be to, at the end of a working day, look at some dependabot PRs and choose which ones to merge and let dependabot do the work over night.

**Comment by greysteil** [comment]
Not quite. It will do that for the first one (realise it can't merge, trigger a rebase, and then merge after the rebase. However, the other two won't be automatically rebased after they get out-of-date a second time. I think it would be good if they did, though, so I'm going to implement that now.

**Comment by greysteil** [comment]
Implemented. Thanks for the feedback!

**Comment by thomaseizinger** [comment]
Wow that was quick! :open_mouth: 

You are amazing man! Thank you!
