### ISSUE TITLE
Rate Limiting Auto-Rebases

### ISSUE THREAD

**Issue by osman** [dependabot/feedback#367]
We often see an issue where merging a branch, causes all pending Dependabot PRs to automatically get rebased. For us, this causes swarms of running jobs in CircleCI. It would be nice if those rebases were sent sequentially.

For example, given 5 pending dependabot PRs, the current implementation results in 5+4+3+2+1 = 15 builds. If they are sent sequentially (and auto-merge is turned on) then it would be 5+5 = 10 builds. For 10 pending PRs, it would be 55 builds vs 20.

For this reason, we currently have auto-rebase turned off and would like to turn it back on.

**Comment by feelepxyz** [comment]
@osman great suggestion! We've been thinking of something similar but haven't managed to get to it yet due to a bunch of ongoing robustness work. We're keen so will get to to in due course! Sorry to keep you waiting.

**Comment by feelepxyz** [comment]
@osman added your suggestion to this existing issue: https://github.com/dependabot/feedback/issues/316
