### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by Eddi2015** [dependabot/feedback#369]
I can't log in to my DependaBot Dashboard. It just randomly says this: Authentication failure

Sadly there's not much more information that I can give you.

**Comment by greysteil** [comment]
Hmmm, that’s weird. Have you tried clearing your cookies and removing the Dependabot OAuth permission in GitHub? Then make sure you’re hitting https://app.dependabot.com

**Comment by greysteil** [comment]
The link to death Dependabot in GitHub is https://github.com/settings/apps/authorizations

**Comment by greysteil** [comment]
@Eddi2015 did you get to the bottom of this?

**Comment by Eddi2015** [comment]
Gonna try it again tomorrow. If the problem persists I'll reopen the issue.
