### ISSUE TITLE
Microsoft acquisition

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#37]
According to Microsoft latest news,...will anything change for dependabot ?
![selection_002](https://user-images.githubusercontent.com/5235127/40950321-01ad4230-68be-11e8-97db-b08ce6878757.jpg)

**Comment by greysteil** [comment]
It shouldn’t do - Microsoft have said they’re committed to continuing to build GitHub as a platform for other apps, so I don’t see any reason anything will change with Dependabot.

If we see a large number of people moving to GitLab it will increase the priority that we add support for that, though.
