### ISSUE TITLE
[python]: Missed update

### ISSUE THREAD

**Issue by JayH5** [dependabot/feedback#370]
Hi there 👋

I'm seeing an update that is failing to be detected for a Python package, about 8 hours after release on PyPI, and after pressing the `Bump now` button. The requirement is [here](https://github.com/praekeltfoundation/debian-wheel-mirror/blob/d65af2813d64d9750afe91223036604ca3dbfdcb/requirements.txt#L10). The pinned version is `regex==2019.02.07` when the latest version is `2019.02.18`.

`regex`'s version numbers are a bit non-standard and `pip` will normalise out the leading `0`'s (e.g. normalised to `2019.2.18`). Not sure if that's relevant.

This package has been updated many times by Dependabot in the past so I'm just checking if something has changed.

Thanks 🙏

**Comment by greysteil** [comment]
Thanks for the feedback - I'll take a look.

**Comment by JayH5** [comment]
Just had 3 Dependabot PRs come through so I'm guessing you fixed something 😄

**Comment by greysteil** [comment]
Yes - boosted the number of workers on our queues. Lots of PRs going out this morning and we'd got backed up! 😄

**Comment by JayH5** [comment]
Thanks a lot!
