### ISSUE TITLE
Individual Contributor License agreements

### ISSUE THREAD

**Issue by bsideup** [dependabot/feedback#371]
Hi!

Some orgs require signing iCLAs before accepting the PRs. Spring projects is a good example of such.

Would it be possible to manually request signing the iCLA by Dependabot to keep the check happy?
Example:
https://github.com/bsideup/liiklus/pull/94#issuecomment-464639640

**Comment by greysteil** [comment]
This one's a real pain. Dependabot acts as a GitHub app, so there's no user to be logged in as (it's not possible to log in as `dependabot[bot]`. As a result, Dependabot needs to be whitelisted in the CLA checker.

We've worked with the folks at [cla-assistant](https://github.com/cla-assistant/cla-assistant) to make that easy there, but it looks like you're using a different provider. Let me dig into how whitelisting works for that one.

**Comment by bsideup** [comment]
Hi @greysteil! Thanks for a fast answer. Ask me if you need to know anything about the Pivotal's CLA check.

**Comment by greysteil** [comment]
Will do! Just looking through the code [here](https://github.com/pivotalsoftware/pivotal-cla) for a way to whitelist.

**Comment by bsideup** [comment]
Maybe you can share how "cla-assistant" did it in their implementation (from the GitHub's API point of view). I will forward it to the Pivotal's CLA check team for diiscussion

**Comment by greysteil** [comment]
They ended up adding a general whitelist category, with its own UI: https://github.com/cla-assistant/cla-assistant/issues/173.

Having scanned the Pivotal CLA repo I can't find anything to allow whitelisting there. I think this is definitely going to require some work from the CLA check team as a result. 😢

Can I leave this one with you? Basically what is needed is some kind of whitelisting that allows the CLA to be skipped.

**Comment by dsyer** [comment]
It's not clear that a whitelist is acceptable on legal grounds. We might have to insist that the PR is sent by an identifiable user account or something.

**Comment by bsideup** [comment]
I will check with the CLA check team whether it's okay from the legal side and get back to you as soon as I have some information about it.
Thanks for reacting so incredibly fast👍 ...as always 😅

**Comment by greysteil** [comment]
No worries.

@dsyer - I could put something in the Dependabot T&Cs saying Dependabot gifts its commits if your lawyers provide guidance on what they'd need. Would want it to be general and apply to everyone.

**Comment by greysteil** [comment]
Closing as stale, but ping me if there are any changes Dependabot can make to help here.
