### ISSUE TITLE
PR to update Python package 'slugid' linking to wrong repository

### ISSUE THREAD

**Issue by edmorley** [dependabot/feedback#372]
Hi

Dependabot opened a PR to update the `slugid` Python package here:
https://github.com/mozilla/treeherder/pull/4658

However the repo and compare view links within the PR description link to the Javascript version of the library (https://github.com/taskcluster/slugid) rather than the Python port (https://github.com/taskcluster/slugid.py).

The PyPI page for the package is here:
https://pypi.org/project/slugid/

On that page the homepage for the package is listed as:
http://taskcluster.github.io/slugid.py

I'm presuming Dependabot is scraping the homepage and finding this GitHub URL reference here?

```
Slugid.py

A python port of https://github.com/taskcluster/slugid
```

Perhaps the scraping could check to see if there are multiple GitHub URLs specified, and if so, only link to the homepage URL not the first GitHub URL found?

Also, I'm presuming it would help if the actual repository URL was set in the PyPI metadata in `setup.py`. Which fields does Dependabot use?

CC @jhford

**Comment by greysteil** [comment]
Ah nuts. Yes, that's exactly the issue - the Dependabot logic for finding git sources for Python packages is [here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/metadata_finder.rb). Let me take a look into what we ned from `slugid` to get the correct URL.

**Comment by greysteil** [comment]
PR to address in `slugid` is [here](https://github.com/taskcluster/slugid.py/pull/9).

This is a furstrating but pretty unlikely case - Dependabot does quite a lot to check that the source it's linking to is correct (including checking that the name of the package appears in the README for the source. Getting fooled by a port like this seems quite unlikely, and hard to work around, but I'll have a think on how we can change our logic to guard against it further.

**Comment by edmorley** [comment]
> Dependabot does quite a lot to check that the source it's linking to is correct (including checking that the name of the package appears in the README for the source. Getting fooled by a port like this seems quite unlikely

Ah I didn't know it did that - I agree this is likely something that's not going to come up often and therefore not worth trying to fix. Thank you for the metadata PR against slugid :-)
