### ISSUE TITLE
sidekiq-ent missing changelog

### ISSUE THREAD

**Issue by bzf** [dependabot/feedback#374]
Could you add the changelog for the `sidekiq-ent` gem? It's available [here](https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md).

Thanks!

**Comment by greysteil** [comment]
Hmmm, that's going to be slightly trickier than it sounds. Dependabot's changelog lookup is all programmatic. Let me take a look...

**Comment by bzf** [comment]
Cool, I understand that it might be complicated to have some external changelog URL for some packages. Can't think of any other package where this could be applicable either 😄 

Thanks for having a look though! 👍

**Comment by bzf** [comment]
Noticed today that it's the same for the `sidekiq-pro` gem 😄 

https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md

**Comment by greysteil** [comment]
Yeah, I noticed that too. It's a really important gem, so I'd like to get this working 🙂

**Comment by greysteil** [comment]
Been working on this this morning. I think [this change](https://github.com/dependabot/dependabot-core/compare/da3fb24..04c06f) should fix this. Will deploy this afternoon.

**Comment by greysteil** [comment]
Change is now deployed, so this should be fixed. 🎉

**Comment by bzf** [comment]
Awesome! Thank for putting time into fixing this 😄

**Comment by greysteil** [comment]
No worries - Dependabot is really just a collection of hundreds of small bits of polish, so it's almost always worth our time to make things a little bit better 🙂
