### ISSUE TITLE
UI is very slow on a large collection of repos

### ISSUE THREAD

**Issue by chriseyre2000** [dependabot/feedback#375]
We have over a thousand git repos which makes the user interface rather slow.
This also makes editing fields unreliable - it can take several attempts to allow an item to be updated.

**Comment by greysteil** [comment]
Thanks for the feedback. Can you let us know exactly which screens are slow (even better if you tell us exactly which endpoints)?

There are some things we can change here, if it's our backend that's slow, and others that are trickier (if it's GitHub responding slowly).

**Comment by chriseyre2000** [comment]
Most of the management screens are slow. Specific project setting updates are unreliable for example moving to live update.

**Comment by greysteil** [comment]
Hmmm, I can't see any reason why that endpoint would be slow - changing the update schedule doesn't make any requests to GitHub (except for auth), and it's a show view so I can't see how we could have many DB queries.

I guess it's possible that a large number of other requests could be being made at the same time and slow things down, but I'm not see any errors in our backend related to this whatsoever.

@feelepxyz - any ideas?

**Comment by greysteil** [comment]
@chriseyre2000 can you let me know the name of the GitHub account you're seeing this on?

**Comment by feelepxyz** [comment]
@chriseyre2000 do you have an example project id that you're finding slow? For the live updates, are they not triggering updates where you think they should?

**Comment by MatMoore** [comment]
Hi @feelepxyz,

This might be a slightly different problem, but my organisation also has > 1000 repos and if I go to

https://app.dependabot.com/accounts/ministryofjustice/add

Then I can't actually get to the repo I want to add because I have to keep clicking "show more repos". This makes it hard to set up dependabot in the first place (I've been using the [config file](https://dependabot.com/docs/config-file/) as a workaround).

**Comment by feelepxyz** [comment]
@MatMoore oh yeah the dashboard really isn't built to manage that many repos. Sorry if this is causing any inconvenience!

We're currently focusing on improving config files and will be adding account level settings in near future, hopefully reducing the need for the dashboard.

How are you finding the setup with config files? Anything missing or making it hard to manage your scale?

**Comment by MatMoore** [comment]
@feelepxyz I'm only working with a few of the repos myself so I didn't really have problems with it, it's just I had to read the documentation instead of just clicking a button so it took a little bit longer than it otherwise would have.

I don't know if its feasible but it would be nice as well if there was an example for every language that I could just copy into new repos, a bit like how github can generate .gitignore files for you.

**Comment by feelepxyz** [comment]
> I don't know if its feasible but it would be nice as well if there was an example for every language that I could just copy into new repos, a bit like how github can generate .gitignore files for you.

@MatMoore thanks! We've been thinking of creating a PR with the config file for the first language you add from the dashboard. Is this what you had in mind?

**Comment by MatMoore** [comment]
I'm not sure - what do you mean by the first language added from the dashboard? In our case we use a mix of languages so the config would still need to be different for different repos.

**Comment by feelepxyz** [comment]
@MatMoore one idea we've been toying with is allowing you to add repos from the UI but have it create the config file for you based on the settings/language defined in the dashboard. Nothing immediate planned on this but we're keen to improve the experience of getting started with config files over the next few months.

**Comment by chriseyre2000** [comment]
The projects are all private (mergermarket). 
The main problem I have is the UI being incredibly slow/imprecise when editing particular project settings. I am trying to get as much as I can set to immediate updates and auto merge once tests pass.

**Comment by feelepxyz** [comment]
@chriseyre2000 sorry for the crappy experience! When you say imprecise, do you have a specific example in mind? Also, what browser are you using? Have you tried logging in an incognito/private tab with the same slowness? Would be helpful to get as much detail as possible to figure out what's going on here.

Also, if you're setting up lots of projects with the same settings, config files might make the setup a bit quicker: [config  file docs](https://dependabot.com/docs/config-file/)

**Comment by feelepxyz** [comment]
@chriseyre2000 FYI I've seen quite a few errors for your account so digging into these to see what's going wrong

**Comment by chriseyre2000** [comment]
The main errors are when using the dropdown clicking on an item has no effect, using the keyboard sometimes worked.

I have been using chrome on mac, not yet tried incognito mode

**Comment by feelepxyz** [comment]
@chriseyre2000 looks like we're doing too many requests causing GitHub to rate limit some requests, which in turn causes flaky responses on the front end.

I've made a change reducing the number of requests on the dashboard which should improve things for you. Could you see if this has improved things for your account?

**Comment by chriseyre2000** [comment]
Thanks that's much better.

**Comment by feelepxyz** [comment]
@chriseyre2000 great! Thanks for reporting this and sorry for the slow turnaround!
