### ISSUE TITLE
Dev/Prod dependency decision wrong when using both setup.py & Pipfile

### ISSUE THREAD

**Issue by richardson-trevor** [dependabot/feedback#376]
In our libraries we tend to use a setup.py file to specify the library and it's dependencies and a Pipfile for other potential environment-pinning declaration (tests, etc). Using this, it seems deps in the setup.py file are always considered dev deps in PRs from Dependabot, even when they are declared in the `install_requires` block. Is this expected? I am not familiar with the code here and had some trouble tracking down where the decision was made as to whether deps were dev or prod. Appreciate any guidance/input!

Excellent work with this product. It has saved our team a ton of time!

**Comment by greysteil** [comment]
Oh good catch! Fixed in https://github.com/dependabot/dependabot-core/commit/d65f08d7244e3c97b003fe2bb6f18e7c1d08a54f, which I'm releasing now - thanks for flagging.
