### ISSUE TITLE
Doesn't update package.json when using tabs

### ISSUE THREAD

**Issue by dimitarnestorov** [dependabot/feedback#377]
https://github.com/dimitarnestorov/use-hooks/commit/4c31123eaa4aa11bc2dd64e03cd1be4d271cb6bd

It only updates `yarn.lock`. The only thing strange in my repo would be that my `package.json` uses tabs instead of spaces (yarn supports it). Not 100% sure if that's the case though.

**Comment by greysteil** [comment]
It looks like Dependabot has (correctly) identified your repo as a library, so it assumes you don't want it to update the `package.json` unless required. You can change that setting in your dashboard though - just click the cog by the update config and you'll get a screen which has this option:

![image](https://user-images.githubusercontent.com/1144873/53266487-c821b980-36d8-11e9-8a2e-69abb393bab6.png)

**Comment by dimitarnestorov** [comment]
@greysteil Is there an option to bump the versions only for development dependencies?

**Comment by greysteil** [comment]
Yep! For that you'll need to do the configuration using a [config file](https://dependabot.com/docs/config-file), and to specify `dependency_type: development` under `allowed_updates`.
