### ISSUE TITLE
Unable to access dependabot dashboard on new account

### ISSUE THREAD

**Issue by elashpear** [dependabot/feedback#378]
Hello, I recently replaced my GitHub account with a new one tied to my company email address. Now, when I try to use the Dependabot dashboard, it tells me I need to install the dependabot app, but when I do I get an error:
<img width="640" alt="screen shot 2019-02-22 at 2 30 37 pm" src="https://user-images.githubusercontent.com/47397266/53275051-7401df80-36ae-11e9-813c-3dfa7af8406f.png">

The Network monitor shows the following request failed:
```
GET /active_repos?account-id=47397266&account-type=user HTTP/1.1
Host: api.dependabot.com
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Authorization: Bearer [SANITIZED]
Origin: https://app.dependabot.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36
Accept: */*
Referer: https://app.dependabot.com/accounts/elashpear
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

With this response:
```
HTTP/1.1 404 Not Found
Server: Cowboy
Date: Fri, 22 Feb 2019 01:27:10 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD
Access-Control-Expose-Headers: 
Access-Control-Max-Age: 1728000
Content-Type: application/json
Cache-Control: no-cache
X-Request-Id: 089a8051-86cf-4750-8b49-49d9a0e42545
X-Runtime: 0.201197
Vary: Origin
Transfer-Encoding: chunked
Via: 1.1 vegur

{"errors":[{"status":404,"title":"Not Found","detail":"Account not found"}]}
```

The second time I try to log into Dependabot, I'm prompted to install again, but as I already have the app installed in my personal and org accounts, clicking it just takes me to the GitHub settings page for the Dependabot app:
<img width="629" alt="screen shot 2019-02-22 at 2 34 32 pm" src="https://user-images.githubusercontent.com/47397266/53275220-06a27e80-36af-11e9-9adf-43e6b20105b3.png">

So I can't seem to use the Dependabot admin panel anymore. Uninstalling the GitHub app and starting over just loops me back to the beginning (404 error, then GitHub settings pages).

**Comment by hmarr** [comment]
That's no good - sorry about this! And thanks for the detailed bug report.

It could be that your credentials have been cached too aggressively in localstorage.

If you try running `curl -H "Authorization: Bearer {TOKEN}" https://api.github.com/user` with the token you removed from the request, you should be able to see which user the token belongs to.

If the token does belong to your other user, clearing out any cached data (in Chrome, that's Web Inspector -> Application -> Clear Storage) should fix it.

Let us know if that's not the issue and we'll investigate further.

**Comment by feelepxyz** [comment]
@elashpear did you manage to get it working?

**Comment by elashpear** [comment]
@hmarr you're right! My old token was cached - clearing site storage allowed me to go through new account setup successfully.

I didn't notice until just now but there was a hint on the logout menu - my old username was displayed next to the `Log out` button even though my new user was shown at the top of the drop-down!
