### ISSUE TITLE
Live updates not triggering

### ISSUE THREAD

**Issue by Harmon758** [dependabot/feedback#379]
I have a repository's update schedule set to "Live updates", but it was last checked 3 days ago and there's at least two dependencies with updates:

![image](https://user-images.githubusercontent.com/9403740/53307927-ac4a1f00-3862-11e9-9e76-25b7970540ed.png)

**Comment by greysteil** [comment]
Hmm, I can see that Dependabot only picked up the `jsonschema` and `configparser` updates this morning, when it did its daily update job. Let me take a look into why...

**Comment by greysteil** [comment]
OK, I think there's some funky caching going on in warehouse that means Dependabot isn't getting the updates from the [updates feed](https://pypi.org/rss/updates.xml) that it should be getting. I'm going to work around that on our side.

Thanks for flagging this - would have been very hard to track down without the heads up.

**Comment by greysteil** [comment]
OK, this should be fixed now. We're now hitting the updates feed once a minute, rather than once every 10 minutes, and are caching the updates we've previously seen, rather than relying on them being less than 10 minutes old at the point we check.

**Comment by Harmon758** [comment]
I think there's still updates being missed.
The ones I've noticed that haven't triggered yet:
- matplotlib 3.0.3
- attrs 19.1.0
- certifi 2019.3.9
- psutil 5.6.0 (and 5.6.1)

**Comment by greysteil** [comment]
I looks like Dependabot did trigger update runs for all of the above, but because you had 10 PRs open at the time it didn't create new PRs for you (Dependabot limits itself to 10 open PRs at any given time).

Now that you've closed those PRs you'll receive the additional updates.

**Comment by Harmon758** [comment]
Ah, I didn't know that. Thanks!

**Comment by skalero01** [comment]
@greysteil right now the live updates are not working on my side. Did a push to a package 10 minutes ago and it dependabot hasnt updated all the projects using the package. Its using packagist. Do you know how often the system checks for live updates?

**Comment by Harmon758** [comment]
I had a successful live update just 12 hours ago.

**Comment by skalero01** [comment]
@Harmon758 do you know if there isnt any delay to make the update? or should it be done immediately?

**Comment by Harmon758** [comment]
It tends to be fairly prompt. 10 minutes is hardly a long enough time to wait before concluding that live updates aren't working at all though. And even if you are encountering an issue, it's unlikely to be the same as this one.

**Comment by Harmon758** [comment]
I just had another live update trigger, so they are definitely still working.

**Comment by greysteil** [comment]
Not sure how to debug this one, but FYI Dependabot triggers those updates by checking https://packagist.org/feeds/releases.rss every 10 minutes, so there will generally be a short delay.
