### ISSUE TITLE
Edited by someone other than Dependabot

### ISSUE THREAD

**Issue by jacobwgillespie** [dependabot/feedback#38]
I sometimes get this message, for instance at https://github.com/jacobwgillespie/styled-icons/pull/122.  As far as I know, nothing other than Dependabot has updated that PR.

**Comment by greysteil** [comment]
Thanks for the head up - I’ll dig into it.

**Comment by greysteil** [comment]
@jacobwgillespie - have you definitely seen this before? Dependabot has a different commit SHA stored against that PR, but I can't think of any reason how it could have got that wrong...

**Comment by greysteil** [comment]
Ah, actually, I think I get it. The registry went a little haywire and sent Dependabot a *lot* of hooks about that particular release, which triggered a lot of contemporaneous update runs. This is going to be race-condition related. I'll keep digging...

**Comment by greysteil** [comment]
OK, race condition is now fixed so this can't happen again. I'll update the head commit for that PR on Dependabot's side manually now, too.

Thanks for reporting this!

**Comment by jacobwgillespie** [comment]
Awesome, thanks!  Yeah, this is the 2nd or 3rd time I'd seen this, so nice to have it fixed!  🎉
