### ISSUE TITLE
Could it create an issue instead of PR?

### ISSUE THREAD

**Issue by php-coder** [dependabot/feedback#380]
I have opted out from dependabot some time ago but I'm still need some kind of notifications :) Is it possible to configure dependabot to create issues about available updates instead of pull requests?

Thanks!

**Comment by greysteil** [comment]
I'm not against this, but it would be quite a lot of work on our side and it's not a priority for the next 3-6 months.

In the meantime, hacking something together to do this using https://github.com/dependabot/dependabot-core, following the pattern in https://github.com/dependabot/dependabot-script, shouldn't be too tricky.

**Comment by feelepxyz** [comment]
@php-coder added your comment to this existing issue: https://github.com/dependabot/feedback/issues/117
