### ISSUE TITLE
Dependabot couldn't parse the go.mod found at /go.mod

### ISSUE THREAD

**Issue by simonpasquier** [dependabot/feedback#381]
I've tried dependabot on https://github.com/prometheus/prometheus/ but it can't parse the `go.mod` file. It might because of the `replace` directive.

**Comment by hmarr** [comment]
Sorry about this - I'll have a look and get back to you shortly!

**Comment by simonpasquier** [comment]
No problem. Many thanks for the tool!

**Comment by hmarr** [comment]
I've found the issue - we didn't have bzr installed, and `labix.org/v2/mgo` requires bzr to be installed (it's fetched from https://launchpad.net/mgo/v2).

I'll have a fix deployed soon, and let you know as soon as it's out.

**Comment by hmarr** [comment]
The fix is out, and I tested it on a fork of https://github.com/prometheus/prometheus, and it all seems to be working now.

Sorry for the initial trouble you faced, and please let me know if you spot anything else not working as expected!

**Comment by simonpasquier** [comment]
Thank you very much for the very fast answer! I'll be definitely poking with dependabot in the coming weeks.

**Comment by hmarr** [comment]
Great! Any questions - just ask.
