### ISSUE TITLE
Default reviewers / labels

### ISSUE THREAD

**Issue by waghanza** [dependabot/feedback#383]
Hi,

Actually **default_reviewers** and **default_labels** stay on each package levels, I mean not globally (but for each dependency).

I think this could be a great addition to have the same features, but in a global scope, I mean having
~~~yaml
version: 1
default_reviewers:
  - reviewer1
  - reviewer2
default_labels:
  - label1
  - label2
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
~~~
so as the `PR` create by @dependabot-bot is labeled and reviewer is picked by default (if no one is specified at dependency level).

Regards,

**Comment by feelepxyz** [comment]
@waghanza thanks for the suggestion and sorry for the slow response on this one! We're currently planning a bunch of work to add account level settings to the config file so want to figure this out before sharing general settings that might make it less intuitive.

**Comment by feelepxyz** [comment]
@waghanza added your suggestion to this existing issue: https://github.com/dependabot/feedback/issues/353
