### ISSUE TITLE
For JS dependencies that specify a git source and a SemVer requirement, use the version number (from the tag) instead of the commit SHA

### ISSUE THREAD

**Issue by guillaumecostanza** [dependabot/feedback#386]
Hi,

Is it possible to use package.json version instead of commits for private repositories
Acutal PRs name looks like : Bump <my-private-repo> from `f9db710` to `0567f71`

**Comment by greysteil** [comment]
Yeah, I'm working on this today. The trouble is that the version in the lockfile is the git SHA, not the tag, so it's a little tricky.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/fe61112d23eebc123a5717704a9cfaf9ae3e75a1.

**Comment by guillaumecostanza** [comment]
@greysteil great ! what will be the behavior ? will it be by default ? when will it be released (so I can test it)

**Comment by greysteil** [comment]
Behaviour is what you'd expect - the PRs will include version numbers, like other PRs do. Deploying now. 🤷‍♂️
