### ISSUE TITLE
Location of requirements file

### ISSUE THREAD

**Issue by peterbe** [dependabot/feedback#387]
We don't have a `/requirements.txt` file but rather it's [`/app/requirements/default.txt`](https://github.com/mozilla/experimenter/blob/master/app/requirements/default.txt)

How do I set that up on...
<img width="909" alt="screen shot 2019-02-28 at 3 55 08 pm" src="https://user-images.githubusercontent.com/26739/53597868-423abe00-3b71-11e9-8122-63bb5dc1f9e7.png">

**Comment by greysteil** [comment]
If you specify the `app` directory Dependabot will figure it out from there :-)

**Comment by peterbe** [comment]
That worked!
