### ISSUE TITLE
Add support for Appraisals file

### ISSUE THREAD

**Issue by olbrich** [dependabot/feedback#388]
The `appraisal`(https://rubygems.org/gems/appraisal) gem is useful for testing against sets of gemfiles (often for testing a gem against a range of different rails versions).  These files are usually generated into a subdirectory by `appraisal generate`, and the `Appraisals` file in the repo usually defines overrides that need to be done against specific versions.

It would be useful if dependabot could:
1. run `appraisal generate` after modifying the Gemfile or gemspec it finds
2. add any generated files to the PR it authors.

**Comment by greysteil** [comment]
Thanks for this. We've got another issue tracking it at https://github.com/dependabot/dependabot-core/issues/978, so I'm going to close, but I agree appraisals support would be nice.
