### ISSUE TITLE
Feature: Auto-merge certain gems

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#39]
It would be really nice if I could mark certain gems as auto-merge. (a whitelist of gems to auto-merge)

On a daily basis, I get dependabot PRs against gems which make frequent releases....and don't need any manual review/evaluation (like aws-sdk, rspec, etc).

I also get PRs for gems which require much more involve evaluation (and may not cause my CI suite to fail, because the "failure" may be more subjective), like jquery-rails, bootstrap, etc.

**Comment by greysteil** [comment]
I'm definitely 👍 on that. I'm powering through a bunch of small bug fixes right now (was on holiday last week), but adding a bunch of merge settings is the next big change I'd like to make.

**Comment by nesl247** [comment]
Isn't this already possible?

![image](https://user-images.githubusercontent.com/1037526/42651251-e0c0d41a-85dc-11e8-8d35-77c639feb807.png)

Or is this just recently added after you spoke @greysteil?

**Comment by greysteil** [comment]
Ah, that was added very recently and I forgot to mention it on this issue. Yes - now possible! 🎉
