### ISSUE TITLE
Add icon for dependabot commits

### ISSUE THREAD

**Issue by styfle** [dependabot/feedback#39]
There is an icon for dependabot on the PR but not in the commit.

Compare the following:

### Icon
https://github.com/styfle/geoslack/pull/11

### No icon
https://github.com/styfle/geoslack/commits/master

**Comment by greysteil** [comment]
@bkeepers / @sbarnekow - any plans to get this one fixed? I put it in the [platform forum](https://platform.github.community/t/commit-avatars-for-bots/2332) a few months ago and you mentioned it was on the backlog - I'm hoping it's a really easy change on your side?

**Comment by greysteil** [comment]
GitHub have said they’re going to fix this [here](https://platform.github.community/t/commit-avatars-for-bots/2332/5) 🎉. Closing this issue for now.
