### ISSUE TITLE
Dashboard error after adding a private repo

### ISSUE THREAD

**Issue by MatMoore** [dependabot/feedback#391]
I added a dependabot config file to a private repo, and when I went back to my organisation dashboard I got this error:

<img width="575" alt="screen shot 2019-03-06 at 13 41 34" src="https://user-images.githubusercontent.com/87579/53885566-fd51d400-4015-11e9-8d04-2fdc1945b943.png">

In developer console I see this error for `https://api.dependabot.com/active_repos?account-id=2203574&account-type=org`

```
{"errors":[{"status":500,"title":"Internal Server Error"}]}
```

**Comment by feelepxyz** [comment]
@MatMoore oh looks like a bug on our side caused by the limit of private repos being hit.

You'll need to upgrade the organisation plan from the marketplace, you can access the link on your plan page: https://app.dependabot.com/accounts/ministryofjustice/plan

Sorting out the bug.

**Comment by feelepxyz** [comment]
@MatMoore deployed a fix for the error message

**Comment by MatMoore** [comment]
Ah ok, that makes sense. Thanks.
