### ISSUE TITLE
Gradle: failed to update dependencies that has referenced versions

### ISSUE THREAD

**Issue by Tapchicoma** [dependabot/feedback#392]
When [dependencies.gradle](https://github.com/freeletics/CoRedux/blob/master/dependencies.gradle) has separated versions variables from dependency declaration depenabot fails to update:
```gradle
ext.versions = [
    someLibrary : '1.0.0',
]

ext.libraries = [
    someLibrary : "com.example:someLibrary:$versions.someLibrary",
]
```

**Comment by greysteil** [comment]
Good catch! It looks like Dependabot wasn't handling that format at all - I've just shipped [this commit](https://github.com/dependabot/dependabot-core/commit/094d5c3f33b72acc7a9f288071a5ff2248c0c254) which will help, but I think there's more work to do when there's an additional layer of indirection. Let me look into that...

**Comment by greysteil** [comment]
Actually, I think that commit fixes things here. 🎉
