### ISSUE TITLE
Dependencies in monorepo

### ISSUE THREAD

**Issue by ream88** [dependabot/feedback#396]
Hey 👋

I have a monorepo GitHub repository and one of my elixir projects in this monorepo loads a dependency from another elixir project in my monorepo. However this fails as @dependabot fails to find the path. Does @dependabot has access to the whole repo, or only the configured directory?

**Comment by greysteil** [comment]
Hey, sorry for the slow reply.

Dependabot has access to the whole repo, so this shouldn't be failing. If you email me the full name of the repo I'll dig into it.

**Comment by ream88** [comment]
Done 😊
