### ISSUE TITLE
Dependabot checks but doesn't create a PR

### ISSUE THREAD

**Issue by kennethlarsen** [dependabot/feedback#397]
We have a private repository with Dependabot setup. At first, it created an issue in the repo saying it couldn't authenticate with our registry. Then I added the credentials and it started checking our dependencies but it just doesn't create any PRs. 

I know that a lot of the dependencies are out of date so it should find something to upgrade.

Am I missing something here?

**Comment by kennethlarsen** [comment]
@greysteil Absolutely - couldn't find that email in the dashboard. Will send a mail.

**Comment by greysteil** [comment]
Oh good point - we should add an issue template to this repo, and include it there.

@feelepxyz if you have a moment could you handle that?

**Comment by greysteil** [comment]
Following up over email.
