### ISSUE TITLE
Private repos for education?

### ISSUE THREAD

**Issue by suhlig** [dependabot/feedback#40]
I am teaching a university course and I host the sources in a _private_ GitHub repo that I got through their "GitHub Education" programme. I'd like to use Dependabot for that project, too. But with the free plan I cannot use private GitHub repos.

Does Dependabot offer a free plan for educational institutions?

**Comment by greysteil** [comment]
I'd really like to get Dependabot included in the GitHub Education programme - fancy dropping education@github.com an email suggesting it?

In the meantime, if you sign up for a free account and ping me the organisation name then I'll set your account to have full access to private repos 🙂.

**Comment by suhlig** [comment]
Awesome; thanks! The org is uhlig-it. 

I‘ll be writing to education@github.com too.

**Comment by greysteil** [comment]
Great - you're all set up! 🎉
