### ISSUE TITLE
Link to search for dependabot PRs

### ISSUE THREAD

**Issue by BRMatt** [dependabot/feedback#40]
We have several repos, and it can sometimes be hard to know which projects have updates. It'd be helpful if there were links in the dependabot UI to the global github search for the org's dependabot updates.

For example, the link for Geckoboard would be: https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Ageckoboard+label%3Adependencies

**Comment by greysteil** [comment]
Interesting - thanks for the suggestion.

Are you imagining a link from the other PRs we create, or from https://app.dependabot.com?

**Comment by BRMatt** [comment]
I was originally meaning app.dependabot.com as it's currently a bit awkward to get an overview of what buildabot has been doing from within the app, but a link in other PRs could be helpful too.

**Comment by greysteil** [comment]
Closing this for now - I'll keep thinking on it as we refactor the dashboard, though :)
