### ISSUE TITLE
Upgrade notice contains escaped URL

### ISSUE THREAD

**Issue by andymckay** [dependabot/feedback#400]
I got this notice, which is 🆒 but I thought it would be easier if the URL in the message was not escaped and the link was clickable:

![Screen Shot 2019-03-12 at 9 50 18 AM](https://user-images.githubusercontent.com/74699/54219394-a84a0e00-44ac-11e9-97b8-b849c0c5213d.png)

**Comment by greysteil** [comment]
Totally agree! @feelepxyz - can you take a look?

**Comment by feelepxyz** [comment]
Nice catch! Deploying a fix for this now ✌️
