### ISSUE TITLE
Unclear why Dependabot is now failing on our repository

### ISSUE THREAD

**Issue by GKFX** [dependabot/feedback#403]
Hi all! Since https://github.com/camdram/camdram/commit/a9e76c405dcaca6886d3fd857cba4d527e6b563c, Dependabot has been giving error messages and as they're quite uninformative I've got no real idea why. See https://github.com/camdram/camdram/pull/608.

The commands I executed on my machine were
* `composer update twig/twig` to generate https://github.com/camdram/camdram/commit/a9e76c405dcaca6886d3fd857cba4d527e6b563c (broke it)
* `composer require twig/twig` to generate https://github.com/camdram/camdram/commit/a3b6209929e6a75a9779181481816cc4e14b2070 (didn't help)

Would it be possible for us to find out what went wrong and how to fix it? Many thanks!

**Comment by greysteil** [comment]
Just dug into this - it looks like those errors are occurring because Dependabot is timing out when trying to regenerate the PR. That's pretty sad, since we're running it on a box for 8GB of ram, and it has 40 minutes to complete.

I'm going to try running locally and see if there's an underlying error that's causing the slowness.

**Comment by greysteil** [comment]
Found the bug - it's [this commit](https://github.com/dependabot/dependabot-core/commit/d99a97a5292e75ff3406c8a5ef38f1200a91bbb8). I'll get that fixed asap.

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/54392668f9eb436cfd59533cc2d31ae0e3b5c4d5.

**Comment by greysteil** [comment]
I was really hoping that had fixed this, but it doesn't look like it has. I'll keep digging.

**Comment by greysteil** [comment]
Finally fixed by removing xdebug from the Dockerfile 🎉
