### ISSUE TITLE
Gradle: dependency was updated to non-released version

### ISSUE THREAD

**Issue by Tapchicoma** [dependabot/feedback#404]
Please check following PR from dependabot:
https://github.com/freeletics/CoRedux/pull/24/files

In this PR bot tries to update [kotlinx.coroutines](https://github.com/Kotlin/kotlinx.coroutines) to the version that I can't find in release notes.

Also version name is suspicious - `'1.1.1-eap13-2-eap13-2'` - two times `eap13-2`.

**Comment by greysteil** [comment]
That's definitely a bug, to do with the way pre-release strings get recorded. I'll dig into it now.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/acb75bf96e5be02641e0a3712f7846978255a7bc. Thanks for reporting!

**Comment by Tapchicoma** [comment]
@greysteil this happened again, see https://github.com/freeletics/CoRedux/pull/74

**Comment by greysteil** [comment]
This is a weird one - that version *has* been released, it's [here](https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-coroutines-core/). Any idea what's going on with that version numbering?

**Comment by Tapchicoma** [comment]
I think, app should ignore any versions that has "eap" in name.

**Comment by greysteil** [comment]
Interesting. Can you point me to anything about what it means, and whether it's specific to this package? (Apologies not to do the research myself - have a lot of right now!)

**Comment by Tapchicoma** [comment]
Generally "eap" stands for "early access program".

Related news for all Kotlin core libraries: https://blog.jetbrains.com/kotlin/2017/06/early-access-program-for-kotlin-1-2-has-been-started/

I would say it is not really specific to this package, but I also it is not used widely.

**Comment by greysteil** [comment]
Awesome, thanks! Fixed in https://github.com/dependabot/dependabot-core/commit/58b529e1b7d632b56e5caa7939778e25ae4f4676.
