### ISSUE TITLE
Feature: Deeper control over bumping frequency

### ISSUE THREAD

**Issue by exactlyaron** [dependabot/feedback#41]
Hi,

It would be really nice to have a deeper control over bumping frequency. 

For example, we've started doing weekly & bi-weekly Friday show and tells.  It would be nice to have the ability to set a specific day for bumping to happen.  The magic happens and a show and tell build is ready with the latest and greatest to show off to our customers.

Rather than having to remember to manually bump, because who wants to do things a bot could do!

Thanks!    😄

**Comment by greysteil** [comment]
Did you check out the account settings in your dashboard (drop down on the top right)? If you've got a repo set for weekly bumping you can choose the day of the week that that happens in there 🙂.

**Comment by exactlyaron** [comment]
Yeah I have, that effects all repos...?  If it could be defined on a repo basis that would be good. 😄   I probably should have clarified, at the moment it's Friday for one customer, another it's probably going to be a Wednesday.

**Comment by greysteil** [comment]
Ah, OK, that makes sense. I'm going to mark this as a dup of https://github.com/dependabot/feedback/issues/15, but I agree we could do better on this one.
