### ISSUE TITLE
Wrong version numbers in pull request title and body

### ISSUE THREAD

**Issue by StephanBijzitter** [dependabot/feedback#41]
We just enabled Dependabot for a few of our repositories, and while the updating is working just fine, the pull requests do contain some wrong information.

It's not shown in the screenshot, but the `yarn.lock` file also indicates the version changed from 21.0.0 to 21.3.2, while Dependabot states (in the title of the pull request and the body of the pull request) that it went from 21.2.0 to 21.3.2.

This seems to be a little bug.
 
![screen shot 2017-11-13 at 13 57 08](https://user-images.githubusercontent.com/1649903/32726925-0d886eb0-c87b-11e7-8e2b-92c81604409c.png)

**Comment by greysteil** [comment]
Ooh, sorry about that - looking into it now.

**Comment by greysteil** [comment]
Hmm, we've got a couple of similar updates in the system and I can't find yours - can you ping me the `yarn.lock` change? You can use `support@dependabot.com` if you'd rather not paste into this issue.

**Comment by StephanBijzitter** [comment]
The `yarn.lock` change:
```
-eslint-plugin-jest@^21.0.0:
 -  version "21.2.0"
 -  resolved "https://registry.yarnpkg.com/eslint-plugin-jest/-/eslint-plugin-jest-21.2.0.tgz#292044df9cf0866ad9c530e78e6528fae287b926"
 +eslint-plugin-jest@^21.3.2:
 +  version "21.3.2"
 +  resolved "https://registry.yarnpkg.com/eslint-plugin-jest/-/eslint-plugin-jest-21.3.2.tgz#b1cefc05f0fed700eb40185a94d16f6d575d1ef9"
```
I'll send a link to the support e-mail and refer to this issue.

**Comment by greysteil** [comment]
Ah, I think that's what's causing us to pick up `21.2.0`, then - the second line of the diff you just pasted says that that's the version yarn was previously locking to...

**Comment by StephanBijzitter** [comment]
We dun goofed. Should've read better.
That indeed makes perfect sense.

Let's hope this "issue" can at least help other people remember to read more carefully... :-)

Thanks for the rapid responses, though.

**Comment by greysteil** [comment]
You're welcome - thanks for reporting it all the same!
