### ISSUE TITLE
Command to combine two version bumps

### ISSUE THREAD

**Issue by jeffparsons** [dependabot/feedback#410]
Sometimes Dependabot doesn't understand interdependencies between my project's dependencies. Ideally Dependabot would understand all the detail of all kinds of package managers, but that's a pretty big ask.

I'd be really happy with a workaround whereby I can ask Dependabot to combine two of its open PRs into one, if I know that they can only be applied together.

My example in this case is the `rusoto-s3` and `rusoto-core` crates which must be updated in lockstep with each other.

**Comment by merwok** [comment]
I think this is the same request as #5

**Comment by greysteil** [comment]
I think so too. It's still valid feedback, though - thanks @jeffparsons.

**Comment by jeffparsons** [comment]
Oops, sorry, missed that! Thanks!
