### ISSUE TITLE
unable to configure gemfury PyPi URLs

### ISSUE THREAD

**Issue by jcjones1515** [dependabot/feedback#413]
After a recent release I am unable to get our private pypi repos from Gemfury to be usable by Dependabot.  Their docs recommend this as the URL to use: 

https://${FURY_AUTH}@pypi.fury.io/gain-bot/

Can you advise on how my Pipfile and config variables should be configured to make this work?  I've tried several variations and none seem to allow us to connect.  I've tried the URL without the environment variable and putting our token in the credentials but it doesn't seem to want to work.  The message I get is:

```Dependabot couldn't authenticate with https://pypi.fury.io/gain-bot/.

Dependabot tried to authenticate with the details you previously provided, but authentication failed. If they are no longer valid you will need to provide Dependabot with new credentials.

You can provide authentication details in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'.```

**Comment by greysteil** [comment]
I made a change to the way Dependabot deals with config variables for Python last week - let me take a look into this.

**Comment by greysteil** [comment]
This should be fixed in https://github.com/dependabot/dependabot-core/commit/790c6714365433f900c7db9880355515ca8b79c5, which I'm deploying now.

**Comment by greysteil** [comment]
OK, this should be fixed now. Thanks for reporting it!

**Comment by cvitan** [comment]
I'm experiencing this issue as well, could something have reintroduced it?

**Comment by greysteil** [comment]
@cvitan we haven't deployed anything that would regress this. Are you using `pypi.fury.io/<username>` as the Index URL and your secret token as the credential?

**Comment by cvitan** [comment]
@greysteil I am indeed doing that, https://pypi.fury.io/myusername as the Index URL and a deploy token from Gemfury as the credential. I just tried generating a new token and regenerating the config, but got the same result:

```
Dependabot couldn't authenticate with https://${GEMFURY_TOKEN}@pypi.fury.io/myusername/.

You can provide authentication details in your Dependabot dashboard by clicking into the account menu (in the top right) and selecting 'Config variables'.
```

**Comment by greysteil** [comment]
OK, let me take a look. Can you email me the full name of the repo, please?

**Comment by cvitan** [comment]
Sent it to your support email. Thanks!

**Comment by greysteil** [comment]
I *think* I've fixed this, and that the issue was that our new proxy service requires the index URL to be specified with a trailing slash. Just waiting to confirm.

**Comment by greysteil** [comment]
Ah, no, it's not that, but I've found the issue. @cvitan this is an issue on Dependabot's side which I'll get fixed in the next hour.

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/1d06827c14a71c3703ea95219f795522f09ae6dc, which I'm deploying now. Thanks for reporting!

**Comment by cvitan** [comment]
Confirmed that it works now, thank you!
