### ISSUE TITLE
Bug: Dependabot replaces package's name

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#415]
I have a project template that I use for all our frontend projects. I am using dependabot for more that a year now.

And several days ago it started to replace `{{ name }}` variable in my template file with `"something"`: https://github.com/wemake-services/wemake-vue-template/pull/1044/files#diff-27505a311bee9f516daedae1ce932387R2

I am not sure why, and it breaks my CI build. That's should not happen. Dependency updates should not change anything except dependencies.

**Comment by greysteil** [comment]
Huh. I can't see why that wasn't happening before, but it's fixed in [this commit](https://github.com/dependabot/dependabot-core/commit/6aa0307c9ec80cee5d6f38ab4a1f815355cb5943). Will be deployed in the next 10 mins or so.

**Comment by sobolevn** [comment]
@greysteil awesome, thank you! 🎉

**Comment by sobolevn** [comment]
I guess this was not happening before, because I forgot about this unit test until last week 😆

**Comment by greysteil** [comment]
Ha! Yep, I think this might be the only repo that Dependabot is actually doing this sanitization on!
