### ISSUE TITLE
Feature request: label PRs that will be auto-merged

### ISSUE THREAD

**Issue by serhalp** [dependabot/feedback#416]
Every PR opened by Dependabot currently gets a `dependabot` label, and every security PR additionally gets a `security` label.

PRs that will be auto-merged currently have this copy in their description:
> If all status checks pass Dependabot will automatically merge this pull request during working hours.

This is requesting that such PRs also get some kind of label (e.g. `automerge` or `dependabot:automerge`).

The flow I'm trying to solve for is searching for open Dependabot PRs that require human intervention. For example, we have Dependabot enabled in 50+ repos, with an auto-merge schedule of Mon-Thu 10am-5pm, so if I'm looking at `label:dependabot` PRs across my org on Monday at 9am, I'm seeing tons of PRs that I shouldn't be bothering to look at because they will be automerged in an hour. I'd like to simply add e.g. `-label:automerge` to that search.

Thanks! Dependabot is awesome.

**Comment by greysteil** [comment]
Sounds legit to me, and pretty straightforward to implement. Give me an hour or so...

**Comment by greysteil** [comment]
Done! If you have an `automerge` label on the repo then Dependabot will label automerge candidate PRs with that. (It won't create the label if you don't have it, though.) Commit is [here](https://github.com/dependabot/dependabot-core/commit/88e88d3c3f9017868beed4c59f66d7ac27ce4cf2).

Thanks for the feature request!

**Comment by marcelolx** [comment]
@greysteil We have dependabot-preview enabled in three repositories, but only in one he adds label `automerge`, and in another two he didn't it, and we don't know why, is there a condition that need to be satisfied for dependabot-preview add the label? Or some repo config?

PS: We have label `automerge` in all repositories.
