### ISSUE TITLE
App - Config Variables UI truncating repository URLs

### ISSUE THREAD

**Issue by roketworks** [dependabot/feedback#418]
In the Config Variables UI, the repository/feed URLs are truncated. This seems to be an issue across multiple feed types. It makes it difficult to see which feeds are configured. A tooltip here would be nice & a wider span for the display of the url. 

![image](https://user-images.githubusercontent.com/3728054/55394381-1c6d5400-5537-11e9-9ab8-0d67e584d09a.png)

**Comment by feelepxyz** [comment]
@roketworks thanks for letting us know! I've made the url/feed fill the space available so less likely to be truncated (also shown on hover if super long).
