### ISSUE TITLE
How to configure it for open-source organisations?

### ISSUE THREAD

**Issue by ssbarnea** [dependabot/feedback#42]
The Python project I maintain are almost always hosted under organisations on GitHub and so far I was not able to find the option to select them.

The current option is to pick only from repositories under my own account, which is pretty useless as these are usually only forks.

What is the trick that we need to do to configure organizations? 

Update: I  was able to figure it out, is named "add billing account", clearly something confusing, probably a better naming would be "Github Organizaton" instead of "Billing account".

**Comment by greysteil** [comment]
Sorry about that! The interface is controllled by GitHub, but if you go to the drop down in the top right of your account and try to add a new organisation you should be able to see all of the pegs GitHub will give you access to. It *may* be that you need to ask an org owner to add Dependabot - sorry about that if so, I’d change it if I could.

**Comment by greysteil** [comment]
Just saw your update - glad you were able to figure it out, and apologies for the GutHub UI!

**Comment by greysteil** [comment]
Cc @chobberoni - I get feedback like the above a lot!

**Comment by chobberoni** [comment]
@greysteil Thanks for pinging me here. Adding this to our issue internally.

**Comment by greysteil** [comment]
Rad - people miss that dropdown all the time, would be awesome to make the flow their clearer 🙂

Always happy to help if I can!

**Comment by sloria** [comment]
I'm still lost as to how to add an organization. Here's what I've tried:

1. Click "Add account" in the Dependabot UI. This takes me to https://github.com/marketplace/dependabot .
2. Click "Set up new plan".
3. Click "Install it for free"

This takes me to this page.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/2379650/44636477-fae13400-a979-11e8-8b5c-f734bfb93f9d.png">

I don't see a dropdown to change the organization or add a billing account.

@greysteil @chobberoni Can you please provide some guidance?

**Comment by greysteil** [comment]
The easiest was is to bypass the marketplace altogether - if you go to https://github.com/apps/dependabot then things should be a lot clearer from there.

I’m in touch with GitHub about improving this, and have even sent them mockups for a design that could work better. They obviously have a lot of other issues to prioritise this against, and I’m not sure I’ve convinced them exactly how confusing the current flow is yet, but I’m sure tagging @chobberoni here will help, so thanks for that.

On the marketplace route, if you click that billing details section it should be selectable, even though it doesn’t look like a drop down. If this is an account that you’re not an admin of it might not be available there though - the link above is much clearer about what to do in that case.

**Comment by sloria** [comment]
Ah, thanks @greysteil ! https://github.com/apps/dependabot was definitely the way to go. I wonder if it would make sense for the "Add account" link in the Dependabot UI to link to that instead of the Marketplace, at least until the GitHub UI is improved?

**Comment by chobberoni** [comment]
@greysteil @sloria This is now fixed and currently in our deploy pipeline.

Updates be live on the site by 12PM PST. Our apologies for the inconvenience.

**Comment by mscoutermarsh** [comment]
@greysteil @sloria The "Switch billing account" drop down now works on this page. Sorry for the trouble!
