### ISSUE TITLE
Create issues if something is broken

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#42]
Right now I am facing a strange situation. I have configured `dependabot` to update my dependencies here: https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json `package.json` is not at the root dir, so I have set this setting:

<img width="501" alt="2017-11-14 23 42 01" src="https://user-images.githubusercontent.com/4660275/32803698-73d2f04e-c995-11e7-9abd-020cac7ebd5f.png">

And I know for sure, that some of the packages are outdated. 
For example, `eslint-plugin-unicorn`:
- actual: `3.0.0` https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v3.0.0
- current: `2.1.2` https://github.com/wemake-services/wemake-vue-template/blob/master/template/package.json#L122

But, nothing happens. I don't know why and I am really missing a feedback from your service.
Possible solutions:
- create an issue, if something from my side is broken: wrong `package.json` format, etc
- create "status" page inside your service, just like the one [github has](https://status.github.com/messages), so I will know that something is broken on your side

How does it sound?

**Comment by greysteil** [comment]
Ah, this is because an unknown error occurred. We do create issues for other errors, but when it's our bad we just show a notification in https://app.dependabot.com saying an unknown error occurred and we're working on it. I'll take a look into what's going on here now.

**Comment by greysteil** [comment]
FYI, in this case it looks like the `{{ .. }}` format in your `package.json` is what's causing issues for Dependabot. I'm trying to fix, but our normal JS expert is @hmarr and he's on holiday...
