### ISSUE TITLE
npm lockfile: tabs become spaces

### ISSUE THREAD

**Issue by RandomByte** [dependabot/feedback#420]
We have the case that after manually regenerating (that is removing and re-creating) our lockfiles (`npm-shrinkwrap.json` or `package-lock.json`) using npm version `6.9.0` they finally respect the indentation used in our project (tabs). This changed our lockfiles from using spaces to using tabs.

Before, our lockfiles where always generated with space-character indentation. I suspect that this changed in npm, but could not find anything pointing to this in npms changelogs ([current releases](https://npm.community/tags/c/announcements/release), [older releases](https://github.com/npm/npm/releases)).

**The issue:** Apparently, Dependabot PRs now seem to change the indentation of our npm lockfiles back to spaces.

**Examples:**  
`package-lock.json`: https://github.com/SAP/ui5-project/pull/155
`npm-shrinkwrap.json`: https://github.com/SAP/ui5-cli/pull/186

**Comment by feelepxyz** [comment]
@RandomByte thanks for the suggestion! This makes sense and we should definitely do what npm does here. It shouldn't be too hard to support. Will hopefully have it done this week.

**Comment by greysteil** [comment]
@feelepxyz - looks like you shipped this back on 25th April so I'm closing.

@RandomByte - thanks for the feedback!
