### ISSUE TITLE
Python requirements update did not respect constraint

### ISSUE THREAD

**Issue by merwok** [dependabot/feedback#424]
I have `django == 1.11.*` in `deps/runtime.in` which is locked to `django == 1.11.16` in `deps/runtime.txt`.

A security PR updated it to version `2.2`, which is incorrect (does not respect specified range + requires updates to the project).

Config: `accounts/caravancoop/projects/24409` (PR 199 which is the most recently updated)

**Comment by greysteil** [comment]
Thanks for the feedback. I’m just about to make security updates move you to the minimal fixed version 🙂

**Comment by greysteil** [comment]
Security updates are now minimal, which fixes the underlying issue here 🎉

**Comment by merwok** [comment]
This came back!

This PR updated django 2.1 in lock file: https://github.com/caravancoop/rest-framework-auth-toolkit/pull/95

Then another PR tried to update to django 2.2: https://github.com/caravancoop/rest-framework-auth-toolkit/pull/96
I closed that one, reopened the first one, but after the rebase it’s also an update to 2.2

**Comment by greysteil** [comment]
Sorry about that - Dependabot's PRs wont' respect constraints unless you ask Dependbaot to only update the lockfile (when you  can specify in your dashboard on the repo settings or through a config file).

**Comment by merwok** [comment]
I supposed that for this project, only lockfile + not only security updates will give the result I want :slightly_smiling_face: 

For the preview version integrated with github security settings, we only have config file, not dependabot dashboard, do we?

**Comment by greysteil** [comment]
Not even config file yet, I'm afraid - we're working on it!

**Comment by merwok** [comment]
Ah so one shouldn’t have both dependabot app + «security PRs: on» at the same time I suppose!

**Comment by greysteil** [comment]
Yeah - if you've got Dependabot Preview on then that should be all you need! :-)
