### ISSUE TITLE
Dependabot fails to notice that a dependency was independently updated to the same value

### ISSUE THREAD

**Issue by jglick** [dependabot/feedback#426]
Not sure if this is considered a bug or not, but consider the situation in https://github.com/jenkinsci/pipeline-cloudwatch-logs-plugin/pull/52#issuecomment-479886277 where Dependabot created (and then updated) a dependencies PR, while I manually created and then merged a more complex PR that included that dependency update as a part of other changes. Surprisingly to me, after merging the manual PR, Dependabot did not seem to notice that anything had changed—perhaps because GitHub does not consider this a merge conflict, in that `git merge` would succeed (even while making no actual tree changes). I needed to manually tell Dependabot to rebase in order to have it notice the actual situation. Other than #230, could this be automatic?

**Comment by feelepxyz** [comment]
@jglick you're right on our rebasing, we try to not do any rebases unnecessarily so wouldn't have triggered one in your case when there are no conflicts. However, Dependabot should figure out that the update isn't necessary once it's done another update check, it's just not immediate 🤖(depends on your schedule)

**Comment by greysteil** [comment]
Just to clarify what Phil said, Dependabot *should* be automatically rebasing if a change is made to a dependency file by someone else. I'm not entirely sure why that didn't happen here - it may be that Dependabot somehow missed a webhook, but if it recurs I want to look into it. Please let us know if you see that!
