### ISSUE TITLE
Our organization is interested in subscribing an Unlimited Plan

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#43]
Our [organization](https://github.com/DSI-Ville-Noumea) , Nouméa TownHall is interested un subscribing to an unlimited account.
You will be contacted i nthe next days by people from AgileSoft , probably [Thomas Lemaire](https://github.com/ThomasLemaire) or  or [Pascal Leléannec](https://github.com/leleannec)  as it is diffcult for us to pay by credit card as a public organisation.
So, at the end, they will pay for us, but the service will only be used on our GH repos.

Thank you in advance for your help.

Best Regards.

Adrien

**Comment by greysteil** [comment]
Hi Adrien,

That's great news - please ask them to contact me on support@dependabot.com and I'm sure we'll be able to figure something out.

Best,

Grey

**Comment by adriens** [comment]
Great, thanks for answer !

**Comment by adriens** [comment]
I've just dropped you an :email:
