### ISSUE TITLE
Add opportunity to reconfigure a language

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#43]
While creating #42 I had to edit a configuration for a language inside a project.
I could not do that for some reason. Do you consider adding this feature?

Thanks!

**Comment by greysteil** [comment]
The UI for the Dependabot dashboard is probably overdue a more comprehensive refresh, but right now the best way to handle this is to delete and then re-create an update config. There's no reason the new UI shouldn't support editing, so I'll keep this in mind when we put it together :octocat:.
