### ISSUE TITLE
Dependabot not monitoring .NET projects in second solution

### ISSUE THREAD

**Issue by hisuwh** [dependabot/feedback#431]
I have two solutions in repository and dependabot does not seem to be bumping versions for projects in the second solution and there does not seem to be any way for me to configure this.

**Comment by feelepxyz** [comment]
@hisuwh 👋could you send over the repo name and I'll take a look at it? If it's private please email to support@dependabot.com

**Comment by hisuwh** [comment]
@feelepxyz done

**Comment by feelepxyz** [comment]
@hisuwh thanks will take this through email
