### ISSUE TITLE
Duplicate PRs created for "Bump Mediatr from 3.0.1 to 6.0.0

### ISSUE THREAD

**Issue by hisuwh** [dependabot/feedback#432]
Dependabot has created a PR for Mediatr 6.0.0 as well as for a number of internal packages of ours that depend on Mediatr.

We have merged the latter into the Mediatr branch as neither will build without the other.  This PR is still open as their are a number of changes that still need to be made to get this to build.

We have now received another PR for Mediatr

**Comment by feelepxyz** [comment]
@hisuwh what repo is this happening on?

**Comment by hisuwh** [comment]
@feelepxyz sent you an email regarding this and #431

**Comment by hisuwh** [comment]
Looking again at this one looks like one of them is `Mediatr` and the other is `MediatR` in the .csproj
.NET package names aren't case sensitive but looks like Dependabot is treating them as if they are and raising PRs for different spellings separately (I did see this before)

**Comment by feelepxyz** [comment]
@hisuwh oh yeah looks like that will trip up the updater. Thanks for spotting it!

**Comment by greysteil** [comment]
Thanks for this @hisuwh and @feelepxyz. Should be fixed by https://github.com/dependabot/dependabot-core/commit/68ea682feeb0ea9db5e620caa0268ccc33c8eee6, which is deploying now. :octocat:

**Comment by hisuwh** [comment]
Awesome thanks guys
