### ISSUE TITLE
Dependabot couldn't find a build.gradle for this project

### ISSUE THREAD

**Issue by e4basil** [dependabot/feedback#434]
Dependabot couldn't find a **`build.gradle`** when i upgrade to **`build.gradle.kts`**

Issue [link ](https://github.com/e4basil/PercentageProgressBar/issues/30)

**Comment by feelepxyz** [comment]
@e4basil hey sorry about this, we currently don't support Kotlin build files. There's an open issue for this: https://github.com/dependabot/feedback/issues/172
