### ISSUE TITLE
Question about Python requirements.txt

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#435]
I currently have a python setup in my repository that I have enabled dependabot on. I use both `Pipfile` and a `requirements.txt` file due to different requirements on development machines vs. build machines.

My question is, will dependabot update both files at the same time when a new version of a dependency is out? I did receive a PR updating the version of a package in the `Pipfile`, but there was no corresponding update to the requirements.txt. I manually updated the file in the PR as you can see: https://github.com/RohanNagar/thunder/pull/428

Is the reason dependabot didn't update the requirements file because it is named `readthedocs-requirements.txt` and not `requirements.txt`? If that is the case, would it be possible to expand the allowed names of the requirements files, or should I rename my file to `requirements.txt`?

Thanks for the help

**Comment by greysteil** [comment]
This is a bit of a tricky one. Dependabot will try to do both, but it's not perfect at it yet. If you generate your requirements file with `pipenv lock -r` or `pipenv lock -r -d` then Dependabot should realise that it needs to update those, too. If you don't and are using Pipenv then it will skip them. We could definitely do better there.

**Comment by RohanNagar** [comment]
Ah I see. I'll try generating the requirements file with `piping lock`, thanks!
