### ISSUE TITLE
Funky update removes django

### ISSUE THREAD

**Issue by merwok** [dependabot/feedback#436]
Hello!  tl;dr: upgrading a django extension removed way too many things from requirements file

In one project based on django-cms, I have removed `django` from `requirements.in` to let django-cms control the accepted django version (and hopefully let us update from django 1.11 this year).

Extracts from requirement files before the problem:

```
# deps/runtime.in
...
django-cms == 3.5.*
django-nested-admin == 3.0.*
...
```

```
# deps/runtime.txt
...
django-cms==3.5.3
django-nested-admin==3.0.21
django==1.11.20           # via ..., django-cms, ... (not django-nested-admin)
...
```

dependabot opened a PR: `Bumps django-nested-admin from 3.0.21 to 3.2.1.`

deps/runtime.in:

```diff
-django-nested-admin == 3.0.*
+django-nested-admin ==3.2.*
```

deps/runtime.txt:

Removed dependencies of some top-level dependencies: django-cms, requests, fulltext!

**Comment by greysteil** [comment]
Ack, sorry about this! Can you tag `@dependabot` in the offending PR? That way I can find it in our system and see what's happened.

**Comment by merwok** [comment]
It’s a private repo, I suppose I should give you the dependabot project ID and time of the PR?

**Comment by merwok** [comment]
django-nested-admin released a new version; the PR was closed in favour of a new one, which does not show the problem I reported!
