### ISSUE TITLE
Issue with determination of top-level dependencies or security patch for Python requirements

### ISSUE THREAD

**Issue by merwok** [dependabot/feedback#437]
Hello!  I get many PRs for dependencies of dependencies that I would prefer not to care about.

Example: https://app.dependabot.com/accounts/caravancoop/projects/20105

- [ ] Only security updates
- [ ] Only lockfile updates (ignore updates that require Pipfile changes)
- [x] Only top-level dependencies (and security patches for subdependencies)

First option: I am interested in all updates of my direct dependencies.
Second option: the text lets me think this is only for Pipenv, not requirement.in/.txt files managed with pip-tools, so I can’t check that (or I would!)
Third option: good, I care about pytest but not attrs!

But: I get PRs for attrs https://github.com/caravancoop/xpuni-be/pull/79/files

Maybe I was misled by «security patches»: I thought it meant «updates with the security label, that fix security issues», but maybe it means «bump in the last component of the version number»?

**Comment by greysteil** [comment]
Thanks for creating this, and apologies for the delay getting back to you.

I'm a little confused - can you describe the setup that you want here?

(For Python, Dependabot will treat `requirement.txt` files that are generated by `pip-tools` as lockfiles for a `requirement.in` manifest file.)

**Comment by merwok** [comment]
Thanks for the info about non-pipfile lockfiles, I will use that option to ensure big dependencies (django 1.11 → 2.0) are always handled manually!

Ideal setup: only update lock file; upgrade direct dependencies; security upgrades for sub-dependencies.

The PR I linked is a non-security update to a sub-dependency.

**Comment by greysteil** [comment]
Ah, OK, I've just taken a look at what's happening here. It looks like you're specifying custom names for the files that pip-compile compiles too (for example, from just looking at the files it's not clear how `runtime.txt` is put together).

Dependabot's detection of how pip-compile files are linked is based on their filenames. It can match a `<name>.in` file to a `<name>.txt` file, but if you use custom names it won't know how to connect the two, and falls back to doing to treating the `.txt` files as if they weren't associated with pip-compile.

**Comment by greysteil** [comment]
I'm closing because I don't *think* Dependabot can easily handle this `pip-compile` case. `pip-compile` is a very flexible tool, and whilst we try to support as many setups as possible, looking at your files I can't imagine any way that Dependabot could figure out how to build your `runtime.txt` without downloading arbitrary binary files, which it can't do.

If you can switch to a setup where you have a `runtime.in`, perhaps that just requires in some of your other `.txt` or `.in` files, Dependabot should be able to handle that.

**Comment by merwok** [comment]
But that is the setup!  In a `deps` sub-directory, I have `runtime.in`, `tests.in` and `ci.in` that are pip-compiled to their matching `.txt` versions.

**Comment by greysteil** [comment]
It looks like you also have `develop.txt` and another file (can't remember the name), though?

**Comment by merwok** [comment]
`devel.txt` is the only file without a `.in` counterpart (it contains httpie, pdbpp, etc. without version constraints)
