### ISSUE TITLE
Add a feature to star the repo

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#44]
Some similar services also has a little feature (that I really enjoy) to star the repo which they are working with.

It is totally not required (but nice).

**Comment by greysteil** [comment]
Thanks for the suggestion! I've added a link to our GitHub to the footer of the webpage, and pinned the relevant repos, which is a start at least! 😄

**Comment by sobolevn** [comment]
Oh, I meant user's repo. But you also deserve a star!

**Comment by greysteil** [comment]
Haha, ah, interesting, I though you meant one of those "this thing has <X> stars on GitHub" badges. Starring user repos is a really nice idea - I'll have a look into whether it's even possible with bots (we use an app-user, not an OAuth user).

**Comment by greysteil** [comment]
Sadly not enabled for apps yet ([docs here](https://developer.github.com/v3/activity/starring/#star-a-repository)). I'll ping GitHub with the use case you suggested to see if they're up for enabling it :)
