### ISSUE TITLE
Publish PGP Key

### ISSUE THREAD

**Issue by l0s** [dependabot/feedback#44]
I'm glad to see that Dependabot is [signing commits](https://dependabot.com/blog/signed-commits). When browsing commits through GitHub, I see that the signatures are verified. However, when browsing commits from the command line using `git log --show-signature`, I see the following message:

    commit bf52ced07e44c9cda73e3bfc0f8b7c83d3dbff51
    gpg: Signature made Sun Apr 15 14:43:12 2018 PDT
    gpg:                using RSA key 4C0F2888C98CF331
    gpg: requesting key 4C0F2888C98CF331 from hkps server hkps.pool.sks-keyservers.n
    et
    gpg: Can't check signature: No public key
    Author: dependabot[bot] <support@dependabot.com>
    Date:   Sun Apr 15 21:43:11 2018 +0000

        Bump org.apache.maven.plugins:maven-surefire-plugin from 2.20.1 to 2.21.0
        
        Bumps org.apache.maven.plugins:maven-surefire-plugin from 2.20.1 to 2.21.0.
        
        Signed-off-by: dependabot[bot] <support@dependabot.com>

Will you please publish the public key either on the dependabot.com website or on the SKS Keyserver pool?

**Comment by greysteil** [comment]
Thanks for the heads up! I've pushed the public key and verified that `git log --show-signature` now shows good signatures.

**Comment by l0s** [comment]
Thanks!
