### ISSUE TITLE
Bug: Live Update broken

### ISSUE THREAD

**Issue by simlu** [dependabot/feedback#440]
**Setup:**

Using a configuration file with live updates <details> <summary>`/.dependabot/config.yml`</summary>

```json
version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"

    target_branch: dev

    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "all"

    version_requirement_updates: increase_versions
```

</details>

**Problem:**

Everything worked fine until I clicked "Bump now" in the dependabot GUI. Live updates now no longer appear to be working.

Please let me know if you need further details!

**Comment by greysteil** [comment]
Clicking "Bump now" shouldn't make any difference to your standard setup at all. What's the reason you think live updates aren't working? I can dig into the repo if needed.

**Comment by simlu** [comment]
Here is one repo where it doesn't work: https://github.com/blackflux/object-scan
But I have the same configuration under all blackflux organization repos.

Something definitely changed. Most of the repos are interdependent. So when I release a new version dependabot used to almost instantly create PRs. I have waited several hours, but this now no longer happens and I need to click the bump now button (which I have done, so there are currently no updates pending I think).

Would be great if you could look into it! I can add create easily create outdated dependencies if needed.

Cheers and Happy Easter, L~

**Comment by greysteil** [comment]
Hmmm, this looks related to npm's issues on Friday / Saturday - https://status.npmjs.org/#week.

Dependabot has a follower that uses `replicate.npmjs.com` to listen for new pushes. It looks like we're just seeing error responses from npm from that now - I'll see if there's anything we can do on our side.

**Comment by simlu** [comment]
Possibly related to this [black magic](https://github.com/dependabot/feedback/issues/255#issuecomment-436574414)? A magically changing setting? Sorry, but what a terrible decision...

**Comment by simlu** [comment]
For now I just added a "Bump all" button. Not great but at least workable :)

![bumpAll](https://user-images.githubusercontent.com/1539747/56477996-4a6ff500-6460-11e9-94f3-ed82fcf1b492.png)

**Comment by greysteil** [comment]
> Possibly related to this black magic? A magically changing setting? Sorry, but what a terrible decision...

@simlu if you would like my help please behave respectfully. Unconstructive comments like this are unhelpful and demotivating.

**Comment by simlu** [comment]
> @simlu if you would like my help please behave respectfully. Unconstructive comments like this are unhelpful and demotivating.

I'm Sorry. This was not meant to be disrespectful or demotivating. I was a bit frustrated and I'm sorry that showed 😕 Thanks for calling me out. Let's discuss a constructive solution to that problem in the other issue I opened

**Comment by simlu** [comment]
> Dependabot has a follower that uses replicate.npmjs.com to listen for new pushes. It looks like we're just seeing error responses from npm from that now - I'll see if there's anything we can do on our side.

Do you have a link to the API documentation that you're using?

**Comment by greysteil** [comment]
Yep - basically following the setup described [here](https://github.com/npm/registry-follower-tutorial).

It *seams* like npm have resolved the issues in the last few hours, so I'm going to tentatively close this. There have been no changes on our sides to our follower setup in the last 10 months, so I'm pretty confident the break wasn't on our side, but if you continue to see Dependabot missing live updated for JS please comment here.

**Comment by simlu** [comment]
Thanks for posting the link! I wasn't aware that was a thing. Great to know

So far live updates seem to be working again
