### ISSUE TITLE
Gradle JitPack integration

### ISSUE THREAD

**Issue by RDIL** [dependabot/feedback#441]
Please make it so that dependabot can update modules in build.gradle when published on https://jitpack.io !  Thanks :D

**Comment by greysteil** [comment]
This should work automatically if you've got jitpack listed in your repositories. Is there a repo you can point me to where you don't think it's picking it up?

**Comment by RDIL** [comment]
https://github.com/hyperiumjailbreak/client - I've had to manually bump `com.github.hyperiumjailbreak.Installer:COMMIT_ID`.

**Comment by greysteil** [comment]
Slightly confused, as I don't think I changed anything here, but https://github.com/hyperiumjailbreak/client/pull/44 suggests this is now fixed...
