### ISSUE TITLE
Bug: Auto switch from "build" to "chore" commit message

### ISSUE THREAD

**Issue by simlu** [dependabot/feedback#442]
For some arbitrary reason dependabot changed the commit syntax by itself. See here https://github.com/blackflux/lambda-serverless-api/commits/master?before=335f2365005b9c099e033eda92085b7dfbf816a0+140

According to this [comment](https://github.com/dependabot/feedback/issues/255#issuecomment-436574414) it should stick to one type?

I've originally reported this issue [here](https://github.com/dependabot/feedback/issues/440#issuecomment-485285885), but it's a separate issue.

**Comment by simlu** [comment]
Also what is up with this commit message?!

https://github.com/blackflux/object-scan/pull/292/commits

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/1f1923f81964fb47c4e3d2c35df39eb70138794c. Issue here is that you have 30 commits in a row that didn't match any commit setup known to Dependabot (since `amend` isn't an Angular prefix). I've adjust the logic to prefix you with `build` in that case.

**Comment by simlu** [comment]
@greysteil Great and thank you. Does that also change/fix the "bump" style commit messages (the 6th pr in the screenshot)?

**Comment by simlu** [comment]
Also would you mind explaining how the commit message style is determined? Does it just look at all past commits? From the comment I linked it sounded like you had to force push to a dependabot branch with a different commit message?

**Comment by greysteil** [comment]
For sure - on my phone as am out for the next few hours (it’s a bank holiday here in the U.K.) but will get back properly when I’m back 🙂

**Comment by simlu** [comment]
@greysteil No worries and enjoy your holiday! I might open a separate issue later to discuss possible improvements since this is a resolved bug report now.

**Comment by simlu** [comment]
So how can we differentiate between dep and dev deps? It seems its just set to bump now?

**Comment by greysteil** [comment]
Want to put in a PR to add the scope if it's being used?

**Comment by simlu** [comment]
Sure

**Comment by simlu** [comment]
Done [here](https://github.com/dependabot/dependabot-core/pull/1121).

**Comment by simlu** [comment]
On second thought no. I don't have ruby or an IDE set up for it :)

Makes it very time intensive to debug
