### ISSUE TITLE
Bi-weekly schedule

### ISSUE THREAD

**Issue by thedotedge** [dependabot/feedback#444]
Hi!
Would it be possible to add bi-weekly as bumping schedule?
![image](https://user-images.githubusercontent.com/227241/56571568-82407f00-65bd-11e9-828c-65e4e29a6a2d.png)

**Comment by greysteil** [comment]
Definitely possible, but I'd rather not expand the list unless there's a compelling reason. (Let me know if so and I'll re-open!)
