### ISSUE TITLE
Dependabot creates security pull requests, which do not fix the security problem

### ISSUE THREAD

**Issue by jonasbb** [dependabot/feedback#449]
I created a dummy repo to show the problem at [dependabot-test](https://github.com/jonasbb/dependabot-test/pulls).

Github warns about three vulnerabilities in SQLAlchemy, Jinja2, and pyyaml. Dependabot creates pull requests for only two, Jinja2 and pyyaml.
Neither of those two pull requests fixes any of the vulnerable versions, they do not even update the mentioned dependencies. They only happen to update unrelated dependencies with loose enough constraints, that an update is possible.

All vulnerable versions come from a single dependency, which uses "==" constraints in its [requirements.txt](https://github.com/thanethomson/statik/blob/56b1b5a2cb05a97afa81f428bfcefc833e935b8d/requirements.txt). Thus, it shouldn't be possible for dependabot to even update vulnerable dependencies while fulfilling the constraints.

So to summarize: Dependabot should not create a security pull request, if the pull request does not even update the vulnerable dependency.

**Comment by greysteil** [comment]
Thanks! I'm working on a fix for this right now - it's similar to the issue [here](https://github.com/dependabot/dependabot-core/pull/1123).

Should have this fixed in the next hour.

**Comment by greysteil** [comment]
Fixed, and Dependabot auto-closed those PRs when I asked it to rebase them.

Thanks again for flagging this, and for the reproduction case.

**Comment by jonasbb** [comment]
Thanks for the quick help. Great support 😊
