### ISSUE TITLE
Bad commit message generated

### ISSUE THREAD

**Issue by simlu** [dependabot/feedback#454]
Looking at [this pr](https://github.com/blackflux/set-compressor/pull/127/commits) with the commit `Bump @blackflux/eslint-plugin-rules from 1.0.10 to 1.0.11`

The [commits history](https://github.com/blackflux/set-compressor/commits/dev) of the target branch (and all branches) includes a commit `fix: updated deps` a few commits back.

Hence I would expect an Angular style commit message. What went wrong here?

Another reason why I'd really like https://github.com/dependabot/feedback/issues/443 to be implemented. It's not very convenient to find out that releases that should have gone our didn't. Especially when they're security related...

Looking forward to getting this resolved. Please let me know if you need any more details!

**Comment by greysteil** [comment]
Looks like the previous Dependabot commit used the "Bump ..." style, though. As a result, Dependabot picked that up and used it, so as to stay consistent with previous Dependabot commits. If you use the "squash and merge" option to change the commit format next time you merge a Dependabot PR, it will pick up the change.

**Comment by simlu** [comment]
That makes sense. However the prs are automatically merged, so it's very hard for me to intercept. I might have to change the automatic merging script to only automatically merge if it matches the appropriate syntax.... Arg...

**Comment by greysteil** [comment]
Can you not use commitizen or something like that to fail the build if the syntax doesn't match?

**Comment by simlu** [comment]
Yeah, that might be the easiest. We use [gally](https://www.npmjs.com/package/gally), and it doesn't have the functionality atm but might be easy to add. Not feeling like using another tool just for this... I'll think about it :)

**Comment by simlu** [comment]
Sorry to chime in here again... what is going on with this commit message?
https://github.com/blackflux/object-scan/pull/353/commits

I thought deps or dev-deps would always be indicated?

**Comment by greysteil** [comment]
It looks like your last Dependabot commit now matches the `conventional_prefix` style ([logic here](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/message_builder.rb#L233-L241)), so Dependabot is correctly trying to stay consistent with its pervious commits by continuing to use that.

**Comment by simlu** [comment]
@greysteil Man.. that branching is certainly not trivial to understand... :)
