### ISSUE TITLE
Unclear Bundler::VersionConflict 

### ISSUE THREAD

**Issue by Bertg** [dependabot/feedback#456]
Hi,

I got the below error message in the Dependabot overview.

```
Dependabot can't resolve your Ruby dependency files.

As a result, Dependabot couldn't update your dependencies.

The error Dependabot encountered was:

Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "ipaddr":
  In Gemfile:
    openssl (~> 2.1.2) was resolved to 2.1.2, which depends on
      ipaddr

Could not find gem 'ipaddr', which is required by gem 'openssl (~> 2.1.2)', in any of the sources.
If you think the above is an error on Dependabot's side please don't hesitate to get in touch - we'll do whatever we can to fix it.
```

This does not make a lot of sense to me. 

* There is one source: ```https://rubygems.org```
* ```openssl``` and ```ipaddr``` have been part of the Gemfile.lock for some time; and have not caused issues in the past
* Locally trying to bundle the Gemfile has no issues

Maybe provide some more feedback in the error as well? Which gem was Dependabot trying to update, and to which version?

Also, it would be nice to get some type of message from Dependabot that this has happened. And more importantly that it does not seem to be retrying.

**Comment by greysteil** [comment]
Thanks for the report @Bertg. Can you let me know the URL of the repo this is happening on (you can email support@dependabot.com if private).

On notifications - Dependabot will create an issue on your repo if you have issues enabled, but otherwise we don't have a way to get in touch with you (we don't have email addresses etc.!)

**Comment by greysteil** [comment]
Thanks for the details. This looks really weird to me. The dependency that Dependabot is trying to update and getting that error is Nokogiri - what do you get running `bundler update nokogiri` locally?

**Comment by Bertg** [comment]
@greysteil Based on our latest develop commit, executing ```bundler update nokogiri``` is successful and bumpy the gem ```Using nokogiri 1.10.3 (was 1.10.2)```

**Comment by greysteil** [comment]
FYI, this has something to do with Ruby's [standard gems](https://stdgems.org/) changing between the Ruby version you're using and the version that Dependabot is using. I haven't figured it out yet, but I will...

**Comment by greysteil** [comment]
More progress - I have a failing test case [here](https://github.com/dependabot/dependabot-core/pull/1144).

**Comment by greysteil** [comment]
Cracked it. Will get https://github.com/dependabot/dependabot-core/pull/1144 deployed in the next hour.

**Comment by Bertg** [comment]
Great job! Thanks! 
Everything is wording fine and dandy again.
