### ISSUE TITLE
My application requires version bump on pull requests

### ISSUE THREAD

**Issue by marcotc** [dependabot/feedback#457]
👋 Dependabot team,

My gem requires a version bump, my case a Ruby project that requires all PRs to bump up our `VERSION` constant in our `lib/*/version.rb` file.

All dependabot PRs currently fail to pass our linting step because of this.

Has this issue come up before? Is there a recommended way to handle this situation?

**Comment by cabello** [comment]
We also require a CHANGELOG entry, so I wonder if there is any extension hooks when Dependabot is about to propose a file change. We are able to perform these changes using Thor generators.

**Comment by greysteil** [comment]
Hmmm, sounds like you're going to need something in addition to Dependabot to help out there - Dependabot doesn't know how to do it, and it's quite specific to your setup.

Have you looked at creating an action for this? That would be my recommendation.

**Comment by cabello** [comment]
We don't have access to Github Actions 😭

**Comment by greysteil** [comment]
😢 I don't know what more to suggest.

You can at least piggy-back off of some of the logic Dependabot has written if you write a bot to do this, though - [this class](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_updater/github.rb) has all the logic we use to push to an existing Dependabot branch (we force push over it so you'll want to edit that bit). Creating commits that update multiple files is a bit of a faff through the API, so hopefully that helps a bit.

**Comment by cabello** [comment]
Thanks @greysteil for the pointers, yes we were discussing the possibility of spinning our own bot, it's likely what we are going to do, Github Actions seems far away from us at the moment.
