### ISSUE TITLE
Don't bump to versions that are already allowed by the version range

### ISSUE THREAD

**Issue by kornelski** [dependabot/feedback#458]
I would like to use dependabot to remind me and test semver-incompatible versions, but don't bother updating within semver-compatible range, because the package manager updates these automatically anyway.

If I specify a dependency version using a range such as `^1.0.0`, currently dependabot will make a PR when version `1.1.0` is released. However, that seems unnecessary to me, because the version range already allows `1.1.0` and later `1.x` versions. I'd prefer to get a PR only when `2.x.x` or later is released, because that's the only case when I *have to* update the version.

Currently there's a setting to automatically merge PRs with patch/minor/in-range bumps, but there's no option to do the opposite — ignore patch/minor bumps, and make PRs only for major ones.

**Comment by greysteil** [comment]
Thanks for the issue. You'll get that behaviour if you don't commit a lock file for your project - is that an options? If not, what's the reason you're committing your lockfile if you don't want to specify the patch / minor release?

**Comment by kornelski** [comment]
Oh, I forgot about the lockfile. In that case it's all A-OK!
