### ISSUE TITLE
Pipfile.lock getting clobbered with path based dependencies

### ISSUE THREAD

**Issue by greenape** [dependabot/feedback#460]
We have a a couple of Pipfiles which have another path in the same repo as an editable dependency, e.g. `project_b = {editable = true,path = "./../project_b"}` in project a's Pipfile.

When dependabot updates the lock file for project _a_, the lock files lose all the previously locked deps from project b (e.g. https://github.com/Flowminder/FlowKit/commit/7ff5d33bae3cbc65354ef18e64283d88beb4837e), necessitating a manual relock of the Pipfile.

Anything we can do to stop that happening?

**Comment by greysteil** [comment]
Oooh, that looks like a bug to me. Let me dig into it.

**Comment by greysteil** [comment]
Ack, actually, on second thoughts, I think what's needed here is [this feature](https://github.com/pypa/pipenv/pull/3304) in Pipenv, which *should* be released soon. 🤞

**Comment by greenape** [comment]
I did wonder if that might be the issue actually. Pipenv’s release cycle could do with being _bit_ more frequent 🙄

**Comment by greenape** [comment]
Any chance this is going to be resolved now there's a new Pipenv release?
