### ISSUE TITLE
Don't show archived repos in repo add screen

### ISSUE THREAD

**Issue by captn3m0** [dependabot/feedback#466]
Archived repos on GitHub are marked as read-only. Commits pushed from Dependabot would fail regardless of the repository being enabled.

It is much better to hide these repos entirely on the Add Screen.

**Comment by greysteil** [comment]
These should already be being filtered out. Is there a particular repo that's showing up that shouldn't be?

**Comment by captn3m0** [comment]
My bad. I thought I'd archived a certain repo, when I hadn't.

Thanks!

**Comment by greysteil** [comment]
Haha, no worries, I did find a small related bug when I investigated, which was that archived repos with a config file would still be shown. Fixed that but figured it was unlikely to be what caused the above! 🙂
