### ISSUE TITLE
`@dependabot rebase all` command

### ISSUE THREAD

**Issue by mockdeep** [dependabot/feedback#469]
I have a bunch of dependabot PRs open right now that all failed the build due to an issue in the CI setup. It would be nice to be able to trigger all of the PRs to rebase, rather than needing to go through them all one by one.

Another thought is that maybe it would be good to have a setting for only failing PRs to automatically rebase when there is an update to the target branch.

**Comment by greysteil** [comment]
Thanks for the suggestion. I think this would have to belong in the dashboard, and I don't think we'd want to give it the prominence it would have if we added it there. We try to keep Dependabot super simple, and I think this is going to have to be a casualty of that.

Thanks for the suggestion all the same - really appreciate it.
