### ISSUE TITLE
Elasticsearch docker image needs authentication

### ISSUE THREAD

**Issue by jvdlaar** [dependabot/feedback#47]
I have a docker image that contains:
```
FROM docker.elastic.co/elasticsearch/elasticsearch:6.2.4
```
Which is the official elasticsearch docker image. But dependabot says:

> Dependabot couldn't authenticate with docker.elastic.co.

But as far as I know the elasticsearch docker image is open for everyone without authentication. What to do?

**Comment by greysteil** [comment]
Hmmm, this could be due to a transitory timeout issue on the part of the registry. Let me dig into it and get back to you.

**Comment by greysteil** [comment]
This is definitely a bug on our side. I’ll fix it today

**Comment by greysteil** [comment]
Fixed. Thanks so much for the bug report, and sorry you ran into this. (You're already on the latest version of that container, so Dependabot didn't bump your version, but it will if/when a new one is released.)

**Comment by greysteil** [comment]
(And just FYI, the fix was [this commit](https://github.com/dependabot/dependabot-core/commit/9d8bf59c1d1073f1a70f5b2076c23625145dd53a).)

**Comment by jvdlaar** [comment]
Thanks this seems to solve the error in our situation :+1:
