### ISSUE TITLE
Support Yarn Workspaces

### ISSUE THREAD

**Issue by bennyn** [dependabot/feedback#47]
I wanted to install Dependabot for a JavaScript project but it doesn't work because it requires a `package.json` and a `package-lock.json`. My repository is using Yarn, so it only has a `package.json` and a `yarn.lock` file (similar to `package-lock.json`). 

Can you please make Dependabot work with Yarn lockfiles?

**Comment by greysteil** [comment]
Hi @bennyn, did you try selecting the yarn option in the language drop down? Dependabot does support Yarn - apologies for any confusion!

**Comment by bennyn** [comment]
Uh, damn! I didn't see that there is another "JavaScript" in the dropdown. 🙈 It works now. Thanks for the hint! And a **BIG PLUS** for your fast response time!

**Comment by bennyn** [comment]
P.S. I enabled it now with Yarn but I am seeing an unknown error:

![Screenshot](https://user-images.githubusercontent.com/469989/32832810-17b440e8-c9fd-11e7-8b13-22f90bbf6564.PNG)

**Comment by greysteil** [comment]
Hmmm, that means I'll have an exception report on my side - I'll take a look into it now.

**Comment by greysteil** [comment]
Ack, that error is because you're using `yarn workspaces`, which I didn't even know were a thing. I'll  look into a fix over the next few days, but it's not trivial 😞 .

**Comment by bennyn** [comment]
@greysteil Ok! So I will reopen this issue and rename it. Thanks for taking a look into it! 

There is a great introduction on Yarn workspaces here:
- https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/

The Yarn Workspaces feature has been published with Yarn 1.0:
- https://code.facebook.com/posts/274518539716230

**Comment by greysteil** [comment]
Yarn workspaces are now working! 🎉
