### ISSUE TITLE
gcr.io authentication

### ISSUE THREAD

**Issue by hazcod** [dependabot/feedback#470]
I am currently using the Container Registry on google cloud.
This allows me to create service accounts for access to this registry, but it is only possible to authenticate using either:
- a P12 file
- a JSON file

So no password authentication. Any ideas?

**Comment by greysteil** [comment]
I *think* the instructions [here](https://github.com/dependabot/feedback/issues/279#issuecomment-443182680) should get this working. Let me know if they don't, though...

**Comment by hazcod** [comment]
This works, thank you @greysteil !
Can this be added into some kind of README/note?

**Comment by greysteil** [comment]
Yeah! @feelepxyz can you add something to the frontend?

**Comment by feelepxyz** [comment]
Yes adding a help note when adding docker registries on the dashboard!
