### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by cabello** [dependabot/feedback#475]
https://dependabot.com/blog/hello-github/

You all have done amazing work so far, excited for what's coming next! 🎉

**Comment by greysteil** [comment]
This is so kind, thanks @cabello.

We couldn't be more excited about what's coming next. There's so much good we can do with Dependabot at GitHub - it's going to be amazing.

We're also deeply indebted to everyone who has given us feedback, reported bugs, or made contributions to this repo. Thanks you. Without you, Dependabot would be rubbish(!).

**Comment by ryan-ccn** [comment]
This app is absolutely wonderful :+1: :+1: :+1:

**Comment by feelepxyz** [comment]
🎉
