### ISSUE TITLE
Feature Suggestion: multiple tags per PR

### ISSUE THREAD

**Issue by RoryO** [dependabot/feedback#48]
When a project has multiple languages in one repo you cannot tell from the PR list what language the dependency belongs to. For instance, in a Rails or Django app there are both Ruby/Python and NPM  dependencies. Adding a tag with the language helps quickly sorting and routing to the right people.

**Comment by greysteil** [comment]
There's an option to set this up manually (just comment `@dependabot uses these labels` on a Ruby PR with the right labels, and then the same on a Python one using different labels), but I quite like the idea of doing it by default - I'll have a look at getting that setup 🙂.

**Comment by greysteil** [comment]
(And thanks for the feedback!)

**Comment by greysteil** [comment]
Just implemented this in https://github.com/dependabot/dependabot-core/commit/c540f5ca58b932e3b393c596c227a548ac0d5349. Will take effect on Monday.

Thanks again for the feedback!
