### ISSUE TITLE
Remove branches after merge

### ISSUE THREAD

**Issue by Floppy** [dependabot/feedback#48]
Dependabot gets my update process down to two clicks. This is obviously incredible. BUT it could be one click if Dependabot had an option to automatically remove its branch after it was merged in. Not everyone would want this (maybe?), so it should be an option rather than always-on behaviour, but it could probably be on by default.

**Comment by greysteil** [comment]
We actually already do this, it's just that we wait 10 seconds before deleting the branch (so as not to cause annoying UI conflicts on GitHub. 🎉 

No-one's complained yet...

**Comment by Floppy** [comment]
Oh! I can stop clicking the button then! I never even realised :D
