### ISSUE TITLE
Auto closing of pull requests not merged

### ISSUE THREAD

**Issue by dkocher** [dependabot/feedback#481]
I am giving dependabot a try but the bot seems to close pull requests opened before I had a chance to review them. 

See https://github.com/iterate-ch/cyberduck/pulls?q=is%3Apr+is%3Aclosed

Also this happens as my own users instead of the bot user. See for example https://github.com/iterate-ch/cyberduck/pull/37

**Comment by greysteil** [comment]
Do you have any other automation set up on that repo? Dependabot doesn't have access to your user account, so can't close PRs in your name - perhaps there's something else at work here, that isn't Dependabot?
