### ISSUE TITLE
incorrect link "view pull requests" in settings

### ISSUE THREAD

**Issue by ashkulz** [dependabot/feedback#484]
The link "view pull requests" in the settings page (as shown below) is incorrect.

![Screenshot at 2019-05-27 18-19-16](https://user-images.githubusercontent.com/854352/58420841-fe8e1c80-80ab-11e9-94d8-577dfc7efbdd.png)

It should go to `REPO/pulls/app%2Fdependabot-preview` instead of `REPO/pulls/app%2Fdependabot`.

I do understand this is because of the recent change, just thought to let you know :smile:

**Comment by greysteil** [comment]
Ooh, thanks for the heads up. @feelepxyz can you take a look?

**Comment by feelepxyz** [comment]
Deploying a fix now! Thanks for reporting @ashkulz 🙌
