### ISSUE TITLE
New dependency version for Jackson is not detected

### ISSUE THREAD

**Issue by whiskeysierra** [dependabot/feedback#487]
https://github.com/whiskeysierra/jackson-module-unknown-property/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
https://github.com/whiskeysierra/jackson-module-unknown-property/blob/master/pom.xml#L48

**Comment by greysteil** [comment]
I'm not sure what happened here, and can't replicate locally (Dependabot happily finds the update on my machine). If it recurs can you open and issue and *not* do the update yourself, so I can step the whole way through?
