### ISSUE TITLE
Access issue when resolving terraform dependencies on repos with ?ref arguments

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#489]
We are monitoring the terraform configuration files on one of our private repositories.

In one of our `.tf` files, we have:
```
module "eks-development" {
  source = "github.com/tablexi/terraform_modules?ref=37a2235//aws/eks"
...
```

Now we're getting dependabot issues opened regularly like:
```
Dependabot couldn't resolve your project's dependencies as it couldn't access terraform_modules?ref=37a2235.

You can grant Dependabot access to terraform_modules?ref=37a2235 by adding the repository here. We'll automatically close this issue and kick off another update run once permission is granted.

You can mention @dependabot in the comments below to contact the Dependabot team.
```

This is unexpected, since the `terraform_modules` project is public, and there's no reason we would need to grant access to it (nor can we).

Expected behavior: it resolves the issue, and fetches the source dependency with the ref properly.

**Comment by greysteil** [comment]
Should be fixed by https://github.com/dependabot/dependabot-core/commit/67b531950b66f25d531f4faeff76c7de7114ff1f - thanks for reporting!
