### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#49]
I want to inform my users, that dependencies are up-to-date.

The easiest way to do it, as for me, is a badge. Something similar to:

![dependencies](https://img.shields.io/david/expressjs/express.svg)
![dev](https://img.shields.io/david/dev/expressjs/express.svg)

Do you have any plans to support this feature?

**Comment by greysteil** [comment]
Yes, we'd be really keen to support that. I want to wait a month to see how GitHub's dependency graph support shakes out (it might well make more sense to power a badge with that), but if there's a role for Dependabot to play here we'll do it. Would be free publicity for us, after all!

**Comment by StephanBijzitter** [comment]
Don't forget to throw in a badge that is used only to advertise :-)
https://img.shields.io/badge/Dependabot-active-brightgreen.svg

**Comment by mydearxym** [comment]
+1

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#374
