### ISSUE TITLE
Conservative security updates

### ISSUE THREAD

**Issue by matiaskorhonen** [dependabot/feedback#49]
Please support a mode that creates PRs with the minimum update required to solve security issues.

e.g. if rails 4.2.7.1 has a security issue that's solved by 4.2.7.2, don't try to bump the version all the way up to 5.2.0.

**Comment by greysteil** [comment]
Interesting. I'm totally +1 on this, and will add it to my backlog.

**Comment by atherdon** [comment]
I want badge too!

**Comment by greysteil** [comment]
We do this now! Sorry it took a while.

(Still rolling out across languages, but done for everything except PHP.)
