### ISSUE TITLE
Support for Directory.Build.props files in .NET projects

### ISSUE THREAD

**Issue by xt0rted** [dependabot/feedback#492]
`Directory.Build.props` files can be used to add dependencies that all projects in the repo should have, or all projects under a specific folder such as `/test` where each project references the same testing packages for example.

Currently these files aren't being updated like my `.csproj` files are. They're xml files just like `.csproj` and use the same `ProjectReference` syntax.

An example of these being used can be found in the [getsentry/sentry-dotnet](https://github.com/getsentry/sentry-dotnet) repo where there's multiple levels of files:

- [/Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/Directory.Build.props)
- [/benchmarks/Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/benchmarks/Directory.Build.props)
- [/samples/Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/samples/Directory.Build.props)
- [/src/Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/src/Directory.Build.props)
- [/test/Directory.Build.props](https://github.com/getsentry/sentry-dotnet/blob/bc8b6bf9ffe9f34cd1fa9fc0119f2b71b85a6b2e/test/Directory.Build.props)

There's some logic behind how they're traversed but I don't think that's really relevant here, but [here's the docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019) that talk about it.

**Comment by xt0rted** [comment]
After taking a look at the nuget code it turns out these files are supported. My issue looks to be that I added Dependabot before creating my `Directory.Build.props` files and my unit test project so they weren't being picked up and checked. Removing the .net language and re-adding it picked up all of the newer files (multiple missing `.csproj` files, multiple `DirectoryBuild.props`, and the `global.json`).

**Comment by greysteil** [comment]
Ah cool, that makes sense. Dependabot would have picked up the new files the next time it ran, too.

Is there anything left to do here, or can this be closed?

**Comment by xt0rted** [comment]
I think everything is working as expected now.
