### ISSUE TITLE
No Dependabot PRs made for recent GitHub security alerts

### ISSUE THREAD

**Issue by JacobEvelyn** [dependabot/feedback#493]
Hi there! We recently got a few of GitHub security alerts and noticed that Dependabot hasn't made PRs for them. See: https://github.com/panorama-ed/nds/network/alerts and https://github.com/panorama-ed/rainbow-backend/network/alerts

I also noticed that the security PR that Dependabot _did_ make in the `nds` repo wasn't tagged with `security` as usual.

Is this behavior normal? I feel like I might be misunderstanding something about how Dependabot works here, possibly re: the GitHub acquisition (congrats, by the way!).

**Comment by JacobEvelyn** [comment]
Thanks for the context, @greysteil! That explains the label change. Do you know if there's a way of seeing all security PRs across all repos now that they don't have the `security` label? We found it really useful to be able to go to github.com/pulls and find all security Dependabot PRs across all repos to prioritize those and make sure we didn't miss any.

Re: the lack of a PR to fix the security alerts, I think it's actually just that no patched version for that dependency has been released yet. Sorry for the alarm!

**Comment by greysteil** [comment]
Ah cool. If you filter for `author:app/dependabot` that should get you all the PRs created by the automated security fixes app.

**Comment by JacobEvelyn** [comment]
Thanks @greysteil! Am I correct that that filter will start giving us non-security PRs once all of the "Dependabot Preview" functionality is in "Dependabot"?

**Comment by greysteil** [comment]
Yep! We’ll figure out another way to get a view of any security PRs at that point

**Comment by JacobEvelyn** [comment]
Great, thanks!
