### ISSUE TITLE
Dependabot encountered an unknown error.

### ISSUE THREAD

**Issue by j0k3r** [dependabot/feedback#498]
While trying to bump deps, I got the message:

> Dependabot encountered an unknown error.
>
> We've been notified of the problem, and are working to fix it.

I'm sure you were notified about that but I would like to be able to track the progress if any.

Dependabot url: https://app.dependabot.com/accounts/wallabag/repos/9193949
Repo url: https://github.com/wallabag/wallabag

**Comment by greysteil** [comment]
Sorry about that one! We're experiencing very high volumes since the GitHub announcement, so I'm not as on top of errors as usual, but I'll get to this one! I'm working through all the new edge cases we've seen methodically this week and next.

**Comment by j0k3r** [comment]
@greysteil thanks, looks like it's fixed :+1:
