### ISSUE TITLE
Can't login to configure

### ISSUE THREAD

**Issue by leastprivilege** [dependabot/feedback#499]
I added more repos, tried to configure - but I always get this:

<img width="1999" alt="Screenshot 2019-06-04 09 03 36" src="https://user-images.githubusercontent.com/1454075/58858431-cd16e180-86a7-11e9-9402-909a39e05d32.png">

**Comment by greysteil** [comment]
@feelepxyz can you take a look?

**Comment by feelepxyz** [comment]
@leastprivilege oh looks like the installation has somehow been deleted, could you try deleting and revoking Dependabot Preview from github and trying to connect again?
- Revoke `Dependabot Preview`: https://github.com/settings/apps/authorizations
- Uninstall Dependabot Preview: https://github.com/settings/installations

If you then visit the dashboard it should ask you to authorise and then install the app again (you won't loose any of your config): https://app.dependabot.com/

**Comment by leastprivilege** [comment]
That seems to work - thanks!
