### ISSUE TITLE
Semantic Commit Messages

### ISSUE THREAD

**Issue by bennyn** [dependabot/feedback#50]
It would be nice if the **Dependabot** creates [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages) (like Greenkeeper 😋 ).

So instead of:
> Bump react-hot-loader from 3.1.2 to 3.1.3

It could create a PR with the following commit message:
> chore(package): Bump react-hot-loader from 3.1.2 to 3.1.3

**Comment by greysteil** [comment]
Sounds like a good idea - done!
