### ISSUE TITLE
Code Climate encountered an error attempting to analyze this pull request.

### ISSUE THREAD

**Issue by stefanahman** [dependabot/feedback#503]
Hello!

This morning we encountered the following error message:

> Code Climate encountered an error attempting to analyze this pull request.

![image](https://user-images.githubusercontent.com/1053201/58931481-25111f00-8760-11e9-81f3-3f83e612ebae.png)

Detail page:

![image](https://user-images.githubusercontent.com/1053201/58931503-30644a80-8760-11e9-96dd-907380ea5d91.png)

I assume that we don't we to add the bot to the CodeClimate team and I'm not sure we even can.

**Comment by greysteil** [comment]
Hmmm, there's no way for you to add bots to your GitHub organisation - that's not how they work. Do you have a contact at Code Climate you can speak to about the above? Seems like a bug / bad UI on their side, and I can't think of anything we can do about it.
