### ISSUE TITLE
Dashboard is empty even after adding repo

### ISSUE THREAD

**Issue by Daenyth** [dependabot/feedback#509]
I added a private repo to dependabot, but when I go to my dashboard, it doesn't show up - I get a blank page (the header nav bar is there).

It sent update PRs, so I know it's working beyond the dashboard.

**Comment by feelepxyz** [comment]
@Daenyth oh what account you having issues with and what browser are you using? Could I also ask for a screenshot of the browser console to help with debugging? https://help.grasple.com/frequently-asked-questions/how-do-i-open-my-browser-console-and-take-a-screenshot

**Comment by Daenyth** [comment]
This is for `teikametrics`

<img width="1226" alt="Screen Shot 2019-06-06 at 4 08 34 PM" src="https://user-images.githubusercontent.com/14644/59063112-66dfb980-8875-11e9-86e8-3088bed130b4.png">

**Comment by feelepxyz** [comment]
@Daenyth hm not getting any clues from that output :( Could you try logging in a new incognito window and see if this works? Could be an extension which is blocking some request.

If this doesn't work try re-installing `Dependabot Preview`: first [revoke authorisation](https://github.com/settings/apps/authorizations) and [uninstall app](https://github.com/settings/installations). If you then visit the dashboard it should ask you to re-auth/install the app: https://app.dependabot.com/

**Comment by Daenyth** [comment]
The same thing happened.

I signed in with my github account, added the app to the organization, gave
permission for one repository, and then it directed me to the dashboard,
which was again blank.

**Comment by feelepxyz** [comment]
Hmm could you send a screenshot of the networks tab after a reload in the browser devtools? Does it also not work in chrome ingnito mode or a different browser? Sorry for the crude and slow debugging on this!

**Comment by rebelagentm** [comment]
@Daenyth 👋 Did this issue get resolved?
