### ISSUE TITLE
Feature: Configurable approval count for merge on approval

### ISSUE THREAD

**Issue by cvitan** [dependabot/feedback#512]
Currently Dependabot attempts to merge a PR when one approval is done, if the account setting `Treat PR approval as a request to merge` is set. If a repo is set to require two approvals, Dependabot will make an attempt after the first approval, and fail with the message `At least 2 approving reviews are required by reviewers with write access.` and not make another attempt when another approval is done.

It would be great if it would be possible to implement one of the following features:

1. Do the merge attempt when the number of approvals defined in the repo branch rule `Require pull request reviews before merging` is reached for the given repo.
2. Provide a "number of approvals" setting on a repo level.
3. Provide a "number of approvals" setting on an account level.
4. Re-attempt merging on each approval.

**Comment by greysteil** [comment]
Good shout - we can definitely do better there. I'm implemented (4), which I think is the most robust option. Thanks for the heads up!
