### ISSUE TITLE
Python bug

### ISSUE THREAD

**Issue by RDIL** [dependabot/feedback#515]
Hello dependabot,
in the https://github.com/cakebotpro/cakebot repository, I have dependabot installed.
It isn't bumping dependencies however, and I think I know why.

As you can see, my `requirements.txt` looks like:
```bash
--index-url 'https://cakebot.mycloudrepo.io/public/repositories/py'
--extra-index-url 'https://pypi.org/simple'
setuptools==41.0.1
wheel==0.33.4
area4==2.5.7
discord.py==0.16.12
PyGithub==1.43.7
reverse_geocoder==1.5.1
lcbools==1.0.2
beautifulsoup4==4.7.1
iss_api==1.1
filehandlers==1.2
slots==1.0
factdata==1.0
crime==0.2
```
at the time of writing this.
We need the cloudrepo prioritized, and so we have this specified.

I believe that because of this, dependabot is not able to accurately read the config, thus not bumping the dependencies. (the `area4` dependency has been out of date for more then a day, and I have live updates switched on)

This is just a theory, if I'm wrong please correct me.

Thanks!

**Comment by greysteil** [comment]
Sorry it's taken me so long to get to this. Those single quotes are confusing Dependabot - I'll get that fixed right now.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/bfb6798127b30c10bf2d1fb224f2499f04dea741, which will be deployed in the next 15 minutes. Thanks for reporting this!

**Comment by RDIL** [comment]
Thank you for fixing it 😀!
