### ISSUE TITLE
See what packages were discovered

### ISSUE THREAD

**Issue by a-h** [dependabot/feedback#517]
When I logged into the dashboard and view my project, I expected to see a list of all of the dependencies for that project which were scanned, and their versions.

Without it, I'm not 100% sure that Dependabot has done anything or not, or if it's seen all of the dependencies.

**Comment by greysteil** [comment]
Thanks for the feedback. Since we're integrating Dependabot directly into GitHub the dashboard is going to go away in the not too distant future, so this is a "won't fix" for now. We'll integrate Dependabot with GitHub's dependency graph as we move across, which should be a good long-term solution.

**Comment by a-h** [comment]
Unfortunately, the Github dependency graph doesn't support Go at the moment. Does that mean that there's a plan to get it to support Go module files (`go.mod`)?

**Comment by greysteil** [comment]
You bet!
