### ISSUE TITLE
Dependabot merged a PR after CI failed

### ISSUE THREAD

**Issue by antross** [dependabot/feedback#519]
Not sure if this has happened before, but this one caught my attention because it broke our builds. The PR in question was https://github.com/webhintio/hint/pull/2581

Our CI runs on Azure Pipelines and it specifically looks like we failed the "Checkout" phase for this particular PR so we never got far enough to fail the actual tests. That part was likely an Azure Pipelines issue, but I still wouldn't have expected this PR to get merged as the status reported back to GitHub indicated the CI check failed.

**Comment by greysteil** [comment]
Ooh, that's not good. I'll dig into exactly what happened here, but I'm guessing it's todo with the check runs not being created immediately. It's surprisingly hard for Dependabot to know whether checks are expected to be created or not, which is something I'd like to work with GitHub to improve.

**Comment by antross** [comment]
Any luck figuring out what happened? I just had two other PRs get merged this morning which failed CI. I'm going to disable the automerge feature in our project for now and revisit once we think there's a fix.

**Comment by antross** [comment]
Though I do suspect your original guess is correct. I've seen GitHub list a PR as green for 15-30s before registering we have additional checks to be performed - and I'm sure it easily take significantly longer than that.

**Comment by antross** [comment]
@greysteil If these delays continue to be a problem, what would you think about adding an option to the `config.yml` to specify how many checks to wait for? This is typically a consistent number for all of our dependabot PRs. That of course assumes you have access to the number of checks from GitHub.

**Comment by greysteil** [comment]
FYI, I've added a 1 minute delay before Dependabot merges PRs. That should fix this as long as check runs are kicked off in a relatively timely manner - thanks for reporting it!
