### ISSUE TITLE
Add dependabot by default on a repo that is tagged as Java

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#52]
...or add it by default to any freshly created repo on a given organization.

**Comment by greysteil** [comment]
I'm 👍 on this as a setting. Needs careful thought, and to be a setting, but I think Dependabot's onboarding experience for new repos could be better.

**Comment by davidgoate** [comment]
maybe some overlap here on https://github.com/dependabot/feedback/issues/59

**Comment by adriens** [comment]
Yes, for newly created would make the job for sure :+1:

**Comment by greysteil** [comment]
We've just shipped support for [config files](https://dependabot.com/blog/introducing-config-files/), which I think a good solution here. 🎉
