### ISSUE TITLE
.NET: dependabot fails to locate project files with multi-line definition in sln file

### ISSUE THREAD

**Issue by ChrisMaddock** [dependabot/feedback#520]
When a project has a multi-line definition in a solution file, dependabot skips the project file. This caused problems with adding dependabot to the [NUnit Console](https://github.com/nunit/nunit-console) as we then then hit inconsistent dependencies problems, as not all project files were updated in sync.

I tracked down the cause of the issue - this is noted as a TODO in the source, although I couldn't find a related ticket.

https://github.com/dependabot/dependabot-core/blob/819ce2a2f35303c172325145ba9420f07b15ec01/nuget/lib/dependabot/nuget/file_fetcher/sln_project_paths_finder.rb#L24-L25

A 'standard' project declaration would look like this:

```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "nunit.engine.tests", "src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj", "{D694CB69-6CFB-4762-86C2-EB27B808B282}"
EndProject
```

The version we have in the NUnit Console project looked like this:

```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "nunit.engine.tests", "src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj", "{D694CB69-6CFB-4762-86C2-EB27B808B282}"
	ProjectSection(ProjectDependencies) = postProject
		{B1D90742-39BD-429C-8E87-C5CD2991DF27} = {B1D90742-39BD-429C-8E87-C5CD2991DF27}
		{C2A8FC7A-FA64-46EA-AF6D-73D6B371DBF8} = {C2A8FC7A-FA64-46EA-AF6D-73D6B371DBF8}
		{28B605B2-E2E9-417E-8369-49E263F1F31B} = {28B605B2-E2E9-417E-8369-49E263F1F31B}
		{0DE218CA-AFB8-423A-9CD2-E22DEAC55C46} = {0DE218CA-AFB8-423A-9CD2-E22DEAC55C46}
	EndProjectSection
EndProject
```

I _think_ it should be possible for dependabot just to skip any content between the `Project` and `EndProject` tokens, regardless if it includes newlines or not. Unfortunately, I don't know enough about ruby to offer that as a PR, I'm afraid!

Thanks for putting the tool online - I think it'll be super helpful for NUnit, once we get things set up! 😄

**Comment by greysteil** [comment]
Thanks for this! I'm travelling and am currently Dependabot's only .NET person, but I'll try to get this fixed when I have a monent.

**Comment by ChrisMaddock** [comment]
Awesome - thank you! No urgency for us, I think we can get around it by modifying out sln file. 😄

**Comment by greysteil** [comment]
Fixed this on 18th June and forgot to close out this issue!

**Comment by ChrisMaddock** [comment]
Yay - thanks!
