### ISSUE TITLE
Feature request: Force conventional commit syntax

### ISSUE THREAD

**Issue by jwalton** [dependabot/feedback#522]
On some of my projects, dependabot commits with conventional commit (e.g. https://github.com/jwalton/passport-strategy-runner/commit/ed1b559dc74015bab14adbfb9483f8cc2f20bc09) but on some of my projects it does not (e.g. https://github.com/jwalton/node-promise-breaker/commit/eb3ad8478420178f9de17cc0c0cd3c60e558532e).

Is there a configuration setting somewhere to force it to use conventional commit?

**Comment by greysteil** [comment]
There's no configuration setting at the moment, but Dependabot will match the style of the most recent Dependabot commit when creating new PRs, so if you use the "squash and merge" option when merging a PR, and edit the commit title to be your preferred style then Dependabot will use that.
