### ISSUE TITLE
Docs needed for pip-compile support

### ISSUE THREAD

**Issue by craigds** [dependabot/feedback#523]
I'd love some more documentation about just exactly _how_ dependabot handles pip-compile workflows, as I haven't really found any so far. Some questions I have:

 * what python version does it use? How does it detect that? Is there any way we can specify it?

 * what OS does it run on? (this matters quite a lot; e.g. pip-compile builds on OSX produce quite different results than builds on linux) Is there any way we can specify it?

 * how does it know what order to compile the files in (e.g. does it resolve `-r other.txt` lines in the `.in` files and build a graph? or does it just do them alphabetically, etc) Is there any way we can specify it?

* is there a way we could give dependabot a key & url to use our private pypi mirror (devpi at present) with custom packages on it? Or do we just have to tell it to blacklist any custom packages we have?

**Comment by greysteil** [comment]
We generally just try to do the right thing, and treat it as a bug if we don't, but on those questions:
- We try to match your Python version. The relevant logic is [here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L442-L449).
- Dependabot runs on linux. There's no way to specify that at the moment, but we'd like to address that in future if it causes issues for customers
- It figures out the order to compile in based on the requirements tree. The logic is [here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb#L391-L404).
- You can specify private credentials in your [dashboard](https://app.dependabot.com) - use the drop down in the top right and select "config variables".

Hope that helps!
