### ISSUE TITLE
dependa-spin

### ISSUE THREAD

**Issue by peterennis** [dependabot/feedback#524]
here:

![dependa-spin](https://user-images.githubusercontent.com/140737/59395508-2a123780-8d39-11e9-83fe-3dc72d9b24cc.gif)

**Comment by greysteil** [comment]
This looks like it is a general GitHub issue, related to a large diff, rather than a Dependabot one. Closing, but let me know if I'm missing something.

**Comment by peterennis** [comment]
OK. Do I let it spin for hours and hope for a resolution ???
If it is expected to do something then a message would be helpful.
If it is stuck in a loop how are users expected to know ???

**Comment by greysteil** [comment]
To be honest I’ve never even seen the /conflicts URL in that image, and it 404s when I attempt to view it. I really have no idea on this one - support@github.com would know better, but I’m pretty sure it’s not Dependabot related.

**Comment by greysteil** [comment]
Oh, I guess you’re in a GitHub code editor to resolve the conflicts? This is going to be a bug in that!

Happily, Dependabot can resolve conflicts for you automatically if you comment `@dependabot rebase`.

**Comment by peterennis** [comment]
Here: https://github.com/peterennis/aeicons-react/pull/4 
👍 
I will check how the process went with the test app after completing the other merges.

**Comment by peterennis** [comment]
Upgrade went smooth. Thanks for the help 😄
