### ISSUE TITLE
Reporting missing Changelog

### ISSUE THREAD

**Issue by pwim** [dependabot/feedback#525]
I noticed the `money` Gem is missing a Changelog. Is this something that's automatically flagged for you, or should I report it? If I should report, how should I do so?

**Comment by greysteil** [comment]
It's not automatically flagged. Looking at our open source PRs it looks like Dependabot is able to find the changelog most of the time (like [here](https://github.com/kyoshidajp/ec2spec/pull/43)). Not sure what must have happened here as a result - perhaps GitHub timed out during the request. Is the PR open source?

**Comment by pwim** [comment]
No, it's not open source. The PR was created on 2019-06-13T02:29:32Z, so before that open source one. 

Perhaps always including a changelog section, and being explicit if you can't find anything would help. As it is, it took me a minute to confirm that there was in fact no changelog being listed. Such a section could also provide instructions for reporting the missing changelog.

Anyways, it looks like it was a transient issue, so I guess it should be there for future updates of this gem. Thanks!
