### ISSUE TITLE
PRs to update to Rails 4.2.11.1 get closed automatically

### ISSUE THREAD

**Issue by anym0us** [dependabot/feedback#526]
The following thing happens with Rails 4.2.11.1 PR:
<img width="778" alt="Screen Shot 2019-06-13 at 4 02 26 PM" src="https://user-images.githubusercontent.com/5333431/59434948-3a87e800-8df5-11e9-9478-678af5f17665.png">

However, Gemfile has an outdated version. Here're some of the changes from the closed PR:
<img width="197" alt="Screen Shot 2019-06-13 at 4 05 20 PM" src="https://user-images.githubusercontent.com/5333431/59434997-57bcb680-8df5-11e9-8fdc-21e62ebb9d5f.png">

And also, Rails 4.2.11.1 release exists:
https://github.com/rails/rails/releases/tag/v4.2.11.1

**Comment by feelepxyz** [comment]
@anym0us oh don't think this is a general problem. On which which repo/pull request did this happen? If it's a private repo please send the link to support@dependabot.com
