### ISSUE TITLE
Should not overwrite symlinked requirements.txt with dereferenced file

### ISSUE THREAD

**Issue by kojiromike** [dependabot/feedback#527]
We have a requirements.txt that is a symlink to python/requirements.txt in the same repository. Dependabot opened a PR to (correctly) update a dependency in python/requirements.txt, but it also updated requirements.txt, overwriting the symlink with another copy of the file, and breaking our workflow.

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/19a3c4b7f60d873ef644d338bbf63e9734ec4747, which I'll get deployed now. Thanks for the feedback, and sorry it took a little while to address!
