### ISSUE TITLE
Attempts to add a new repo result in 404 error

### ISSUE THREAD

**Issue by fcalderon** [dependabot/feedback#528]
Greetings dependabot team, and congratulations on being acquired by GitHub. That news made me really happy.

## The issue

When I try to add a repo from my organization using the dependabot dashboard (/accounts/<org_name>/add), the "Add Selected (x)" button loads for a bit and then nothing happens. This issue seems similar to #496 but the error message is different and I'm only adding a single repo.

I opened dev tools and noticed that the `update_configs` `POST` request fails with a `404` error. The error response body doesn't say much, but here it is in case it helps:

```json
{"errors":[{"status":404,"title":"Not Found"}]}
```

Here's the request body in case it helps. I'm omitting some info but can provide it upon request

```json
{
  "repo-id": "<some-number>",
  "repo-name": "<repo-name>",
  "update-schedule": "daily",
  "package-manager": "npm_and_yarn",
  "lockfile-only": false,
  "security-updates-only": false,
  "update-subdependencies": false,
  "automerge-rule-development-deps": "never",
  "automerge-rule-runtime-deps": "never",
  "directory": "/",
  "account-id": <some_number>,
  "account-type": "user"
}
```

One thing to note is that in the request body, the `account-type` is `"user"`, however, this account is an organization of which I am the "owner" and admin. 

## Potentially useful context

The organization account used to be a user account and we recently converted it into an organization. Dependabot was initially setup for two of our repos while it was a user account.

Currently, dependabot is working just fine with two of our repositories (the two we created while it was user account.) Updating the settings for these repo's work just fine. Our problem seems to only be affecting adding new repos. 

## What I've tried

* Manually adding the configuration to a repo in a `.dependabot/config.yml` and then try to add the repo again

Unfortunately, I don't have another repo readily available that I can add for this organization. But I can create one and try again if needed.

**Comment by feelepxyz** [comment]
@fcalderon oh taking a look. Which org name is this happening for? If you want you can also send any further info by email to support@dependabot.com to help debug this account ✌️

**Comment by feelepxyz** [comment]
@fcalderon hm not sure but the installation might be out of sync here, want to try the brute force option and re-install the app for both your personal and org account?

- Uninstall for user: https://github.com/settings/installations
- Uninstall for org: `https://github.com/organizations/<ORG NAME>/settings/installations`

Then try installing it again: https://app.dependabot.com/ 🤞

**Comment by fcalderon** [comment]
Hi @feelepxyz, sorry it took so long for me to reply. The organization name is ScholarJet. I'll try the brute force approach like you suggested and will report back :crossed_fingers: !

**Comment by fcalderon** [comment]
@feelepxyz - I followed your instructions and re-installed dependabot on both accounts (organization and personal) and it's nice working like a charm. Thanks so much for your help!

**Comment by feelepxyz** [comment]
Great news! 🎉🤠
