### ISSUE TITLE
How do I add an organization repo - I am the owner

### ISSUE THREAD

**Issue by peterennis** [dependabot/feedback#529]
I looked at #42 and #59 

No help. Info is as clear as mud.

How do I add an organization repo to dependabot?

**Comment by greysteil** [comment]
Did you figure this out?

You need to install Dependabot on that organisation. You can get a link to the install page from the drop down in the top right of your account, or on [this page](https://github.com/apps/dependabot-preview/installations/new). You'll then need to switch view to that organisation (from the same drop down) and add the repo to Dependabot as you normally would.

![image](https://user-images.githubusercontent.com/1144873/59562902-87083900-902a-11e9-9866-44e5d69d4ca7.png)

**Comment by peterennis** [comment]
The link you provided was exactly the answer I was looking for 👍
