### ISSUE TITLE
Improvement of conventional commit messages

### ISSUE THREAD

**Issue by exactlyaron** [dependabot/feedback#53]
Hello, (yes, me again)

I've done a bit of a search;

https://github.com/dependabot/dependabot-core/issues/246
https://github.com/dependabot/dependabot-core/issues/192

Because of the way things are going we're moving away from the monorepo approach and having things separate to make it easier for publishing and building.

So we're using [semantic-release](https://github.com/semantic-release/semantic-release) and [commitizen](https://github.com/commitizen/cz-cli) with the [cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) which is based on [Conventional Commits](https://conventionalcommits.org/).

I'd like to request some enhancements. (Unless they're already in place and I'm missing them again)

- conventional commit messages for commits (build or chore)
- scope package.json file at the moment no file is scoped (example: https://github.com/wmfs/food-hygiene-blueprint/commit/b904956ffafe52fa8bd1eff4d9d0e69616960af6).  I've seen your example of it happening in a way previously here - https://github.com/wireapp/wire-web-packages/pull/142 but that doesn't seem to happen now?

Greenkeeper differentiates between dependancies & devDependancies.  deps get a fix: and devDeps get a chore.  The fix triggers a release.  This is perfect for our a lot of our packages and in theory how we'll be building products. At least how I see it happening in my head any way.   It would be nice if dependabot had a config to do something similar?  😉 

I might be able to jig things with [commit-analyzer](https://github.com/semantic-release/commit-analyzer) if dependabot was doing a conventional message ... but it might end up being a bit messy.

There is a lot of love for dependabot at [wmfs](https://github.com/orgs/wmfs) though and the support for Docker will come in handy very soon! 👍 

Thanks,

**Comment by greysteil** [comment]
Thanks for the feedback!

On conventional commits, it looks like it was just a case of Dependabot recognising that your repo had switched over. I can see that https://github.com/wmfs/food-hygiene-blueprint/pull/8 uses angular style.

On scoping, what's your use case for it? I removed it a few months ago because Angular themselves don't use it for package upgrades ([Angular commits here](https://github.com/angular/angular/commits/master/package.json)).

On differentiating between deps and devDeps, I can see where you're coming from, but are you sure you want t release each time one of your deps gets a patch / minor release? If you're not pinning your dependencies, which for a library you probably shouldn't be (to increase the number of dependencies that can be shared by those downloading it), then a release isn't really necessary I don't think? It also feels a bit weird to mark performance enhancements in sub-dependencies as a `fix` (or feature additions as a `feat`, since it's not a `feat` in your library).

**Comment by zeke** [comment]
I'm also using semantic-release and would love for dependency update to be able to trigger releases.

**Comment by greysteil** [comment]
@zeke - do you have an idea of how exactly you would want that to work?

**Comment by zeke** [comment]
I think the way Greenkeeper does it works well. I think for runtime deps they do a `fix: ` prefix and for dev deps they do `chore: `

I know configuration is kind of a last resort, but maybe a configurable prefix would be good?

Just to throw a wrench in things here, I'm working on a new project https://github.com/electron/algolia-indices which should ideally be (semantically) released when _any_ dep is updated, regardless of whether it's a runtime dep or a dev dep.

**Comment by exactlyaron** [comment]
> On conventional commits, it looks like it was just a case of Dependabot recognising that your repo had switched over. I can see that wmfs/food-hygiene-blueprint#8 uses angular style.

Okay that makes sense, I've removed the old monorepo and setting up the new repos individually now.

> On scoping, what's your use case for it? I removed it a few months ago because Angular themselves don't use it for package upgrades (Angular commits here).

It's just a nice thing isn't it really.  We're trying to get into the habit of writing better commits and making this easier to read.

> On differentiating between deps and devDeps, I can see where you're coming from, but are you sure you want t release each time one of your deps gets a patch / minor release? If you're not pinning your dependencies, which for a library you probably shouldn't be (to increase the number of dependencies that can be shared by those downloading it), then a release isn't really necessary I don't think? It also feels a bit weird to mark performance enhancements in sub-dependencies as a fix (or feature additions as a feat, since it's not a feat in your library).


Right bare with me here, (@jezhiggins could probably explain better than I can) but basically Tymly is very modular in it's make up, with [plugins](https://wmfs.github.io/key-concepts/#plugins) and [blueprints](https://wmfs.github.io/key-concepts/#blueprints) and a core [Tymly](https://github.com/wmfs/tymly-core) at it's heart.  The plugins in particular use Tymly for testing and in some cases have it as a dependency.  Blueprints have plugins as dependancies.  It's like a web but not really a web. 

A good example has actually cropped up this morning.

Tymly-core was updated and released [v.1.1.1 ](https://github.com/wmfs/tymly-core/releases/tag/v1.1.1) a few days a go.  We have [Tymly-runner](https://github.com/wmfs/tymly-runner) which makes for a configurable env to run Tymly(s), this has Tymly as a [dependency](https://github.com/wmfs/tymly-runner/blob/master/package.json#L29).  Now Dependabot came along as Tymly v1.1.1 was released and updated the [version](https://github.com/wmfs/tymly-runner/commit/94d6bb98718a9110ccddd15237705134a39f1ccf) in the package.json of Tymly-runner.  High five Dependabot!   But... with the way the commits are formatted semantic-release didn't do a release of Tymly-runner using with the v1.1.1 of Tymly.

This in turns can impact on builds of Tymly products - but that's a longer thing to type out.

I'm not starting to think the initial title of the request should  be different.

**Comment by exactlyaron** [comment]
This may interest you as well @zeke 

> I might be able to jig things with commit-analyzer if dependabot was doing a conventional message ... but it might end up being a bit messy.

I've just had a go with commit-analyzer plugin and it's worked rather nicely and simply as well. 

```
"release": {
    "analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {"type": "build", "release": "minor"}
      ]
    }
  }
```


So when dependabot comes a long with a [commit](https://github.com/wmfs/building-blueprint/commit/e2f3ff6f73d13631e43cbf38e6d633a5e3a483f9) and it's merged the commit message having 'build:' will trigger a minor release.  Party time!   🎉🎉

If dependencies and devDependancies were differentiated by Dependabot? Similar to Greenkeeper, then we could use the plugin to give devDependancies a patch release etc if it's updated as a chore for example.


But Dependabot (when we pay for the private repo access 💰 ) is going to work super for how we're building Tymly products though, basically everything gets installed as defined by a package.json, node_modules is thrown into a Docker image and that's pushed ready to be used.

So with the [greater control](https://github.com/dependabot/feedback/issues/15) of bumping we'd be able to define specific builds for show and tells or tested by customers then they only get bumped and build at specific days of the week.

**Comment by greysteil** [comment]
Interesting. I can see an argument for using the `scope` to differentiate between dev and production dependencies - that would allow you to customise the logic on your side, which I'm 100% onboard with.

What I don't like is changing the commit type itself to `fix` or whatever for production dependencies. I know Greenkeeper does it, but it's not accurate - a lot of those changes will be `build` changes, and naming them `fix` for the benefit of people using automated release tools, at the expense of a misleading name for everyone whose not, doesn't feel right to me.

How about we add in scopes, and go for `build(deps): ...` and `build(devDeps): ...`?

**Comment by exactlyaron** [comment]
Yeah that's understandable in the world of conventional commits.  Scoping would be perfect actually as that can be defined in the release rules of the commit analyzer. 

There is no emoji to show my appreciation for this @greysteil !  👍  Thanks a lot!

**Comment by greysteil** [comment]
Haha, awesome, I'll get it shipped today 🙂

**Comment by greysteil** [comment]
Shipped! https://github.com/dependabot/dependabot-core/commit/ef1b3218c3a28c676a8131cb07cf1b8312a19a4c.

If there's a backlash from people who know more than me about scopes then I may have to revert, but I think it should be fine, and is definitely worth trying. Thanks for the feedback @exactlyaron!

**Comment by zeke** [comment]
Thanks, @greysteil 👏
