### ISSUE TITLE
One of our projects is not automerging

### ISSUE THREAD

**Issue by chriseyre2000** [dependabot/feedback#530]
https://github.com/mergermarket/debtwire-company-subscriber

This has PR's that have passed tests but has not been merged.

Do we have snyk checks that we are not using?

**Comment by greysteil** [comment]
Looking now, thanks for reporting!

**Comment by chriseyre2000** [comment]
I manually merged the branch

**Comment by greysteil** [comment]
OK, can you leave an `@dependabot` comment if this happens on another PR and let me investigate before merging?

**Comment by chriseyre2000** [comment]
ok
