### ISSUE TITLE
Allow commit message change with @dependabot command

### ISSUE THREAD

**Issue by Nargonath** [dependabot/feedback#531]
I'm using `semantic-release` to manage my packages hence my commit follows the conventional commit message. The commits from dependabot are created as `chore(dep):` but in some of my packages I want the dependencies changes to trigger a release. For that I have to amend the commit myself every time and it's cumbersome. Would it be possible to add a command to dependabot that we could use to update the commit message? Perhaps something like `@dependabot amend` that would allow to overwrite the commit message or something like `@dependabot bump patch/minor/major` but that would not make much sense for those not relying on commits for their semantic versioning.

Thanks!

**Comment by richardson-trevor** [comment]
We've got a thread running on this here: https://github.com/dependabot/feedback/issues/443

**Comment by greysteil** [comment]
Let's close this and focus the discussion there.

Also, for the case you've described above I would recommend using the GitHub UI for "squash and merge" to amend the commit message when merging.

**Comment by Nargonath** [comment]
Yeah indeed could just squash it using GH UI. I've looked at the issue you mentioned but felt it was a bit different of my use case hence I opened a new issue. Thanks for your input.
