### ISSUE TITLE
Dependabot is not running daily updates on expected schedule

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#532]
My organization is set to Update run day and time  "monday 02:00 CDT".

This morning, at 08:00 CDT, dependabot opened PRs for some "daily update" projects.

This behavior seems to have changed between May 22nd (where I can see PRs which are opened near 2am), and June 3rd (where I see PRs opened near 5am).

I can't really tell whether it's project-specific or org-wide. Strange though....seems to be moving around, day -to-day.

Ideas?

**Comment by greysteil** [comment]
This is one for @hmarr as I’m pretty sure it’s because the additional volume has increased our queue lengths.

**Comment by hmarr** [comment]
Yeah it's that our growth since the acquisition has meant the batch jobs are taking longer and longer to run. I'm currently waiting on AWS to approve a limit increase, which will allow us to increase the size of the pool of workers (and pay AWS lots more money 😄).

**Comment by hmarr** [comment]
In case it's of interest, here's how the size of the queue has increased over the past few weeks. The first week is pre-acquisition, the rest is post-acquisition. 📈

![image](https://user-images.githubusercontent.com/110275/59648227-f1f96300-9143-11e9-92d4-4c5e6d9b79be.png)

**Comment by hmarr** [comment]
(And to be clear, that's Dependabot Preview - not the GitHub-integration version, which runs on different infrastructure)

**Comment by rdunlop** [comment]
Thank you @greysteil @hmarr for the great feedback. congrats on all your success.

I've moved my scheduled time back 3 hours, so that we are more likely to have the dependabot tasks run during our off hours.

Thanks again.

**Comment by hmarr** [comment]
This should be in a much better state now - we've been using many more machines to process the update jobs for the last couple of days.

Here's the graph showing the backlog each day (the spikes for the past two days are much smaller):
![image](https://user-images.githubusercontent.com/110275/59879363-22bde000-9370-11e9-9617-5cc40e2dbeef.png)

And here's our throughput (updates performed per minute):

![image](https://user-images.githubusercontent.com/110275/59879400-39fccd80-9370-11e9-8796-fc4e7a3c006d.png)

I'll close the issue for now but feel free to get in touch if you spot this causing problems again!
