### ISSUE TITLE
Unable to detect correct Python version

### ISSUE THREAD

**Issue by frafra** [dependabot/feedback#534]
My `setup.py` contains this line:

```
 python_requires='>=2.7, <3', 
```
-- https://github.com/GeoNode/geonode/blob/4b7dbff0ea884c9aa5f9ce45ad1eab9dc7ccb083/setup.py#L42

It seems that this is not sufficient to let dependabot detect that the project is using Python 2. I did not find any documentation about how it is able to detect that, so it is hard to understand what to setup in my project to avoid having pull request of dependencies that are Python 3 only.

**Comment by greysteil** [comment]
Ah, interesting. We could do better here, but it's not trivial.

Currently, Dependabot uses simple indexes to the get a list of all available versions. We don't currently look at the Python version when doing so, but I've just added [this logic](https://github.com/dependabot/dependabot-core/commit/48848b9f1fda86b78755520cead6eff47dc2d8b8) that will make it easier for us to. The next thing we need to do is find a good Python version to use given a `python_requires` line (we'll probably want to take the lower bound). I'll try to get to that today, but if I haven't done so in the next week please remind me!

**Comment by frafra** [comment]
Hi! Any news about that?

**Comment by greysteil** [comment]
Not yet. I've just done a big refactor of our Python version detection code, though (it's [here](https://github.com/dependabot/dependabot-core/pull/1241)), which will make this possible. Next step is to parse the `python_requires` version in `PythonRequirementParser`, and final step (after that) will be to use the detector class when dealing with `requirement.txt` files.

**Comment by greysteil** [comment]
Shipped in https://github.com/dependabot/dependabot-core/commit/3011eab55d1b620d4ffbe4a9466a97e9a96de8df. 🎉

**Comment by greysteil** [comment]
Thanks for suggesting this, and for the encouragement to get it done.
