### ISSUE TITLE
Webhook not received for completed check suite?

### ISSUE THREAD

**Issue by RDIL** [dependabot/feedback#535]
Hello Dependabot,
Earlier, I used `@dependabot squash and merge` on a pull request the bot made to save myself some time, however it looks like it did not work.

I ran the command, and the PR body was updated to say it would automatically be squashed and merged once the CI passed on it.

The only problem is that it didn't get merged.

The CI passed 3 minutes after the PR was opened, and yet 19 minutes after (when writing this), it didn't squash it.
I had to do it manually :(

The PR in question is https://github.com/RDIL/Gatsby-app/pull/104

Thank you in advance!

**Comment by greysteil** [comment]
Can you let me know if this happens again and *not* merge the PR in the meantime? It's tricky to debug what has happened if you do. In this case my hunch is that Dependabot hadn't yet received a webhook from GitHub about the check runs, but I'm not certain.

**Comment by RDIL** [comment]
Okay, I'll do that for the next bump which will likely be tomorrow.

**Comment by RDIL** [comment]
By the way, congrats on staff badge :)
