### ISSUE TITLE
Unable to find documentation link from home page

### ISSUE THREAD

**Issue by jglick** [dependabot/feedback#536]
Finding https://dependabot.com/docs/config-file/ starting from either https://dependabot.com/ or https://app.dependabot.com/ seems impossible; have to [Google it](https://google.com/search?q=dependabot+docs)!

**Comment by greysteil** [comment]
It's right here, on the add repos screen:

![image](https://user-images.githubusercontent.com/1144873/59774166-dab19700-9263-11e9-8444-95a3bd914261.png)

We should add a link from https://dependabot.com, tough - @feelepxyz can you take that?

**Comment by feelepxyz** [comment]
Yup adding a link to the website footer!
