### ISSUE TITLE
@dependabot merge does not work from PR review summary comment

### ISSUE THREAD

**Issue by jglick** [dependabot/feedback#537]
It seems that if you say `@dependabot merge` as the main comment of a PR review is ignored. The bot only listens to regular comments, which are a different GH event type. See https://github.com/jenkinsci/archetypes/pull/49#pullrequestreview-251760870 for an example.

**Comment by greysteil** [comment]
From memory I *think* this is an issue with the GitHub API not making it possible to add a reaction to the main comment of a PR review. I work for GitHub now, so hopefully can do something about that...

**Comment by greysteil** [comment]
I've chased this up internally. FYI, Dependabot *does* listen and respond to overall review comments - it just can't add a reaction to them at the moment.

**Comment by greysteil** [comment]
Got this fixed within GitHub, so Dependabot can now give overall PR review comments a reaction. 🎉
