### ISSUE TITLE
Detect and automatically update `replace` field as well

### ISSUE THREAD

**Issue by yongtang** [dependabot/feedback#538]
When dependabot updates the go.mod, it didn't capture the replace. For example, in go.sum we have
```
require (
  ...
  github.com/miekg/dns v1.1.12
  ...
)
replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
```
When updates `github.com/miekg/dns v1.1.12` to `v1.14` (See PR https://github.com/coredns/coredns/pull/2899), it could easily find out that:

```
replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12
```
should be changed to
```
replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.14
```
as well. But it is not working this way so there is a duplication of libraries.

**Comment by hmarr** [comment]
I just want to clarify your use of the `replace` directive. Are you using it to pin that library to `v1.1.12`? If so, I wouldn't expect a version (`v1.1.3`) to be specified on the left hand side of the `=>` operator.

Assuming that's what you're trying to achieve - you're right that we don't support that properly right now. I'll have a look into fixing it. Thanks for reporting!

**Comment by yongtang** [comment]
Thanks @hmarr. In our case, we have dependencies of `github.com/miekg/dns` from our repo (coredns) and we need `v1.1.12`. However, we also depends on `caddy` which currently have a go mod dependency of `github.com/miekg/dns v1.1.3`.

What we want to achieve, is to rewrite caddy's dependency to point to `v1.1.12`, so `replace` is used.

When we do update in our repo (coredns), we expect the bump  `github.com/miekg/dns` from v1.1.12 to v1.1.13. However, by default the caddy's dependency is still `v1.1.3`. Unless dependabot could automatically rewrite the `replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.12` to `replace github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.13`, we will end up with two versions of `github.com/miekg/dns` again: One from `v1.1.13`, and another is `v1.1.12` (from caddy but was replaced by the `replace` rule).

**Comment by hmarr** [comment]
Hmm, that doesn't fit with my understanding of how Go modules works. You should only get one version per (major version of a) module. Go modules uses the [Minimum Version Selection](https://research.swtch.com/vgo-mvs) algorithm to decide which version to use. Each version specified in a `go.mod` is the minimum usable version, and MVS effectively picks the maximum of each of these specified versions.

Given that, I'd assume that the `replace` is redundant in your case - MVS should be picking the more recent version by default.

**Comment by hmarr** [comment]
Closing for now, but please let me know if I've misunderstood @yongtang!
