### ISSUE TITLE
Does not find multiple python requirements file in the same directory

### ISSUE THREAD

**Issue by wtanaka** [dependabot/feedback#539]
We have a directory in a repository with more than one requirements file in it.  Some of the filenames do not end in .txt, like "pip-requirements".  Others do.  Dependabot is only checking one of the multiple requirements files.  Is there a possibility of making it check all of them instead?

**Comment by StevenWan-minted** [comment]
Similarly, there is a directory that only has a requirements file that is not ended by .txt, dependabot is not picking it up either

**Comment by greysteil** [comment]
Oh man, that makes things way harder for Dependabot. What's the reason for not using a `.txt` suffix for them?

**Comment by wtanaka** [comment]
No particular reason.  If we renamed the "xxx-xxx-requirements.txt" to "xxx-xxx-requirements" would that cause the rest of the "*requirements*" files in the directory to be picked up?

**Comment by greysteil** [comment]
Afraid not - Dependabot pulls down files one-by-one (we never clone your repo) so we use heuristics to discover which files to pull down. The logic is [here](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_fetcher.rb) (written in Ruby).

I've not heard of anyone else not using a `.txt` suffix (or `.in` for pip-compile files), either when working in Python myself or talking to Dependabot customers. Is this common? If you add `.txt` suffixes then Dependabot will start picking up those files.

**Comment by wtanaka** [comment]
You'd probably have a much better sense of what's common for sure!  I did find a few other examples in the wild:

https://github.com/gregoryely/condapysit/blob/master/dockerfile#L32
https://extensions.ckan.org/extension/stromnetzberlin/
https://www.noisebridge.net/wiki/Phong#Requirements
https://hub.docker.com/r/trustcode/odoo/dockerfile
https://blog.e0ne.info/post/virtualenv-and-pip-instead-of-buildout/

**Comment by greysteil** [comment]
Thanks for the additional context. I'm going to put this as a "won't fix" since the official documentation puts `.txt` at the end of each suggested requirement file name, and it would be painful to deviate from that (we have to distinguish requirement files from pip-compile files, etc.). If you rename your requirement files to end with `.txt` Dependabot will work on them.
