### ISSUE TITLE
Feature: Peer Dependencies for node/npm

### ISSUE THREAD

**Issue by dwieeb** [dependabot/feedback#54]
I'm not sure the best way to handle this, but dependabot does not seem to look at peer dependencies.

Because peer dependencies are often added as dev dependencies as well (so that the package exists during development), a possible additional feature (perhaps when https://github.com/dependabot/feedback/issues/5 is accomplished), is to group the peer dep with the dev dep.

References:
- https://docs.npmjs.com/files/package.json#peerdependencies
- https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by skjnldsv** [comment]
@greysteil any clue for this?

**Comment by greysteil** [comment]
Yes! We're spinning work on it back up this week. I have a branch that half does it, and we should be able to get it over the line this week. 🤞

**Comment by skjnldsv** [comment]
You're awesome! :tada:

**Comment by greysteil** [comment]
FYI, the first version of this is going to be deployed tomorrow. At first it will just block Dependabot from creating updates that break peer dependencies. From there the next step is for Dependabot to update multiple dependencies at once if/when necessary, and to be able to add peer dependencies to your `package.json` if doing an update requires doing so. It's quite a lot of extra complexity, but it's worth it.

The PR that adds initial support is [here](https://github.com/dependabot/dependabot-core/pull/730) if anyone is interested, and will be deployed tomorrow morning.

**Comment by feelepxyz** [comment]
Dependabot can now update multiple dependencies at once when required by a major version upgrade, for example updating both `react` and `react-dom` from version `15.x` to `16.x` 🎉

This should work for most common cases of peer dependency requirements. We haven't yet dealt with the case when a new version adds a new peer dependency requirement. For example, when using `react-apollo@1.x` Dependabot won't take you to version `2.x` as it adds a new peer dependency requirement for `apollo-client`.

If you're interested, here's the [PR](https://github.com/dependabot/dependabot-core/pull/774).
