### ISSUE TITLE
Respect custom registry  in .npmrc

### ISSUE THREAD

**Issue by egoist** [dependabot/feedback#541]
In my project I have `.npmrc`:

<img width="391" alt="屏幕快照 2019-06-21 下午7 49 48" src="https://user-images.githubusercontent.com/8784712/59920681-e10b6300-945d-11e9-96c9-79a8c9f4966d.png">

But Dependabot still installs dependencies with yarn's default registry:

<img width="1561" alt="屏幕快照 2019-06-21 下午7 50 35" src="https://user-images.githubusercontent.com/8784712/59920708-f7192380-945d-11e9-8971-1aeacf12949c.png">

**Comment by greysteil** [comment]
Oh interesting. I bet we've got some logic that is ignoring the default registry, but of course for Yarn it makes a difference. Will dig into this and get it fixed for you.

**Comment by greysteil** [comment]
Hmmm, I can't find what's causing this. We're still writing the `.npmrc` when we attempt to do the update, so it should be working.

@feelepxyz can you take a look? Could have something to do with Lerna being in the mix, too? A relevant PR with the registry change is [this one](https://github.com/saberland/saber/pull/272/files).

**Comment by feelepxyz** [comment]
Oh yeah will take a look! Assuming this works as expected when doing yarn
install locally?

**Comment by feelepxyz** [comment]
Hey, not sure we can do much about this atm as this is happening inside
yarn. Yarn always seems to rewrite registry.npmjs.org to
registry.yarnpkg.com in yarn.lock as soon as you do any type of update
(e.g. yarn add) ignoring what's in your .npmrc.

Did you recently move from npm to yarn? Any reason you are keen to keep it
as registry.npmjs.org?

**Comment by ffflorian** [comment]
@greysteil 
I am using both a [`.npmrc`](https://github.com/ffflorian/gh-open/blob/e8d8fcff1c475641285a88bc15dc742cdfa3c399/.npmrc) and a [`.yarnrc`](https://github.com/ffflorian/gh-open/blob/e8d8fcff1c475641285a88bc15dc742cdfa3c399/.yarnrc) file and still, dependabot somehow [doesn't respect the registry](https://github.com/ffflorian/gh-open/commit/e8d8fcff1c475641285a88bc15dc742cdfa3c399).

**Comment by ffflorian** [comment]
I tried solving this in the dependabot settings, but I can't set the registry with an auth token :slightly_frowning_face: 

![Screenshot from 2019-07-19 13-39-37](https://user-images.githubusercontent.com/5497598/61532647-c4e1ee00-aa2a-11e9-8a22-bb58833e6219.png)

**Comment by greysteil** [comment]
@ffflorian ah, interesting. I've just pushed https://github.com/dependabot/dependabot-core/commit/b1d75e35334f44307b71edec509bc085b311069f, which I'll deploy today, which will fix this in the case that you've got a `.yarnrc` file.

**Comment by greysteil** [comment]
OK, I think as part of fixing the above I now fully understand this.
- Yarn ignores it when an `.npmrc` sets the registry to `https://registry.npmjs.org`
- Yarn doesn't ignore it when a `.yarnrc` does the same

As a result, Dependabot will now write a `.yarnrc` for those cases.

@egoist - the one thing I'm unsure of is when you're getting those `https://registry.npmjs.org` entries on https://github.com/saberland/saber. Do you have a global `.yarnrc` file somewhere that could be causing that? Or did you used to have one?

**Comment by rebelagentm** [comment]
@egoist 👋 Did this get resolved?

**Comment by ffflorian** [comment]
After @greysteil's fix it works for me by using a custom `.yarnrc` file.

**Comment by rebelagentm** [comment]
Great!  Thank you!

**Comment by fernan256** [comment]
Hi @greysteil we implemented the dependabot but we are having the issue mentioned in the first comment, the yarn.lock URLs are updated from this:
![imagen](https://user-images.githubusercontent.com/8095849/74369616-6a3c2500-4db4-11ea-8cfc-437bc3afa784.png)

to this:
![imagen](https://user-images.githubusercontent.com/8095849/74369640-745e2380-4db4-11ea-9d97-f18124b94270.png)

We have both .yarnrc and .npmrc with the same registry URL.

**Comment by ffflorian** [comment]
@fernan256 what is the content of your `.yarnrc` file?

**Comment by fernan256** [comment]
Thanks for the quick response @ffflorian the content of the `.yarnrc` is `registry "https://registry.npmjs.org/"` and a private registry so it has two lines. But in this repo, we also have a `.npmrc` that contains the same as the `.yarnrc`. Could this be the cause of the problem to have both yarn and npm?

**Comment by fernan256** [comment]
@ffflorian hey there, any heads up you could give me to avoid the changes on the URLs?

**Comment by ffflorian** [comment]
@fernan256 I don't know if it makes any difference but my `.yarnrc` file looks like this:

```
--registry "https://registry.npmjs.org"
```

and my `.npmrc` file looks like this:

```
registry=https://registry.npmjs.org/
save-exact=true
```

I don't think the problem is that you have both rc files, but maybe your additional private registry is somehow interfering with dependabot's yarn installation? Maybe @greysteil can answer that?

**Comment by fernan256** [comment]
@ffflorian yes I think we have some issues with the private repo, @greysteil quick question, using private repo is there any extra configuration we need to do?

**Comment by greysteil** [comment]
@feelepxyz is your man on this one - I don't work on Dependabot anymore (I do all of GitHub's security stuff instead).

**Comment by feelepxyz** [comment]
@fernan256 have you given Dependabot access to the private registry? You can do this from the [dashboard](https://app.dependabot.com/) by adding config variables in your account settings.

I've not managed to reproduce this issue, here's a working PR: https://github.com/feelepxyz/yarnpkg/pull/1/files using this config: https://github.com/feelepxyz/yarnpkg/blob/master/.yarnrc

**Comment by fernan256** [comment]
@greysteil I think we solved it using the `--` in front of both registry definitions in the `.yarnrc` file, the npm and the private.

**Comment by fernan256** [comment]
@feelepxyz quick question, what config needs to be added to give access to a private registry, and another thing, for us using the `--` some times works ok and some times still changes the registry from npm to yarnpkg.
