### ISSUE TITLE
Provide option to not rebase

### ISSUE THREAD

**Issue by oliikit** [dependabot/feedback#542]
Looks like there's a master ticket of rebasing options over in https://github.com/dependabot/feedback/issues/316 - but I wanted to open an issue here to not detrack that conversation.

Would it be possible to have the option to completely turn off rebasing? It throws some CI checks out of balance for certain repos, and it take a bit of manual work to get all checks passing.

**Comment by greysteil** [comment]
Would just disabling rebasing from you account settings work for you here? We'll probably move the option down to the repo level in time.

![image](https://user-images.githubusercontent.com/1144873/59962971-a1d42500-94e4-11e9-9975-f1d27d3e7a0c.png)

**Comment by oliikit** [comment]
Ah - I didn't realize that was an option. Repo level would be a great addition - but this should suffice.

**Comment by greysteil** [comment]
Awesome. Repo level is definitely coming!

**Comment by codebycliff** [comment]
Any idea how long before repo level rebasing is out?
