### ISSUE TITLE
The github username has been changed, causing the service to be unable to use the dependabot

### ISSUE THREAD

**Issue by addstone** [dependabot/feedback#544]
![image](https://user-images.githubusercontent.com/6231419/60070506-8cac0000-9749-11e9-9e2d-33b21bf817b2.png)
![image](https://user-images.githubusercontent.com/6231419/60070655-00e6a380-974a-11e9-8457-e9157650a299.png)

**Comment by addstone** [comment]
dependabot.com  找不到地方改变用户名

**Comment by addstone** [comment]
github 用户名改变后在 dependabot 未同步，导致不能使用相应的服务

**Comment by feelepxyz** [comment]
@addstone updated your username ✌️ It's usually synced every time we do an update on your account.

**Comment by addstone** [comment]
Thank you very much
