### ISSUE TITLE
Self hosting dependabot

### ISSUE THREAD

**Issue by hueneburg** [dependabot/feedback#547]
Hi, I was wondering if there is a way to self host dependabot. This would allow bigger organizations who want to keep their code on their own servers to use it as well.

Or am I just too stupid to find the documentation for that?

**Comment by greysteil** [comment]
Definitely not too stupid! We don't support GHE (or self-hosting) yet, but are planning to - there's an issue tracking it [here](https://github.com/dependabot/feedback/issues/485). In the meantime, there's also [Dependabot Script](https://github.com/dependabot/dependabot-script) which you can use to run locally, but lacks some of Dependabot's functionality.

Finally, if you'd like to help us prioritize GHE support please get in touch with your GitHub sales rep and tell them it's something you'd like to see.

**Comment by mraghurao92** [comment]
@greysteil  I  hosted dependabot for our enterprise github using **generic-dependabot-script**. 
It scans only maven central repo and update the dependencies but not our custom repos. Is this an expected behavior or am I doing anything wrong?.
