### ISSUE TITLE
Directory.Build.Targets with variables

### ISSUE THREAD

**Issue by leastprivilege** [dependabot/feedback#548]
We use this file

https://github.com/IdentityServer/IdentityServer4/blob/master/Directory.Build.targets

It makes use of variables. Dependabot does not seem to pick this file up.

Do I need to do anything special - or is this not supported yet?

**Comment by greysteil** [comment]
This wasn't supported but should be now!

**Comment by leastprivilege** [comment]
Would the next run pick that up automatically?

**Comment by leastprivilege** [comment]
Actually I just tried it. It doesn't find the targets file automatically.

Even removing and re-adding the repo always defaults to the 1st csproj file (but this is a mono repo with several projects + the targets file at the root).

<img width="692" alt="Screenshot 2019-07-02 09 24 37" src="https://user-images.githubusercontent.com/1454075/60492502-6a673480-9cab-11e9-8729-5e8001284587.png">

**Comment by greysteil** [comment]
If you hover over the `...` in that screen you'll see the other files Dependabot is monitoring. They are:

```
[
"/src/IdentityServer4/src/IdentityServer4.csproj",
"/src/Storage/src/IdentityServer4.Storage.csproj",
"/src/AspNetIdentity/src/IdentityServer4.AspNetIdentity.csproj",
"/src/AspNetIdentity/host/Host.csproj",
"/src/IdentityServer4/host/Host.csproj",
"/src/EntityFramework.Storage/src/IdentityServer4.EntityFramework.Storage.csproj",
"/src/EntityFramework/src/IdentityServer4.EntityFramework.csproj",
"/src/EntityFramework/host/Host.csproj",
"/Directory.Build.targets",
"/global.json"
]
```

**Comment by leastprivilege** [comment]
You are right! There is some room for improvement in this UI ;)
