### ISSUE TITLE
Allow unique commit message style for prod & dev deps

### ISSUE THREAD

**Issue by richardson-trevor** [dependabot/feedback#551]
As requested in https://github.com/dependabot/feedback/issues/443#issuecomment-506284543, opening a ticket to track for folks using conventional commits with semantic-release. 

### Summary
We are using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) in combination with [semantic-release](https://semantic-release.gitbook.io/semantic-release/) to automate cutting new versions of libraries. To make this work well with dependabot, we would like to have commits for prod dependencies use `fix` as a prefix, whereas for dev deps we want to use `chore`. https://github.com/dependabot/dependabot-core/pull/1227 got us a large way in the right direction in giving us the ability to configure, but configuration is static and thus we have no way to get the behavior we need to fully automate away these updates. If this could be supported, that'd be 👍 🎆 ✅ 🎉 .

Note: Initial conversation around some of this can be found in https://github.com/dependabot/feedback/issues/443

**Comment by greysteil** [comment]
Thanks for this. I've added a `prefix_development` option that will let you specify a different prefix for development dependencies to production ones. It's documented [here](https://dependabot.com/docs/config-file/#commit_message).
