### ISSUE TITLE
Error with 403 Forbidden

### ISSUE THREAD

**Issue by rafaelszt** [dependabot/feedback#552]
Hello,

Getting the following errors when accessing the website.
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
api-request.js:65 Uncaught (in promise) ApiBadResponse: GET https://api.dependabot.com/update_configs/[REDACTED]
    at https://app.dependabot.com/static/js/main.0d98dc86.chunk.js:1:6126
```

And when I try to access the a config page for a given repository it crashes with the same error.

Any help?

**Comment by feelepxyz** [comment]
@rafaelszt oh will take a look! Possibly something is out of sync with GitHub. Could you send the update config id to [support@dependabot.com](mailto:support@dependabot.com)?

**Comment by rafaelszt** [comment]
@feelepxyz seems like it's back on sync again, since it's working now. If you still wanna take a look at what was happening I can send you the id, otherwise we can close this.

**Comment by feelepxyz** [comment]
Nice one! Lets close for now, we sync a bunch of resources on each update so if you have any issues manually bumping could help fix things up.
