### ISSUE TITLE
Total number of open PRs on app homepage

### ISSUE THREAD

**Issue by oliikit** [dependabot/feedback#553]
It would be great to have the total number of open PRs on the app UI homepage so teams can see how much is on their plate when dealing with multiple repos.

Right now, you can kind of get away with a simple global search with your organization and the labels you use for Dependabot, but it still isn't the greatest.
https://github.com/search?utf8=%E2%9C%93&q=label%3Adependencies+state%3Aopen&type=Issues&ref=advsearch&l=&l=

(Seems like #268 is closely related, but the ask here is just total number of PRs open.)

Thanks again for all your work into this! ❤️ I really appreciate you all's involvement in the community.

**Comment by greysteil** [comment]
Thanks for the kind words. We'd love to integrate this into some kind of organization insights page within GitHub. Will likely be part of the GitHub integration once complete :-)

**Comment by oliikit** [comment]
Awesome, thanks for the update! 😃 I can go ahead and close this since it's on your roadmap. Can't wait!
