### ISSUE TITLE
Bulk Update Repo Settings

### ISSUE THREAD

**Issue by jpinkster** [dependabot/feedback#554]
We love this app and have it running for about 30 different active repos. Currently we have to open each repo settings if we want to change the default Reviewer and Update Schedule. I would be awesome if we could bulk edit some shared settings that would exist across all project types

**Comment by greysteil** [comment]
Thanks for the kind words! The plan on this one is to allow a global config file (or something similar), the same way you can have a `.github` repository with global GitHub settings. I'm not exactly sure how the details will work yet, but it will be part of the full integration with GitHub.

**Comment by jpinkster** [comment]
ok cool that would be nice to consolidate those settings into the repos `.github` folder!

**Comment by Piedone** [comment]
@greysteil can you tell what the `.github` repository is? We're desperately looking for a way to centralize managing some of the configs of our ~400 repositories, including dependabot "Data services" settings. I can't seem to find any information about having such a magic repository (I created one and nothing really seems special). I know about the `.github` folder.

**Comment by greysteil** [comment]
There are some docs focussed on code of conduct that describe how `.github` repos work [here](https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file). Basically it's like having a `.github` folder with those contents in every repo.

We're also working on org settings for GitHub's security features more generally - @infin8x is leading the work there.

**Comment by Piedone** [comment]
Ah, I see, thank you. This is great but unfortunately not quite what we're looking for. @infin8x could you point me to something where I can follow this effort?

**Comment by infin8x** [comment]
Hi @Piedone, unfortunately not - we don't have an externally-facing tracking issue for that work. For now, your best bet is to keep an eye on the [GitHub changelog](https://github.blog/changelog/).

**Comment by Piedone** [comment]
OK, thank you.
