### ISSUE TITLE
Overlapping text on the repos page

### ISSUE THREAD

**Issue by aaajanp** [dependabot/feedback#555]
On the repos page, if your config name is too long, it can overlap the "last checked" label. Adding some margin between the two would look better.

<img width="671" alt="Screenshot 2019-07-01 at 21 36 54" src="https://user-images.githubusercontent.com/20663698/60465441-ff851180-9c48-11e9-9ea3-3ec2c60e68a1.png">

**Comment by greysteil** [comment]
Thanks for the heads up. @feelepxyz can you take a look?

**Comment by feelepxyz** [comment]
@aaajanp nice catch! Deploying a fix now ✌️
