### ISSUE TITLE
Dependabot is failing to find the .csproj file

### ISSUE THREAD

**Issue by glennawatson** [dependabot/feedback#557]
I am getting a issue generated by dependabot that it can't find the csproj https://github.com/glennawatson/GitSMimeSign/issues/2

There is one at https://github.com/glennawatson/GitSMimeSign/blob/master/src/GITSMimeSign/GitSMimeSign.csproj

I am wondering why it's generating the following issue?

```
Dependabot couldn't find a .(cs|vb|fs)proj for this project.

Dependabot requires a .(cs|vb|fs)proj to evaluate your project's current .NET dependencies. It had expected to find one at the path: /src/<anything>.(cs|vb|fs)proj.

If this isn't a .NET project, or if it is a library, you may wish to disable updates for it from within Dependabot.

You can mention @dependabot in the comments below to contact the Dependabot team.
```

I added one originally for the `/` root folder then tried `/src` after the failure, hence the two issues in my repo.

**Comment by glennawatson** [comment]
https://github.com/glennawatson/GitSMimeSign/issues/1 and https://github.com/glennawatson/GitSMimeSign/issues/2

**Comment by greysteil** [comment]
It looks like the difficulty here is that your `.sln` file specifies the paths as being in the `GitSMimeSign` and `GitSMimeSign.Tests` directories, but the casing on the actual directories differs (it's `GITSMimeSign` and `GitSMimeSign.Tests`). Filenames on GitHub are case sensitive - if you update the casing to match then Dependabot should work as expected.

**Comment by glennawatson** [comment]
Ah thanks for that. One suggestion would be maybe to update that issue message? It's suggesting it can't find csproj without mention of the sln.

**Comment by greysteil** [comment]
Good shout - implemented in [this commit](https://github.com/dependabot/dependabot-core/commit/18b65b014e77feebce8bc08862b85e6f9ae5f600).

Thanks for giving Dependabot a try!
