### ISSUE TITLE
Bug: Commits entries need escaping to prevent unwanted modifications to local issues

### ISSUE THREAD

**Issue by etrepum** [dependabot/feedback#56]
The PRs that Dependabot generates do not properly escape the Commits entries, such that if they contain text such as `#1234` these issues will reference local issues, causing unwanted and confusing noise on those issues. It gets worse when the commit messages contain actions such as `Fixes #1234` and then closing the Dependabot PR will close some unrelated local issue.

The attached screenshot is of a Rubocop update PR with a tooltip showing a reference to an issue that is local.

![image](https://user-images.githubusercontent.com/26596/41486165-4c7f09e2-7098-11e8-8f8f-dc3f5df2a7b0.png)

**Comment by greysteil** [comment]
Eek, hadn't seen that before - will fix right away.

**Comment by greysteil** [comment]
Can you link me an example PR with the ref spam in it, please?

**Comment by etrepum** [comment]
It's in a private repo, would that still be helpful? https://github.com/playfig/website/pull/6227

**Comment by etrepum** [comment]
Here's a gist with the text from the PR https://gist.github.com/etrepum/7c4f0370b03fa0fe7da2bf72a8b8d44b

**Comment by greysteil** [comment]
👍, thanks.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/ceb2fc635451b9bcef9fcb711c670d2cc09c9ce5, which is deploying right now.

Very sorry about that - looks like this was an edge case that we missed. I'll add tests for it so it can't regress later, but wanted to get this deployed straight away.

**Comment by etrepum** [comment]
Thanks! The speed at which you acknowledged and fixed this issue is truly impressive :)
