### ISSUE TITLE
PHP: Dependabot updating lock file with other packages

### ISSUE THREAD

**Issue by tmcnicholls** [dependabot/feedback#560]
Dependabot opened 2 PRs on a repository today. One was to update PHPStan, the other for PHPUnit.

The composer.lock in both PRs also included package updates for packages not named in the title. The PHPStan PR also included the PHPUnit update, along with `beberlei/doctrineextensions` and `symfony/finder`. The PHPUnit PR also included the PHPStan update.

They also included an internal composer package which had changes merged to master in preparation for a scheduled release, which hadn't happened yet. This is normally ok in our workflow as we would just not composer update the internal package on develop/master until the parent feature branch is merged to repository which has this code as a dependency.

However, Dependabot also updated this internal package and it wasn't caught in code review. The result was that the internal package went to production with updates which were incompatible with the production codebase.

**Comment by greysteil** [comment]
@tmcnicholls can you @-mention dependabot in the bad PRs, so I can find them in our backend?

We shell out to Composer for the updated lockfile generation, and try to lock things down before doing so, but it sounds like we didn't do enough on that here.

**Comment by tmcnicholls** [comment]
@greysteil I've just mentioned you in both PRs.

Thanks

**Comment by greysteil** [comment]
Awesome, got the tags and will dig into it!

**Comment by joshhornby** [comment]
Hey @greysteil this has just happened to me as well. I'll mention you on the PR now.

**Comment by greysteil** [comment]
Thanks for that @joshhornby - we're working on a fix at https://github.com/dependabot/dependabot-core/pull/1332.

**Comment by joshhornby** [comment]
Hi @greysteil 

Thanks for working on this, has it been released? We've tried rebasing our PR's this morning and still seeing the same issue?

Thanks

**Comment by greysteil** [comment]
Doing it now :-)

**Comment by joshhornby** [comment]
Great news, can you let me know when it's live so I can rebase our PRs 👍

**Comment by greysteil** [comment]
Of course - it's deployed now :-)

**Comment by joshhornby** [comment]
Existing PRs still have the bug, even after a `recreate`. Is this to be expected? I can tag you in a PR is it would help?

**Comment by greysteil** [comment]
Drat. And sure thing. I'm actually on holiday this week, and maintaining this isn't mean to be my job, but I'll try. 😢

**Comment by joshhornby** [comment]
It can wait till next week, go enjoy the holiday. I've tagged the PR but please wait till next week to look into it.

**Comment by greysteil** [comment]
Not sure what stopped the fix taking effect previously, but I've just rebased the PR this was happening on and it's working s expected now. Thanks for your patience.
