### ISSUE TITLE
Automatically assign milestone

### ISSUE THREAD

**Issue by WyriHaximus** [dependabot/feedback#561]
Hey would it be possible to automatically assign a milestone to a PR Dependabot opens?

**Comment by greysteil** [comment]
Yes! You can already comment `@dependabot use this milestone` if you're not using config files. Not sure why they're not supported in config file - @feelepxyz any ideas? Would look something like:

```
default_milestone: 1
```

**Comment by WyriHaximus** [comment]
Neat! We also discussed this in the team, and what we are thinking of is picking the latest open milestone. (Which would be dynamic where the config file is static.) But we came to the conclusion such option would be rather complex to meet most of the desires patterns out there and that such thing wouldn't be something to burden an external service with.

**Comment by feelepxyz** [comment]
Ah yeah never added this because I was unsure how it would fit with other SCM APIs but we're probably not going to support another SCM any time soon so happy with `default_milestone: id` 🤠

**Comment by greysteil** [comment]
Ah cool, that makes sense. All coded up at https://github.com/dependabot/dependabot-backend/pull/1172 if you want to do the honours there @feelepxyz.

@WyriHaximus - makes sense. We won't support that, at least for now, but it's the perfect candidate for a GitHub Action.

**Comment by WyriHaximus** [comment]
@greysteil thinking the same time if we would have access to actions ;). But might actually write one on my own account first :)

**Comment by greysteil** [comment]
You'll have them pretty soon, I promise ;-)

**Comment by WyriHaximus** [comment]
Cool!
