### ISSUE TITLE
Dependabot comments are using incorrect github links

### ISSUE THREAD

**Issue by hlascelles** [dependabot/feedback#562]
The issue links in dependabot comments are links to the local repo, not the original dependency repo. See https://github.com/hlascelles/que-scheduler/pull/80 for an example.

This would just be annoying, but it is actually now somewhat dangerous, as merging that PR will automatically close the repository's unrelated (but same numbered) PRs. This has happened with the example above. When that PR was merged, this unrelated PR was closed automatically: https://github.com/hlascelles/que-scheduler/pull/18

**Comment by hlascelles** [comment]
Essentially, I think this is a regression of this bug: https://github.com/dependabot/feedback/issues/144

**Comment by greysteil** [comment]
Thanks for the bug report - fixed in https://github.com/dependabot/dependabot-core/commit/4c6485529379a5a5a52238bdfe7e732299b0f52c. (Looks like we'd never been sanitizing lowercase `gh-` references.)
