### ISSUE TITLE
"Dependabot commands and options" section uses outdated @ username

### ISSUE THREAD

**Issue by dpursehouse** [dependabot/feedback#563]
For example:

```
`@dependabot rebase` will rebase this PR
```

but the username is now `dependabot-bot`

**Comment by greysteil** [comment]
Hmm, that shouldn't be the username - `dependabot-bot` has been retired. You should be seeing either `dependabot[bot]` or `dependabot[preview]`, our comment handling listens for all variants (but the preferred name is just `dependabot`).

**Comment by dpursehouse** [comment]
OK, I just checked again.  The actual username I'm seeing on the PR is `dependabot-preview`, but if I start typing a comment the one I see in the autocomplete list is `dependabot-bot`.

<img width="379" alt="Screen Shot 2019-07-08 at 19 54 41" src="https://user-images.githubusercontent.com/836426/60805145-4085a480-a1ba-11e9-8ec0-7e43f12d669c.png">

**Comment by greysteil** [comment]
Ah, that's a different issue, and a wider GitHub one. GitHub doesn't currently suggest autocompletes for app names. @feelepxyz is working to fix that now, so no need to re-open this :-)
