### ISSUE TITLE
Remind users about notification settings

### ISSUE THREAD

**Issue by kevinhughes27** [dependabot/feedback#564]
I added Dependabot to a few of my personal projects that it turns out I wasn't actually watching on GitHub so I didn't catch the opened PRs for a bit. I might have missed it but it could be a good opportunity after configuring a repo to remind users to check their notification settings for that repo.

**Comment by feelepxyz** [comment]
@kevinhughes27 good point! I think we'll hold off on adding more features like this to the existing Dependabot Preview dashboard and instead focus on integrating Dependabot with GitHub where everything would be happening in the same interface so less chance of missing updates. We could also tailor the messaging based on the users actual settings.

**Comment by kevinhughes27** [comment]
Makes sense!
