### ISSUE TITLE
Sometimes sqash and merge does not work

### ISSUE THREAD

**Issue by mxschmitt** [dependabot/feedback#565]
Example PRs:
- https://github.com/react-bootstrap/react-bootstrap/pull/4008
- https://github.com/react-bootstrap/react-bootstrap/pull/4006

You then have to try it multiple times. Sometimes it's then working but sometimes also not.

I think, that this is due the GitHub merge technology, that they have to check the status again if it's mergeable. Maybe some kind of round robin implementation could fix this by trying it multiple times e.g. 3 against the GitHub API.

**Comment by feelepxyz** [comment]
@mxschmitt hopefully fixed now, we where drowning in webhooks for a while which was causing commands to queue up for ages. Let us know if this keeps happening!
