### ISSUE TITLE
Wiped Configurations

### ISSUE THREAD

**Issue by markwallsgrove** [dependabot/feedback#567]
We somehow managed to wipe all our of applications when using the ui with multiple users within a organisation.

**Comment by feelepxyz** [comment]
@markwallsgrove oh you mean all projects where removed from the Dependabot dashboard? Which organisation did this happen for?

**Comment by markwallsgrove** [comment]
@feelepxyz yes. The organisation was [Talis](https://github.com/talis).

**Comment by feelepxyz** [comment]
@markwallsgrove looks like you have three active repositories configured, one using config files so won't be configurable via the dashboard anymore.

Could you email [support@dependabot.com](mailto:support@dependabot.com) with the repository names you lost configuration for? I would like to confirm which private repos where affected. Will close this to continue via email.
