### ISSUE TITLE
How to tell Dependabot to make semantic pull requests

### ISSUE THREAD

**Issue by Richienb** [dependabot/feedback#568]
I've got Dependabot set up on most of my repositories along with Probot's Semantic Pull Requests bot.

How do I tell Dependabot to globally create semantic pull requests?

**Comment by feelepxyz** [comment]
@Richienb you can specify the commit message prefix and scope using config files: https://dependabot.com/docs/config-file/#commit_message

By default, Dependabot will attempt to detect your commit message preferences (including semantic commits) and use those based on the last commits from master.
