### ISSUE TITLE
Please clarify license for commercial use

### ISSUE THREAD

**Issue by acraven** [dependabot/feedback#569]
I would like to set-up dependabot for a client I'm working for, but I'm certain as to the license terms and cost of such use. The web-site and repo seem inconsistent.

**From https://dependabot.com/** Dependabot has been acquired by GitHub and is now free of charge
**From https://github.com/dependabot/dependabot-core/blob/master/LICENSE** You must limit use of this software in any manner primarily intended for or directed toward commercial advantage or private monetary compensation to a trial period of 32 consecutive calendar days.

**Comment by feelepxyz** [comment]
@acraven @greysteil is currently looking into our licenses with GitHub so best placed to answer but he's away this week at an offsite.

**Comment by greysteil** [comment]
@acraven the license on Dependabot Core is for using that library to self-host a dependency updating tool - it doesn't apply to using the hosted Dependabot service.
