### ISSUE TITLE
"Manage plan" takes me to 404 page

### ISSUE THREAD

**Issue by lipis** [dependabot/feedback#57]
https://github.com/marketplace/dependabot/upgrade/null/5231014

**Comment by greysteil** [comment]
Hmmm, that `null` looks deeply suspicious, doesn't it?! I'll get on it.

**Comment by greysteil** [comment]
Fixed! Sorry about that.

**Comment by lipis** [comment]
No problemas.. :) That was fast.. 🍻 🍺

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#381
