### ISSUE TITLE
pyproject.toml support

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#57]
There's a new thing in `python` world to manage dependencies: `pyproject.toml` and [`poetry`](https://github.com/sdispater/poetry).

Dependabot currently does not support this format of dependencies, do you have any plans on supporting it?

**Comment by adriens** [comment]
Ths would be great to get .NET/NUGET support...we could hence monitor [chocolatey](https://chocolatey.org/packages/schemacrawler) source packages :+1:

**Comment by greysteil** [comment]
.NET support is shipped! Merged PR is [here](https://github.com/dependabot/dependabot-core/pull/212) - feel free to comment there, but let's leave this issue to `poetry` comments.

**Comment by sloria** [comment]
@greysteil Now that .NET support is shipped, are there plans for pyproject.toml/poetry support?

I am evaluating package managers (pipenv vs. poetry) for a project at work, and support in dependency updater services (I'd love to use Dependabot!) will play into the discussion.

I don't mean to add pressure to implement this. We'd just like to make as informed decision as possible when choosing our package management tool.

**Comment by greysteil** [comment]
Yes - I want to add poetry next.

FWIW, I'm a bit worried about the fractured Python ecosystem on this one. I'd really like to dive in and help the Pipenv team write a resolver, which is the critical advantage that poetry has over Pipenv at the moment, but I'm not well placed to do so.

I'll try to add Poetry support over the next week, and let you know if I hit any issues.

**Comment by sloria** [comment]
> FWIW, I'm a bit worried about the fractured Python ecosystem on this one.

Same. The ecosystem is a bit in flux ATM, and there's still a lot of work to do (and not enough time!).

> I'd really like to dive in and help the Pipenv team write a resolver, which is the critical advantage that poetry has over Pipenv at the moment, but I'm not well placed to do so.

Good on you if you decide to contribute; seems like a major gap with pipenv.

FWIW, the reason I'm considering poetry is for other reasons: https://github.com/sdispater/poetry#install-command (see the last three subsections in the "What about Pipenv?" section).

Thanks so much for your work on this!

**Comment by greysteil** [comment]
@sloria, @sobolevn - just finished working on this, check out dependabot/dependabot-core#635. Will get it merged and deployed tonight / tomorrow morning.

**Comment by sobolevn** [comment]
@greysteil awesome! You can use https://github.com/mimesis-lab/mimesis-factory for integration tests, if needed. 

Will be happy to be an early adopter.

**Comment by sobolevn** [comment]
Merged! https://github.com/mimesis-lab/mimesis-factory/pull/26

@greysteil thank you for making this, you are awesome!
