### ISSUE TITLE
Only open PRs for releases that have been stable for X days/a week

### ISSUE THREAD

**Issue by samselikoff** [dependabot/feedback#571]
I was wondering if there's a way to tell Dependabot to only open PRs for new releases that have been "stable" for a week.

By a stable release, I mean one that has been out for a week (or X days), _with no subsequent releases since_.

The problem this addresses is that sometimes OSS maintainers release a few versions quickly due to bugs, or a new release of a lib will get several patch versions in the first few hours or days after release. It'd be nice to be able to ignore those early versions (e.g. 1.0.0) and just wait a day or two until the more stable version (e.g. 1.0.3) was released.

**Comment by RohanNagar** [comment]
Possible duplicate of

https://github.com/dependabot/feedback/issues/108

https://github.com/dependabot/feedback/issues/295

**Comment by samselikoff** [comment]
Yep, missed those! Thanks
