### ISSUE TITLE
Alert if dependencies are published without TFA

### ISSUE THREAD

**Issue by phallguy** [dependabot/feedback#572]
Was just reading about how the [strong_password gem was hijacked](https://withatwist.dev/strong-password-rubygem-hijacked.html) and thought it would be great if dependabot could alert if we depend on any gems/node modules/etc that are published by owners that _do not_ have TFA enabled on their account. Not sure if the package repos provide insight required to alert on this but I think it could be a valuable step to protecting the ecosystem.

**Comment by hmarr** [comment]
💯

We've been thinking a lot about this. In general, we want to verify that the artefact in the package registry comes from a legitimate maintainer, and none of the steps along the way have been compromised (GitHub / SCM, CI/CD, package registry).

Unfortunately it doesn't look like many (if any) registries make it easy for us to figure out if an account uses 2FA, but we've got some other thoughts about how we could achieve this in the future (e.g. something akin to docker automated builds, matching the contents of the package to what's in source control).

**Comment by phallguy** [comment]
Awesome. Love the work y'all are doing. thanks for the update! Feel fee to close.
