### ISSUE TITLE
Many lines deleted from yarn.lock file

### ISSUE THREAD

**Issue by aiham** [dependabot/feedback#573]
This might be related to #213 and #243 

Dependabot is creating a yarn.lock file which is different to what yarn client creates on dependabot's PR branch. It's deleting thousands of lines from yarn.lock just for bumping the patch version of a single dependency.

I hit this in a private repo so I've moved just the package.json files to demonstrate the issue. It's a yarn workspace project with multiple packages.

See https://github.com/aiham/dependabot-yarn-bug-repro/pull/1

This is what happens when I run yarn on that branch:

```
[11:55:22][~/dev/dependabot-yarn-bug-repro](dependabot/npm_and_yarn/lodash-4.17.14)$ yarn
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
...snip...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
$ patch-package
patch-package 6.1.2
Applying patches...
No patch files found
✨  Done in 29.85s.
[11:55:51][~/dev/dependabot-yarn-bug-repro](dependabot/npm_and_yarn/lodash-4.17.14)$ git diff --stat
 yarn.lock | 15160 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------
 1 file changed, 14504 insertions(+), 656 deletions(-)
[11:56:04][~/dev/dependabot-yarn-bug-repro](dependabot/npm_and_yarn/lodash-4.17.14)$
```

**Comment by aiham** [comment]
I think I've found the issue. It's only seeing the root package.json file, not the other packages. Maybe because they're nested 2 levels down?

![Screen Shot 2019-07-12 at 2 13 41 pm](https://user-images.githubusercontent.com/609164/61101964-47106680-a4af-11e9-8899-cff400fa2c7f.png)

**Comment by feelepxyz** [comment]
@aiham ah yeah we currently only fetch one level deep on globs so don't find the nested packages (would result in too many requests if we did).

Think this would work if you expanded the packages glob for each nested folder:

```
"workspaces": [
    "foo/bar/*",
    "foo/something-else/*"
  ],
```

Although, not sure about `patch-package` - does this rewrite your lockfile after install?

**Comment by aiham** [comment]
Thanks.
