### ISSUE TITLE
Not able to add GitHub Package Registry as Rubygems server (via GUI)

### ISSUE THREAD

**Issue by andreas-venturini** [dependabot/feedback#574]
Expected: I can add gemsource credentials for my org's GitHub Rubygems server 
Actual: Shows error *Config variables may not specify GitHub as the host*

![image](https://user-images.githubusercontent.com/4801917/61123142-e92a5180-a4a3-11e9-9886-53d42554cf58.png)

**Comment by feelepxyz** [comment]
@andreas-venturini ops that looks like a bug! Taking a look now.

**Comment by feelepxyz** [comment]
@andreas-venturini should be fixed now, want to give it another go?

**Comment by andreas-venturini** [comment]
Works now :+1: 

Thanks for the quick fix :)
