### ISSUE TITLE
No help link on config.yml errors

### ISSUE THREAD

**Issue by tdukart** [dependabot/feedback#576]
If there's an error in a config.yml file, there's no easy way to find the documentation. It would be useful if the GitHub issues and Dependabot UI would link to the help documentation so that users can easily recheck.

**Comment by greysteil** [comment]
I... have no idea why we're not linking to the docs in the error message. Sorry! Fixing now - thanks for reporting!

**Comment by greysteil** [comment]
New error message has the following text at the bottom:

Please update the config file to conform with Dependabot's specification using our [docs](https://dependabot.com/docs/config-file/) and [online validator](https://dependabot.com/docs/config-file/validator/).
