### ISSUE TITLE
dependabot stuck trying to create automated security fix

### ISSUE THREAD

**Issue by amclin** [dependabot/feedback#578]
Dependabot has been attempting to create an automated fix for a lodash security issue for 3 days with no resolution and no way to cancel or restart the process. There is no resulting PR in my project

![Screen Shot 2019-07-15 at 12 04 39 PM](https://user-images.githubusercontent.com/105728/61242269-20923b80-a6fa-11e9-806b-c5237e67e06f.png)

**Comment by feelepxyz** [comment]
@amclin oh yeah looks like it's stuck! Could you email the account/repo name to [support@dependabot.com](mailto:support@dependabot.com) so we can find the alert and debug?

**Comment by amclin** [comment]
I resolved it by manually updating dependencies shortly after noticing it. Since github doesn't preserve the notification history for security alerts and since I was updating several repos at the same time, I can't confidently identify which repo I encountered this in.

It was one of the following:
https://github.com/amclin/aem-packager
https://github.com/amclin/aem-packager-example
https://github.com/amclin/videojs-scene7
https://github.com/amclin/amc-drupal-theme

**Comment by greysteil** [comment]
OK, I'm going to close but please let us know if/when you see this again!

**Comment by jkhulme** [comment]
It's a private repo - but I've been seeing the same behaviour - https://github.com/38dgs/falc/network/alert/yarn.lock/lodash.mergewith/open

Dependabot says:
Generating an automated security fix
started on 11 Jul by dependabot

**Comment by greysteil** [comment]
@brrygrdn can you take a look at this one? Looks like it has the stuck behaviour you were attempting to fix.

**Comment by tiagomsmagalhaes** [comment]
@greysteil I also see this behaviour on /network/alert/yarn.lock/lodash/open , and I don't have lodash listed on package.json

**Comment by brandon-kyle-bailey** [comment]
Is there any scope for a fix for this? Encountering this problem on two of my repos:
[https://github.com/brandon-kyle-bailey/gatsby-starter-default](https://github.com/brandon-kyle-bailey/gatsby-starter-default)
[https://github.com/brandon-kyle-bailey/react-js-intro](https://github.com/brandon-kyle-bailey/react-js-intro)

**Comment by rebelagentm** [comment]
@brrygrdn Are @brandon-kyle-bailey's issues related to the same problem?

**Comment by johnhunter** [comment]
Seeing the same thing on two private repos this morning. Been "Generating an automated security update" for over 3 hours. Any indication what the issue is?

**Comment by Etheryte** [comment]
I used to have the same problem on [vue-auto-dropzone](https://github.com/Etheryte/vue-auto-dropzone), after multiple retries it finally resolved with the following error:

> Dependabot cannot create a pull request as one or more other dependencies require a version that is incompatible with this update.

If you're running into the same issue, try and see if you might be in a similar situation.  

As for Dependabot, it would be super helpful if the error message outlined what dependencies are incompatible.

**Comment by feelepxyz** [comment]
> As for Dependabot, it would be super helpful if the error message outlined what dependencies are incompatible.

Yep for sure, we've got this planned but is a while out.

A common example where Dependabot can't fix the vulnerability is, for example, npm sub-dependencies. Usually, there are multiple dependencies that have version requirements on the same sub-dependency (e.g. `kind-of: ^3.0.0` and `kind-of: ^1.0.0`) installing several different versions ranges but the vulnerability is only fixed in the latest major version (e.g. `6.0.3` for [kind-of](https://www.npmjs.com/package/kind-of)). In these cases dependabot can't update because the highest possible versions of `kind-of` are `1.1.0` and `3.2.2` which are both still vulnerable).

These types of issues render the above error message but it's quite a lot of work to figure out which dependencies prevented the update and provided a user-friendly error message.

**Comment by ben-z** [comment]
Same issue in https://github.com/unicorns/rainbows for dependency `minimist`:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/5977478/78515237-15e56e00-7783-11ea-9481-23a92ad166d3.png">

**Comment by ollien** [comment]
Same issue with the same module as @ben-z in https://github.com/ollien/pipes and https://github.com/ollien/slime-mold/

**Comment by DanteAlighierin** [comment]
Same problem - https://github.com/DanteAlighierin/VueCRM
![image](https://user-images.githubusercontent.com/49035889/83421681-28052500-a431-11ea-9efc-8fcd19bce5be.png)

**Comment by DipanshiB** [comment]
I've been having the same issue with multiple repositories. Depend-a-bot gets stuck for hours and no PR gets generated.
