### ISSUE TITLE
Auto-merge bypassing the reviews

### ISSUE THREAD

**Issue by tristanbes** [dependabot/feedback#579]
Hello,

I'd like to propose the idea of a feature enabling dependabot to bypass the "Require pull request reviews before merging"

The only way to get dependabot to merge with this settings activated consumes a lot of human time accross 300 repositories full of JS dependencies.

**Comment by greysteil** [comment]
The solution we're currently proposing for this one is to have an "auto-approve" bot that marks Dependabot PRs as approved immediately. We built a GitHub action for it [here](https://github.com/marketplace/actions/auto-approve).

We're also working with the branch protection team to allow you to specify apps that are allowed to push to branches (the same way you can specify users that are). There's an issue tracking that [here](https://github.com/dependabot/feedback/issues/86).

**Comment by tristanbes** [comment]
Good to know you're on it :) Thanks

**Comment by tristanbes** [comment]
@greysteil is that possible that your approve "Yproximite" organization to join the beta for Github Actions please ? I need this github action :D

**Comment by greysteil** [comment]
Sure thing - you *should* be on the beta now :octocat:

**Comment by tristanbes** [comment]
Thanks :). I'll close this issue since your Github Action should solve this ;)
