### ISSUE TITLE
How does CI detection for compatibility work?

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#58]
I understand from [this](https://dependabot.com/compatibility-score.html) page that dependabot looks at CI results and excludes repos with no CI. 

My question is how does dependabot classify a repo as having CI?

All of my repos are built with a Jenkins instance which triggers on webhooks for each PR or commit to a feature branch, master or develop. Very occasionally I see badges for 100% compatible but my CI build failed. Perhaps this is just some rounding up like 99.99% passed and that's being rounded up to 100. But I was curious about whether dependabot actually knows my repos have CI.

If it's relevant the repos contain a `Jenkinsfile` at the project root and also the Jenkins instance is setting the overall status via the Github API

**Comment by greysteil** [comment]
Hmmm, Dependabot should be picking up those CI runs. Can you give me an example repo name (either here or via email) and I'll check that it is?

The CI score excludes any cases where tests were failing prior to the PR being created, so it could be that, too.

**Comment by davidgoate** [comment]
@greysteil i referenced you on one PR, i'll try to find another. As I said, i think it's rare. Perhaps I'm wrong that the base branch (in my case develop) had a passing CI status at the time the PR was created. I'll try to keep a closer eye out.

**Comment by greysteil** [comment]
Just saw - taking a look now!

**Comment by greysteil** [comment]
Debugged with @davidgoate - in this case it was because CI was erroring on the base branch on the PR.
