### ISSUE TITLE
PHP: Dependabot suggests incompatible packages

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dependabot/feedback#580]
Hey there,

Dependabot seems to be ignoring my PHP version constraint in my `composer.json` file and suggesting packages which are PHP 7+ when I say my package is compatible with `>=5.6.0`: https://github.com/ElvenSpellmaker/PipeSys/blob/master/composer.json#L19

As you can see the PR here suggests 4.3.1: https://github.com/ElvenSpellmaker/PipeSys/pull/18

And in their `composer.json` it shows it can't run on PHP 5: https://github.com/phpDocumentor/ReflectionDocBlock/blob/4.3.1/composer.json#L13

Shouldn't it _not_ suggest packages which it can know will break?

Thanks =)

**Comment by greysteil** [comment]
Good shout. Fixed by https://github.com/dependabot/dependabot-core/commit/0577301987e1ef6b6f370d714f8cc5596652b935, which I'll get deployed today.

**Comment by ElvenSpellmaker** [comment]
Thanks! I'll check it out, will I need to close the current PR from the bot?

**Comment by greysteil** [comment]
It should close it automatically :-)

**Comment by ElvenSpellmaker** [comment]
Excellent, thanks!

**Comment by ElvenSpellmaker** [comment]
@greysteil Did you manage to get the deploy done in the end? The PR is still open. =)
