### ISSUE TITLE
Unexpected auto merge after `cancel merge`

### ISSUE THREAD

**Issue by atomatt** [dependabot/feedback#583]
(We only enabled dependabot last week so apologies if we've misunderstood how it should be used.)

dependabot created a PR that failed CI and required code changes, as well as a couple of rebases due to other merged PRs.

Our test coverage is good but it was Friday afternoon and I was not 100% confident with the changes so I decided to manually merge after the weekend. I posted a `cancel merge` comment to "cancel a previously requested merge and block automerging"; dependabot acknowledged the comment. It seemed we had control over the merge.

However, after a colleague accepted the PR, I resolved another merge conflict, and CI passed, dependabot surprised us by auto merging anyway.

Did I misunderstand the `cancel merge` documentation? If so, is there another way to tell dependabot that a human will merge a specific PR.

The PR is https://github.com/bitnami/stacksmith/pull/2225 if that helps.

**Comment by greysteil** [comment]
Just looked this one up in our database. Somehow that PR has got `merge_requested: true` against it, which should only happen when someone comments `@dependabot merge`. Is there any chance someone did that *after* that `cancel merge` request was made (or at about the same time - could be the result of a race)? That's the reason Dependabot ended up performing the merge - it also had `automerge_block_requested` set.

**Comment by atomatt** [comment]
afaict, no-one said `@dependabot merge` at any time. The sequence events is basically:

1. I said `@dependabot cancel merge`.
2. dependabot added a :+1: to the `cancel merge` comment.
3. I pushed an additional commit (I think I also rebased).
4. My colleague approved the PR
5. I resolved a new merge conflict and pushed again
6. CI passed
7 dependabot auto merged the branch.

**Comment by greysteil** [comment]
Ooooh, I bet it came from the approval. Let me dig into that.

**Comment by greysteil** [comment]
OK, it's definitely that. You have `Treat PR approval as a request to merge` set on the Bitnami account, so when your colleague approved the PR that was treated as a new request to merge, and superseded the previous `cancel merge` comment.

I think that's a little too subtle, and only an explicit `@dependabot merge` command should now have caused it to merge - I'll update our logic accordingly.

**Comment by greysteil** [comment]
Implemented. Thanks for flagging this!
