### ISSUE TITLE
[PHP] Major and Minor updates constraints in composer.json

### ISSUE THREAD

**Issue by carusogabriel** [dependabot/feedback#587]
Hello there 👋 

Is there an away to configure Dependabot to create the following changes in `composer.json`:

```diff
-        "foo/bar": "^0.1",
+        "foo/bar": "^0.6",
```

instead of:

```diff
-        "foo/bar": "^0.1",
+        "foo/bar": "^0.1 || ^0.6",
```
? I think the techinical term is `replace range` instead of `increase range`.

I think it is something related to https://dependabot.com/docs/config-file/#version_requirement_updates, right? If it is nos implemented yet and nobody is working on, can you guide me so I can create a PR for this? ☺️ 

Thanks ❤️

**Comment by greysteil** [comment]
Using `increase_versions` should fix that - I've just updated the docs :-)
