### ISSUE TITLE
pip-tools and "lockfiles updates only"

### ISSUE THREAD

**Issue by David-Guillot** [dependabot/feedback#589]
Hi there,

`pip-tools` user here.

Requirements files structure:

* Multiple "source" requirements files named `src-requirements-something.in`
* Multiple "lock" requirements files names `requirements-something.txt`

Our workflow:

* In our `src-requirements-something.in` files, we use:
  * `==X.Y.*` for big/critical dependencies like Django that follow SemVer and handle LTS versions
  * `==X.*` for smaller dependencies
* We want a bot that suggests updates to lock files while keeping compatibility with what we humanly decide in source files

So we configured Dependabot with `Only lockfile updates` option enabled, and here is what we get:

* All files are detected :+1: (a very quick indicator of "source" and "lock" files would be comforting)
* But **absolutely no update has been suggested**, while running `pip-compile -U src-requirements-something.in` shows many updates

Did we do something wrong?

I understand the complexity of keeping compatibility with source files, since Dependabot doesn't know the logic of which source file generates which lock file. But if Dependabot works on lock files only, at least it should open too many PRs, no?

Thanks in advance,

**Comment by greysteil** [comment]
Doesn't sound like you did anything wrong! Want me to take a look into the repo? I need to know which one it is to do so - you can email me on support@dependabot.com or just post the name here.

**Comment by greysteil** [comment]
OK, this should be fixed by https://github.com/dependabot/dependabot-core/commit/d14643d2b8ea3e49c0b2d5a353a7c431850ee1fb which I'll get deployed in the next 30 minutes. Thanks for reporting it!

**Comment by David-Guillot** [comment]
Hi @greysteil ,

While i'm amazed by your reactivity and your velocity, the fix didn't make things better for our repo :confused: . No PR has been opened. Maybe it hasn't been deployed yet, in which case displaying the `dependabot-core` version on the dashboard would make things clearer ;)

**Comment by greysteil** [comment]
Deploy got delayed by yesterday's `pip` and `pip-tools` updates, which changed a bunch of internal APIs. Should be working now.

**Comment by David-Guillot** [comment]
Yes!! Seeing PRs arriving right now, thanks a lot!! Great service :+1:
