### ISSUE TITLE
Global GitHub Organisation Settings

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#59]
I did perviously mention this in another PR: https://github.com/dependabot/feedback/issues/24

>  it would be awesome to be able to configure a team or people as reviewers and assignees globally for the organisation per technology, e.g. java pulls, docker pulls, JS pulls for ALL repos in the org. I really love the innovative chat bot nature of just tagging @dependabot in the PR but the downside is for each repo i need to first wait for the first PR to arrive, manually assign reviewers and assignees and then type two things to dependabot. Great for one or two repos, less cool for 10+. Also easy to forget on new repos we set up which would mean that if we are filtering on PR's assigned to us or marked for review they get missed. Just a suggestion ;)

This is becoming a slightly bigger issue for me with a growing number of repos.

In addition, it'd be great if there were a way to do this so that dependabot would just start doing this for all repos in my org (if i give it permission). It's a small step -  but it adds friction each time a new repo is created to remember to go in and turn on dependabot and also remember to add the technology choices when they are added, e.g. today I create a new blank repo for a Java API (but can't yet set up dependabot as it can't find a `pom.xml`), tomorrow I add a `pom.xml` so I can add Java bumping, tomorrow I add a `Dockerfile` and need to remember to add `Docker` and so forth.

Ignoring technical limitations, if I could dream the perfect UX on this from my personal point of view. I'd sign up for dependabot, give it access to my org on github, set some global things like which techs i want (java, docker, javascript etc), who will review PR's and then click go - at which point dependabot will manage all existing and future repos automatically with no manual intervention unless I want to deviate from this norm (e.g. excluding a repo).

Might be a tricky one, but I thought I'd share my opinion on what could make dependabot even more awesome (for me).

**Comment by davidgoate** [comment]
May be some feature overlap here with: https://github.com/dependabot/feedback/issues/52

**Comment by greysteil** [comment]
Thanks @davidgoate. @petehamilton - food for thought in terms of re-designing onboarding!

**Comment by greysteil** [comment]
We've just shipped support for [config files](https://dependabot.com/blog/introducing-config-files/), which I think a good solution here. 🎉
