### ISSUE TITLE
Use `pipenv lock` with the `--pre` option when necessary

### ISSUE THREAD

**Issue by dpursehouse** [dependabot/feedback#592]
I added a new dependency on `black` in my python project, which uses `pipenv`, and dependabot has reported that it can't install it. See https://github.com/dpursehouse/pygerrit2/issues/86

This seems to be because `black` is a "pre-release" dependency.  I'm not 100% sure what that means -- I'm able to install it fine with `pip`, but `pipenv` chokes on it.  I've been able to get around it by using the `--pre` option as mentioned in the error message.

**Comment by greysteil** [comment]
Looks like this is a pipenv level problem - see https://github.com/pypa/pipenv/issues/1760. Pinning to a specific version in your `Pipfile` will allow Dependabot to work.

**Comment by dpursehouse** [comment]
Thanks for the hint.  I'll look into this tomorrow.

**Comment by dpursehouse** [comment]
It looks like this resolved itself without me having to do anything.
