### ISSUE TITLE
Elixir 1.9.X

### ISSUE THREAD

**Issue by kassio** [dependabot/feedback#597]
Getting the following error with Elixir 1.9.X:

<hr>

Dependabot can't evaluate your Elixir dependency files.

As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.

The error Dependabot encountered was:

```
** (UndefinedFunctionError) function System.get_env/2 is undefined or private. Did you mean one of:

      * get_env/0
      * get_env/1

    (elixir) System.get_env("WARNING_AS_ERRORS", "false")
    mix.exs:42: Budgeting.MixProject.warnings_as_errors/0
    mix.exs:12: Budgeting.MixProject.project/0
    (mix) lib/mix/project.ex:738: Mix.Project.get_project_config/1
    (mix) lib/mix/project.ex:110: Mix.Project.push/3
    (stdlib) lists.erl:1263: :lists.foldl/3

{"error":""}
```

You can mention @dependabot in the comments below to contact the Dependabot team.

**Comment by greysteil** [comment]
@kassio can you check if this is now fixed?

**Comment by kassio** [comment]
Yes, thanks. It's fixed.
