### ISSUE TITLE
Bot is overwriting github dependencies with npm dependencies 

### ISSUE THREAD

**Issue by PascalSalesch** [dependabot/feedback#598]
[https://i.imgur.com/F9ZOYSR.png](https://i.imgur.com/F9ZOYSR.png)

The `github:sale-sh/api-client#development`-syntax seems to be working fine
but not the `git+ssh://git@github.com/sale-sh/api-client.git`-syntax

**Comment by greysteil** [comment]
Looking into this now. I there a particular repo you're seeing this on? If you give me the name here (or in an email to support@dependabot.com) I'll use it to replicate and ensure this is fixed.

**Comment by rebelagentm** [comment]
👋 @PascalSalesch Did this get resolved?

**Comment by PascalSalesch** [comment]
atleast I didn't experience it anymore after this one time
