### ISSUE TITLE
Github search friendly config filename

### ISSUE THREAD

**Issue by chenrui333** [dependabot/feedback#599]
Right now, the config filename is `.dependabot/config.yml`, but it is not quite easy to do the search wile Github search syntax, `filename:config.yml`.

I wonder if we want to do the config filename like `.dependabot.yml` within `.github` folder or `.dependabot/dependabot_config.yml`.

**Comment by greysteil** [comment]
We're planning to start supporting `.github/dependabot.yml` for the fully-integrated GitHub version of Dependabot (but don't support it yet). To avoid any conflicts with Dependabot Preview we can't make that change yet, though.

In the meantime, try https://github.com/search?utf8=%E2%9C%93&q=path%3A.dependabot+filename%3Aconfig.yml&type=Code&ref=advsearch&l=&l=

**Comment by chenrui333** [comment]
That is pretty cool search syntax, did not know that before. 

Thanks for the update on the github version of Dependabot progress.
