### ISSUE TITLE
Badges!

### ISSUE THREAD

**Issue by greysteil** [dependabot/feedback#6]
Badges provide a great way to see whether a projects dependencies are up-to-date at a glance. With Gemnasium no longer operating, it would be particularly nice to provide them.

**Comment by styfle** [comment]
Beyond badges, it would be good to link to a page showing which dependencies are out of date. This could replace https://david-dm.org

**Comment by adriens** [comment]
Yes, please, badges and dashboard for reports on dependencies

**Comment by adriens** [comment]
You can get a kind of dashboard by using advanced Github issue earch, for example, in my case :

The closed PR i had from dependabot on all my repos :

`org:adriens is:pr author:app/dependabot is:closed`

**Comment by adriens** [comment]
> Stay with me!

Sure we do ! :smile_cat:

**Comment by netzulo** [comment]
i need this for my python projects :'(

**Comment by greysteil** [comment]
I'm working on it! Starting out with a badge for viewing the SemVer compliance of a dependency - check it out [here](https://dependabot.com/compatibility-score.html?dependency-name=puma&package-manager=bundler&version-scheme=semver). PR to shields.io [here](https://github.com/badges/shields/pull/1734). Once that's working I'll start thinking about a badge to show whether you have any out-of-date dependencies.

**Comment by adriens** [comment]
Hey @greysteil , this is even around 1000 times much better than expected dude !!!  

![2018-06-16 18_47_39-dependabot compatibility score](https://user-images.githubusercontent.com/5235127/41496900-e4af09da-7195-11e8-81ea-16e1c7c521fd.png)

**Comment by simlu** [comment]
Very much looking forward to this!

**Comment by simlu** [comment]
I'm the creator and maintainer of [js-gardener](https://github.com/simlu/js-gardener). Currently in the process of switching from greenkeeper to dependabot. It would be super nice to have even just a simple "enabled" badge. Outdated dependency check would be awesome as well obviously as it would replace [david-dm](https://david-dm.org/). Looking forward to your upcoming work here!

**Comment by simlu** [comment]
@davidkassa I'm not sure I understand. Can you clarify?

**Comment by adriens** [comment]
Where should we pass the

```
@dependabot badge me
```

to get the job done ?

**Comment by greysteil** [comment]
If you comment that on any Dependabot PR then it will give you the code to add an "enabled" badge to your README 🙂.

(Sorry, should have commented that here a while ago - was waiting until I'd got a badge for outdated dependencies, too, but then got pulled onto something else!)

**Comment by styfle** [comment]
@greysteil You might want to submit a PR to Badgen too which is a newer, faster version of shields https://github.com/amio/badgen-service

**Comment by greysteil** [comment]
Will do - no harm in being covered there, and if it's quicker it might be worth me switching. Thanks for the heads up.

**Comment by greysteil** [comment]
I opted against repo name as the identifier as it would create a minor security issue (you could use it to find the names of private repos an organisation that was using Dependabot owned). Instead the identifier in there is the GitHub repo ID, which you can get from the https://api.github.com/repos/your/repo. Apologies it’s a faff for non-enabled repos - I couldn’t think of anything more convenient that was still secure.

**Comment by simlu** [comment]
I think the main problem I have with this is that:
(1) it is impossible to figure out if a badge actually belongs to a given repo by looking at the code only
(2) you can't predict the badge url for public repos (required for my use case)

I agree with your reasoning, however the **industry standard** seems to be to use an api key for private repos (travis and circle both do this). This is way more convenient since it solves (1) and makes (2) possible for public repos.

Looking forward to you thoughts on this! Thank you very much for all your work!

**Comment by greysteil** [comment]
Hmmm, I don't have an obvious answer for this.

Adding API keys to Dependabot would be quite a lot of work - I appreciate CircleCI and Travis do it, but they're both teams of 50+ people and I'm one guy! Unless there are other compelling reasons for Dependabot to have them I'm not sure it's worth it for just this case.

Can you think of any other way we could get around the security issue here? One way, for public repos, would be to allow the repo name to be passed as the identifier for public repos only. That would at least solve (2), but could be confusing without some accompanying work for "unknown" badges (a helpful show page explaining, perhaps.

**Comment by simlu** [comment]
@greysteil 

I think a good solution would be 
(1) use the repo name for the badge instead of the repo id
(2) when the repo is private require the repo id as an "api key"

This would allow you to later replace the repo id with a proper api key as well as solve my two issues I mentioned above.

E.g. circle is doing it as `https://circleci.com/gh/COMPANY/REPO.png?style=shield&circle-token=TOKEN_HERE` (where the circle-token is only needed for private repos)

You could do that the exact same way except use the repo id instead of a generated custom token.

**Comment by davidkassa** [comment]
Great addition. Will worth the four hours, if you ask me.

**Comment by greysteil** [comment]
@styfle - FYI, I switched to Badgen and am super happy with it. Thanks for the recommendation!

**Comment by greysteil** [comment]
Glad you like it! And yeah, I wouldn't dream of creating a dependencies badge that isn't backed by a status page - getting that status page built is the blocker, but I'll get the one it!

**Comment by vip32** [comment]
can we somehow test drive the new badges?

**Comment by greysteil** [comment]
Yes! @feelepxyz is doing the status page work over the next week or so - we'll let you know when it's done.

**Comment by xRahul** [comment]
Hey @greysteil Is the status page done?

**Comment by greysteil** [comment]
Not yet - we crunched on config files in the end. Show pages for update configs (with all their dependency details) likely to be the next thing we work on, though 🙂

**Comment by noneissome** [comment]
What's the status on this issue?

**Comment by greysteil** [comment]
Still the same as the above, I'm afraid.

**Comment by yss14** [comment]
This is now working. Just comment on a dependabot PR with `@dependabot badge me` and you will receive markdown for a personalized badge.

**Comment by greysteil** [comment]
We're going to have a really big update on the show view for update configs soon (likely in May), but I don't want to spill the beans on it yet. 🙂

**Comment by simlu** [comment]
@yss14 Can you clarify what is exactly working? Are dependency status pages available now?

**Comment by yss14** [comment]
@simlu Sorry, I must have overseen a comment above where this was already mentioned. I related to the plain [![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=yss14/musicshare)](https://dependabot.com) badge.

**Comment by simlu** [comment]
@greysteil I'm counting the days :)

**Comment by AndrewLeedham** [comment]
Is it possible specify the style of the badge, like https://badgen.net or https://shields.io. I tried `&style=flat-square`, but that doesn't seem to be supported.

**Comment by greysteil** [comment]
OK, so the update here is that Dependabot has been acquired by GitHub! As a result, we're going to be working with the dependency graph team to integrate a view of how up-to-date you are there, add details of any dependencies you're ignoring, etc. It's a big project! But given that full integration with GitHub is the way that we're going I'm going to close this.

@AndrewLeedham that's not configurable at the moment, but behind the scenes we're using badgen to generate Dependabot's compatibility score badges, so it wouldn't be too tricky for me to change for `dependabot-preview`, at least. Which badge were you wanting to style?

**Comment by adriens** [comment]
Congrats @greysteil  !!! 👏 👏 👏  Your product trully rocks, it was just a matter of time 🙏

**Comment by AndrewLeedham** [comment]
Thanks @greysteil. The flat square style, perhaps passing subdomain forward would work with badgen?

**Comment by jsmiith** [comment]
Congrats!!!

**Comment by AndrewLeedham** [comment]
@greysteil Any updates on this?

**Comment by greysteil** [comment]
None, and I have too many things on my plate to promise anything. 😞

There is some good news, though - Dependabot returns JSON from its badge endpoints if requested, so it should be possible to add the code directly to badgen...

**Comment by AndrewLeedham** [comment]
> None, and I have too many things on my plate to promise anything. 😞
> 
> There is some good news, though - Dependabot returns JSON from its badge endpoints if requested, so it should be possible to add the code directly to badgen...

Oooh that is good news. Can you point me in the right direction of that endpoint, is it documented anywhere?

**Comment by greysteil** [comment]
Sure can - it's exactly the same API as the badges themselves come from, just with the accept header set to `application/json`.

So [![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=yss14/musicshare)](https://dependabot.com) would be https://api.dependabot.com/badges/status?host=github&repo=yss14/musicshare. For private repos you have to add `&identifer=<the github repo's ID>` onto that.

**Comment by AndrewLeedham** [comment]
@greysteil Thanks for this, I'll work on implementing it into badgen. What are the possible values for `host`?

**Comment by greysteil** [comment]
Just “github”, and now that they own Dependabot that’s unlikely to change!

**Comment by AndrewLeedham** [comment]
:rocket: I implemented the dependabot badge in badgen and it has been merged https://github.com/badgen/badgen.net/pull/288 use https://flat.badgen.net/dependabot/user/repo?icon=dependabot :smiley:

**Comment by greysteil** [comment]
BNice one @AndrewLeedham! Thanks 😄
