### ISSUE TITLE
php/Syphony/drupal support

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#60]
Hi,

i wonder if there could be some guidelines on how to monitor drupal modules/dependencies ?...especially for security updates. As it is based on php i guess something could be done ?

**Comment by adriens** [comment]
...or map it on drush commands ?

**Comment by greysteil** [comment]
If you're using Composer to manage your drupal dependencies then everything should just work. There's an article on how to do so [here](https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies).

**Comment by adriens** [comment]
Thanks a lot for your guidelines : this is really very interesting, i'm taking a closer look at it. :+1: This cloud allow us to make a big step forward in security !

**Comment by adriens** [comment]
@greysteil : i close the issue. I'll let you know if we need some guidelines on how to set it up.
