### ISSUE TITLE
NuGet version range is ignored

### ISSUE THREAD

**Issue by vslynko** [dependabot/feedback#612]
Prerequisite: I fix the nuget package version to a single version, because of a license restriction.
```
<PackageReference Include="Aspose.Words" Version="[17.9.0]" />
```
Nevertheless the following PR was created
![image](https://user-images.githubusercontent.com/12891283/62115810-59fda600-b2b9-11e9-872f-b52bd1f78592.png)

#479 related.

**Comment by greysteil** [comment]
This is deliberate - Dependabot will update your project file with new ranges, and it's hard to see how it would work with NuGet if it didn't. In this case you perhaps want to ask Dependabot to ignore that dependency?
