### ISSUE TITLE
Is dependabot accepting open-source license of repo to which it contirbutes?

### ISSUE THREAD

**Issue by planger** [dependabot/feedback#615]
This may sound a bit strange, but since dependabot is a contributor to many open-source projects (recently including a few of ours), I was wondering whether there is a definition / terms of use somewhere of whether dependabot agrees to any open-source license of the projects to which dependabot contributes.

We use CLA assistant to make every contributor confirm that he/she agrees to publish his/her contribution under the terms of the open-source license of the respective projects. Tracking the contributors and having them agree explicitly to the terms is important in some scenarios, e.g. if you want to put the project under the IP control of some open-source foundations at some point. Of course, dependabot didn't sign the CLA, while still being a very active and friendly contributor :)
I know, I can whitelist dependabot so that CLA assistant won't complain, but I wanted to ask what the implications regarding its contributions are, since I didn't find anything specifically defined in that matter.

Thanks!

**Comment by greysteil** [comment]
We clarified this in the "Intellectual Property" section of our [terms](https://dependabot.com/terms/) a few months back.

> As part of providing the Service, Dependabot generates software code contributions to the customer's repositories. For the avoidance of doubt, Dependabot grants to each customer a non-exclusive, worldwide right or license to perform, display, and use the contributions and any content contained in, accessed by or transmitted through Dependabot to customer's repositories.

**Comment by planger** [comment]
Oh, I missed that. Thanks a lot for clarifying!
