### ISSUE TITLE
List equivalent image tags in Docker PR

### ISSUE THREAD

**Issue by GaryGSC** [dependabot/feedback#616]
**Feature request:** List equivalent image tags in Docker PR

---

I'll start by explaining my use case.

I'm using Dependabot to update my images that are based on [`node`](https://github.com/nodejs/docker-node). Node has [multiple release lines](https://nodejs.org/en/about/releases/). Right now, [they have an `lts` tag and a `current` tag](https://hub.docker.com/_/node/) representing `10.16.0` and `12.7.0`. I'd like to stay on the LTS line. Right now, my options to do that using Dependabot aren't great.

If I use `FROM node:10.16.0` in my Dockerfile, I understandably get a Dependabot PR trying to bump node from `10.16.0` to `12.7.0`. While that's nice, that would require me to move from the LTS line to the current line, which has less of an expectation of stability.

So, what are my options? `FROM node:10.16.0` doesn't work. What if I use `FROM node:lts`? Well, then I'd be subject to a moving version number, possibly across major versions. They treat that tag a lot like `latest`. That's out of the question.

I can pin my docker images using a digest, using something like `FROM node:lts@sha256:523f767f8907f002316d3334bdb9d1154c7c6f6157c7aed3de5305726a963616`. [Dependabot supports this](https://github.com/dependabot/dependabot-core/blob/master/CHANGELOG_ARCHIVE_2017_TO_2018.md#v06922-3-september-2018)! That signals to Dependabot that I want to stay on the `lts` line, while avoiding any issues with mutable tags and moving version numbers. Yay! That's great and all, but now it's not very clear on if a PR represents a change from:
- `10.16.0` to `10.16.0` with some small underlying base image updates
- `10.16.0` to `10.16.1`
- `10.16.0` to `12.7.0` (in the hypothetical case that 12.7 went LTS)

---

What would I want?

The PR to indicate that it represents a change to an image that's been tagged
`10.16.0-stretch`, `10.16-stretch`, `10-stretch`, `dubnium-stretch`, `lts-stretch`, `10.16.0`, `10.16`, `10`, `dubnium`, and `lts`.

Then, I'd be able to tell what a change from `node:lts@sha:AAAA` to `node:lts@sha:BBBB` actually means.

**Comment by greysteil** [comment]
Interesting. Have you considered using `FROM node:10.16.0@sha256:523f767f8907f002316d3334bdb9d1154c7c6f6157c7aed3de5305726a963616` and then telling Dependabot to ignore the major version update if it suggests moving to `12.7`? I think that would be the clearest way to have everything described in your Dockerfile.

**Comment by GaryGSC** [comment]
I like that idea. Would I get a PR trying to bump it to `10.16.1` if I did that?

**Comment by greysteil** [comment]
Absolutely - you can ask dependabot to `@dependabot ignore this major version` until it gets down to 10.x.x.

**Comment by GaryGSC** [comment]
Oh, cool. That's a pretty decent solution that handles the majority of the problem. Thank you!

**Comment by GaryGSC** [comment]
My particular case is basically resolved, then. 🙂

If you'd like to keep this issue open, feel free. Bumping from one SHA to another isn't very clear.

**Comment by greysteil** [comment]
Awesome. I'm going to close, but agree we could use some docs on this one!
