### ISSUE TITLE
Go Modules support is outdated

### ISSUE THREAD

**Issue by jamezrin** [dependabot/feedback#617]
I issued an underlying issue in gomodules-extracted repo, see it for context https://github.com/dependabot/gomodules-extracted/issues/2

But basically, the current implementation of go modules is outdated and there are things that were fixed in it.

**Comment by jamezrin** [comment]
Some extra info just in case https://github.com/dependabot/gomodules-extracted/issues/2#issuecomment-516989437

**Comment by hmarr** [comment]
Updated in v0.111.40. Thanks for reporting.
