### ISSUE TITLE
Development dependency PRs to merge automatically - doesn't merge deeper dependencies?

### ISSUE THREAD

**Issue by rdunlop** [dependabot/feedback#619]
If I have the "Development dependency PRs to merge automatically" setting set to "All updates", and I have no filters set (e.g. "Only top-level dependencies(...)" is NOT checked.)

and my Gemfile references:
```
group :development, :test do
  gem "rspec-rails"
end
```

and my Gemfile.lock has:
```
...
rspec-core (3.8.0)
      rspec-support (~> 3.8.0)
    rspec-expectations (3.8.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-mocks (3.8.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.8.0)
    rspec-rails (3.8.2)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.8.0)
      rspec-expectations (~> 3.8.0)
      rspec-mocks (~> 3.8.0)
      rspec-support (~> 3.8.0)
    rspec-support (3.8.0)
    rspec_junit_formatter (0.4.1)
      rspec-core (>= 2, < 4, != 2.12.0)
...
```

Why isn't `rspec-expectations` automatically merged when version 3.8.4 was created? CI passed successfully https://github.com/tablexi/dashboard/pull/698.

Is it only expected to auto-merge top-level dependencies? I would expect that a gem which is only used by a top-level "development" gem, would itself be considered a "development" gem.

**Comment by greysteil** [comment]
It sounds like it should be being automerged. What does the PR description say?

**Comment by rdunlop** [comment]
Oh, It says "Dependabot will not automatically merge this PR because it includes a patch update to a production dependency.".....but it's not a production dependency, afaict.

**Comment by greysteil** [comment]
Ah OK, I know what this is. Dependabot isn't able to identify whether sub-dependencies are production or not (it should be able to, but can't at the moment). As a result it's being conservative and treating it as production.

I have an idea on how to fix the above - let me take a look.

**Comment by greysteil** [comment]
Fixed by [these](https://github.com/dependabot/dependabot-core/commit/1f2cbb1772a8d9bb0af59af3026f0b54fe92d2c2) [commits](https://github.com/dependabot/dependabot-core/commit/1a797bf4d26f56b55ba2ee1b6f4613a06251cb9a) which I'll get deployed tomorrow. Thanks for reporting!
