### ISSUE TITLE
Ignore major version question

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#62]
Hi there,

In some of our java repos we depend on `Edgware.SR3` for 

```xml
 <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
 </dependency>
```

Today `Finchley.RELEASE` was released and dependabot diligently recommends the update.

Sadly, this repo is a spring boot 1.x app which means that it can't use Finchely (it's spring boot 2+). However, I would want dependabot to recommend `Edgware.SR4` if/when it becomes available. 

So I don't want to entirely ignore the dependency, but I do want to ignore this version (which I thought was major) - so I type `@dependabot ignore this major version` and wait a few minutes but no comment was made on the PR to give feedback on whether this worked or not. Can dependabot cope with this type of version naming?

**Comment by greysteil** [comment]
OK, fix deployed - can you try commenting `@dependabot ignore this major version` on that PR again?

**Comment by NargiT** [comment]
Will this still upgrade minor version ? I guess it's not part of the dependabot-core?

**Comment by greysteil** [comment]
You'll still receive minor version updates if you're ignoring a major version, yes.

**Comment by NargiT** [comment]
Is this feature available in dependabot-core ? I was not able to find how to pass this kind of parameter to avoid major updates when a project is "late".

**Comment by feelepxyz** [comment]
@NargiT ah no that logic doesn't live in dependabot-core and you'll have to write that yourself if you're self hosting it.
