### ISSUE TITLE
PHP: Dependabot suggests incompatible packages (Part 2)

### ISSUE THREAD

**Issue by ElvenSpellmaker** [dependabot/feedback#623]
Hi there,

I have a private repo which is running Dependabot and I have a PR for upgrading a package:
![image](https://user-images.githubusercontent.com/2286713/62618784-07516900-b90d-11e9-8e5f-13566f549675.png)

However my constraint in my `composer.json` is:
```json
		"vlucas/phpdotenv": "^2.5"
```
This version shouldn't be matching?

![image](https://user-images.githubusercontent.com/2286713/62618857-35cf4400-b90d-11e9-95da-0b884f087a7a.png)

**Comment by greysteil** [comment]
By default Dependabot will generate PRs for updates outside of the version range you specify in your `composer.json` (and will update the `composer.json`) accordingly. You can configure that behaviour at the update config level from the Dependabot dashboard.

**Comment by ElvenSpellmaker** [comment]
Hey, thanks, how do I do this please?

**Comment by greysteil** [comment]
Click the cog next to the update config, and then click the second box here:

![image](https://user-images.githubusercontent.com/1144873/62619244-31eff180-b90e-11e9-9ba8-ed3812cf2fd5.png)

**Comment by ElvenSpellmaker** [comment]
Excellent thanks @greysteil!

**Comment by andig** [comment]
Just noticed the same and would like to reopen as it don't feel this is addressed by the settings.

Case: PR openened with bump to dependecy requiring php 7.2 while `composer.json` supports `^7.1` (see https://github.com/andig/carddav2fb/pull/152 vs https://github.com/andig/carddav2fb/blob/master/composer.json#L12).

While it would be ok to update the `composer.json`, it is not acceptable to break the php version requirements.

**Comment by andig** [comment]
Actually, as the case is a bit different here I've split this in to a separate issue.

**Comment by ElvenSpellmaker** [comment]
Yeah I did think my issue shouldn't've been closed tbh.

Changing the settings shown above breaks what I initially wanted.
