### ISSUE TITLE
Create a JIRA issue when creating a Pull Request

### ISSUE THREAD

**Issue by ryanwi** [dependabot/feedback#625]
I've been setting up dependabot across more than a dozen repos and would like to create JIRA tickets as dependabot creates Pull Requests to let teams know of updates on their apps. This can kind of be done with Zapier, but is a pain to set it up for every repo. Any hints or plans for achieving this?

**Comment by greysteil** [comment]
Thanks for using Dependabot!

I don't think Jira ticket creation is something we'd want to support natively within Dependabot, especially as the whole interface is moving within GitHub. I guess I'd expect GitHub-related Jira automation to either live within Jira or to be a GitHub app. I'm guessing [this app](https://github.com/marketplace/jira-software-github) doesn't help?

**Comment by ryanwi** [comment]
Thanks for taking a look, Grey. I agree it probably makes sense as a general GitHub --> Jira integration. The existing app will link to existing Jira issues from GitHub, but I have not yet discovered anything for creating issues in Jira (outside of Zapier that is). I'll provide that feedback on the Jira Github app as well.

**Comment by greysteil** [comment]
👍 I can imagine that's an automation that a lot of folks would want!
