### ISSUE TITLE
Custom triggers/hooks

### ISSUE THREAD

**Issue by hazcod** [dependabot/feedback#626]
Hi,

I have a bit of a niche use case; would it be possible to use dependabot as a notification system? I have a couple of use cases where I would want to receive a trigger via a pull request with the new version. e.g.;

- a docker version that is set in a Terraform configuration file as a debian package (e.g. `apt-get install docker-ce=${docker_version}`)
- a redis version that is set in a Dockerfile installation command (e.g. `ENV redis_version=1.0` and `curl http://redis-${redis_version}`)

e.g. https://github.com/stefanprodan/scaleway-swarm-terraform/blob/master/variables.tf#L2

Thanks.

**Comment by greysteil** [comment]
I'd love to say yes on t his one, but it's not on our roadmap and we have to prioritise quite ruthlessly at the moment. It probably *is* something you could build with some of the helper  classes in [Dependabot Core](https://github.com/dependabot/dependabot-core) and some tweaking, though.
