### ISSUE TITLE
Remove `.` from branch name

### ISSUE THREAD

**Issue by petergrau** [dependabot/feedback#627]
Similar to this feature request  #135 we would need to be able to remove `.` from the branch name.

We are using the branch name as a subdomain and therefore cannot have `.` in the name. As there are other feature requests in that area #545 maybe it would make sense to provide the possibility to apply a regular expression to the branch names?

**Comment by greysteil** [comment]
Thanks for getting in touch. This is the first request I've seen to substitute out `.`s - would it be possible to do it in your automation rather than on the Dependabot side? It doesn't feel unreasonable to use `.`s in a branch name - I've typed them in branches I've created manually myself!

**Comment by petergrau** [comment]
that is actually the workaround we implemented now (replacing it in our code). 

I am aware that this specific use case might be a bit out of the regular ;-) That is why I added my second comment that maybe a good solution could be to allow the usage of a regular expression that would offer any flexibility people need?

**Comment by greysteil** [comment]
Makes sense!

Totally buy that a regex would be a good general solution but I can see it being a pain to maintain. Folks are bound to enter regexes that delete the entire branch, for example, and we have a bunch of logic on our side that helps efficiently prune our webhook load (we get millions) based on the relevant branch including `dependabot`. I've also not heard of many other characters that folks want/need to remove (the `@` and `/` characters are thee only two).

I'm going to leave this for now and close it, but if others have the same issue please comment here and I'll review.

Thanks for the feedback and discussion @petergrau!

**Comment by clxmstaab** [comment]
we experience the very same problem. using the `.` in the branch name doesnt work, because we use it as a domain (subdomain) name

**Comment by dlasky** [comment]
same issue here as well, its used for namespaces which suffers a similar issue

**Comment by staabm** [comment]
We also have this problem. Just having a replace `.` by e.g. `-` like the already existing handling for the `/` char would save our live

**Comment by staabm** [comment]
Maybe someone has a workaround to rename the dependabot branch via a github action after dependabot pushed the PR? Would that work?
