### ISSUE TITLE
Run `go mod vendor` in Go projects with a vendor directory

### ISSUE THREAD

**Issue by scothis** [dependabot/feedback#628]
Some Golang module projects still vendor their dependencies to speed build time in CI and protect against an upstream dependency being mutated or deleted.

Dependabot will update the go.mod/.sum files for a new dependency, but does not update the vendor directory. This has the impact of running CI against the old version of the module rather than the updated version.

For Golang module projects that have a vendor directory. Dependabot should run `go mod vendor` after updating the go.mod file and commit the results as part of the changeset.

**Comment by hmarr** [comment]
We definitely plan to support vendoring in the future, but it'll probably be a few months until we get to it. We're tracking this in https://github.com/dependabot/dependabot-core/issues/670.
