### ISSUE TITLE
"@dependabot merge" merged before CI passed

### ISSUE THREAD

**Issue by eedwards-sk** [dependabot/feedback#629]
this is related to #212

I've encountered the same behavior recently.

- A dependabot PR failed CI.

- A dev issued `@dependabot merge`

- Issue auto-updated to "Dependabot will merge this PR once CI passes on it, as requested by {user}"

8 Days later, I issued `@dependabot rebase`

This caused the PR to rebase, which cleared the previous CI failure status. Our CI system kicked in and saw the new commit and started building, but before it could hit the github API to set the CI in progress, dependabot had **already merged and closed the pr**.

It appears that after it rebased, when the CI failure status disappeared, and before a new CI "pending" run showed it, dependabot decided that a lack of any CI information was "passing" and decided to merge it.

This feels like incorrect behavior. I would expect that if it knew the repo / PR was already subject to CI checks, that it would not suddenly decide to merge in the absence of one.

You can even see if I look at the PR now, it shows a pending check, even though it's already closed.

<img width="554" alt="Screen Shot 2019-08-09 at 12 19 36 PM" src="https://user-images.githubusercontent.com/34585329/62796908-fedd6780-ba9f-11e9-8ee7-be68b972ebf1.png">

**Comment by greysteil** [comment]
Hey @eedwards-sk,

This is an *extremely* helpful bug report - thank you for it! I'm updating our backend logic to apply the same fix we now use for newly created PRs (waiting 60 seconds before checking for CI). That change will be deployed in the next 10 minutes.

Thanks masses for the bug report!
