### ISSUE TITLE
config.yml not detected on initial repo add

### ISSUE THREAD

**Issue by sgrimm-sg** [dependabot/feedback#634]
To try out Dependabot, I forked one of my private repos and added a simple `.dependabot/config.yml` to the repo root. Then I logged into Dependabot, gave it permission to access the new repo, and tried to add the repo.

Despite the presence of the config file, the "add repo" UI still forced me to pick a language and a directory (it's a monorepo) and then the initial bump scanned the entire dependency list rather than honoring the `allowed_updates` clause in my config file, and submitted PRs for dependencies the config file says not to update.

I made a small change to `config.yml`, and once it saw the commit with that change, Dependabot started using the configuration.

**Comment by feelepxyz** [comment]
@sgrimm-sg hm been looking into this and I think you where simply too quick for us to process the webhook from github notifying about the repo being added to the installation.

I've tested the flow you explained and there's a small delay between adding the repo to the installation and dependabot seeing this and processing the config file.

I'll close this as I don't think there's anything broken other than webhooks possibly being slow.
