### ISSUE TITLE
Python2 requirements.txt with pylint

### ISSUE THREAD

**Issue by dsgnr** [dependabot/feedback#635]
I have a python 2 project which has a requirements.txt that includes `pylint==1.9.5`. Depenadbot appears to be wanting to upgrade the Pylint version to that of Python 3, currently `2.3.1` according to PyPi.

Is there a way that Dependabot can detect, or be told which Python version is being used?

**Comment by greysteil** [comment]
There is - it tries its best to figure it out using the logic in [this class](https://github.com/dependabot/dependabot-core/blob/master/python/lib/dependabot/python/file_parser/python_requirement_parser.rb). Perhaps the easiest way to help it out is to include a `.python-version` file (used by `pyenv`). Is there any way that Dependabot should have figured it out from your existing files? If you link to the repo I can take a look.
