### ISSUE TITLE
Go repo must contain a go.mod

### ISSUE THREAD

**Issue by andig** [dependabot/feedback#638]
Error is triggered when adding a repo where master branch does NOT contain go.mod but its part of the selected target branch.

Adding repo should search for go.mod in target branch instead of master.

**Comment by feelepxyz** [comment]
> Adding repo should search for go.mod in target branch instead of master.

@andig oh yeah this should be the expected behaviour! Do you have a repo you are trying to set up? If it's private, please email to [support@dependabot.com](mailto:support@dependabot.com)

**Comment by andig** [comment]
Darn- it actually *does* work that way. Invalid report, please forgive me!

**Comment by feelepxyz** [comment]
Ah no worries!
