### ISSUE TITLE
PHP: Dependabot suggests package with incompatible PHP version (Part 3)

### ISSUE THREAD

**Issue by andig** [dependabot/feedback#639]
Case: dependabot openened PR with bump to dependency requiring `php ^7.2` while project's `composer.json` requires `php ^7.1`. This breaks compatibility for users on minimum php version.
For an example see andig/carddav2fb#152 vs https://github.com/andig/carddav2fb/blob/master/composer.json#L12.

While it would be ok to update the `composer.json`, it is not acceptable to break the php version requirements.

Split from https://github.com/dependabot/feedback/issues/623

**Comment by andig** [comment]
cc @feelepxyz

**Comment by greysteil** [comment]
Should be fixed by https://github.com/dependabot/dependabot-core/commit/68b7bf95a2c22b777f56a7528d9641898fe74665.
