### ISSUE TITLE
Run on multiple branches

### ISSUE THREAD

**Issue by DeepDiver1975** [dependabot/feedback#64]
Hi,

we have multiple release branches within our repo and I'd like to run dependencybot on all our release branches.

This is the error I'm getting - or am I miss understanding this .... THX a lot

![bildschirmfoto von 2017-12-20 11-29-03](https://user-images.githubusercontent.com/1005065/34202756-011c6a94-e579-11e7-8991-5f88b437fef6.png)

**Comment by greysteil** [comment]
Interesting - not a use case I’d thought of but easy for us to support. I’ll make the change later today and close this when it’s done.

**Comment by DeepDiver1975** [comment]
> Interesting - not a use case I’d thought of but easy for us to support. I’ll make the change later today and close this when it’s done.

Thanks for your fast feedback - much appreciated!

**Comment by greysteil** [comment]
Fix is deploying now. 🎉

**Comment by DeepDiver1975** [comment]
Thanks a lot! Setting it up now!

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#388
