### ISSUE TITLE
Merge conficts in csproj when updating multiple dependencies

### ISSUE THREAD

**Issue by simondel** [dependabot/feedback#64]
I just merged a PR for a .NET Core project to upgrade the Moq dependenency from 4.8.2 to 4.8.3. 

After the merge, another PR has a merge confict (Microsoft.NET.Test.Sdk from 15.5.0 to 15.7.2)

![image](https://user-images.githubusercontent.com/4221997/41707335-23dfb6f8-753e-11e8-9f53-55782636e30e.png)

Doing a rebase has fixed the conflict, however I would not expect a merge conflict to occur in this scenario.

The respective PR's are https://github.com/stryker-mutator/stryker-net/pull/30 and https://github.com/stryker-mutator/stryker-net/pull/31

**Comment by greysteil** [comment]
We can't control when git decides there's a conflict (that's down to git's internals), but we can ensure Dependabot rebases files automatically when it should. Just updated the list of files it will look for potential issue with in https://github.com/dependabot/dependabot-core/commit/02ae4de4792c20991d676dd14fa82f2168fdb27e.

Thanks for the prompt on this, and for testing out Dependabot on .NET!

**Comment by simondel** [comment]
Awesome, I can see it rebasing now :)
![image](https://user-images.githubusercontent.com/4221997/41717055-c0eb0d02-7558-11e8-9d64-61548d0492b2.png)
