### ISSUE TITLE
Unable to recreate closed PR

### ISSUE THREAD

**Issue by jglick** [dependabot/feedback#641]
I had what looks like a CI flake in https://github.com/jenkinsci/bom/pull/69. I tried to force a rebuild by closing and reopening the PR, but this did not work, so I tried `rebase`, which Dependabot refused since the PR was already up-to-date with master. (Can it not just humor me and rebase anyway?) So then after closing it again and planning to wait a minute before reopening I saw that the branch was deleted. This meant it could not reopen the PR—there is no longer a branch. Fine, so I asked to `recreate`. But that was also refused with

> Looks like this PR is closed. If you re-open it, I'll rebase it, as long as no-one else has edited it.

which is not helpful because I _cannot_ reopen it now!

So now I am left with manually filing a PR with the same diff.

**Comment by feelepxyz** [comment]
@jglick ah yeah there's definitely room for improvement here, we've opted for specific commands that don't try to be too clever. You should be able to reopen it with `@dependabot reopen`

**Comment by greysteil** [comment]
FYI, I've updated the text Dependabot comments with for these cases so it's clearer. Thanks for the heads up.
