### ISSUE TITLE
Live updates for JavaScript do not seem to work

### ISSUE THREAD

**Issue by goloroden** [dependabot/feedback#649]
We are using Dependabot for a number of npm packages we are building, and all of them are configured to update all direct dependencies in live mode.

Unfortunately, so far we didn't get PRs – except if we manually bumped the modules.

I expected "live" to mean more or less the moment that a dependency gets published to npm, but this is definitely not working (there are several missed updates, even from single packages, and the "last check" says more than one day ago).

Am I missing something? Do you need any more info on this to track this down? Anyone else with the same behavior for npm?

**Comment by feelepxyz** [comment]
@goloroden thanks for reporting! Looks like our service that follows npm registry updates had run out of memory. It should be back up and running now but will take a little while to drain the backlog.
