### ISSUE TITLE
Private pypi servers

### ISSUE THREAD

**Issue by khornberg** [dependabot/feedback#65]
Are there plans to enable private pypi servers?

**Comment by greysteil** [comment]
Yes! I need to do a bit of work to enable it first, but should be able to ship something today or on Sunday.

**Comment by greysteil** [comment]
Private PyPI servers should be working now! Dependabot will read your `pip.conf` and/or your `requirements.txt` to find them.

Let me know if you have any trouble - it's a brand new features so may not be perfect, but I've tested internally.

🍸

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#389
