### ISSUE TITLE
Update Rust to 1.37.0

### ISSUE THREAD

**Issue by Jake-Shadle** [dependabot/feedback#650]
> Dependabot can't resolve your Rust dependency files.
> 
> As a result, Dependabot couldn't update your dependencies.
> 
> The error Dependabot encountered was:
> 
> ```
> error: failed to parse manifest at `/home/dependabot/dependabot-updater/dependabot_tmp_dir/components/client/Cargo.toml`
> 
> Caused by:
>   the `default-run` manifest key is unstable
> 
> Caused by:
>   feature `default-run` is required
> 
> this Cargo does not support nightly features, but if you
> switch to nightly channel you can add
> `cargo-features = ["default-run"]` to enable this feature
> ```
> 
> If you think the above is an error on Dependabot's side please don't hesitate to get in touch - we'll do whatever we can to fix it.
> 
> You can mention @dependabot in the comments below to contact the Dependabot team.

We updated to Rust 1.37.0 last week and started using the new [`default-run`](https://blog.rust-lang.org/2019/08/15/Rust-1.37.0.html#choosing-a-default-binary-in-cargo-projects) feature added to cargo, but dependabot is using an older version of cargo so this breaks upgrading as listed above.

**Comment by greysteil** [comment]
Sorry about that! I thought a previous change to the Dockerfile would update this, but it looks like updating a comment no longer busts the cache. [This change](https://github.com/dependabot/dependabot-core/commit/bf2e814923940de02169a13c72429f8add241291) will, though, so this should be fixed today.

**Comment by Jake-Shadle** [comment]
Thanks!

**Comment by repi** [comment]
Verified that it works now for us, thanks!
