### ISSUE TITLE
Prefer most specific tag for docker image upgrade PRs

### ISSUE THREAD

**Issue by davidkarlsen** [dependabot/feedback#657]
I think it would be preferable to use the most specific tag for image upgrades, e.g. do `node:12.9.0-stretch` instead of `node:12.9-stretch`.
The reason for this is that 12.9 is typically used as tag for all 12.9.x, and by doing PRs per patch release it's easier to get a build triggered.

**Comment by greysteil** [comment]
Dependabot should be continuing to pick the most specific tag for you if that's the setup you currently have. Are you seeing behaviour where it's not doing that?

**Comment by davidkarlsen** [comment]
Yes, in this PR: https://github.com/evryfs/node-dev-docker/pull/18/files

**Comment by greysteil** [comment]
👍 have replicated locally and will have a fix soon.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/cd13233e6dd918e250f33dab81d072e7397f2e49, which will be deployed in the next hour. Thanks for reporting this!

**Comment by davidkarlsen** [comment]
Awesome - thanks a lot!
