### ISSUE TITLE
Handling of Cargo workspace member lists doesn't support globs correctly

### ISSUE THREAD

**Issue by jonas-schievink** [dependabot/feedback#659]
Dependabot opened https://github.com/jonas-schievink/rubble/issues/76 after I changed a workspace's `members` list entry from `"demos/*"` to `"demos/*/"`. Cargo handles the latter without problems (as a regular shell glob), but Dependabot didn't like it.

Cargo.toml: https://github.com/jonas-schievink/rubble/blob/dd2c617b4ec5022c2d52741ad4aac44873ae5b9d/Cargo.toml#L5

**Comment by greysteil** [comment]
Thanks for the  heads  up. Should be fixed in the  next release (sometime today).
