### ISSUE TITLE
anchor tags to projects/repos in dashboard page

### ISSUE THREAD

**Issue by asherf** [dependabot/feedback#66]
Hi,
 Can we get anchor tags so we can link directly to specific projects/repos in the dashboard page?
 i.e. something like: `https://app.dependabot.com/accounts/<org name>/repos#my-app-repo`

**Comment by greysteil** [comment]
Great idea! Should be easy, too - I'll do it now.

**Comment by greysteil** [comment]
Done! I'll tweak the display a bit (currently non-existent), but every repo now uses its name as an anchor.
