### ISSUE TITLE
Support for Docker compose files

### ISSUE THREAD

**Issue by armin-joellenbeck** [dependabot/feedback#66]
Knowing when new Docker images are published would be helpful when the are used in a Docker compose file too.

Just like #20, with the file `docker-compose.yml` instead of `Dockerfile`.

**Comment by greysteil** [comment]
👍  for this, and should be relatively straightforward. A couple of things I want to get to first, but I'm definitely game for adding this to Dependabot at some point!

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#390
