### ISSUE TITLE
Incorrect repository owner for pact-ruby

### ISSUE THREAD

**Issue by yahonda** [dependabot/feedback#661]
Today we received a pull request from dependabot whose title is "Bump pact from 1.41.0 to 1.41.1" which bumps pact version fronm 1.41.0 to 1.41.1.

To compare the differences between 1.41.0 and 1.41.1, clicked "See full diff in compare view", it links to the old organization one. 

```diff
    nokogiri (1.10.4)
      mini_portile2 (~> 2.4.0)
    oj (3.9.1)
-    pact (1.41.0)
+    pact (1.41.1)
      json (> 1.8.5)
      pact-mock_service (~> 3.0)
      pact-support (~> 1.9)
```

### Actual result
https://github.com/realestate-com-au/pact/commits

### Expected result
https://github.com/pact-foundation/pact-ruby/commits

**Comment by greysteil** [comment]
Fixed by https://github.com/pact-foundation/pact-ruby/pull/195. Thanks for the heads up.
