### ISSUE TITLE
Automerge not being performed

### ISSUE THREAD

**Issue by vectronic** [dependabot/feedback#664]
Hello,

I am trying to understand why auto-merge is not being performed with this PR:

https://github.com/flowscripter/tsconfig/pull/34

In the logs:

https://app.renovatebot.com/dashboard#github/flowscripter/tsconfig/93445683

I can see:

`DEBUG: No check runs found(branch="renovate/patch-devdependencies")`

and

`INFO: PR is not ready for merge (branch status is pending)`

Have I somehow managed to confuse Dependabot or am I missing something obvious?

**Comment by feelepxyz** [comment]
@vectronic looks like you're using Renovate so won't be able to debug this for you but I'm guessing it's similar to Dependabot in that it won't automerge without any tests. So you'll probably need to add some test CI step that gets run on PRs.

https://docs.renovatebot.com/noise-reduction/#automerging

**Comment by vectronic** [comment]
@feelepxyz Sorry I got mixed up with your competitor - embarrassed!
