### ISSUE TITLE
Not ignoring Python dependency

### ISSUE THREAD

**Issue by YakDriver** [dependabot/feedback#667]
[Our project](https://github.com/plus3it/watchmaker) maintains compatibility across Python versions 2.6-3.7. This is a portion of our `requirements.txt`:

```
pytest==3.2.5;python_version<"2.7" or python_version=="3.3"
pytest==4.6.3;python_version<"3.5" and python_version>="2.7"
pytest==5.1.2;python_version>="3.5"
```

We want Dependabot to ignore the first two lines but _not_ ignore the third. 

We modified the file to use `<` for the purpose of helping Dependabot ignore these lines. Based on #658, it seems like the `<` should do the trick. However, Dependabot [does not ignore](https://github.com/plus3it/watchmaker/pull/968/files) the second line.

Can you offer any suggestion?

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/e6d724af653ed435c206bd6ea7f9d776796c8485. Thanks for the heads up!

**Comment by YakDriver** [comment]
Wow. Very responsive. Thanks, @greysteil !
