### ISSUE TITLE
The flash message duration is a bit short.

### ISSUE THREAD

**Issue by zeke** [dependabot/feedback#67]
I'm not able to fully read most of these before they disappear:

![screen shot 2018-06-21 at 2 24 58 pm](https://user-images.githubusercontent.com/2289/41746372-f34ab846-755e-11e8-9560-f3754525fb12.png)

It would be good to make them display for longer, or make them stay on the screen until dismissed.

**Comment by greysteil** [comment]
👍 - thanks for the feedback, I'll increase the display time.

**Comment by greysteil** [comment]
Updated, just for that notification (it's no 8 seconds for that one and still 5 seconds for the shorter ones).

Thanks again for the feedback!
