### ISSUE TITLE
Alerts for security PRs

### ISSUE THREAD

**Issue by ocudigital** [dependabot/feedback#675]
It would be awesome to have an alerting systems for when dependabot notices a security update / problem.    Options for email and SMS would be a bonus.

**Comment by feelepxyz** [comment]
@ocudigital 👋 you can already get this through GitHub Security alerts: https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies which is what we use to create pull requests to fix vulnerable dependencies.
