### ISSUE TITLE
Merging after approval and protected branches

### ISSUE THREAD

**Issue by rtpg** [dependabot/feedback#677]
We have the following setup:

 - a non-`master` default branch
 - requiring approval before merging into this default branch
 - `master` as a protected branch
 - We _don't_ have automerging enabled on dependabot

On every dependabot PR recently, we hit the following:

 - someone approves the PR
 - almost immediately after, Dependabot posting the following:

 > Dependabot tried to merge this PR, but received the following error from GitHub:
 > `You're not authorized to push to this branch. Visit https://help.github.com/articles/about-protected-branches/ for more information.`

To be honest I don't get why it's even trying to merge, since automerging is disabled. I get that "approval" might look like "it's OK to merge now" but seems like something odd to do given that automerging is already a setting (=> there's some awareness of preferences on this)

I don't know what the source of this is (a race condition on the approval? Dependabot trying to merge to `master` instead?), but given our pretty straightforward usage I don't think it's an issue on our side.

**Comment by feelepxyz** [comment]
@rtpg 👋 hm looks like it's hitting the push restriction on the non-default branch. If you've restricted who can push to this branch you can add Dependabot Preview to the list of users who are allowed to push (from the protected branch settings page).

What repo have you set this up on? If it's a private repo please email it to [support@dependabot.com](mailto:support@dependabot.com).

**Comment by rtpg** [comment]
Hey @feelepxyz what you said is right, so this seems like the source of the issue.

However, we _don't want dependabot to merge the PRs even if it's approved_. We have our own merging patterns on some of this stuff and ideally we would just like dependabot to not take the "Github PR approval" as license to hit the merge button.

We don't have dependabot "automerge" enabled by the way.

This is a really useful tool, just trying to clean up an annoyance.

**Comment by rtpg** [comment]
by the way, sent the private repo name via email just now

**Comment by feelepxyz** [comment]
> We have our own merging patterns on some of this stuff and ideally we would just like dependabot to not take the "Github PR approval" as license to hit the merge button.

@rtpg ah in that case you should disable "Treat PR approval as a request to merge" in your [Dependabot dashboard](https://app.dependabot.com) account settings (top right nav > settings).
