### ISSUE TITLE
Use a specific nvmrc file?

### ISSUE THREAD

**Issue by hkung77** [dependabot/feedback#678]
I'm wondering if we can specify a specific node / npm version for dependabot to use. Or if it can detect a .nvmrc file and adjust. 

The reason I'm asking is because I see some differences when it generates the package-lock.json file.

Thanks so much!

**Comment by feelepxyz** [comment]
@hkung77 👋 there's currently no way to configure the npm version 😢 we always try to keep it up to date but are currently trailing a few versions behind the latest due to some breaking changes. Would you like to specify npm 5 or are you seeing changes for different npm 6 versions?

**Comment by hkung77** [comment]
@feelepxyz I have several projects that use dependabot, they each have their own npm version. 
Thank you for the information!
