### ISSUE TITLE
[Python]: Distributions uploaded at slightly different times can lead to build failures

### ISSUE THREAD

**Issue by JayH5** [dependabot/feedback#68]
Hi there 👋,

One problem we are occasionally encountering is when Dependabot opens a new PR for an updated Python package but only some distributions have been uploaded for that package to PyPI.

If a Python package contains native extensions then the binary distributions (a.k.a. wheels) are platform-specific. If you try to install a package on a platform for which the correct wheel is not available, it must build the package from source. PyPI registers a new version of a package as soon as *any* distribution with that version is uploaded. This means that there is a race condition when a distribution has been uploaded and Dependabot creates an update PR before the correct distribution for the target platform has been uploaded. This can cause CI builds to fail for Dependabot PRs. Running the build again later, once a suitable distribution has been uploaded, fixes the issue.

We've seen with `lxml` and `numpy` that those projects tend to upload their wheel distributions before the sdist/source distributions. This causes issues when using Alpine Linux (which is quite common with Docker containers) as Alpine doesn't support Linux wheels and must build from source, but the source distribution (a.k.a. sdist) is not available on PyPI yet.

I'm not sure exactly what the correct fix for this is. I don't think we've actually seen this issue with Requires.io or pyup.io but that may just be because those services are slower creating PRs than Dependabot. A potential solution could be to add a delay to creating PRs when a new version appears on PyPI. Another solution may be to add an option to always wait for the sdist distribution to be available on PyPI before creating a PR.

Thanks 🙏

**Comment by greysteil** [comment]
Hi @JayH5,

Oh, interesting, I had no idea.

OK, so the two possible fixes:
1. I'm guessing you're using live-updating, and that's (part of) what's causing this problem? Currently we're getting live update data by polling [this endpoint](https://pypi.org/rss/updates.xml) every 10 minutes and kicking off update runs immediately if we see new packages. There's already a small delay built in to creating PRs as a result - it takes us 30 seconds or so to spin up a box to do the update. **I could add a manual delay of 10 minutes to this.**
2. Information about the available distributions tells me whether an sdist distribution has been pushed. I could ask Dependabot to only create updates when one is.

Can you think of any situation where (2) isn't the right thing to do? It seems the more robust of the two options if not.

**Comment by JayH5** [comment]
@greysteil I do prefer (2), but technically there is nothing stopping someone from *not* uploading an sdist 😕.

I should also note that a bunch of what I said I'm pretty sure is happening but I haven't 100% confirmed everything. What we have is a Travis CI build where some jobs are Debian-based and can use wheels, and some jobs are Alpine-based and need the source. They all run at roughly the same time and sometimes the Debian builds pass and the Alpine ones can't find the correct distribution and fail. Restarting the Alpine builds later (usually a few hours later or whenever I happen to get to it) fixes things. I haven't actually looked at the PyPI page for the package to check which distributions are listed there.

**Comment by PatMyron** [comment]
[These dependabot builds](https://github.com/PatMyron/advent-of-code/pulls?q=label%3Adependencies) frequently need to be restarted later for the Travis CI environment to find the latest dependency version

This could hurt the signal/noise ratio of compatibility scores

**Comment by greysteil** [comment]
Hmmm, that's frustrating.

I've just added a 10 minute delay to Dependabot PR creation for Python repos using Dependabot in "live" mode. Hopefully that's enough to fix this. 🤞

**Comment by PatMyron** [comment]
@greysteil Was thinking about the same solution. Are security vulnerabilities exempt from being delayed?

**Comment by greysteil** [comment]
Yep - security updates will still process immediately.

**Comment by JayH5** [comment]
Still saw this happen yesterday with `lxml==4.3.3` 😢. Still not sure much can be done about it, though. Don't know why it takes the authors so long to upload the different types of packages, but I guess there's no _requirement_ for when individual package files are uploaded.

**Comment by JayH5** [comment]
OTOH, this is going to be less of an issue for us specifically as we're building on fewer different platforms in the future.

**Comment by greysteil** [comment]
That's really annoying. All I can recommend is asking for an `@dependabot recreate` if/when that happens.
