### ISSUE TITLE
Set pull request prefix in webapp config

### ISSUE THREAD

**Issue by kylemh** [dependabot/feedback#683]
I would like to be able to define a prefix for pull request titles for the PRs that Dependabot creates. Somewhere on this view would be ideal!

![Screen Shot 2019-09-23 at 9 28 29 AM](https://user-images.githubusercontent.com/9523719/65444334-ad393400-dde4-11e9-914f-62c0ad6d6e34.png)

**Comment by feelepxyz** [comment]
@kylemh you can set this up if you use config files: https://dependabot.com/docs/config-file/#commit_message - probably won't port it to the UI as I'm keen to move everyone to config files eventually.
