### ISSUE TITLE
Dependabot only full releases

### ISSUE THREAD

**Issue by RichardKreutzfeldt2000** [dependabot/feedback#684]
Hello,

I want Dependabot to only update dependencies to versions, which are final releases.
For example, the version number of a dependency is "2.9.9.3", but Dependabot wants to update it to "2.10.0.pr3".
I was trying to solve this with wildcards, but it didn't work.

Is there currently a way to solve this?

My attempt:
```version:1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          dependency_name: "*"
          version_requirement: "*alpha*, *beta*, *b*, *rc*, *pr*, *cr*, *m*, *ea*, *incubating*, *atlassian*, *snap*"
      - match:
          dependency_name: "com.google.guava*"

**Comment by feelepxyz** [comment]
@RichardKreutzfeldt2000 yes we'll need to add it here https://github.com/dependabot/dependabot-core/blob/master/gradle/lib/dependabot/gradle/version.rb#L19-L27

Would you rank `pr` the same as `cr` and `rc`?

**Comment by RichardKreutzfeldt2000** [comment]
@feelepxyz thank you. yes, i would rank them the same.
