### ISSUE TITLE
Set Run Day/Time in config file for weekly and daily update schedules

### ISSUE THREAD

**Issue by stefankraus-wf** [dependabot/feedback#687]
As a user of Dependabot, I want to be able to set the day and time for PRs to be opened in my dependabot config file so that I can configure via those yaml files rather than the global Dashboard settings. 

When going to the [dashboard](https://app.dependabot.com) I see the option to configure the Day / Time for runs on a daily or weekly schedule

![image](https://user-images.githubusercontent.com/17010515/65543365-a7bc1680-ded6-11e9-9390-7d3ff67b0272.png)

![image](https://user-images.githubusercontent.com/17010515/65543404-b73b5f80-ded6-11e9-977d-7a9b20bd801e.png)

However, I do not see that option to add to the configuration file in the configuration docs here : https://dependabot.com/docs/config-file/ instead, there is just the line

> For daily and weekly schedules you can also specify the run day and time in your dashboard account settings.

I would like an option in the configuration file under the `update_schedule` tag to specify the preferred Day and Time to run the update.

**Comment by michael-garland** [comment]
Any update on this enhancement?

**Comment by feelepxyz** [comment]
@michael-garland we just launched a beta of a GitHub native Dependabot: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

We've moved most account settings to the config file and these can be set per package manager, here are the full docs for reference: https://help.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically

**Comment by stefankraus-wf** [comment]
Nice, the config file seems to have all of the options that I would like to see! Thanks @feelepxyz I'd consider this issue resolved!
