### ISSUE TITLE
Repositories in composer.json

### ISSUE THREAD

**Issue by yaroslavmo** [dependabot/feedback#692]
How does dependabot manage [repositories](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository) in composer.json file?

I forked some repos and set composer to require forked packages using the vsc repositories functionality. But dependabot does not consider them and just downloads last release (not from forked package). Although, composer does download correctly, from a forked version.
Here is the [link](https://github.com/yaroslavmo/df-graphql/) to such repo.

Thank you!

**Comment by yaroslavmo** [comment]
I even tried to configure private packagist and it still does not open a PR for the last release.

**Comment by feelepxyz** [comment]
@yaroslavmo good question! I haven't had a chance to dig into this properly yet but will have a look.

**Comment by yaroslavmo** [comment]
So it appears that If a package is not on packagist.org then dependabot cannot see its new version?

I tried to go over it by adding packages to private [packagist](https://packagist.com) and specifying "PHP registry" config variable (repo.packagist.com) but it still does not see the new version. Although, I can see the new version on packagist.com dashboard.

**Comment by yaroslavmo** [comment]
@feelepxyz I could not make PHP registry work. I added [df-core](https://github.com/yaroslavmo-df/df-core) and [df-graphql](https://github.com/yaroslavmo-df/df-graphql) to private packagist. Then added PHP registry config variable with the token. I see that on packagist there is 16.0.0 version of df-core and df-graphql requires df-core 15.0.3 version. Dependabot just does not create new PR. So private packagist integration does not work. Could you please check it. Thank you

**Comment by feelepxyz** [comment]
@yaroslavmo sorry for the delay, we're pretty swamped at the moment so taking a bit longer to get through issues. Which repository are you expecting updates on that is configured to fetch from the private packagist registry?

Some of the related logic lives here if you want to have a peek: https://github.com/dependabot/dependabot-core/blob/master/composer/lib/dependabot/composer/update_checker/latest_version_finder.rb#L90-L112 (also any PHP help would be much appreciated as we currently don't have anyone who's very familiar with it!)

**Comment by yaroslavmo** [comment]
I created a new release for df-core that should be bumped [here](https://github.com/yaroslavmo-df/df-graphql/blob/0b8f7598d2fe929215bfdfd82e44747f8c845e88/composer.json#L35) and private packagist shows me that it sees it. But dependabot would not create a PR.

Unfortunately, I am not very familiar with Ruby, but I looked through the class you showed. There is logic regarding [packagist.org](https://github.com/dependabot/dependabot-core/blob/790a7c275863cf2c26d4663394890045a4af1bd1/composer/lib/dependabot/composer/update_checker/latest_version_finder.rb#L104)(public) but I don't see any logic regarding packagist.com(private one). Dependabot integrates private packagist through PHP Registry config variable maybe logic for that is in the other place? Could you please share where PHP Registry magic happens?

And just FYI here is how private packagist connected in the composer.json file:
`"repositories": {
        "private-packagist": {
            "type": "composer",
            "url": "https://repo.packagist.com/yaroslavmo-df/"
        },
        "packagist.org": false
    },`

**Comment by yaroslavmo** [comment]
I can even see my new version in the response on https://repo.packagist.com/yaroslavmo-df/packages.json endpoint that dependabot uses.

**Comment by yaroslavmo** [comment]
I could not find any info on 'Git source' config variable. Could you explain to me how it works?

**Comment by feelepxyz** [comment]
@yaroslavmo hm looks like we have a bug in our config file parsing which preventing any updates on your repo. When I try running an update against your composer file I see an update for df-core to version 16.0.0 so your setup looks good! Let me try debug what's going on with the config parsing.

**Comment by feelepxyz** [comment]
@yaroslavmo looks like the Dependabot Preview app doesn't have access to your repo: https://github.com/yaroslavmo-df/df-graphql

Could you check that `df-graphql` is added to list of installed repositories for `Dependabot Preview`? https://github.com/settings/installations (if this is the case could you try re-installing the app?)

**Comment by yaroslavmo** [comment]
I managed to use the git source config variable to connect dependabot to github directly. So everything works as expected now. Thank you.
