### ISSUE TITLE
Bug: scheduled updates being missed

### ISSUE THREAD

**Issue by ryanblock** [dependabot/feedback#695]
#### Expected behavior
- Schedule updates should update on the cadence specified
- In this case, the cadence specified is daily:
![image](https://user-images.githubusercontent.com/200964/65841620-23540400-e2d9-11e9-855a-8abccbb3faad.png)

#### Actual behavior
- dependabot has not run for 3+ days
![image](https://user-images.githubusercontent.com/200964/65841625-2fd85c80-e2d9-11e9-962b-0c13f1266977.png)

#### Repro steps
- Set up daily checks
- See if updates occur daily

**Comment by feelepxyz** [comment]
@ryanblock we only run daily updates on weekdays. Looks like this has successfully run this morning without any updates required. We can definitely do a better job communicating this, will fix this 👌

**Comment by ryanblock** [comment]
Ah, right on, that's totally fine (and a kind consideration to overworked devs). Thanks!
