### ISSUE TITLE
mixed upper/lower case python packages not cleaned up

### ISSUE THREAD

**Issue by mikespub** [dependabot/feedback#696]
For mixed-case python packages like Flask-SQLAlchemy, dependabot does recognize the need to update the requirements.txt and creates a pull request for it.

But if the requirements are then updated by the user, dependabot does NOT recognize that the pull request is no longer needed, so it remains open. Lower-case python packages are cleaned up correctly.

**Comment by rebelagentm** [comment]
Hi! 👋  Thank you for reaching out.  A couple of questions:

1) What package manager are you using?
2) Do you have a repo and/or example dependency files that we can use to reproduce your case?  If they are private, you can e-mail them to support@dependabot.com.

**Comment by rebelagentm** [comment]
Hello again!  This should now be fixed.
