### ISSUE TITLE
Dependabot generates package-lock.json that is out of sync with package.json

### ISSUE THREAD

**Issue by bjoerge** [dependabot/feedback#697]
I'm not entirely sure what's going on here or if it's a misconfiguration on our part, but when bumping versions, dependabot removes a lot of dependencies from `package-lock.json`, causing `package.json` and `package-lock.json` to get of sync.

Here's an example of a pull request from dependabot that upgrades a single dependency (`date-fns`), but removes 13,795 lines from the matching `package-lock.json`: https://github.com/sanity-io/sanity-template-gatsby-blog/pull/73

This again causes CI builds to fail since `package-lock.json` doesn't include all the dependencies that are declared in `package.json`:
```
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

The repository is configured using a yaml config file that can be found here: https://github.com/sanity-io/sanity-template-gatsby-blog/blob/master/.dependabot/config.yml

Any help/pointers would be appreciated.

**Comment by feelepxyz** [comment]
@bjoerge oh taking a look!

**Comment by feelepxyz** [comment]
@bjoerge looks like the template name is causing npm to silently bail out on installing any dependencies (npm warning: `Invalid name: "<#< repository.name >#>-studio"): https://github.com/sanity-io/sanity-template-gatsby-blog/blob/master/template/studio/package.json#L3

Dependabot doesn't have the best lerna support, e.g. won't run any bootstrap commands for you but you should be able to make your project work by changing the package name to something valid according to npm.

**Comment by bjoerge** [comment]
Ahh, that makes sense! It means the error is on our side. Thank you so much looking into it! 🙏
