### ISSUE TITLE
[Question] How to not update to the next Version

### ISSUE THREAD

**Issue by mimmi20** [dependabot/feedback#702]
In my PHP Projects I use PHPUnit 7.5.x or 8.0+ because my projects should work on PHP 7.1. The actual Version of PHPUnit is 8.4.0 which requires PHP 7.2.

Every time PHPUnit publishes a new Release Dependabot creates a new PR with an update to the newest PHPUnit version which fails in the build process.

Do I have to define a PHP version in the composer.json file to avoid this?

**Comment by bmuskalla** [comment]
You may want to try using https://dependabot.com/docs/config-file/#ignored_updates
