### ISSUE TITLE
Dependabot trying to bump from commit hash version to older tagged version

### ISSUE THREAD

**Issue by mueller-ma** [dependabot/feedback#704]
https://github.com/openhab/openhab-android/pull/1577

Why does the bot try to bump the library? The [commit has (be5d2cd) we use as version is from 24 Jan](https://github.com/heremaps/oksse/commit/be5d2cd6deb8cf3ca2c9a740bdacec816871d4f7), the [tagged version (0.9.0) is from 19 Jun 2018.](https://github.com/heremaps/oksse/releases/tag/0.9.0)

**Comment by rebelagentm** [comment]
Hi!  I responded to your original issue earlier today, but I'll put the update here too.

It looks like Dependabot was not recognizing that as a git dependency and was instead thinking the commit SHA was a version number. I'm working on a fix for it.

**Comment by rebelagentm** [comment]
Hello again!  This should be fixed now in https://github.com/dependabot/feedback/issues/704.  You should see it in v0.113.12.  Thanks for using Dependabot!
