### ISSUE TITLE
Error bumping dependencies

### ISSUE THREAD

**Issue by Jaanki** [dependabot/feedback#709]
I am running dependabot against "https://github.com/Jaanki/submariner" and "https://github.com/Jaanki/coastguard" and getting "Dependabot couldn't parse the go.mod found at /go.mod." error

**Comment by feelepxyz** [comment]
@Jaanki looks like these versions are invalid:
- https://github.com/Jaanki/submariner/blob/master/go.mod#L11
- https://github.com/Jaanki/coastguard/blob/master/go.mod#L11

If you change this line to `replace github.com/bronze1man/goStrongswanVici => github.com/mangelajo/goStrongswanVici v0.0.0-20190701121157-9a5ae4453bda` it should work.

This is the error from go: `github.com/mangelajo/goStrongswanVici@v0.0.0-20190223031456-9a5ae4453bd: invalid pseudo-version: revision is shorter than canonical (9a5ae4453bda)`
