### ISSUE TITLE
List projects with Pull Requests for a given dependency update

### ISSUE THREAD

**Issue by connorshea** [dependabot/feedback#71]
For example, I have the selenium-webdriver gem and it was upgraded from 3.12.0 to 3.13.0: https://dependabot.com/compatibility-score.html?dependency-name=selenium-webdriver&package-manager=bundler&previous-version=3.12.0&new-version=3.13.0

It has a 95% success rate, but for my repository it [is failing](https://github.com/connorshea/mdn-compat-data-explorer/pull/91). Since 57 projects have upgraded this dependency via dependabot, that'd mean 2 other projects have this same problem.

It'd be nice if I could look at the other repositories that updated between these versions and see how others are fixing the problem if they have it.

**Comment by greysteil** [comment]
I'm super keen on this - I want to make it available to maintainers, too, so they can debug issues more easily too.

The work we've done on comaptibility scores recently with [this page](https://dependabot.com/compatibility-score.html?dependency-name=selenium-webdriver&package-manager=bundler) should dovetail into this nicely. cc @petehamilton.

**Comment by connorshea** [comment]
👍 glad to hear it, thanks for all your work on dependabot!

**Comment by feelepxyz** [comment]
@connorshea 👋we now show failing PRs on the compatibility page: https://dependabot.com/compatibility-score/?dependency-name=selenium-webdriver&package-manager=bundler&previous-version=3.12.0&new-version=3.13.0
Would love to hear if you find this helpful!

**Comment by connorshea** [comment]
Is kind of like to see all PRs even if they succeeded (maybe being a button to decrease the performance impact?) but regardless this feature is great! Thanks :D

**Comment by feelepxyz** [comment]
@connorshea ah interesting, anything specific you'd like to figure from this data?

Currently the table will show all updates that failed CI, even if it later went green and merged. Our initial thinking was that the succeeded builds won't give you that much interesting information, but keen to hear if we've missed something!
