### ISSUE TITLE
Projects stuck in `checking now, hold tight!` status, dependencies possibly not being updated

### ISSUE THREAD

**Issue by ryanblock** [dependabot/feedback#713]
Hi there!

Noticed that for all of our projects, Dependabot has been stuck in a `checking now, hold tight!` status. There's also been a dropoff in dependency PRs (but it's hard to say whether that's causal or corollary as yet). 

Just started seeing this in the last day so and wanted to give it a shout out since it's obviously strange and unexpected behavior:

![image](https://user-images.githubusercontent.com/200964/66853419-1ae40600-ef34-11e9-8c69-0e8ea8fb7a77.png)

**Comment by rebelagentm** [comment]
@ryanblock Thank you letting us know!

@feelepxyz Thoughts on what's happening here?

**Comment by feelepxyz** [comment]
@ryanblock @JoshKeegan thanks for reporting! We're running a big backlog of update jobs and have upped our worker count to get through this so should clear out today.

**Comment by ryanblock** [comment]
Thanks @feelepxyz!
