### ISSUE TITLE
Error bumping dependencies (PHP Composer)

### ISSUE THREAD

**Issue by tombonez** [dependabot/feedback#714]
Hi,

I hope you're doing well!

I've had an issue for a little while now with my Composer file being flagged with "Error bumping dependencies" when an update is due (I've purposely left a dependency behind to help debug this).

The Dependabot project URL is: https://app.dependabot.com/accounts/tombonez/repos/208536201

The repo is set to private, so if you need me to post my Composer file or would like access just let me know.

Thanks in advance,
Tom :)

**Comment by rebelagentm** [comment]
Hi! 👋 I think you need to add the `ACF_PRO_KEY` to your environment variables in the dashboard (https://app.dependabot.com/accounts/tombonez/config-variables).

**Comment by tombonez** [comment]
Hi @rebelagentm 

Thanks for the reply!

I originally thought this might be the issue but the error still persists after adding it.

I do however have a second variable in my Composer file but Dependabot states `Only the following ENV keys are allowed: ACF_PRO_KEY` which is preventing me from adding the second variable `GRAVITY_FORMS_KEY`.

Any idea on how I can resolve this?

Thanks in advance,
Tom :)

**Comment by feelepxyz** [comment]
@tombonez yeah this will probably prevent the update. We could also allow this key to be added as a config variable. @rebelagentm would you be up for taking a look at adding this to the backend?

**Comment by tombonez** [comment]
Hi @feelepxyz 

Thanks for the reply!

This would be amazing if possible.

Cheers,
Tom :)

**Comment by rebelagentm** [comment]
> @rebelagentm would you be up for taking a look at adding this to the backend?

I'll take a look.

**Comment by feelepxyz** [comment]
@tombonez is there a reason you've added `&t={%version}` in the url for `advanced-custom-fields/advanced-custom-fields-pro` and `ver={%version}` in the url of `gravityforms/gravityforms` - this seems to be causing problems when we run composer complaining that the version environment variable isn't set.

**Comment by tombonez** [comment]
Hi @feelepxyz 

Yes, basically this passes the package version into the URL to make sure all environments are downloading the same version.

I believe this is handled via [private-composer-installer](https://github.com/ffraenz/private-composer-installer/blob/master/src/PrivateComposerInstaller/Plugin.php#L60), which is why it's not an environment variable. 

Cheers,
Tom :)

**Comment by tombonez** [comment]
If it'd be worth me setting up a dummy example of this in action via Composer, just let me know.

Happy to help out in any way I can.

Cheers,
Tom :)

**Comment by feelepxyz** [comment]
@tombonez ahh we don't run that plugin which is probably why this is failing. We're currently focusing most of our efforts on the GitHub integration so might take a while for us to get to this. 

We'd also appreciate any help if you're familiar setting it up. I think we would want to load it in our composer helpers here: https://github.com/dependabot/dependabot-core/tree/master/composer/helpers

**Comment by tombonez** [comment]
@feelepxyz Totally understandable! Even though this setup is supported natively in Composer (and required in my case), it certainly isn't a standard use case and for the mean time I don't mind updating my projects locally (as far as I know, without Dependabot I'd mostly be having todo this anyway 😜).

If I find time to get Dependabot setup locally along with a basic understanding on how it works, I'll see if there's anything I can do to help.

Cheers,
Tom :)

**Comment by tombonez** [comment]
@feelepxyz Looks like private-composer-installer has just been [updated](https://github.com/ffraenz/private-composer-installer/releases/tag/v3.0.0) to support inline version numbers in the Composer file without it clogging up composer.lock (there was a bug in the previous version that would keep adding versions to the end of the URLs).

I've gone ahead and updated my Composer file with inline version numbers, so hopefully with`GRAVITY_FORMS_KEY` added as a variable in Dependabot I should be good to go 🤞

Is it still okay to get this added? No worries if you're all too busy 🙂

Cheers,
Tom :)

**Comment by feelepxyz** [comment]
@tombonez sweet! This might work then, you should be able to add `GRAVITY_FORMS_KEY` from the dashboard: https://app.dependabot.com -

**Comment by tombonez** [comment]
Thanks @feelepxyz I've gone ahead and added the variable and now I have the following error:

```
Dependabot can't resolve your PHP dependency files.

As a result, Dependabot couldn't update your dependencies.

The error Dependabot encountered was:

The "https://[REDACTED]/?plugin=gravityforms&key=-&ver=2.4.14.6" file could not be downloaded (HTTP/1.1 404 Not Found)

If you think the above is an error on Dependabot's side please don't hesitate to get in touch - we'll do whatever we can to fix it.
```

So I assume there's more to a variable being added to the Composer file then I assumed (at least based on the error, the variable is just being replaced by a dash) ☹️

Cheers,
Tom :)

**Comment by feelepxyz** [comment]
@tombonez you're right, we also need to add support in our auth proxy. Will have a look at adding this, hopefully get to it in the next couple days.

**Comment by tombonez** [comment]
Thanks a ton @feelepxyz 🙂

**Comment by feelepxyz** [comment]
@tombonez think this is fixed now 🙏 Can you confirm?

**Comment by tombonez** [comment]
It most certainly is, I just received a pull request and merged the updates 😃

Thanks a ton both @rebelagentm and @feelepxyz on this one, really appreciate it!

**Comment by rebelagentm** [comment]
Glad we could help!
