### ISSUE TITLE
Wrong version in "bump from" title

### ISSUE THREAD

**Issue by web2033** [dependabot/feedback#716]
For several times already I see this behavior (same version "from" and "to"):

![2019-10-16_095347](https://user-images.githubusercontent.com/11320080/66895448-8218bd80-effb-11e9-9828-e51e4a2e5f49.jpg)

**Comment by feelepxyz** [comment]
@web2033 thanks for reporting! Taking a look.

**Comment by feelepxyz** [comment]
@web2033 deploying a fix for this.
