### ISSUE TITLE
Configure updates from private Maven repository

### ISSUE THREAD

**Issue by triffer** [dependabot/feedback#717]
Hi, 

We have a private Maven repository hosted on Cloudsmith. This repository is also configured with the correct credentials in Dependabot's config variables.
As build tool we use Gradle and the repository is also included in the Gradle config.
Unfortunately Dependabot does not create PRs, although there are new versions of dependencies.

Is there anything else to consider when configuring that we might have missed?

Thanks in advance

**Comment by rebelagentm** [comment]
@feelepxyz Thoughts on what might be happening here?

**Comment by paddycarey** [comment]
Paddy from @cloudsmith-io here, happy to help debug on our side if needed, just shout :)

**Comment by feelepxyz** [comment]
@triffer which repo are you seeing this issue on? We can check the logs to see what might be wrong. If it's a private repo please email it to [support@dependabot.com](mailto:support@dependabot.com).

**Comment by triffer** [comment]
@feelepxyz Thanks. I wrote an email, because it is a private repo.

**Comment by rebelagentm** [comment]
👋 We received your support e-mail and looked into it.  Unfortunately, we don't support private repositories in Gradle at the moment.  We're keen to add support for this, but we're pretty swamped at the moment, so it may be some time before we get to adding this.

We're going to open a separate tracking issue for this.

**Comment by rebelagentm** [comment]
New tracking issue:  https://github.com/dependabot/feedback/issues/755
