### ISSUE TITLE
Provide option to configure format of branch name

### ISSUE THREAD

**Issue by edkellena** [dependabot/feedback#72]
Hey,
It would be super awesome if we could specify some format for the branch name created.

Use-case:
Our CI system sees a PR raised and will run through a build process that generates a Docker image and tags it with the branch name.  Unfortunately Docker tags have more limited scope than Git branches...
`A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.`

The `/` in the Dependabot branches is causing that tagging to fail.  We can work around this with some awk/shell wizardry I guess, but would be nice not to have to do this.

**Comment by greysteil** [comment]
Thanks for the feedback @edkellena.

It's a totally legit request, but I'm not keen on changing things on Dependabot's side for a couple of reasons:
- branch name generation is already [quite complicated](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/pull_request_creator/branch_namer.rb) and I don't want to add more considerations to it
- there's no obvious place to put the setting in the frontend at the moment

Do you have control over the build process on your side? I'm hoping it would be straightforward for you to sanitize the branch name when generating a tag.

**Comment by edkellena** [comment]
Fair enough 👍 I did wonder whether it would be a fruitless ask!   Would be happy to attempt a PR for the generation, but without the UI setting available, that would be a bit pointless.

I do have some very hacky workaround at the moment, which I'll try to unhack soon.  Cheers though!

**Comment by greysteil** [comment]
Always worth asking! Thanks for understanding 🙂 .

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#396
