### ISSUE TITLE
Getting dependabot pings w/o installing

### ISSUE THREAD

**Issue by tapaswenipathak** [dependabot/feedback#723]
Hey: Receiving dependabot pings w/o installing in any of my repositories.

- https://github.com/tapaswenipathak/Help-The-Needy/pull/4
- https://github.com/tapaswenipathak/Open-Source-Programs/pull/179

What's going on? Can you please help?

**Comment by msfjarvis** [comment]
Like the PR says, these were created by GitHub through dependabot after they scanned your repository and found vulnerable dependencies.

**Comment by feelepxyz** [comment]
@msfjarvis thanks for explaining! @tapaswenipathak we're currently rolling out Dependabot as part of GitHub Security Alerts which is why it's now available to any GitHub repository that has enabled Security Alerts. You can opt out from future pull requests in your account security settings: https://github.com/settings/security

**Comment by tapaswenipathak** [comment]
I read wrong, thanks, disabled. Weirdly, I received pings only these repositories and many repositories are running Django.

**Comment by rebelagentm** [comment]
@tapaswenipathak We haven't finished the rollout yet, so it may not have reached all of your repositories just yet.  Also, it would only affect repos for which you have Security Alerts enabled.

**Comment by tapaswenipathak** [comment]
@rebelagentm: Just an FYI, I don't have any security alerts enabled, even for these repositories.

**Comment by rebelagentm** [comment]
@feelepxyz Any idea why @tapaswenipathak would be seeing these even with security alerts turned off?

**Comment by feelepxyz** [comment]
Strange! That definitely shouldn't be happening, @tapaswenipathak what do you see under the "Security" tab for the repository?

When Security Alerts are enabled it will look something like this:

<img width="1165" alt="Screenshot 2019-10-31 at 09 50 31" src="https://user-images.githubusercontent.com/20165/67936556-e7f07200-fbc3-11e9-9c77-7dd2e01c5161.png">

When disabled:

<img width="1122" alt="Screenshot 2019-10-31 at 09 51 11" src="https://user-images.githubusercontent.com/20165/67936631-0b1b2180-fbc4-11e9-801f-69047655bd26.png">

**Comment by tapaswenipathak** [comment]
@feelepxyz: I have no security alerts enabled. Do you see the little Django alert of critical severity?

![](https://i.gyazo.com/ab194e5b32a7a1a07e97add33787e863.png)

 Wrong, right?
