### ISSUE TITLE
CircleCI checks didn't run

### ISSUE THREAD

**Issue by chrishenry** [dependabot/feedback#725]
Hi, really loving the idea of Dependabot. Super helpful for resolving small security issues that typically wouldn't surface in my day to day.

I had Dependabot open a few PRs for my private repo today. Upon inspecting, none of them had checks run. I use CircleCI, and my required checks were all in the orange, executing state, but there were no jobs being run on Circle. I also asked dependbot to rebase one, hoping that would trigger the workflow, but no luck there either.

This makes Dependabot less automatic than intended. Hope there's a resolution!

**Comment by feelepxyz** [comment]
@chrishenry thanks for the feedback! 🙏Hmm sounds like a potential issue with Circle not kicking off a job when the PR was openened though? Are the jobs by any chance queued in Circle?

**Comment by NNTin** [comment]
I'm not using CircleCI but I know from Travis and Azure Pipelines that you can configure the CI which jobs are to be run depending on if it was a branch commit from the same repo, if it was a pull request coming from the same repo, if it was a pull request coming from a fork repo.  

It is good that such differentiation exist. Because a malicious attacker could commit bogus code and through the automatic CI testing tell it to leak the set environment variables by doing some POST requests.

**Comment by chrishenry** [comment]
Hi there, @feelepxyz. We checked, and there weren't any queued builds, so I don't think that was the issue. To be clear, this is an active repo correctly configured, and running lots of jobs thru circleCI everyday. 

What I'm not sure of is if we have to do additional configuration to ensure that jobs opened by dependabot are run through the normal pipeline. Is anyone aware of actions that we need to take?

**Comment by feelepxyz** [comment]
@chrishenry strange! Don't think it's a Dependabot issue though as we have no control over what checks get run on a created PR. Have you been in touch with CircleCI about the issue?

**Comment by feelepxyz** [comment]
Going to close this out, let us know if there's anything we could do on our side but pretty sure this will be an issue with Circle not picking up webhooks from GH (or something similar).

**Comment by chrishenry** [comment]
Hi! I had meant to update this. 

Not sure if anything changed with Dependabot, but the last PR it opened had jobs run correctly in CircleCI.

**Comment by tasos31** [comment]
@chrishenry 
Did you solve this?
Started facing the same problem today.
Half of the PRs from dependabot dont run circleCI checks for some reason.

**Comment by chrishenry** [comment]
Hi @tasos31. I hadn't done anything differently, PRs just started running. 

Recently, I also saw builds fail due to lack of seats on CircleCI, so that might be something for you to checkin into.
