### ISSUE TITLE
Dependabot making more changes then required

### ISSUE THREAD

**Issue by bmalinconico** [dependabot/feedback#726]
Dependabot seems dead set on downgrading the ruby gem `google-protobuf`. Every PR which it has submitted includes this change inappropriately. What information can I provide you with to help diagnose this issue further?

![image](https://user-images.githubusercontent.com/19909708/67496920-2ed1eb00-f64b-11e9-9b26-16e92ccb6619.png)

**Comment by feelepxyz** [comment]
@bmalinconico looks like 3.10.0 was yanked which is why bundler wants to downgrade: https://rubygems.org/gems/google-protobuf/versions/3.10.0

**Comment by bmalinconico** [comment]
Ah thank you, sorry for the unnecessary issue

**Comment by feelepxyz** [comment]
@bmalinconico no worries! Thanks for flagging it, always good to sanity check our updates 🙌
