### ISSUE TITLE
Dependency gets auto-merged when not all checks are green

### ISSUE THREAD

**Issue by shockie** [dependabot/feedback#727]
I'm seeing some PR's getting merged before all the checks are green. On this project, we auto merge dependencies for Javascript, we have two checks:
* **stale**: Github Action, a check that happens within seconds.
*  **CI build**: external CI build service, which takes some time (some minutes).

![](https://img.springe.st/2019-10-25_0944-34.png)

You see that only one of the two checks was completed ( the stale check was complete, CI was not) before dependabot decided to merge the PR back into `master`.

I have another example that confirms this behavior, unfortunately the project is private so I can't link directly to the PR.

My assumption is that dependabot waits for all the checks to be successful, according to your configuration info:

> Dependabot can automatically merge dependency update PRs for you. **For all of the options below we'll wait until all your status checks pass before merging**. You can also set working hours for automerging in your account settings.

**Comment by feelepxyz** [comment]
@shockie 👋 This is sadly a limitation to how GitHub checks works where they sometimes don’t get set as pending on the PR right away.

You can set some checks as required to prevent merging: https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks
