### ISSUE TITLE
Pull Request Opening Process Is Incredibly Noisy Borderline Psychotic In Design

### ISSUE THREAD

**Issue by postables** [dependabot/feedback#731]
Overall dependabot is great, however it is *incredibly* noisy. Lets say it needs to update 6 dependencies, each of these dependency updates will require a separate PR. Then when that PR is merged, the remaining 5 need to be re-based. 

For 6 PRs, this means we need to run a total of **30 differrent builds in ci** that is legitimately insane. There is no reason to require this noisy of a process, and the entire process would be infinitely more smooth if all dep updates were merged into a single PR.

**Comment by postables** [comment]
Actually I underestimated the 30 different buids. When using Travis CI which treats a PR with 2 builds (branch, and pull request) that means 6 PRs requires **60 different builds in ci**.

**Comment by feelepxyz** [comment]
Will close this issue and track progress in the existing issues.

**Comment by postables** [comment]
Wooo!!! Glad to hear this is on the minds of the dependabot devs! And good to know about the rebase disabkr
