### ISSUE TITLE
GitHub Security history: "Integration Dependabot was granted access to additional repositories"

### ISSUE THREAD

**Issue by dentarg** [dependabot/feedback#737]
Just want to check, is this correct behaviour from Dependabot? I haven't actively been granting access to additional repos that recently that many times. 

Is this from just merging a pull request created by Dependabot? It says "git" as "actor" on most of them.

![Screenshot 2019-10-30 at 18 57](https://user-images.githubusercontent.com/42626/67885786-7b845d00-fb48-11e9-8055-c36d2187323a.png)

**Comment by brrygrdn** [comment]
Hi @dentarg!

We are in the process of rolling Dependabot out to all repositories, as part of that process we are now installing it on your account - or adding repositories to an existing install - when we detect a manifest file being pushed.

In this case, the actor of 'git' is correct as it is being added to the install in response to a pushed change.

I hope that answers your question!

**Comment by dentarg** [comment]
@brrygrdn thanks for the quick reply and clarifying that

A follow-up question, I can see some (older) Dependabot repositories_added events that specify a, to me, completely unrelated GitHub username as actor. Why is that? I sent this to support@github.com with more details, see Ticket ID: 443237

**Comment by brrygrdn** [comment]
@dentarg We are aware of an issue where the incorrect actor was being attributed to the Dependabot actions that is now resolved. I'll refer to your ticket and verify that it is indeed the known issue.

**Comment by dentarg** [comment]
> A follow-up question, I can see some (older) Dependabot repositories_added events that specify a, to me, completely unrelated GitHub username as actor.

I got the following explanation from GitHub Support

> The good news is that this does not represent any kind of security breach or threat - this is a slight error in the way our system has logged things.
>
> Dependabot installation is opt-in-by-default, and it uses manifest files to co-ordinate its activity. If there is no manifest file (or the current one hasn't been updated in 90 days) then our system is primed to re-check for manifest files as soon as someone views the /network/dependencies page of the repository (and install Dependabot if it's not already installed).
>
> The error on our part was recording the browsing user as the source of the change, rather than our Dependabot system, and we're working on updating that now!

**Comment by alexalemanhdz** [comment]
> @dentarg We are aware of an issue where the incorrect actor was being attributed to the Dependabot actions, that is now resolved. I'll refer to your ticket and verify that it is indeed the known issue.

I have a recent Dependabot action attributed not to it but to "ghost", the profile for deleted accounts. Is that a bug or is it expected behavior?
