### ISSUE TITLE
No PR created for one of our private repositories + no issue created

### ISSUE THREAD

**Issue by tectac** [dependabot/feedback#738]
Hi,

We are experiencing a intriguing "issue" with one of our `private` repository named `core-lambda`.
- It contains 1 "simple" solution file with 20+ `.net core 2.1` projects
- Issues are enabled in this repository
- The Dependabot Preview GitHub Apps is installed
- I can currently see 8 available nuget package updates using Visual Studio

Dependabot seems to be able to scan our repository successfully but it does not create PRs or issues.

Is there a way to check the logs to see what is going on?

**Comment by rebelagentm** [comment]
👋 Looking at a dry run of Dependabot, I get eight packages updated:

- AWSSDK.SQS
- AWSSKD.S3
- Microsoft.Extensions.Configuration
- Microsoft.Extensions.Configuration.EnvironmentVariables
- Microsoft.Extentsions.DependencyInjection
- System.Data.SqlClient
- Microsoft.Extentions.Http
- RavenDB.Client

I know our queue had a bit of a backlog to process, so it's possible there was just a delay in the issues getting created.  Can you tell us if you're still experiencing this issue?

**Comment by tectac** [comment]
Well

These are the current opened & closed PR. No issues.

![image](https://user-images.githubusercontent.com/5117668/67995295-a8d62580-fc84-11e9-9a01-c0cd9a58a197.png)

![image](https://user-images.githubusercontent.com/5117668/67995284-93f99200-fc84-11e9-82b8-fc586b1e2860.png)

Dependabot says our repo was scanned 3 hours ago
![image](https://user-images.githubusercontent.com/5117668/67995328-d327e300-fc84-11e9-9e07-4c84cc537885.png)

Dependabot works really well for our other repositories.

**Comment by rebelagentm** [comment]
Dependabot is picking up the private registry `http://nuget.executivecentre.net/index.json`, but it is not finding any versions.  We get a `NoSuchKey` error.  Is there perhaps credentials that you need to configure on Dependabot so that it can access your registry?

**Comment by tectac** [comment]
That's weird because this solution does not rely on nuget packages available on this nuget repository. Also it's working for other solutions (in other GitHub repositories) relying on this nuget repository.

Also since this repo is not protected by a username/password can your remove the URL?

Thx
Seb

**Comment by rebelagentm** [comment]
Removed the URL.  Sorry about that!

In your configuration for Dependabot, you have some config variables.  That configuration contains the Nuget repository that was popping up for this repo.  When I did a dry run that doesn't include the config variables, Dependabot finds the updates.  When Dependabot runs with the config variables, it does not find the updates.

Unfortunately, Dependabot does not currently have a way to set per-repo config variables, so you've hit a limitation in what Dependabot can do for this repo.  To override your config variables for this repo, you could add a `nuget.config` file to it that specifies the default `nuget.org` source.  I tested this out locally, it and it appears to work.

**Comment by tectac** [comment]
After adding a custom nuget.config, it works great!
