### ISSUE TITLE
build(devDeps): bump ... violates config-conventional

### ISSUE THREAD

**Issue by ianwremmel** [dependabot/feedback#74]
The capital "D" in "devDeps" violates the all-lowercase scope rule specified by [config-conventional](https://www.npmjs.com/package/@commitlint/config-conventional) and, I believe, [config-angular](https://www.npmjs.com/package/@commitlint/config-angular).

**Comment by exactlyaron** [comment]
This was fixed in here - https://github.com/dependabot/dependabot-core/issues/560   😃

**Comment by greysteil** [comment]
Yep, sorry about this one! New commits will use the `deps-dev` scope.

**Comment by ianwremmel** [comment]
Awesome, thanks!
