### ISSUE TITLE
Doesn't update yarn.lock for repo using workspaces

### ISSUE THREAD

**Issue by Gregoor** [dependabot/feedback#740]
Heya, thanks for the hard work :)

It looks like dependabot is not updating our `yarn.lock` file in a yarn workspace repo, despite the docs saying it should be supported. Bug or misconfiguration on our side?

Here's an example PR:
https://github.com/mdn/stumptown-renderer/pull/209

**Comment by rebelagentm** [comment]
Hi!  Thank you!  We're glad you're enjoying Dependabot.

We'll take a look at what's going on.

**Comment by feelepxyz** [comment]
@Gregoor yes this should work but you'll need to change the directory to the root `/` so Dependabot picks up the workspaces config in `package.json` and the `yarn.lock` file.

You should be able to edit this from your [Dependabot dashboard](https://app.dependabot.com/accounts/mdn).

**Comment by Gregoor** [comment]
Oh my, didn't realize there was a dashboard. That solved it. Thanks for taking the time to look into this!
