### ISSUE TITLE
NuGet live-updates are delayed for more then an hour

### ISSUE THREAD

**Issue by Konard** [dependabot/feedback#742]
Hello, a have multiple repositories and all of the use dependabot just because if the work can be done by a bot - it should be done by a bot, not a human. Human should save their time. But dependabot for last months seems to delay pull request for NuGet packages for quite a long time (this is noticeable when I'm trying to make as much of updates to the packages as possible in the single day) . Even `bump` button does not help.

**Comment by feelepxyz** [comment]
@Konard hey we're working in improving this as we've seen quite a lot of growth the last month resulting in our queues backing up several times.

**Comment by feelepxyz** [comment]
This should now be fully resolved, GitHub also had an outage causing webhooks to take a while to deliver which is also sorted.
