### ISSUE TITLE
PHP: Dependabot is updating additional composer dependencies instead of just a single one

### ISSUE THREAD

**Issue by marcaddeo** [dependabot/feedback#745]
Recently Dependabot has created two PR's on our (private) repository. Both of them are updating two dependencies, when they should only update a single.

The first PR is titled `Bump symfony/phpunit-bridge from 4.3.4 to 4.3.6`, and as the title says it updates the `symfony/phpunit-bridge` dependency as expected. However, for some reason the `drupal/google_tag` dependency is also updated.

Expected:
![image](https://user-images.githubusercontent.com/199649/68221963-4187e080-ffb8-11e9-897d-7dcc4d6340ae.png)

Unexpected:
![image](https://user-images.githubusercontent.com/199649/68222031-5ebcaf00-ffb8-11e9-9241-f156e018d550.png)

In our `composer.json` for `drupal/google_tag` we have:
`"drupal/google_tag": "1.x-dev",`

So it's a dev dependency, and we're not locking it into a specific hash or anything... But I don't think that should get updated.

When I run `composer update symfony/phpunit-bridge` locally, the `drupal/google_tag` dependency does not get updated. So it seems to be an issue with how Dependabot is updating composer packages.

**Comment by feelepxyz** [comment]
@marcaddeo ah yes could well be an issue, nice one on debugging it on your end. Could I ask you to also try deleting any local cache/installed packages and then running `composer update symfony/phpunit-bridge` to be sure it's not a composer issue? We mostly delegate updates to composer so just want to make sure we are looking at the same starting point.

**Comment by marcaddeo** [comment]
@feelepxyz after a cache clear, it appears I am able to reproduce the issue lately. I suppose that makes this a Composer issue, or user error. But this behavior doesn't seem normal to me, so...

**Comment by feelepxyz** [comment]
@marcaddeo ah yeah it could be that the version requirement `1.x-dev` is too loose and composer decides to re-check it every time it updates. `npm` does a similar a thing and I found the only way around it was to set a stricter version requirement and then let Dependabot keep it up to date.

**Comment by marcaddeo** [comment]
Yeah I'm not sure whats going on with that package.. They seem to have some sort of virtual dev releases.. or something, too... i.e. `8.x-1.2+3-dev` -> `8.x-1.2+10-dev`. I'm thinking maybe they removed the previous virtual releases or whatever, and now Composer is just trying to solve the problem and updating it as it goes. Or it just treats dev releases differently and updates them when it pleases... I thought `npm` was the only heathen, so hopefully that's not the case :)

**Comment by marcaddeo** [comment]
Well, this can be closed. I'll probably just lock it into a specific commit hash for now.
