### ISSUE TITLE
Automerge not working

### ISSUE THREAD

**Issue by tlvince** [dependabot/feedback#751]
I've enabled automerge on my [eslint-config-tlvince](https://github.com/tlvince/eslint-config-tlvince/blob/dc0302f3d91e3ced469e43fe6a0d37f6d6c4c530/.dependabot/config.yml) repo (as well as in my Dependabot account settings). However, there are currently [3 open Dependabot PRs](https://github.com/tlvince/eslint-config-tlvince/pulls) that have not automerged.

A branch protection rule (that status checks must pass) has been applied to this repo. Could this be the issue?

![Screenshot from 2019-11-05 23-55-28](https://user-images.githubusercontent.com/323761/68256520-5308d100-0028-11ea-9093-30cde9edcf32.png)

Either way, the status checks have passed on Dependabot's PRs, so I would've expected them to be automerged.

**Comment by tlvince** [comment]
Repo settings (in case it helps):

![image](https://user-images.githubusercontent.com/323761/68293000-f4be0b80-0084-11ea-82ef-f99ee5dc7542.png)

**Comment by tlvince** [comment]
Auto-merge now appears to have "just worked":

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/323761/68298781-2a1d2600-0092-11ea-9770-3c1fa53e33d1.png">

I didn't change anything on my side 🤔 Is there a certain condition its looking for, or perhaps it just takes some time?

**Comment by feelepxyz** [comment]
@tlvince nice one! We've had an outage over the last few days causing our queues to back up and get delaued, on top of this GitHub had another outage causing webhooks to take a long time to deliver which would have delayed any automerges.

Both issues have now been fully resolved so going to close, let us know if this crops up again!

**Comment by tlvince** [comment]
Thank you!

Out of interest, does Dependabot have a status page?

**Comment by feelepxyz** [comment]
@tlvince not yet, we will probably integrate into the GitHub status page at some point.
