### ISSUE TITLE
 Dependabot encountered an unknown error - in multiple repositories

### ISSUE THREAD

**Issue by esakal** [dependabot/feedback#757]
Hello,
I'm getting error `Dependabot encountered an unknown error` both in:
1. github dashboard > security tab
2. https://app.dependabot.com/ 

The error **happens** on multiple public repositories.
- https://github.com/kaltura/playkit-js-kaltura-live
- https://github.com/kaltura/playkit-js-qna
- https://github.com/kaltura/playkit-js-transcript

It **works** on some other repositories in our company like:
- https://github.com/kaltura/playkit-js-contrib
- https://github.com/kaltura/playkit-js-hotspots

Please advice,
Eran.

**Comment by feelepxyz** [comment]
@esakal hey sorry for the delay on this! It looks like we're failing to download one of your path dependencies (`kaltura-typescript-client`) because it's over 1mb in size. This is a limitation of the GitHUb repo contents API. I'm looking into this, not sure we actually need to fetch the contents of this dependency to be able to complete the update.

**Comment by feelepxyz** [comment]
@esakal did some more investigation and looks like we can't easily omit fetching the path tarballs as this breaks resolution. Would it be possible for you to include your path dependencies uncompressed instead? We would then only download the included `package.json` file.

**Comment by esakal** [comment]
@feelepxyz thanks for helping me with this one. I though the local tar file might cause this problem but when I pointed dependabot to a branch which didn't include this dependency it still failed.

when you say `include your path dependencies uncompressed` do you mean keeping this library content uncompressed? if so this is a bit problematic as it contains more the 2000 files. any other alternative?

**Comment by feelepxyz** [comment]
> when you say `include your path dependencies uncompressed` do you mean keeping this library content uncompressed? if so this is a bit problematic as it contains more the 2000 files. any other alternative?

@esakal I see! Yeah that's not great. The problem is currently that the GitHub API doesn't allow files larger than 1 MB using the contents API. Do you need to bundle the packed dependency in the project? Could you publish it as a private dependency on npm?

> I though the local tar file might cause this problem but when I pointed dependabot to a branch which didn't include this dependency it still failed.

Which repo was this on?

**Comment by feelepxyz** [comment]
@esakal hey totally missed that we already deal with fetching large files from GitHub we just had some bad code for dealing JS specific path dependencies that meant we tried to fetch `..path/package.tgz/package.json`.  Working on a fix here: https://github.com/dependabot/dependabot-core/pull/1519

**Comment by esakal** [comment]
@feelepxyz awesome! I just started getting PRs for those two repositories. Thanks!

**Comment by feelepxyz** [comment]
@esakal great news! Thanks for reporting.
