### ISSUE TITLE
[Feature request] Support vendoring for Python

### ISSUE THREAD

**Issue by Kristinita** [dependabot/feedback#76]
### 1. Request

It would be nice, if would be possible upgrade dependencies, not only version numbers in requirements file.

For example, it would be nice add an option, that bot will run command after each version changing in requirements file.

### 2. Steps to reproduce

I develop plugins for Sublime Text, written on Python. By technical reasons I need add dependencies to my repository.

In my [**repository for testing**](https://github.com/Kristinita/SashaAnotherPyup) I add outdated version of [**PyPI gsearch**](https://pypi.python.org/pypi/gsearch) module to `requirements.txt` file. I use command:

    pip install -r requirements.txt -t . --upgrade

### 3. Justification

Automatically dependencies upgrading may save developers time.

I test Dependabot on my test repository. Dependabot only [**change dependency version**](https://github.com/Kristinita/SashaAnotherPyup/pull/2) in `requirements.txt` file, but not upgrade my gsearch dependency, that I include to my repository.

I need upgrade my dependency manually; after merging I need run command again:

    pip install -r requirements.txt -t . --upgrade

It would be nice, if Dependabot will run this command automatically after each version change in `requirements.txt` file.

Thanks.

**Comment by greysteil** [comment]
Thanks for the feedback @Kristinita. This one will require quite a bit of work on our side, given the way we currently update Python files (it's using regexes, not shelling out to Python). I'd like to do it in future, though, so will keep it here as a reminder.

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#400
