### ISSUE TITLE
[PHP] dependabot does not create PR to update dependencies

### ISSUE THREAD

**Issue by Lctrs** [dependabot/feedback#761]
Dependabot does not create PRs to update dependencies in my PHP library anymore.

Running dry run script tells me update is not possible, but I don't know why.

Repo URL : https://github.com/Lctrs/DBAL-Specification

Output of dry run : 
```bash
[jparmentier@toolbox dependabot-core]$ bin/dry-run.rb --requirements-update-strategy=increase_versions --dep=phpunit/phpunit composer Lctrs/DBAL-Specification
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.5-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> fetching dependency files
=> dumping fetched dependency files: ./dry-run/Lctrs/DBAL-Specification/
=> parsing dependency files
=> updating 1 dependencies

=== phpunit/phpunit (8.4.2)
 => checking for updates
 => latest version from registry is 8.4.3
 => latest resolvable version is 
 => requirements to unlock: update_not_possible
 => requirements update strategy: increase_versions
    (no update possible)
```

**Comment by Lctrs** [comment]
Found out why. Will update this with an explanation next week.

**Comment by feelepxyz** [comment]
Great! Thanks for going through the effort of testing the dry run 😍 Let us know if there anything you believe could be handled better in dependabot-core.

**Comment by Lctrs** [comment]
Soooo... Better late than never.

What happened then ?

Before running `composer`, dependabot will get your lowest supported PHP version in your `composer.json` (at key `require.php`) and put it in the key `config.platform.php` so that composer will resolve the updates of your dependencies on your lowest supported PHP version no matter what PHP version `composer` is actually running on.

Problem is that when one of the library that you depends on requires a higher version of PHP, `composer` will not be able to resolve your dependencies to an installable set because it thinks it doesn't run on an high enough PHP version.

Example : I was requiring php `^7.2` in my library, so dependabot put `7.2` in the key `config.platform.php`. But one of my dependency (`infection/infection`) requires PHP `^7.2.9`, so resolving my dependencies was impossible.

If you came across this issue, be aware that behaviors of both dependabot and composer are correct on all of this. To fix this, you should raise your minimum PHP version to match the ones of your dependencies.

**Comment by Lctrs** [comment]
See https://github.com/dependabot/feedback/issues/761.

**Comment by Lctrs** [comment]
Sorry if I'm not very clear, english is not my primary language.

**Comment by Lctrs** [comment]
Enhancement idea : add support for bumping the key `require.php` like any other dependencies. Could be done by parsing the response of https://www.php.net/releases/index.php?json&max=100&version=7.2 for example.

**Comment by feelepxyz** [comment]
@Lctrs thanks for writing that up! 🙇 Would you be up for creating a new issue for the enhancement idea? We could then close this out and track the feature request only.

**Comment by Lctrs** [comment]
@feelepxyz I finally don't think this is a good idea. Could trigger a lot of failed CI builds depending on which PHP version is available on it...

I think a better idea could be to create an issue in users' repositories to let them know something is wrong (#739 ?).

**Comment by feelepxyz** [comment]
@Lctrs yes we're keen to improve this. We've been thinking of solving it with better logs or a UI view of your dependencies that clearly shows what the maximum resolvable version is. I don't think we want to open Issues as this would create a lot of noise for big projects. Going to close this one out. It's high up on our list of priorities already to expose this information somehow but will take some time as we're focused on integrating Dependabot with GitHub for the next few months.
