### ISSUE TITLE
dependabot-preview not generating the security patch PRs

### ISSUE THREAD

**Issue by chenrui333** [dependabot/feedback#762]
I noticed recently that the dependabot-preview did not generate the security patch PRs.

For example, this repo, https://github.com/meetup/pro-web

**Comment by chenrui333** [comment]
@feelepxyz Do you have any ideas about this? I am still having this issue. Thanks!

**Comment by feelepxyz** [comment]
@chenrui333 sorry for the slow reply! Looks like there is one dependency which hasn't received a PR where it should have (`https-proxy-agent`). Looking into this.

There are a few others that can't be updated/are not vulnerable:
- moment (blocked by convict@4.0.1)
- utile (no patch available)
- tar and protobufjs are not vulnerable (we might have some incorrect security alert data on these though)

**Comment by feelepxyz** [comment]
@chenrui333 looks like you've hit your open pull request limit (10) which is why you are not receiving any more pull request. If you merge some of these you should start receiving PRs again or up the limit in your dashboard settings: https://app.dependabot.com/accounts/meetup/settings

**Comment by chenrui333** [comment]
I see. Totally make sense, just updated the setting on this.

**Comment by chenrui333** [comment]
It works. Thanks a lot!

**Comment by feelepxyz** [comment]
Turns out we also had some bad data for `https-proxy-agent` which is now fixed 👌

**Comment by chenrui333** [comment]
@feelepxyz looks like set-value vulnerability never generates PR:

![image](https://user-images.githubusercontent.com/1580956/71336057-9d300e00-2513-11ea-8338-5b26d0d3b5ff.png)

**Comment by chenrui333** [comment]
Please ignore the generating message.
