### ISSUE TITLE
Hitting '#/update_configs' had more items than the allowed 125

### ISSUE THREAD

**Issue by craigbensemann** [dependabot/feedback#765]
We have a large monorepo and have been using dependabot for a few months. I've been slowly adding more and more projects to the config.yml and just hit the max 125 number of update configs.

I have a couple of questions. 

What is the recommended best practices for adding update_configs - should you create a single entry for say maven at the root level or multiple maven entries for each submodule. I see a trade off between having to upgrade a dependency across the entire repo in one go with the former and a more fine grained upgrade/rollout in the later.

Some package managers (eg docker) require a docker file at the directory specified and do not search sub directories. This forces you to add an entry per Dockerfile in your repo. Currently we have 150 Dockerfiles in the repo. This alone is more than the limit. How can we deal with this? Could we increase the 125 max limit?

Our repo is private but I'll email through the details in case it helps.

Thanks
Craig

**Comment by feelepxyz** [comment]
@craigbensemann we've increase the limit to 250 per repository. We can't yet lift this more as we are constrained by our backend and GitHub rate limits per repository which we risk hitting otherwise.
