### ISSUE TITLE
[info] composer version

### ISSUE THREAD

**Issue by captn3m0** [dependabot/feedback#766]
What's the composer version running for PHP updates?

Asking because composer version differences cause changes in case, order of JSON for some reason.

**Comment by feelepxyz** [comment]
@captn3m0 it looks like we always install the latest one for PHP 7.3: https://github.com/dependabot/dependabot-core/blob/master/Dockerfile#L106 so should be at `1.9.1`,

**Comment by captn3m0** [comment]
Thanks a lot. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
