### ISSUE TITLE
Support Jinja Templating in requirements files

### ISSUE THREAD

**Issue by jamescurtin** [dependabot/feedback#769]
I maintain a [Python cookiecutter library](https://github.com/cookiecutter-flask/cookiecutter-flask) and would like to be able to include conditional blocks in in requirements files so that the dependencies in the output project are tailored to the user's inputs.

Currently, dependabot fails to parse requirements files if they contain Jina templates. Example failure:
```python
InstallationError('Invalid requirement: \'{%- if cookiecutter.use_heroku == "yes" %}\' (from line 11 of /home/dependabot/dependabot-updater/dependabot_tmp_dir/prod.txt)')
```
And the corresponding change I made that temporarily resolved the issue: [PR](https://github.com/cookiecutter-flask/cookiecutter-flask/pull/582/files)

-----

Would you consider adding this functionality? (For reference, it appears that Pyup supports this functionality. [Example Pyup PR](https://github.com/pydanny/cookiecutter-django/pull/2310/files))

**Comment by rebelagentm** [comment]
👋 Thanks for writing in!  The team has been pretty swamped lately and we have a large number of feature requests and enhancements.  But we'll take this into consideration as soon as we can.
