### ISSUE TITLE
Github Commit Profile Image Missing

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#77]
I know this is a small thing, but I was wondering if this was a bug. If you see [here](https://github.com/RohanNagar/thunder/commits/master) the profile image of dependabot is the default Github image, and not the bot image.

Perhaps this is a side effect of doing the "Squash and Merge"?

**Comment by greysteil** [comment]
Thanks for the feedback @RohanNagar.

@sbarnekow - one for someone from GitHub?

**Comment by sbarnekow** [comment]
Thanks for the ping @greysteil 😄  Could you pass that on to support@github.com so it can get routed to people working on it?

**Comment by greysteil** [comment]
Thanks @sbarnekow. Looks like this might be fixed now, though! 🎉

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#401
