### ISSUE TITLE
Dependabot creating bugs for missing Gopkg.toml in go:modules repo

### ISSUE THREAD

**Issue by MirahImage** [dependabot/feedback#771]
The .dependabot/config.yml contains the line
`- package_manager: "go:modules"` but dependabot continuously opens issues with
`Dependabot couldn't find a Gopkg.toml for this project` in our project.

Unfortunately, the repository is not public, so we have emailed this to dependabot-support@github.com as well.

**Comment by feelepxyz** [comment]
@MirahImage looking into this! Will respond to the email ticket with any follow up and close this 👌

**Comment by MirahImage** [comment]
Thanks for helping us figure out what was going on!
