### ISSUE TITLE
Dependabot encountered unknown error

### ISSUE THREAD

**Issue by micahbeeman-wf** [dependabot/feedback#773]
My private repository is unable to run dependabot due to an unknown error: https://app.dependabot.com/accounts/Workiva/repos/19081101

Is there a way to tell what the problem is? The repository is https://github.com/Workiva/janitor

^ I tried emailing support since this is a private repository but haven't heard back.

**Comment by rebelagentm** [comment]
👋 We can look into it.  We're also working on ideas to provide more visibility into logs to provide customers with more troubleshooting info.

I'm not sure which support channel you e-mailed, but would you mind sending the user/org and repo name over to dependabot-support@github.com?

Thank you!

**Comment by micahbeeman-wf** [comment]
@rebelagentm That is the email address I sent my initial message to on November 18.

**Comment by feelepxyz** [comment]
@micahbeeman-wf sorry for the delay! It looks like one of your requirements files includes a tarball which we don't fully support yet. Will take a look at adding support.

**Comment by micahbeeman-wf** [comment]
The tarball I was using has since been made into a public pypi package so I switched to using that and this issue was resolved! Thanks!
