### ISSUE TITLE
Dockerfile downgrade RC to BETA

### ISSUE THREAD

**Issue by grachevko** [dependabot/feedback#779]
dependabot replaced latest `7.4.0RC6-fpm-buster` version of php to older `7.4.0beta4-fpm-buster.`

https://github.com/automagistre/automagistre/pull/278

**Comment by feelepxyz** [comment]
@grachevko thanks for reporting! Looks like Dependabot doesn't handle the uppercase `RC6` properly and thinks it's lower than the beta version. Will get this fixed.
