### ISSUE TITLE
Report dependabot errors as issues in the repository

### ISSUE THREAD

**Issue by CAFxX** [dependabot/feedback#784]
It would be great if dependabot could open an issue in the repo when it encounters an error. We have many private repos, and sometimes dependabot starts to choke on one of them, but the only way we can discover it is by:
- noticing that dependabot is not opening PRs anymore on that specific repo (hard to notice when you have many repos)
- go on app.dependabot.com and notice there is an error reported for that repo

If dependabot, after failing a few runs on a repository, could open an issue on the repository then this problem would be easier to notice and remediate. Bonus points if the issue contains the specific error message and it is auto-closed once dependabot completes one successful run.

**Comment by rebelagentm** [comment]
Hi! 👋 Dependabot should be doing this already.  Have you enabled "Issues" on the repo(s)?

**Comment by CAFxX** [comment]
@rebelagentm almost all repos accept issues creation. Note though that repos are private.

**Comment by rebelagentm** [comment]
@CAFxX So just to confirm, Issues are enabled on most of your repos?

@feelepxyz Would the repos being private prevent Dependabot from being able to open these issues?

**Comment by feelepxyz** [comment]
@CAFxX weird! What you laid out is literally what Dependabot **should** be doing already.. which repo are you seeing this on? If it's a private repo please email it to [dependabot-support@github.com](mailto:dependabot-support@github).
