### ISSUE TITLE
Dependabot does not find tensorflow2

### ISSUE THREAD

**Issue by epa095** [dependabot/feedback#785]
Suddenly dependabot claims that it can not resolve `tensorflow==2.0.0` 
[Link](https://github.com/equinor/gordo-components/issues/758)

**Comment by shields-fn** [comment]
It looks like Dependabot is now using Python 3.8. `tensorflow` is on PyPI only as wheels, and none are posted for 3.8.

**Comment by epa095** [comment]
Look like that was the reason, thanks @shields-fn  :-)

**Comment by shields-fn** [comment]
@epa095 Is this fixed for you? Our builds continue to fail to resolve.

It took months after Python 3.7's release for Tensorflow to ship packages, so this likely won't become moot for a while.
