### ISSUE TITLE
feature request: auto-merge in-range updates

### ISSUE THREAD

**Issue by christopherthielen** [dependabot/feedback#79]
I'm using dependabot for javascript.  

### Feature Request: 
I'd like the ability to auto-merge any in-range updates.  It would be even better if those in-range updates could be consolidated into a single PR. 

I want to have two workflows with dependabot:

- In range updates: auto-merge (assuming CI passes).  I assume the changes will not break my app.  However, I'd like CI to run to verify this. After CI passes, I want my package.json and yarn.lock file updated and committed.
- Out of range updates: Run CI, but do not auto-merge.  I need to manually check breaking changes.

## Additional thoughts

 Dependency updates can be categorized in a few different ways:

1) in-range (matches the package.json semver)
2) out-of-range
3) minor
4) patch
3) dev deps
4) normal deps
5) security
6) something else that I haven't thought of

### Matrix?

Maybe these could be seen as a matrix:

| - | In range  | Out of range | Minor | Patch | Security | 
| - | - | - | - | - | - |
| Normal deps| X |  |  |  | X |
| Dev deps  | X |  |  |  | X |

I could pick and choose which matrix elements I want auto-merged

### Tags?

Maybe each PR could get Tags which categorize the update type.  The tags could be real github tags, or dependabot only (I don't think it really matters):

Example PR with tags:

**build(deps): bump yargs from 11.0.0 to 12.0.1** [_Development_] [_OutOfRange_] [_Major_]

Then maybe I can create a set of auto-merge combinations:

- Automerge this combination: **[OutOfRange]** + **[Development Dep]**
- Automerge this combination: **[InRange]** + **[Development Dep]**
- Automerge this combination: **[Security]** + **[Development Dep]**
- Automerge this combination: **[Security]** + **[InRange]** + **[Normal Dep]**

...but that might be overcomplicating things.

Looking forward to your feedback

**Comment by greysteil** [comment]
Thanks for the feedback @christopherthielen!

Did you already see the automerge options Dependabot currently has? If you click to edit one of your update configs, or look in the advanced options section when adding a new language, you can ask Dependabot to automerge patch, security, minor or all updates, differentiating between dev and runtime dependencies. You can also specify working hours to do the automerging in (we only released that [yesterday](https://dependabot.com/blog/automerge-working-hours)).

**Comment by greysteil** [comment]
Interesting, thanks for the extra detail.

I think this is a good idea - I'll take a look at implementing it.

BTW, Dependabot won't automerge pre-1.0.0 dependencies or anything else that clearly doesn't follow SemVer (like CalVer dependencies), but tricky deps like `typescript` do pose a problem.

**Comment by greysteil** [comment]
Shipped! 🚢 

![image](https://user-images.githubusercontent.com/1144873/42392781-f8d05dd8-8121-11e8-93a1-070ef8df0a53.png)

**Comment by schoenwaldnils** [comment]
Where can I find this option?

**Comment by feelepxyz** [comment]
@schoenwaldnils it's currently in private beta but happy to add your account! Which github account do you want it enabled for?
