### ISSUE TITLE
Add support Github actions (version tags of other repo's action)

### ISSUE THREAD

**Issue by ChristophWurst** [dependabot/feedback#790]
Hi,

I would like to ask if it would be possible to have Dependabot update used Github actions. I'm new to them but as far as I can tell you usually include a certain version, which is a git tag in another repo. To keep up with changes in the used actions, it would make sense to have Dependabot updates version tag if a newer one exists.

## Example

https://github.com/nextcloud/mail/blob/88ba5d8f5f623ea15325a1594b84c2d0e5339d74/.github/workflows/lint.yml#L42 -> whenever a tag newer than `v1` exists, I would like to receive a PR.

I couldn't find any existing tickets about this.

Thanks :rocket:

**Comment by rebelagentm** [comment]
👋 Hi!  I believe that we do support GitHub Actions.  Support for it was added here:  https://github.com/dependabot/dependabot-core/pull/1313

**Comment by ChristophWurst** [comment]
Right! Totally missed that PR.

![Bildschirmfoto von 2019-12-09 19-55-12](https://user-images.githubusercontent.com/1374172/70463791-ddc46c00-1abd-11ea-96ad-89d31e15a81f.png)

It's currently disabled. But great to hear this is being worked on :)

**Comment by hazcod** [comment]
Is there any news when this would be enabled?
