### ISSUE TITLE
Detect/Keep Python version constraints?

### ISSUE THREAD

**Issue by David-Guillot** [dependabot/feedback#794]
Hi there,

I'm not sure this is a bug or if we're missing something in our config.

* Context: pip-compile
* Dependency to bumping: [kombu](https://github.com/celery/kombu/), from 4.6.6 to 4.6.7
* Characteristic of this update: [kombu's changelog](https://github.com/celery/kombu/blob/master/Changelog.rst#467) tells us that they now require external `importlib-metadata` only for Python<3.8 as it's now part of the standard lib. That's implemented [here](https://github.com/celery/kombu/pull/1086/files)
* Expected behavior: here I'm not sure what's best, between:
  * Be able to tell Dependabot that we are using Python 3.6 for now on our project
  * Let Dependabot keep this Python version constraint as-is for it to apply to our project
* Actual behavior: Dependabot seems to consider our project as Python 3.8 and simply removes `importlib-metadata` in its PR for bumping `kombu`

Are we missing something? Is there a way to tell Dependabot that it should consider our project as a Python 3.6 project? Or is this some kind of bug?

Thanks in advance.

PS : this issue occurs on a private repo, so I'm opening a related Github support case, but I wanted this to be public since we most likely won't be the only ones to face it.

**Comment by waghanza** [comment]
@David-Guillot I think there is no way to define a `python` **version** for _dependabot_, but specifying `python_requires="3.6"` on your `setup.py` will tell to `pip` to search only for package with `Programming Language :: Python :: 3.6` **classifier**.

Perhaps it will help :stuck_out_tongue: 

PS : Giving us your project URL can help to find a workaround

**Comment by David-Guillot** [comment]
It's a private repo, so I can't link it from here. I have opened a case to Github/Dependabot Support, let's see how it goes.

Thanks for your suggestion @waghanza ; unfortunately our project doesn't have any `setup.py` file for now, as we are using `pip-tools` with multiple `*.in` files generating multiple `requirements-*.txt` files. I tried to create a minimal `setup.py` specifying `python_requires="3.6"`, it didn't have any impact when running `pip-compile -P kombu`, so probably won't change Dependabot behavior either...

**Comment by paddycarey** [comment]
We're seeing the exact same issue on some of our repos, we're on 3.7 and Dependabot PRs to libs like kombu are causing unnecessary removals of other deps like `importlib-metadata`. Like @David-Guillot we're also using `pip-tools` with multiple `*.in` files, no `setup.py`.

Have also opened a Github support case re: this issue so waiting to hear back there.

**Comment by David-Guillot** [comment]
## To those experiencing this issue

**Good news**: there is a workaround :tada:. You can create a separate `requirements-pyXX.txt` file containing explicit dependencies to whatever lib that your project needs under Python XX version and that Dependabot tries to delete with its shiny Python 3.8 dependency worker. As these dependencies are now explicit, Dependabot will stop deleting them and you'll be good to go.

Example on our repo:

#### Without the workaround
`requirements.in`
```
kombu==4.6.*
```
`requirements.txt` before Dependabot PR:
```
importlib-metadata==1.6.0  # via kombu
kombu==4.6.6
zipp==3.1.0               # via importlib-metadata
```
`requirements.txt` on Dependabot PR for upgrading kombu:
```
kombu==4.6.8
```
which makes our application crash on Python 3.6 as `importlib-metadata` is not in stdlib yet.

#### With the workaround
`requirements-py36.txt`
```
importlib-metadata==1.6.*
```
`requirements.in`
```
-r requirements-py36.txt
kombu==4.6.*
```
`requirements.txt` before Dependabot PR:
```
importlib-metadata==1.6.0  # via -r requirements-py36.txt
kombu==4.6.6
zipp==3.1.0               # via importlib-metadata
```
`requirements.txt` on Dependabot PR for upgrading kombu:
```
importlib-metadata==1.6.0  # via -r requirements-py36.txt
kombu==4.6.8
zipp==3.1.0               # via importlib-metadata
```
which is what we wanted :tada: .

## To Dependabot team

Although this workaround is not so ugly, probably Dependabot should expose to users the ability to choose which Python version will compile/upgrade their dependencies. What do you think?

**Comment by David-Guillot** [comment]
@rebelagentm maybe? :arrow_up:

**Comment by sfdye** [comment]
The syntax you used in `setup.py` might be problematic.

Maybe try something like:
```
python_requires='>=3.6,<3.8',
```

Full spec:
https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires

**Comment by paddycarey** [comment]
Github support got back to me eventually on this one, you can add a `.python-version` file to the root of your repository and dependabot will respect that when making updates.

**Comment by sfdye** [comment]
So it's pyenv behind the scene then 🤔

**Comment by David-Guillot** [comment]
Oh that's great @paddycarey , thanks a lot for sharing this! Haha Dependabot could document that they're using pyenv with standard Python version numbers, it fixes our issue so easily 👍
