### ISSUE TITLE
Automerge even if there are no CI checks

### ISSUE THREAD

**Issue by JClackett** [dependabot/feedback#796]
Is it possible to auto merge without having CI checks?

A few projects of mine dont use CI and i would still like the pull requests to be merged, is this possible at all?

Thanks

**Comment by feelepxyz** [comment]
@JClackett 👋 currently not possible with Dependabot but you could use a GH Action to do it, for example https://github.com/pascalgn/automerge-action triggering on PRs with the `dependencies` label (assuming this is what Dependabot adds on your PRs, you can change this using a config file https://dependabot.com/docs/config-file/#default_labels).

Hope that helps!

**Comment by JClackett** [comment]
Sounds exactly like what i need, thankyou!
