### ISSUE TITLE
Not receiving updates after move of repository from personal account to organization

### ISSUE THREAD

**Issue by localheinz** [dependabot/feedback#797]
### Moved repository from personal account to organization

Since moving the repository https://github.com/localheinz/php-library-template from my personal account @localheinz to the organization @ergebnis, I have not received any updates anymore.

With the move, the repository URL has changed

```diff
-https://github.com/localheinz/php-library-template
+https://github.com/ergebnis/php-library-template
```

### Integration is enabled

When taking a look at https://app.dependabot.com/accounts/ergebnis/repos/101747763, authorized users can see that the integration is enabled:

![Screen Shot 2019-12-15 at 11 08 06](https://user-images.githubusercontent.com/605483/70861223-35822d80-1f2b-11ea-8074-2261e266b103.png)

### Not receiving updates after move

However, I have not received any updates since moving, and I would have expected at least an update for [`phpunit/phpunit:8.4.3...8.5.0`](https://github.com/sebastianbergmann/phpunit/compare/8.4.3...8.5.0) (see [`composer.json`](https://github.com/ergebnis/php-library-template/blob/0b624306084f4bc8c0d36b333f8c4c6b025d18ac/composer.json#L27).

For example, here's a similar pull request that was opened in https://github.com/localheinz/phpstan-rules/pull/153 **before** moving from @localheinz to @ergebnis.

This also applies to all other repositories moved from my personal account @localheinz to the organization @ergebnis.

### Need help

Can you advise what needs to be done here from my side, or perhaps find out if this is an issue on your side?

**Comment by feelepxyz** [comment]
@localheinz it looks like it's working but that the update isn't possible due to a version constraint from another package, it looks like `infection/infection` has a requirement on `phpunit/phpunit < 8.4`.

The setup looks fine otherwise 👍

**Comment by localheinz** [comment]
@feelepxyz 

Thank you for your feedback! 

I'm closing this issue for now.

**Comment by feelepxyz** [comment]
@localheinz nice one, let us know if you run into any further issues. We're investigating providing more context in the logs as to why Dependabot didn't do an update. You can already check the last update's logs in the dashboard by clicking on the link `last checked 1 day ago` (it will say `no update possible` when it's blocked by another dependencies version constraint but not which one or why yet).

**Comment by localheinz** [comment]
Wonderful!

Thank you, @feelepxyz!
