### ISSUE TITLE
How to tell if config.yml is being parsed?

### ISSUE THREAD

**Issue by ElijahLynn** [dependabot/feedback#799]
I added https://github.com/department-of-veterans-affairs/va.gov-cms/blob/master/.dependabot/config.yml but it doesn't seem to be honoring it. The validator validated it. It would be nice to have a way to plug in a URL of a repo and get some information back on if it is currently being scanned etc. 

I have also opened an enterprise issue with GitHub, `#498940`.

**Comment by feelepxyz** [comment]
@ElijahLynn can you see the added php project in the [Dependabot dashboard](https://app.dependabot.com)?

if it's not showing you'll need to add the repository to the [Dependabot Preview](https://github.com/apps/dependabot-preview) app installed in your [org settings](https://github.com/organizations/department-of-veterans-affairs/settings/installations)

**Comment by feelepxyz** [comment]
@ElijahLynn ah can see that everything except `allowed_updates` and `automerged_updates` has been picked up. You can check the parsed config file in the [dashboard](https://app.dependabot.com/) by clicking on the cog icon for the composer project.

Looking into why these settings have not been picked up.

**Comment by feelepxyz** [comment]
@ElijahLynn ah you need to enable automerging from your account settings, here's an issue that was created https://github.com/department-of-veterans-affairs/va.gov-cms/issues/791

**Comment by ElijahLynn** [comment]
Wow, we rarely use "issues" on this project so I never even looked there. Thank you so much for highlighting this! 

Even if automerging isn't enabled, it should have made the PR already though, right? 

I'll work on getting automerging enabled now.

**Comment by ElijahLynn** [comment]
I think it isn't making the PR because there are 10 open PRs, which we have set to be the max. open PRs.

**Comment by feelepxyz** [comment]
@ElijahLynn no worries! You can check the logs in the dashboard to see what happened in the last update run by clicking on the link `last checked ...`.

**Comment by ElijahLynn** [comment]
K, I also see mixed behavior when I go to my fork setup here https://app.dependabot.com/accounts/ElijahLynn/ and click settings, it shows the UI config. 
![image](https://user-images.githubusercontent.com/1504756/71195076-0c6edf00-2242-11ea-8d43-b99d62d76cee.png)


And when I go to the same for the source, I see it shows the config.yml file instead of the UI (expected). 

![image](https://user-images.githubusercontent.com/1504756/71195131-26a8bd00-2242-11ea-9ed7-01e208ffdbdc.png)

So the way to confirm that a repo is scanning correctly is to go there and see the above screenshot, and then look for _issues_ regarding it.

**Comment by ElijahLynn** [comment]
My fork had the previous default branch of `develop` and upstream had changed default to `master` recently. Changing my default branch to `master` in repo and then "bump now" has my fork showing the config correctly now.

**Comment by ElijahLynn** [comment]
And another issue is that the validator didn't detect that the package name was non-existent. I was using "va.gov/web" and the actual name is "va-gov/web".

**Comment by ElijahLynn** [comment]
Nope, I was wrong, I was using the latter. Still not pulling in that update after latest check, logs don't show it. 

Logs say:

> updater | INFO <job_18255722> Latest version is aac333ed6a49c91c66bef7cd4815437d4526c239
updater | INFO <job_18255722> Requirements to unlock update_not_possible
updater | INFO <job_18255722> Requirements update strategy bump_versions_if_necessary
updater | INFO <job_18255722> No update possible for va-gov/web e17a3cc82ac8a80b67704f205b44cfd1026e425f****

**Comment by ElijahLynn** [comment]
Looking at https://github.com/dependabot/feedback/issues/761 now that mentions php version issue.

**Comment by feelepxyz** [comment]
@ElijahLynn hm that error is returned when dependabot can't update to the new version because of some other dependencies requirement preventing it from working. Could you debug installing that locally to see if it's compatible with the other packages?

> And another issue is that the validator didn't detect that the package name was non-existent. I was using "va.gov/web" and the actual name is "va-gov/web".

Yeah this is tricky at the moment as the validator would have to have access to your repo to validate these.

**Comment by feelepxyz** [comment]
> Looking at #761 now that mentions php version issue.

Yup this is also a common cause for that error 👍

**Comment by ElijahLynn** [comment]
> @ElijahLynn hm that error is returned when dependabot can't update to the new version because of some other dependencies requirement preventing it from working. Could you debug installing that locally to see if it's compatible with the other packages?

Just tested this with `composer update va-gov/web` and works fine on the master branch. 

It would be easier to test locally if we could see the composer command used in the logs.

**Comment by ElijahLynn** [comment]
In summary, I don't think this has anything to do with php version in this case. That dependency doesn't have a php version specified. va-gov/web dependency is here https://github.com/department-of-veterans-affairs/vets-website/blob/master/composer.json

**Comment by feelepxyz** [comment]
@ElijahLynn sad times, looks like dependabot can't deal with php git updates. Didn't know this was the case. Could you open a new issue for this? 🙇

**Comment by ElijahLynn** [comment]
> @ElijahLynn sad times, looks like dependabot can't deal with php git updates. Didn't know this was the case. Could you open a new issue for this?

Done, thanks for the support and direction > https://github.com/dependabot/feedback/issues/803 (I'll be out on vacation until the 6th, no connectivity so apologies for the non-response ahead of time).
