### ISSUE TITLE
Ignore behavior question

### ISSUE THREAD

**Issue by regentgal** [dependabot/feedback#80]
If dependabot submits a PR to move a gem from 1.1.1 to 2.0.0 and we decide to ignore that major version, will we still get another PR if the maintainers issue 1.2.0 or 1.1.2? 

We're looking into using and have a number of older gem versions that we won't be able to update straight away for various reasons. But we still usually want the minor or patch updates.

**Comment by greysteil** [comment]
Hey @regentgal.

At the moment the Dependabot always tries to update you to the latest resolvable version for your `Gemfile`/`mix.exs`/`composer.json`/etc.. Most of the time that will do what you want (most Rails 4.1 Gemfiles are blocked from updating to 5.2 by other dependencies, so will get 4.1.1 -> 4.1.2 PRs if/when they're released) but it's not perfect in the case where you've explicitly asked to ignore a major version that you could update to. Making that better is on my list :-)

**Comment by greysteil** [comment]
A quick update on this one: I just shipped the option to only receive lockfile updates (blog post [here](https://dependabot.com/blog/lockfile-only-updates)). If you've got a Gemfile that only locks the major version on a few things then that *could* be a good option for you to solve the above - it means Dependabot will always honour the requirements specified in your Gemfile, so if you've got `< 2.0.0` in there then you'll get PRs to update to `1.2.0` or `1.1.2` with that option.

Longer term, I want to get Dependabot working like that with ignore conditions, too, but it's painful - Ruby doesn't allow "or" conditions for requirements, so if you tell it to ignore `2.x.x` I don't have a way to specify that Dependabot should be looking for resolvable updates in the range `< 2.0.0 || > 2.0.0`. I'm sure that's a solvable problem, but I don't have an answer for it yet.
