### ISSUE TITLE
Auto-merge set to minor updates should also merge patch updates

### ISSUE THREAD

**Issue by bradleypriest** [dependabot/feedback#80]
I'm not sure if I'm misunderstanding something, but I have a bunch of projects with auto-merge set at different levels.

When a new patch update of a Rubygem comes in the projects with auto-merge set to patch get merged, but the projects with auto-merge set to minor do not.
Surely, auto-merge of minor should encompass patch changes as well.

Does this sound correct, or is there something else going on here?

**Comment by greysteil** [comment]
Huh, that doesn't sound correct - the ones set to minor should be getting merged, too. Can you @-mention dependabot on a PR where that's happened and I'll take a look?

**Comment by bradleypriest** [comment]
So looking a bit closer, the PR says it will be auto-merged, but then doesn't.

![image](https://user-images.githubusercontent.com/167215/42427815-33c41ca2-8363-11e8-9cf2-bf5e6c7de858.png)

**Comment by greysteil** [comment]
Ah, do you not have any CI on that repo? Automerge only works if you've got some tests. I could change that but it's a bit risky...

**Comment by bradleypriest** [comment]
Ok, it's completely unrelated and a coincidence.
The projects I've set to auto-merge minor patches are the less important ones, turns out they also just don't have a CI set up, they're that unimportant.

Seems like if there are no status checks it doesn't auto-merge, which seems like a good call, but maybe you can tweak the message to explain that?

**Comment by greysteil** [comment]
👍
