### ISSUE TITLE
Feature Suggestion: Signed Commits

### ISSUE THREAD

**Issue by davidgoate** [dependabot/feedback#81]
Is there any way that Dependabot could create the PR's with signed commits?

We utilise GitHub branch protection that requires signed commits. 

It's not a huge problem as a regular merge commit from an author who is signing their commits works just fine via the GitHub UI. 

However, it'd be great if dependabot did sign the commit:

1. For extra comfort
2. For a cleaner tree on the base branch since then we would be able to "rebase and merge" via the UI *(currently this is prevented due to the commit being signed)*.

**Comment by greysteil** [comment]
Hey @davidgoate,

I'm probably missing something here, but I'm pretty sure Dependabot already signs its commits. What would you want to be different about, say, the commit in [this PR](https://github.com/dependabot/dependabot-core/pull/578)? Is that `verified` badge not showing up on PRs to your repo?

**Comment by davidgoate** [comment]
@greysteil sorry, you're quite right. I jumped to this conclusion and I should have checked - sorry.

What I have noticed is that after I turn on branch protection in the base branch which requires signed commits I can no longer rebase dependabot PR's. An error message appears saying that GitHub can't sign the commit.

**Comment by greysteil** [comment]
👍 and no worries!
