### ISSUE TITLE
Unable to add Dependabot as a user with push access to my protected branch rule

### ISSUE THREAD

**Issue by romrell4** [dependabot/feedback#815]
This issue was referenced in https://github.com/dependabot/feedback/issues/86 with a workaround, but the issue is now closed, so I don't think anyone's working on it. The workaround will not work for our organization, so I'm hoping that someone can restore the original ability to type "Dependabot" into the search text box after checking "Restrict who can push to matching branches" so that dependabot can automatically merge its own pull requests.

**Comment by feelepxyz** [comment]
@romrell4 deployed a fix for this. Can you confirm it works?
