### ISSUE TITLE
Combine Golang and React repositories 

### ISSUE THREAD

**Issue by regel** [dependabot/feedback#827]
I’m getting started with dependabot. The UI lets me select one single language for one repository. This is a limitation for Golang+React projects where both Gopkg.lock and package-lock.json files are present.

How can I configure Dependabot to use one repository and verify updates for two languages?

**Comment by feelepxyz** [comment]
@regel after adding the first language you add additional languages from the dashboard Home page, underneath the repo:

<img width="687" alt="Screen Shot 2020-01-22 at 09 49 18" src="https://user-images.githubusercontent.com/20165/72883583-7a546d80-3cfc-11ea-858b-a153334a1176.png">
