### ISSUE TITLE
Branches created with slashes causing problem

### ISSUE THREAD

**Issue by dastanko** [dependabot/feedback#829]
We have circleci setup which uses branch names in its build process and it fails with branch names containing slashes. I turned off the setting to use slashes in branch names in dependabot web UI. And now when I hit the "Bump now" button it doesn't regenerate PRs with new branch names without slashes nor `@dependabot recreate` doesn't help. 

Is there any way to recreate existing PRs with new branch names?

**Comment by feelepxyz** [comment]
@dastanko sorry for missing this one, there's currently no way to recreate with a new branch name. You'll have to close the open pull requests and wait for a new version to come around because of the way we assume closed PRs mean to ignore this version.
