### ISSUE TITLE
Support rebase strategy

### ISSUE THREAD

**Issue by Kruspe** [dependabot/feedback#831]
Dependabot should have an option to automatically rebase and merge the PRs it creates.

If you only work on master and run with rebasing if there is a dire need for a branch dependabot automerge feature really clutters your commits with bunch of merge commit. I would like to see an approach to support rebasing strategy by dependabot.

**Comment by eliasnorrby** [comment]
@Kruspe I believe what you're looking for is already available in the dependabot account settings. If you log in to your account at https://app.dependabot.com, there's a checkbox under the Account Settings called "Create a merge commit if a PR is merged by Dependabot". I believe it's checked by default. If unchecked, dependabot will merge the PR just as if you had done it manually using the "Rebase and merge" option, and the target branch (`master`) will have a linear history. 

<img width="374" alt="Screenshot 2020-05-28 at 13 52 02" src="https://user-images.githubusercontent.com/11960052/83138493-295de700-a0eb-11ea-8506-24f44acb9016.png">

What bugs me about this is that it seems to be an exclusively account-wide setting. I would have liked for it to be configurable on a repo-by-repo basis.

**Comment by Kruspe** [comment]
Thanks @eliasnorrby! Have been looking for the option to turn it on. Never occurred to me that it could be an option to turn of merge commits ^^ Amazing!
