### ISSUE TITLE
github-redirect.dependabot.com returns Netlify not found error

### ISSUE THREAD

**Issue by jakejarvis** [dependabot/feedback#832]
In recent bump PRs, clicking a link to an upstream issue, PR, etc. that routes through github-redirect.dependabot.com shows an SSL error about the certificate only being valid for *.netlify.com, and then displays a Not Found error.

Example:
- https://github.com/jakejarvis/jarv.is/pull/44  (click # 233 under release notes)
- https://github-redirect.dependabot.com/kentcdodds/cross-env/issues/223

Thanks! 😊

**Comment by hmarr** [comment]
Thanks for reporting this! We're working on it. We're hoping to have it fixed today.

**Comment by hmarr** [comment]
This is taking slightly longer than we expected, but I'm pretty confident we'll have it wrapped up tomorrow. Sorry for the inconvenience!

**Comment by jakejarvis** [comment]
No need to apologize, not an urgent bug at all. Appreciate the updates!

**Comment by hmarr** [comment]
Fixed. Thanks for bearing with us!
