### ISSUE TITLE
User 0897726477 showing up as making commits

### ISSUE THREAD

**Issue by RohanNagar** [dependabot/feedback#84]
I noticed today that all of dependabot's commits have changed to be from this user: https://github.com/0897726477.

This includes pull requests that have already been merged.

See for example https://github.com/RohanNagar/thunder/pull/59.

Thanks for all your work!

**Comment by greysteil** [comment]
Thanks for the heads up. This is a GitHub issue - that account registered the support@dependabot.com email address with GitHub this morning, and even the email address wasn't verified (I forwarded the verification email to GitHub's support immediately), it is therefore being linked to from Dependabot commits.

I'm working with GitHub to get that fixed immediately (should be done in the next 10 mins).

**Comment by RohanNagar** [comment]
Great thanks, it looks resolved!

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#408
