### ISSUE TITLE
Support for bumping Go vendoring tool configs (dep, vgo, etc)

### ISSUE THREAD

**Issue by hairyhenderson** [dependabot/feedback#84]
Support would likely end up being a little different from other languages, but it'd be nice if dependabot could tell me when my dependencies managed by [dep](https://github.com/golang/dep) or [vgo](https://github.com/golang/dep) have changed.

Thanks!

**Comment by greysteil** [comment]
I'm super up for adding Go support - issue tracking it on dependabot-core [here](https://github.com/dependabot/dependabot-core/issues/449). Might be a little while yet, but I'll definitely get to this!

**Comment by hairyhenderson** [comment]
Awesome, thank you @greysteil!
