### ISSUE TITLE
Unable to evaluate Elixir 1.10 project

### ISSUE THREAD

**Issue by supernova32** [dependabot/feedback#844]
Dependabot can't evaluate your Elixir dependency files.

As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.

The error Dependabot encountered was:

```
** (FunctionClauseError) no function clause matching in Parser.parse_lock/1    
    
    The following arguments were given to Parser.parse_lock/1:
    
        # 1
        {:hex, :bcrypt_elixir, "1.1.1", "6b5560e47a02196ce5f0ab3f1d8265db79a23868c137e973b27afef928ed8006", [:make, :mix], [{:elixir_make, "~> 0.4", [hex: :elixir_make, repo: "hexpm", optional: false]}], "hexpm", "10f658be786bd2daaadcd45cc5b598da01d5bbc313da4d0e3efb2d6a511d896d"}
    
    parse_deps.exs:69: Parser.parse_lock/1
    parse_deps.exs:19: Parser.build_dependency/2
    (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
    parse_deps.exs:101: (file)

{"error":""}
```

This happens when evaluating https://github.com/AlloyCI/alloy_ci and started happenign yesterday after I updated the dependencies and bumped the Elixir version to 1.10. I tried relaxing the requirement to 1.9 as well and it still failed.

**Comment by supernova32** [comment]
Related issue created by @dependabot https://github.com/AlloyCI/alloy_ci/issues/263

**Comment by feelepxyz** [comment]
@supernova32 this should be fixed now 🎉
