### ISSUE TITLE
compatibility badge in PR has wrong link

### ISSUE THREAD

**Issue by slawekjaranowski** [dependabot/feedback#848]
Example
https://github.com/s4u/pgpverify-maven-plugin/pull/62

and badge provide to:
https://dependabot.com/compatibility-score.html?dependency-name=com.google.guava:guava&package-manager=maven&previous-version=20.0&new-version=23.0

**Comment by feelepxyz** [comment]
@slawekjaranowski thanks for reporting, will get this fixed up 👍

**Comment by feelepxyz** [comment]
@slawekjaranowski should be fixed now 👍
