### ISSUE TITLE
Auto-merge seems to be broken?

### ISSUE THREAD

**Issue by JayH5** [dependabot/feedback#85]
Hi again 👋 

I have some PRs that weren't merged by Dependabot, for example [this one](https://github.com/praekeltfoundation/debian-wheel-mirror/pull/195), which says:
```
If all status checks pass Dependabot will automatically merge this pull request.
```

All status checks did pass, but ~13 hours later the PR still hadn't been merged and I had to do so manually.

This issue _seems_ to have appeared around the time that Dependabot asked for access to GitHub's Checks API. This particular repo doesn't use the new Checks API yet, since it is an older open-source project hosted on travis-ci.org. I'm not sure the Checks API has anything to do with the issue or is just a coincidence.

Thanks 🙏

**Comment by greysteil** [comment]
Thanks for flagging this - taking a look now.

**Comment by greysteil** [comment]
Ack, this is indeed checks related. Here's the problem:
- TravisCI had some auto-enrol logic that went a bit wrong (see [this issue](https://platform.github.community/t/feature-request-opt-out-list-for-github-app-repository-access/6022))
- GitHub's UI for checks is a little weird. Pending checks don't show up with a number in the checks tab, but if you click through to the checks tab on your PR you'll see that a queued check exists ([link](https://github.com/praekeltfoundation/debian-wheel-mirror/pull/195/checks))
- Dependabot recently started checking that PR checks were successful before automerging. The presence of a queued check means we hold off merging.

For your repo, I think the solution is to disable those travis checks, probably from within the Travis UI. As a more general Dependabot response, I'm going to contact GitHub and ask them to fix the way checks are displayed to make queued checks more obvious in the UI. I don't think there's a way for Dependabot to easily distinguish between genuinely queued checks and accidental cases like this one. 😢

**Comment by JayH5** [comment]
@greysteil thanks. Unfortunately, I can't find a way to disable those phantom queued Travis builds from within their UI 😢

Settings for the project on travis-ci.com don't seem to stick or have any effect. Until Travis provides a way to transfer open source projects from travis-ci.org to travis-ci.com we might be stuck.

**Comment by greysteil** [comment]
Interesting. I've just done a bit more research and I think Dependabot can actually ignore checks that are in this "queued" state - confusingly, I think they might be created by GitHub rather than Travis CI, and then they just sit there if Travis doesn't respond. I'm going change Dependabot so that it ignore them for now - will get things working in the short term at least.

**Comment by JayH5** [comment]
Thanks. Seems to be working again for that repo 😄
