### ISSUE TITLE
Should I freeze the packages in requirements.txt?

### ISSUE THREAD

**Issue by SVilgelm** [dependabot/feedback#850]
Hello,
Could you explain me how it works with python requirements?
Should I freeze all dependencies?
And the second question, does it work with any requirements.txt files? Like:
* requirements.txt
* dev-requirements.txt
* requirements-test.txt

**Comment by feelepxyz** [comment]
@SVilgelm 👋 Depenabot should scan for any `*.txt` files in the directory you specify. Dependabot will only update what's in your requirements txt file so freezing would make sense if you've installed stuff that's not in there.

**Comment by SVilgelm** [comment]
@feelepxyz thank you,
by freezing I mean setting exit versions.
Right now my it looks like:
```
ossaudit
pyyaml>=4.1
coverage
codecov
black; python_version >= '3.6'
flake8
```

Should I convert it to:
```
ossaudit==0.5.0
pyyaml==5.2
coverage==5.0.1
codecov==2.0.15
black==19.10b0; python_version >= '3.6'
flake8==3.7.9
```
?
I'm asisking because now the bot does nothing with this file

**Comment by feelepxyz** [comment]
@SVilgelm ah yeah you'll want to freeze in that case. Unlesss you have version's that need updating to match the latest released version Dependabot won't do anything.

**Comment by SVilgelm** [comment]
Ok, thank you!!!
