### ISSUE TITLE
How to configure to ensure matching versions of nested dependencies

### ISSUE THREAD

**Issue by ivanixgames** [dependabot/feedback#854]
Hello, 
Within an organization, we have several  private repos used as nested dependencies and we need the common dependencies to match.
I looked at the examples for  dependabot/config.yml but could't see a clear way to do this.

I understand that one issue is that dependabot currently does not poll / support internal github packages, but assuming I can find a workaround using github actions,  I would like to do the following:

![RandomizeDepDiag](https://user-images.githubusercontent.com/858678/74213949-676b0280-4cd6-11ea-9185-611bc1736de0.png)
 

Does this look feasible to do in config.yml and if so how?

**Comment by feelepxyz** [comment]
@ivanixgames 👋 interesting use case! It's not something you can set up with Dependabot at the moment. It only pulls versions from GitHub Packages at most once a day so would just update everything to the latest version available at that time. If you're using npm/yarn you could use peer dependencies to pin a common dependency at a specific version ([example](https://github.com/facebook/react/blob/master/packages/react-dom/package.json#L25-L27)) but Dependabot doesn't actually update this field it only tries to make sure it doesn't update the library to a version where it's violated.

**Comment by ivanixgames** [comment]
@feelepxyz  thanks for the tip! I may be able to get github action handle bumping  the peerDepency version
