### ISSUE TITLE
Security: How this user is able to review this PR?

### ISSUE THREAD

**Issue by crazy-max** [dependabot/feedback#856]
Don't know if it's flaw with GitHub itself or the way Dependabot creates PR to update dependencies but the user `@sadikkuzu` has been able to approve [this PR](https://github.com/crazy-max/ghaction-xgo/pull/76) without access rights to the repository:

![image](https://user-images.githubusercontent.com/1951866/74318155-fcc0d200-4d7c-11ea-84fd-2502209ae34f.png)

I also also noticed he approves a lot of them in other repositories within few minutes:

![image](https://user-images.githubusercontent.com/1951866/74318245-2548cc00-4d7d-11ea-9929-8f31d04504b6.png)

**Comment by crazy-max** [comment]
Ok after digging, it can be done in the `Files changed` tab. For example with [this PR](https://github.com/dokku/dokku/pull/3858) without being a contributor or requested:

![image](https://user-images.githubusercontent.com/1951866/74319525-62ae5900-4d7f-11ea-9c1d-9db902a1cb44.png)

**Comment by crazy-max** [comment]
Looking at [this doc](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/approving-a-pull-request-with-required-reviews), it seems to be the expected behavior :thinking:

**Comment by feelepxyz** [comment]
@crazy-max yeah I think that's expected behaviour for public repos but looks like the approved review check is greyed out due the user not having write access to the repo.

**Comment by crazy-max** [comment]
@feelepxyz Yes that's it. I think it would be nice if GitHub could allow a limitation or at least postpone abuse.

**Comment by feelepxyz** [comment]
@crazy-max yes the user has been reported a few times already, will look into it.
