### ISSUE TITLE
config.yml files are not being observed

### ISSUE THREAD

**Issue by echarrod** [dependabot/feedback#857]
I have enabled dependabot-preview on the following repositories, and also added a config.yml which is located in root/.dependabot/config.yml on master:
https://github.com/getyoti/yoti-python-sdk
https://github.com/getyoti/yoti-dotnet-sdk
https://github.com/getyoti/yoti-php-sdk
https://github.com/getyoti/yoti-go-sdk
https://github.com/getyoti/yoti-ruby-sdk
https://github.com/getyoti/yoti-node-sdk
https://github.com/getyoti/yoti-java-sdk

But these config files do not seem to be used when dependabot creates a PR, e.g.:
https://github.com/getyoti/yoti-python-sdk/pull/150
https://github.com/getyoti/yoti-dotnet-sdk/pull/153
https://github.com/getyoti/yoti-java-sdk/pull/172

I can see all of the repos in my dependabot dashboard:
![image](https://user-images.githubusercontent.com/1381991/74337550-64d0e180-4d98-11ea-84e9-6a2d66632209.png)

(I would expect this PR to have a base branch of `development`, and the specified default reviewers added)

I have validated the config on https://dependabot.com/docs/config-file/validator/ and they seem to be all ok.

**Comment by echarrod** [comment]
I don't think we did anything, but looks like a PR created today is now observing the file: 
https://github.com/getyoti/yoti-node-sdk/pull/139

**Comment by echarrod** [comment]
But not for almost the same config in a different repo:
https://github.com/getyoti/yoti-java-sdk/pull/174

**Comment by feelepxyz** [comment]
@echarrod if you click on the cog icon in the [dashboard](https://app.dependabot.com/) you'll see what's applied from the config file. If it's not applied you could try pushing a change to the file. It should get re-applied on every change to the file if it's valid according to the validator. Sometimes the webhooks are dropped or delayed (should be rare) which can cause the settings to not get set properly.

**Comment by echarrod** [comment]
Ok, I'll try updating the config file. 
Incidentally, when I commented with `@dependabot recreate` the correct base branch was used, but not the reviewers. Is this a bug?

**Comment by echarrod** [comment]
Seems to be fine now after pushing a change to the config file. Will close this
