### ISSUE TITLE
Merging PR creates 2 commits?

### ISSUE THREAD

**Issue by ChrisWiles** [dependabot/feedback#860]
I merge the PR and then two commits show up one from the bot then other from my merge

Merge pull request #459 from dropoff-co/dependabot/npm_and_yarn/devel…
Bump babel-eslint from 8.2.6 to 10.0.3

https://imgur.com/a/4T1PY06

**Comment by feelepxyz** [comment]
@ChrisWiles this is default behaviour with GitHub pull requests. If you click the little arrow next to `Merge pull request` you could select one of the other options that don't do this.

**Comment by ChrisWiles** [comment]
Thanks!
