### ISSUE TITLE
Dependabot API SSL certificate is invalid

### ISSUE THREAD

**Issue by hassankhan** [dependabot/feedback#861]
I cannot login via `app.dependabot.com` on Chrome 80.0.3987.106, I keep getting the following:

![app dependabot com_auth_sign-in](https://user-images.githubusercontent.com/1781985/74556543-30a31f80-4f56-11ea-8819-374e8c83f031.png)

I cleared cookies and local storage (to test) and now get this:

![app dependabot com_auth_callback_browser_session_id=77c3def1c7889ade90397beca68f1a3939a1cab2 code=3579094a93764401ca0b state=9f9df237-fb36-4abd-986f-ef7eee8f341e](https://user-images.githubusercontent.com/1781985/74556588-444e8600-4f56-11ea-8727-c0247bb21ecf.png)

Upon further examination, it seems like the SSL certificate for `api.dependabot.com` is invalid(?)

![image](https://user-images.githubusercontent.com/1781985/74556615-5cbea080-4f56-11ea-87ee-3e784468998b.png)

The weird thing is it seems to work fine on Firefox

**Comment by feelepxyz** [comment]
@hassankhan oh strange! It's using a LetsEncrypt certificate so not sure it's a widespread problem. Try uninstalling `Dependabot  Preview` from GitHub: https://github.com/settings/installations (you can then re-install from https://app.dependabot.com/ and restore the account)

**Comment by feelepxyz** [comment]
@hassankhan are you still seeing this issue?

**Comment by hassankhan** [comment]
@feelepxyz I am, but it seems like it's an issue with my system rather than with Dependabot. Closing the issue now, sorry for the noise.
