### ISSUE TITLE
Single Pull Request when using config file

### ISSUE THREAD

**Issue by Rashad-j** [dependabot/feedback#866]
**Problem explanation:** 
Let's say we have a repository with 4 outdated dependencies, then we usually get 4 Pull Requests at once when using web interface config (your website).
Now, after we switched to file-based config we get only one PR and when merged, we get the next PR next day(1 PR per day).
So, now it takes in general longer (4 days in the example above) than in the past (one day), it is a bit inefficient.

**Suggested solution:** 
Create all PRs at once when using config-file (similar when on-site config). 

The problem occurred in: [https://github.com/hexonet](url)

**Comment by papakai** [comment]
Today we got multiple PR's at once for one repository. Closing this issue therefore. We will continue monitoring this on our end. If necessary, we'll follow-up here.

@Rashad-j be so kind as to close this issue.
