### ISSUE TITLE
Terraform: Dependabot can't parse your main.tf

### ISSUE THREAD

**Issue by hazcod** [dependabot/feedback#868]
Issue: https://github.com/ironPeakServices/infrastructure/issues/17
File in question: https://github.com/ironPeakServices/infrastructure/blob/master/main.tf

Terraform version:
```hcl
terraform {
    required_version = ">= v0.12.19"
}
```

**Comment by feelepxyz** [comment]
@hazcod we're tracking HCL2 support here: https://github.com/dependabot/feedback/issues/671
We've paused most dependabot-core improvements as we integrate Dependabot Preview with GitHub. We're aiming to get back to these improvements in the next 3-6 months.

**Comment by hazcod** [comment]
@feelepxyz Thanks for the update, can't wait for the integration!
