### ISSUE TITLE
Ruby: error when using a gem from a branch.

### ISSUE THREAD

**Issue by davidwessman** [dependabot/feedback#87]
I first got a PR which bumped [Rails from 226406 to b2dbea](https://github.com/pensionsupplysning/web/pull/116) and when I merged this there was a new PR, bumping [Rails from 226406 to f763b2 ](https://github.com/pensionsupplysning/web/pull/118).

After merging the first PR I got conflicts in the second. When asking Dependabot to rebase it said that it was already up-to-date with master.

---

Btw, **I am so grateful for Dependabot**, now I feel like I can be proactive about my dependency management for my projects I'm maintaining.

**Comment by greysteil** [comment]
Thanks for the feedback. This definitely sounds like a bug - I’ll look into it as soon as I’m back from holiday (Friday). In the meantime, really glad to hear you’re enjoying Dependabot!

**Comment by greysteil** [comment]
Just dug into this and discovered a subtle race condition in Dependabot (and possibly a bug in GitHub). It's fixed now (on the Dependabot side), but FYI, here's what happened:
- **2018-02-13 02:14:35** Dependabot created [PR 1](https://github.com/pensionsupplysning/web/pull/116) to update Rails
- **2018-02-13 06:45:42** Dependabot started a new update run, basing PRs off the latest commit at this moment (`9c9347`)
- **2018-02-13 06:46:13** You merged [PR 1](https://github.com/pensionsupplysning/web/pull/116) to update Rails
- **2018-02-13 06:47:12** Dependabot created [PR 2](https://github.com/pensionsupplysning/web/pull/118), based off of `9c9347`

Surprisingly, as a result of the above, GitHub returns a different commit SHA for the base of the PR (`71a10f` - see [this API response](https://api.github.com/repos/pensionsupplysning/web/pulls/118)) to the parent of the commit the PR is based off of (`9c9347` - see [this API response](https://api.github.com/repos/pensionsupplysning/web/pulls/118/commits)). Dependabot correctly stores `9c9347` in its database, but then erroneously was checking whether the PR was up-to-date with master using the `71a10f` response from GitHub.

The fix on Dependabot's side is to use the commit SHA in its database when checking if a PR is up-to-date (now implemented) but I can't help but think the above is a GitHub bug. I see no reason why the same PR created before / after some other commit on master should have a different base commit.

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#411
