### ISSUE TITLE
Sanitize github absolute links in Changelogs

### ISSUE THREAD

**Issue by marcandre** [dependabot/feedback#871]
Please sanitize absolute github URLs in Changelogs.

Maybe I should simply use `[#139]` instead of the full link, but I included `https://github.com/marcandre/backports/issues/139` in the Changelog of `marcandre/backports` and got a whole bunch of back-references in https://github.com/marcandre/backports/issues/139.

I was happy to see from #556 that it is the intent of Dependabot *not to* have all those backrefs created.

**Comment by feelepxyz** [comment]
@marcandre thanks for reporting! Looks like this was due to old changelog being in rdoc. Will take a look at fixing this.
