### ISSUE TITLE
Consider allowing to use .yaml instead of .yml as file extension

### ISSUE THREAD

**Issue by localheinz** [dependabot/feedback#874]
According to [Wikipedia](https://en.wikipedia.org/wiki/YAML), the

> ... official recommended filename extension for YAML files has been `.yaml` since 2006.

Last time I checked, it was not possible to use `.yaml` as file extension for the [Dependabot configuration file](https://dependabot.com/docs/config-file/).

GitHub Actions allows to use `.yaml` files.

I'm aware that this is probably not a very important issue, and I'm aware that this might cause issues, such as

- what should be done when people provide both `.dependabot/config.yml` and `.dependabot/config.yaml`

but I'm a bit curious - have you considered allowing users to use `.yaml` as file extension?

**Comment by feelepxyz** [comment]
@localheinz this should already work 🙌 (although not reflected in the docs)

**Comment by localheinz** [comment]
Thank you, @feelepxyz!
