### ISSUE TITLE
Feature Request > Vulnerabilities detection even without remediation

### ISSUE THREAD

**Issue by adriens** [dependabot/feedback#88]
When i did benchmark dependencies monitoring services, i did give a try for my open source projects. Still today, the service is running on some.

Still we did subscribe ```dependabot``` as it was better matching our requirements.

This morning i got an interesting alert on this service which is [Snyk](https://snyk.io/):

![selection_002](https://user-images.githubusercontent.com/5235127/42658889-603bc46c-8672-11e8-8df3-e9ac92efe62a.jpg)

...telling me that there is a vulnerability...but that there is (for now) no fix available. 

I think that this would be a great feature so we could have actions to prevent intrusions : what do you think about that ?

**Comment by greysteil** [comment]
Interesting. Dependabot really only has its toe in the water of the security world at the moment, and I agree there's lots more we could do here. I want to integrate with a couple more vulnerability alert services first, but once that's done I'm 👍 on creating issues for unremediated security vulnerabilities.

Watch this space!

**Comment by adriens** [comment]
Sute i keep watching this space. I know that customers always ask for more. But just to let you know : we're really happy with this service, constantly improving and providing great and positive feedback on our feature requests...even sometimes with rocket time implementations !

Thanks a lot guys !

**Comment by sundarpsm1986** [comment]
+1

**Comment by greysteil** [comment]
Closing as this is now the responsibility of GitHub Security Alerts (and we're working with that team to keep improving them). 🙂
