### ISSUE TITLE
Update time support

### ISSUE THREAD

**Issue by toshimaru** [dependabot/feedback#88]
Following https://github.com/dependabot/feedback/issues/83#issuecomment-365683003

We can’t know when the update job will be started on the UI. It’d be great if we could see update time and the time is configurable.

I’m using dependabot for update and CircleCI for CI. The repos are private, so the CI container is limited. However, dependabot creates many pull requests and occupies my CI containers. If I could configure the update time to each repos, the CI jobs can be distributed.

**Comment by toshimaru** [comment]
Is it planning to be released?? 

I currently configure the update monthly to prevent it from bumping up automatically.

**Comment by greysteil** [comment]
I haven't had a chance to make the general changes yet (adding a UI), but if you'd like me to update the time Dependabot runs on your account manually I can do that for you - what time would be best?

**Comment by toshimaru** [comment]
@greysteil 
Thanks :)
I've sent time change request to the support email address( support@dependabot.com ).

**Comment by greysteil** [comment]
Great - I've manually updated your account.

**Comment by greysteil** [comment]
You can now set the time Dependabot runs on your account in your settings 🎉.
  
![image](https://user-images.githubusercontent.com/1144873/37255393-c0887328-2543-11e8-9798-36eb348a28ca.png)

**Comment by toshimaru** [comment]
@greysteil Great feature. Thanks a lot! 🎉 💯
