### ISSUE TITLE
Question about multiple target branches

### ISSUE THREAD

**Issue by dmitrykovaltsov** [dependabot/feedback#889]
Many thanks for your work guys. It's amazing tool helps me as well. I have faced with situation when I should update a couple of branches at one time. Any thoughts how I can do it? For example I have got one updated dependence, so is it possible to have 1 pull request to develop branch and 1 to master at one time?Thanks!

**Comment by feelepxyz** [comment]
@dmitrykovaltsov you can set up dependabot to monitor multiple branches and it will open pull requests against each one. Although the target and source branch needs to be the same so you can't go from one to many targets.

You can set up the same project twice with a different `target_branch` (same package manager and direcory) https://dependabot.com/docs/config-file/#target_branch

**Comment by dmitrykovaltsov** [comment]
@feelepxyz Thank you so much! It's a pity that I couldn't find out it by myself 🙄. It's definitely resolve my issue.
