### ISSUE TITLE
Feature: Docker commit message scoping | multi stage support(?)

### ISSUE THREAD

**Issue by exactlyaron** [dependabot/feedback#89]
Hi,

Would it be possible to add scoping to the commit message for Docker updates.  Similar to [this](https://github.com/dependabot/feedback/issues/53) request?  

We have a base image of [Tymly](https://github.com/wmfs/tymly-base) that contains the [stuff](https://github.com/wmfs/tymly-base#what) to make a runnable Tymly.  I'm using the above scoping request [here](https://github.com/wmfs/tymly-base/blob/master/.releaserc.json#L6) so when Dependabot updates one of the packages, [semantic-release](https://github.com/semantic-release/semantic-release) triggers a release during the Travis build and also [tags](https://github.com/wmfs/tymly-base/blob/master/.releaserc.json#L32) the Docker image with the new [version](https://hub.docker.com/r/wmfs/tymly-base/tags/).

This base image is used for functional product builds, essentially you just have to [garnish](https://github.com/wmfs/tymly-base#garnish) it with blueprints.

So an example Dockerfile would look like this...

```dockerfile
#First build
FROM wmfs/tymly-base:1.1.4 AS build
ARG NPM_TOKEN
COPY . .
RUN echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && \
    npm install --production && \
    rm -f .npmrc
# Second build
FROM wmfs/tymly-base:1.1.4
COPY --from=build . .
CMD ["node", "./node_modules/@wmfs/tymly-runner/lib/index.js"]
```

Ideally when a new version of the base image is published then this Dockerfile is updated and a release of the new product occurs containing the new base components. 

As before using [semantic-release commit analyzer](https://github.com/semantic-release/commit-analyzer) is used to define release rules for the dependencies in the package.json and it could also be used to trigger a release of the product build when tymly-base image version is updated by Dependabot.

The release rule could look like this if scoping such as 'docker' was added to the commit message

```bash
"analyzeCommits": {
    "preset": "angular",
    "releaseRules": [
      {"type": "build", "scope":"deps", "release": "minor"}
      {"type": "build", "scope":"docker", "release": "minor"}
    ]
  }
```

The multi-stage build is used because a product build may contain blueprints which are published privately to npm.  In order to get them into the build a .npmrc file is required with an npm token.  The above method follows @alulsh [guide](https://www.alexandraulsh.com/2018/06/25/docker-npmrc-security/) for securely using .npmrc files within a Docker image.  So both FROM images would need to be updated by Dependabot, if this doesn't already occur.

Thanks! 👍

**Comment by exactlyaron** [comment]
Actually...  

So this was all based on the [example](https://github.com/ulgens/ubuntu-python3-nodejs/pull/2) you sent me, and not using a conventional commit message... I'm guessing now this was because Dependabot bot didn't recognise the repo used that format? 

As tymly-base was just updated and on a build Dependabot did the following commit...

```bash
build(deps): bump wmfs/tymly-base from 1.1.4 to 1.2.0
```

:tada:

And it even did both images in the Dockerfile!  

![image](https://user-images.githubusercontent.com/10635652/42688281-8e26c478-8693-11e8-98e7-642cb3d699e5.png)


I can live with that scoping.   :sunglasses:


I shall sheepishly close this and bow down to our dependabot overlord.

**Comment by greysteil** [comment]
🤖
