### ISSUE TITLE
Throttle PR submission

### ISSUE THREAD

**Issue by mtsmfm** [dependabot/feedback#89]
Hi dependabot team,

We're using premium plan and we really love dependabot ❤️ 
It really helps us a lot!

However, we're facing CI queue congestion problem because dependabot sends a lot of PR at once.
Could you throttle PR submission?

**Comment by greysteil** [comment]
Great to hear! We don't have a way to throttle PRs, but I can set what time they're created for you. Is there a time that your CI would otherwise be low volume?

**Comment by mtsmfm** [comment]
@greysteil Can you set 0 AM UTC on every Sunday?

**Comment by greysteil** [comment]
Frustratingly, weekly updates currently have to happen on a Monday (UTC-time), so I can set you any time between 9 AM JST Monday to 9AM JST Tuesday.

(I'm not happy with that constraint, and want to make some changes so I can at least offer you 0AM JST to 23:59PM JST, but it will require some code changes and I'd rather get a temporary fix for you deployed in the meantime.)

**Comment by greysteil** [comment]
Done. Closing, but I'll keep working on making Dependabot better on this.

:octocat:

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#413
