### ISSUE TITLE
Bundle multiple dependency upgrades into one

### ISSUE THREAD

**Issue by hendrikhalkow** [dependabot/feedback#892]
In our project, we use semantic release. Every commit on the master branch results in a new release. We prefer using [GitHub Flow](https://guides.github.com/introduction/flow/) over Git Flow. Now every dependency upgrade in results in a new release. While might is OK for microservices that we build, it's very annoying for libraries that are used by these services because each release would trigger another PR in every component that has the just updated component as a dependency.
Having that said, my feature request is to provide the ability to bundle multiple dependency updates into one. This could work as follows:

- Dependabot checks the dependencies of the repository as it already does. If there is no or exactly one dependency upgrade, Dependabot works as it already does
- If there are at least two dependencies (the threshold should be configurable), Dependabot switches to a Git flow like mode by creating a `dependabot` branch. All PRs go to that branch instead of the default branch
- After collecting dependency upgrades on that branch – the collecting time should be configurable, too – a PR from into the default branch will bundle all these upgrades into a single PR, which will result in a single new release

**Comment by jurre** [comment]
Thanks @hendrikhalkow, this is definitely on our radar, see https://github.com/dependabot/feedback/issues/5.

Currently the team is pretty busy integrating and scaling up dependabot for GitHub.com so it might be a while before we get to this feature.

I'm going to close this issue as a duplicate but please follow #5 for updates on this.
