### ISSUE TITLE
Javascript: Access issue with public repository

### ISSUE THREAD

**Issue by hauke-altmann-as** [dependabot/feedback#9]
When trying to let Dependabot scan Javascript dependencies in a private project, I get an error: 

> Dependabot couldn't resolve your project's dependencies as it couldn't access _glasse_

I wonder if this is a bug as the repository _glasse_ is public (https://github.com/aboutsource/glasse) or if it is necessary to change the way the dependency is added to package.json

``` 
"dependencies": {
    "glasse": "git+ssh://git@github.com/aboutsource/glasse.git#2.3.0",
  },
```

**Comment by greysteil** [comment]
Thanks for the heads up - I’ll take a look

**Comment by greysteil** [comment]
Ah, I think this is going to be because it's using ssh - if you change that to use ssl it will work.

However, Dependabot ought to be able to do better here - I'll get this fixed.

**Comment by greysteil** [comment]
Should now be fixed. 🎉

**Comment by hauke-altmann-as** [comment]
Works. Thanks a lot!
