### ISSUE TITLE
Python dependencies failing

### ISSUE THREAD

**Issue by gotcha** [dependabot/feedback#90]
I get the message below from dependabot on 
https://github.com/collective/collective.redirectacquired/blob/master/requirements.txt

> Dependabot can't evaluate your Python dependency files.
> As a result, Dependabot couldn't check whether any of your dependencies are out-of-date.
> The error Dependabot encountered was:
> Illformed requirement ["==2013b0"]

even though ```pip install -R requirements.txt``` works perfectly (I have tried only with pip 10.0.1)

**Comment by greysteil** [comment]
Huh, that looks very wrong. I'll take a look!

**Comment by greysteil** [comment]
Fixed by https://github.com/dependabot/dependabot-core/commit/281abd125a50cb5e17816ed29db721bcd7bd4c1e.

**Comment by gotcha** [comment]
Thanks for the quick fix.

@greysteil Do you support parsing `requirements.txt` which includes with `-r other_req.txt` ?

**Comment by greysteil** [comment]
Yep, absolutely - looks like some of the PRs generated were to your `nitpicker.txt` file because it was required in (it wouldn't have been picked up otherwise). We also support updating `pip-compile` files (and will regenerate your `requirements.txt` from them) and Pipenv.
