### ISSUE TITLE
Recurrent vulnerability notification for a dependency in a non-existent yarn.lock

### ISSUE THREAD

**Issue by jeremija** [dependabot/feedback#901]
I keep getting a vulnerability notification for a dependency in a non-existent `yarn.lock` file in [jeremija/peer-calls](https://github.com/jeremija/peer-calls). This file did exist at some point, but we've switched to package-lock.json since.

As expected, when I click on the link the file is not found: https://github.com/jeremija/peer-calls/blob/master/yarn.lock

![image](https://user-images.githubusercontent.com/1489493/78422004-8776cc80-765c-11ea-8023-8f9180655e52.png)

**Comment by brrygrdn** [comment]
Hi @jeremija, I had into this, and it seems we had a delay in detecting the removal of that yarn.lock file which is why you got an alert on it.

I've verified that everything looks correct now and you shouldn't get any more spurious alerts on this file, sorry for the hassle.

**Comment by jeremija** [comment]
Thanks for fixing it!
