### ISSUE TITLE
Dependabot screwed up on updating Microsoft.CodeAnalysis.FxCopAnalyzers.

### ISSUE THREAD

**Issue by AraHaan** [dependabot/feedback#906]
First create a c# .net core project (3.1 should work on .net core version).
Second install this version of that nuget package and then run dependabot:
 ``3.0.0-beta4.20207.4+07df2f07``

Notice that the end results are similar to this.
https://github.com/Elskom/zlib.managed/pull/40/files

Also talked about it in the C# discord server as well:
```
Magic Mage Today at 3:09 PM
uh I think something bugged the heck out.
https://github.com/Elskom/zlib.managed/pull/40/files
anyone seen this sort of issue with nuget before?
\`\`\`diff
- <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0-beta4.20207.4+07df2f07">
+ <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.0.0-beta4.20209.1+1b6fbe0e+3.0.0-beta4.20209.1+1b6fbe0e">
\`\`\`
Pyrobolser Today at 3:10 PM
wdym?
That's dependabot, it's a bot that reminds you to update your dependencies
Magic Mage Today at 3:11 PM
that changed causes build to fail saying it is invalid because it duplicated the whole dependency version twice
never seen it fuck up so badly
Pyrobolser Today at 3:12 PM
Oh you mean in the actual change it did
Magic Mage Today at 3:12 PM
yes
Pyrobolser Today at 3:12 PM
I thought you meant the actual github issue :smile:
Magic Mage Today at 3:12 PM
it should be \`\`3.0.0-beta4.20209.1+1b6fbe0e\`\` not \`\`3.0.0-beta4.20209.1+1b6fbe0e\`\` + \`\`3.0.0-beta4.20209.1+1b6fbe0e\`\`
Pyrobolser Today at 3:12 PM
Yeah looks like it had a little copy/paste demon
Magic Mage Today at 3:12 PM
:laughing:
```

**Comment by AraHaan** [comment]
@feelepxyz, @hmarr Any idea why this seems to happen to every last one of my nuget packages (all 14 of them)?

**Comment by AraHaan** [comment]
@gregose, @nmeans any idea why this happens still? I still happens even when on a now newer release. I know the problem is probably discovered thanks to my ``nuget.config``. If needed you guys can create a test case from it too.

**Comment by feelepxyz** [comment]
@AraHaan not sure what's happened here. Will take a look.

**Comment by AraHaan** [comment]
@feelepxyz is it safe to recreate the pr that dependabot made while it was broken?

**Comment by feelepxyz** [comment]
I've run into a snag deploying this, hopefully out later today/tomorrow

**Comment by AraHaan** [comment]
ah ok

**Comment by feelepxyz** [comment]
@AraHaan hey it should be deployed now. Could you try recreating the update?

**Comment by AraHaan** [comment]
Sure.
