### ISSUE TITLE
An API

### ISSUE THREAD

**Issue by WyriHaximus** [dependabot/feedback#91]
An API to add/list/delete repositories. I have a ton of open source packages I like to bulk add them though an API instead of doing 100+ packages through the webUI :zipper_mouth_face: .

**Comment by greysteil** [comment]
Thanks for the request! Adding an API is a bit heavy duty for this, given that it's the first time I've received the request, but if you email the full repo names (account/name format) and the setup you'd like for each one then I'll read whatever pseudo-code you send over and convert it to something I can run in a console on our side 😄.

**Comment by WyriHaximus** [comment]
I'll compile and list and email it to the support email address later today 👍 .

**Comment by greysteil** [comment]
This issue was moved to dependabot/dependabot-core#415
