### ISSUE TITLE
Skipped GitHub Actions jobs prevent automatic merging of PRs

### ISSUE THREAD

**Issue by scothis** [dependabot/feedback#910]
We've been happily using Dependabot's auto merge capability after CI has passed and the PR is approved. GitHub Actions recently started to report the status of jobs that were conditionally skipped for the workflow. PRs with these skipped jobs no longer automatically merge.

For example, this PR is approved and CI passed, but it has not merged:

https://github.com/projectriff/builder/pull/303

(note that I manually merged after 4 days where Dependabot should have merged)

Other PRs without skipped jobs continue to merge as expected:

https://github.com/projectriff/streaming-http-adapter/pull/45

**Comment by PurpleBooth** [comment]
This seems to be effecting me too. It seems to be a relatively recent change.

**Comment by AlCalzone** [comment]
I've wondered about this aswell. Here's an example where even a merge comment doesn't do anything:
![grafik](https://user-images.githubusercontent.com/17641229/80349136-18f9e880-886f-11ea-8c05-1de3b5ddf065.png)

**Comment by tsimbalar** [comment]
We have observed this behavior as well in our organization.

It seems to have started at the very end of the month of April , when "automatic PR review assigment" finally started to work for dependabot's PRs , but telling "squash and merge" would not merge the PR.

**Comment by tsimbalar** [comment]
Just to link issues together, this seem to be similar to https://github.com/dependabot/feedback/issues/948 as well

**Comment by feelepxyz** [comment]
Pushed a fix for merging/automerging when there are skipped check runs. Rolling out fix for both versions of Dependabot.
