### ISSUE TITLE
Avoid notifications on automerged deps

### ISSUE THREAD

**Issue by Jym77** [dependabot/feedback#92]
Hmm. Not sure how much of this is within dependabot hands, and how much is Github config or stuff…

Anyway, I'm watching my repos and thus get notifications when stuff happens on them. When dependabot automerges something, It still creates a PR (to run the tests), and merges it. Which in turn means that I'm getting notification mails for something that is not that important.

Especially, it's something that does not require any action on my side (dependabot does everything) and there is no way (I may be wrong) to see from the mail subject that this is a "no action" notification and not something I need to act on. And even just looking at the conversation requires a bit of work because the initial mail (with the PR) is the same and only the next one will tell me that dependabot merged the PR. So it's "click, scroll, read, delete" Not much work but still enough to make it annoying when multiplying by the number of repos and deps (with ~10 repos and 2 to 5 bumps per week, that's already 20 to 50 mails to process every Monday… and 10 repos is only a small subset of the company, we're still only testing dependabot).

Ideally, I'd like to not receive the PR mails about these. Maybe just a "hey, dependabot bumped something" mail, but even that is no that much necessarily for me (and when we're talking about deps that update almost daily (boto3…) and that we use on ~10 repos, the automerge can generate a lot of spam).

I guess that shutting down these mails completely is not really possible due to Github config (it's Github who sends me the notifications, not dependabot…) Maybe there are some arcane Github options that can allow that (as in "notify me except for PR tagged as 'silent'"), I'm no Github expert.

Another way that could ease that would be to have dependabot put in the PR name an '[auto]' tag or something similar. That way, I'll get mails with subject "[myrepo] Bump foo" and "[myrepo] [auto] Bump bar" and know which ones require action. That might get into another issue when the build (and thus the automerge) fails and actual action is required but I won't see it immediately (believing that this is an automerge and everything is done)… So maybe it's not such a good way to handle that…

Anyway, if a solution can be found to reduce the 'spam' generated by the notifications that don't require action on my side, I'd appreciate :-D

**Comment by simlu** [comment]
FYI We use a gmail filter. It works reasonably well, but has it's limit.

**Comment by ndabAP** [comment]
Found this issue and also wanted to say that this is really annoying when you have a lot of repositories.

**Comment by feelepxyz** [comment]
@ndabAP no worries! I've semi-successfully used this search in Gmail: `from:(dependabot[bot]<notifications@github.com>) Merged into master` to archive automerged updates. Doesn't always seem to match on this though, not sure why.

If you need more advanced filtering maybe a google app script could do the trick? (Only just came across this so haven't had a chance to try it myself)
https://developers.google.com/apps-script/advanced/gmail
