### ISSUE TITLE
[Node] 'null' version string in beta, preview releases

### ISSUE THREAD

**Issue by kazazes** [dependabot/feedback#922]
**Package manage/ecosystem** javascript, yarn

**Manifest contents prior to update**
```diff
{
  "dependencies": {
-   "@prisma/client": "2.0.0-beta.2",
+   "@prisma/client": "2.0.0-previewnull-1",
  }
}
```

**Updated dependency** [Prisma client](https://www.npmjs.com/package/@prisma/client) 

**What you expected to see, versus what you actually saw**
```diff
{
  "dependencies": {
-   "@prisma/client": "2.0.0-beta.2",
+   "@prisma/client": "2.0.0-beta.3,
  }
}
```

**Images of the diff or a link to the PR, issue or logs**

[Lockfile diff](https://gist.github.com/kazazes/a9f4a8bca16872b8c05c8cc299415656).

**Comment by kazazes** [comment]
@jurre missed that! However, that release is 2 months old. Shouldn't dependabot have bumped beta.2 to beta.3 rather than previewnull-1?

**Comment by hmarr** [comment]
> @prisma/client isn't deprecated. GH releases, npm. IIRC prisma-cli was deprecated in favor of the namespaced @prisma/cli.

@jurre was suggesting that the version with the bad version string (`2.0.0-previewnull-1`) be marked as "deprecated" on npm, as Dependabot will automatically ignore npm package versions marked as deprecated. This was already done from [some other packages](https://www.npmjs.com/package/@prisma/cli/v/2.0.0-previewnull-1) that were also published with the broken version string.

**Comment by kazazes** [comment]
@hmarr @jurre, got it. Thanks. Love @dependabot. 

@timsuchanek 🙏 deprecate.
