### ISSUE TITLE
Leaves code un-`go fmt`'ed after bumping version in go.mod

### ISSUE THREAD

**Issue by antifuchs** [dependabot/feedback#924]
I'm seeing a problem (not unlike #909, but different) where bumping a revision in go.mod leaves the code in an un-`go fmt`ed state. The offending PR is:

* https://github.com/antifuchs/htpasswd-login/pull/15

This is failing CI checks because there's a test that ensures that the checked-in version of the code is the same as would have been generated by `go generate` and `go fmt`. There, it looks like `go fmt` [removes a line from go.mod](https://github.com/antifuchs/htpasswd-login/pull/15/checks?check_run_id=621253224#step:6:14) - the errors dependency that has been upgraded in go.sum.

**Package manage/ecosystem**
go.mod
**Manifest contents prior to update**
* [go.sum](https://github.com/antifuchs/htpasswd-login/blob/d06ea9887190f72acc8cc36d5e4ce48bcb67d33e/go.sum)
* [go.mod](https://github.com/antifuchs/htpasswd-login/blob/d06ea9887190f72acc8cc36d5e4ce48bcb67d33e/go.mod)

**Updated dependency**
github.com/gorilla/csrf from 1.6.2 to 1.7.0 
**What you expected to see, versus what you actually saw**
I would expect [the indirect `errors` line in go.mod](https://github.com/antifuchs/htpasswd-login/blob/d06ea9887190f72acc8cc36d5e4ce48bcb67d33e/go.mod#L10) to be dropped.
**Images of the diff or a link to the PR, issue or logs**

* PR: https://github.com/antifuchs/htpasswd-login/pull/15
* CI failure: https://github.com/antifuchs/htpasswd-login/pull/15/checks?check_run_id=621253224#step:6:14
* Repro:
  1. check out the branch
  2. run `go fmt && git diff` - shows a diff of one line.

**Comment by hmarr** [comment]
Thanks for reporting this. I've got a potential fix in https://github.com/dependabot/dependabot-core/pull/1852. We'll get it shipped next week.

**Comment by antifuchs** [comment]
Amazing, thank you!

**Comment by hmarr** [comment]
The fix went out and I just reproduced your setup and confirmed that it's working in production ([example PR](https://github.com/hmarr/dbot-go-mod-cleanup-test-20200513/pull/1/files)).

Thanks for the detailed bug report - it helped hugely in reproducing and fixing the issue.

**Comment by antifuchs** [comment]
Thanks so much for the speedy fix! 

How can I get dependabot to recreate the PR with the fixed code? I tried `@dependabot recreate` a few times, and while it claimed to be rebasing, it didn't change the diff.
