### ISSUE TITLE
[C#] Add option to bundle all updates together to single pr.

### ISSUE THREAD

**Issue by AraHaan** [dependabot/feedback#930]
I would like an option where the user could have the updates bundled all together.

Also maybe an option where we can explicitly define the update chain like so:
![image](https://user-images.githubusercontent.com/15173749/81282814-b3092000-9029-11ea-9f5b-7f9cedceef30.png)
Where it would bundle the updates to the ``Level 0`` API (lowest levels of my apis) first, then wait till those packages are published to 1 of the feeds used on checking the updates, then go in work the way up the ``Levels`` of apis until the last level of it is done.

Sadly each of them for me are in separate github repositories and uses github actions where every direct push gets published to nuget. Going to work out the issue where branches made by dependabot results in a publish before it opens the pr. It is probably a simple github action patch.

**Comment by jurre** [comment]
Hi @AraHaan, this is definitely on our radar as more people have asked for this feature, see https://github.com/dependabot/feedback/issues/185 for example.

The team is currently working hard on integrating dependabot with GitHub natively, so it will be some time before we can get to updates like these.

I'm going to close out this issue in favor of the one I linked to.

**Comment by AraHaan** [comment]
ah I see, somehow github did not tell me it was a duplicate.
