### ISSUE TITLE
Unclear interaction between "Only lockfile updates" vs. "Only security updates"

### ISSUE THREAD

**Issue by benthorner** [dependabot/feedback#937]
On GOV.UK we've been exploring ways to reduce the volume of Dependabot updates. In the Dependabot UI there are two options, which can both be enabled simultaneously:

- "Only security updates"
- "Only lockfile updates (ignore updates that require Gemfile changes)"

I think this corresponds to the following pieces of config:

```
allowed_updates: [{ match: { update_type: "security" } }]
version_requirement_updates: "off"
```

What happens if a security update conflicts with the pinned version of a dependency? Does the security update take precedence over `version_requirement_updates: "off"`?

**Comment by feelepxyz** [comment]
> I think this corresponds to the following pieces of config:
> 
> ```
> allowed_updates: [{ match: { update_type: "security" } }]
> version_requirement_updates: "off"
> ```

👍 

> What happens if a security update conflicts with the pinned version of a dependency? Does the security update take precedence over `version_requirement_updates: "off"`?

They both apply, so if you set `version_requirement_updates: "off"` and the security update requires an update to the manifest, e.g. `Gemfile` or `package.json` to update the version requirement it won't update and log error "Update not possible".

Security only will only attempt to update currently vulnerable dependencies and then get blocked if it requires a version requirement update in the manifest.

We're hoping to start improving the volume issue soon but have been busy integrated Dependabot natively in GitHub.

**Comment by benthorner** [comment]
Good to know - thanks for explaining @feelepxyz!
