### ISSUE TITLE
HTTP 502 error reported as malformed go.mod.

### ISSUE THREAD

**Issue by jmalloc** [dependabot/feedback#938]
Dependabot created https://github.com/dogmatiq/dogmavet/issues/27 to report a malformed `go.mod` file, but the error appears to be related to communicating with GitHub servers, or possibly `http://gopkg.in`.

**Package manage/ecosystem**

Golang

**Manifest contents prior to update**

[go.mod @ 23e713d](https://github.com/dogmatiq/dogmavet/blob/23e713d6849a68d7208b3aadb77f623f6a0d9a01/go.mod)

**What you expected to see, versus what you actually saw**

Assuming this would have been retried, I would expect for this issue not to be opened at all.

Thankyou :)

**Comment by thepwagner** [comment]
👋 we fixed this in https://github.com/dependabot/dependabot-core/pull/1873 , it should be available in https://github.com/dependabot/dependabot-core/releases/tag/v0.117.10

Thanks for the clean report and linking to your issue, it made reproducing this a breeze!

**Comment by jmalloc** [comment]
That's great, thank you :)
