### ISSUE TITLE
Wrong "Changelog" link

### ISSUE THREAD

**Issue by sobolevn** [dependabot/feedback#94]
Today I have received this PR from dependabot: https://github.com/wemake-services/wemake-django-template/pull/220

Everything is fine except the `Changelog` link. It links to the https://github.com/zheller/flake8-quotes/blob/master/release.sh for some reason.

**Comment by greysteil** [comment]
Oops! Thanks for the heads up - fixed in https://github.com/dependabot/dependabot-core/commit/ab193cf7211d1cd0c1fb25b2a787245bddce68c0. 🎉
