### ISSUE TITLE
Rust project generating failure due to "Error during file fetching"

### ISSUE THREAD

**Issue by mikeando** [dependabot/feedback#940]
Dependabot is generating an issue in my repository with the title "Dependabot can't parse your Cargo.toml" - the log suggests the root cause is something else though, it ends with

```
...
  proxy | 2020/05/23 07:54:29 * authenticating github api request
  proxy | 2020/05/23 07:54:29 200 https://api.github.com:443/repos/mikeando/markovian/contents/markovian-cli/Cargo.toml?ref=fa5df5c437b3310b25c2dbf148baac04a264acef
fetcher | ERROR <job_34277781> Error during file fetching; aborting
fetcher | INFO <job_34277781> Finished job processing
```

The job fails, and doesn't generate any dependency updates, just that one issue about an unparsable `Cargo.toml`.

The github repository is https://github.com/mikeando/markovian, the failure message is at https://github.com/mikeando/markovian/issues/1.

The code is rust - structured as a root package with 3 sub-packages. 

This was working on a private repository with the same structure - until a day or so ago (the code in that repository hasn't changed in months) - when it generated the same issue. (I thought it possible a transient network issue and did not report it)

Thanks.

**Comment by feelepxyz** [comment]
@mikeando hm the error isn't great! Looks like there some weird character on line 15 here https://github.com/mikeando/markovian/blob/master/markovian-cli/Cargo.toml#L15 - it's tripping up the Toml parser.

**Comment by mikeando** [comment]
I removed that final character in the .toml file (which I assume was some odd Unicode value,  but was displaying as a space in my editor)  and it looks like dependabot picked it up correctly,  as I've got a few new pull requests. 

Thanks
