### ISSUE TITLE
"Dependabot only supports uninterpolated string arguments to eval_gemfile. Got `file`"

### ISSUE THREAD

**Issue by AtomicLemon** [dependabot/feedback#945]
Hi everyone! I get this error when dependabot tries to parse my Gemfile. Does anyone have any ideas on what could be happening?

Dependabot couldn't parse the Gemfile found at `/Gemfile`.
The error Dependabot encountered was:
```
Dependabot only supports uninterpolated string arguments to eval_gemfile. Got `file`
```

**Comment by feelepxyz** [comment]
@AtomicLemon could you send a portion of your `Gemfile` where you call `eval_gemfile()`? We've explicitly disabled interpolated string arguments here, e.g. `eval_gemfile("#{file_name}")`

**Comment by AtomicLemon** [comment]
This is it:
```ruby
# Load gems from Gemfile.plugin.
#Dir.glob File.expand_path('../Gemfile.plugin', __FILE__) do |file|
#  eval_gemfile file
#end
```

It is commented out, so it shouldn't be causing the problem right?

**Comment by feelepxyz** [comment]
@AtomicLemon ah yeah that's what's tripping up Depenedabot, our parser is really basic and will most likely not be taking the comment into account 🤦  could you try removing this section entirely?

**Comment by AtomicLemon** [comment]
Ah okay that would be it haha, I'll remove it and close this issue. Thanks for the help!
