### ISSUE TITLE
Error after trying to upgrade to v2 via PR

### ISSUE THREAD

**Issue by caneleex** [dependabot/feedback#947]
**Package manage/ecosystem**
java/gradle
**Manifest contents prior to update**
N/A
**Updated dependency**
N/A
**What you expected to see, versus what you actually saw**
What i expected to see is a repository being listed in the dashboard as my other repositories which i upgraded to v2 successfully, but when i try to add the repo manually from the dashboard i actually get this error: ![error](https://scr.mlnr.dev/2020_06_01_23_36_46.png)

**Images of the diff or a link to the PR, issue or logs**
[Repository](https://github.com/caneleex/Spidey)

I tried [several times](https://github.com/caneleex/Spidey/commits/master) but the repo still wasn't and isn't listed in the dashboard.

**Comment by jurre** [comment]
Hi @caneleex I see that you managed to perform the migration eventually, what did you have to do to make this work?

Eager to learn anything we can do to improve the migration experience!

**Comment by caneleex** [comment]
@jurre Ah, i see. I was just wondering how come that my 2 other repositories are still on the dashboard yet the other one isn't.

**Comment by jurre** [comment]
>  I was just wondering how come that my 2 other repositories are still on the dashboard yet the other one isn't.

You've updated those as well? It could be some caching perhaps, but we're rolling out a change to show a notice on those repo's saying that they were successfully migrated to GitHub, that should make this more clear!

> Also, it was a bit easier to "bulk-bump" repositories to check for updates.

Good question, we don't currently have a good alternative for this, but I'm curious about your usecase, what schedule do you have configured, and what prompts you to "bump now" on all repo's? You can still bump an individual repo on the Dependabot tab, but I can imagine that if you want to do many repo's at once this can be cumbersome. Appreciate your feedback!

**Comment by caneleex** [comment]
When a library that i use releases a new update and i like the new features, i want to implement them asap without having to wait for daily updates at 2PM. The dashboard worked pretty well for such cases as i have multiple repositories using the library.
