### ISSUE TITLE
Dependabot considers skipped runs as failures and does not merge corresponding pull requests

### ISSUE THREAD

**Issue by localheinz** [dependabot/feedback#948]
Dependabot currently complains with the following message

### Message

> One of your CI runs failed on this pull request, so Dependabot won't merge it.
> 
> * Delete
> * Create
> 
> Dependabot will still automatically merge this pull request if you amend it and your tests pass.

![Screen Shot 2020-06-02 at 13 45 28](https://user-images.githubusercontent.com/605483/83516554-93093700-a4d7-11ea-8036-5a159441ae89.png)

### Jobs

However, these jobs have not failed, they have been skipped:

![Screen Shot 2020-06-02 at 13 45 42](https://user-images.githubusercontent.com/605483/83516645-c21fa880-a4d7-11ea-87a0-cde9748ca97a.png)

### Handling

Perhaps something could be done on your end to distinguish between failed and skipped jobs? A skipped job is not necessarily an indication of a failure.

In this particular case, we have jobs that create (or remove) staging environments when a pull request has a specific label added (or removed).

**Comment by feelepxyz** [comment]
Pushed a fix for merging/automerging when there are skipped check runs. Rolling out fix for both versions of Dependabot.
