### ISSUE TITLE
sign-up: How do I choose GitHub Organization?

### ISSUE THREAD

**Issue by olleolleolle** [dependabot/feedback#95]
I'm a GitHub user connected to several GitHub Organizations.

When I clicked "Join" I got placed in one of the orgs without any interstitial choice step.

Now, the org picked for me was not the one I need to use.

- Can I change it?
- Can I get to choose which one to connect my account to?
- Can I have more than one?

**Comment by greysteil** [comment]
Prefix: this is a bit painful, and it's on the GitHub side so not something we can change.

Possible solution: 
- Log into your [Dependabot dashboard](https://app.dependabot.com), click on the drop-down in the top right, and then click "Add account" then you'll be taken to a GitHub screen
- From there, scroll to the bottom, select the setup you want, and click "Try free..." / "Install it for free".
- **On the next screen, under billing information, select the organisation you want to install for.** The name may be greyed out, but you'll still be able to select it.
- Complete the order and you're done

Aside: I noticed your account just triggered a rare access bug, so you'll have been served a 500 at some point in the last hour. I've been waiting 1 month for someone to trigger that, and will be using the debug info to fix it today. Thanks (and sorry)!

**Comment by olleolleolle** [comment]
@greysteil Let's see if I am lucky as I go try this _again_. Thanks for responding.

**Comment by greysteil** [comment]
🤞, and sorry it's such a pain. Working with GitHub to try and improve it.

**Comment by greysteil** [comment]
Hmmm, I've just seen that access bug again, and am wondering if it's specific to this case...

**Comment by olleolleolle** [comment]
(I now located the relevant place to pick Org, and have come into it, instead of coming into that other FOSS org. Currently learning to pick Open Source projects - non-private, for learning to use this thing.)

**Comment by olleolleolle** [comment]
@greysteil My question has been answered, and I need to further assistance on this.

I will close this issue, and wish you good luck!
