### ISSUE TITLE
exclude alpha/beta (Maven?)

### ISSUE THREAD

**Issue by plata** [dependabot/feedback#96]
Is it possible to configure dependabot such that only updates to stable versions are show? If not, would be great to have that option.

We have a suggested update to beta here: PhoenicisOrg/POL-POM-5#1178

**Comment by greysteil** [comment]
Ooh, that's no good. For other languages Dependabot will only suggest you update to a beta if you're already on an alpha. I'll get that functionality implemented for Java tonight / tomorrow.

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/6430fc1c13bb42c011675cf998f2a8f09f301976, which is deploying now. Thanks for the feedback!

**Comment by plata** [comment]
Wow, that was fast!
