### ISSUE TITLE
GitHub action updated to non-existent version

### ISSUE THREAD

**Issue by ondrejmirtes** [dependabot/feedback#965]
`actions/cache@v1.1.2` got updated to `actions/cache@v2.1.2` but that version doesn't exist.

**Comment by feelepxyz** [comment]
@ondrejmirtes thanks for reporting! Looking into it 👌

**Comment by feelepxyz** [comment]
@ondrejmirtes can't seem to reproduce this, wondering the tag was yanked from github? Could you try running `@dependabot recreate` on the PR you received to see if it still applies that version?

**Comment by ondrejmirtes** [comment]
It's a private repo but this is what Dependabot did: https://gist.github.com/ondrejmirtes/3e14f3b2e184864b1a6656f35ed41f00

It chose v2 in some cases but v2.1.2 in others. Maybe you'd have access to some logs to see what was going on?

**Comment by ondrejmirtes** [comment]
Another weird thing - Dependabot keeps opening a new PR in that repo for updating `actions/cache` even if it's already updated on master - notice the conflict:

![Screenshot 2020-06-16 at 19 10 56](https://user-images.githubusercontent.com/104888/84805830-2167d780-b005-11ea-9f41-d6efb6d9f7b8.png)

**Comment by feelepxyz** [comment]
> It chose v2 in some cases but v2.1.2 in others. Maybe you'd have access to some logs to see what was going on?

Oh interesting, that looks like a bug! Could you send over the update id from the logs view URL? You can access the logs from Insights > Dependency Graph > Dependabot and click on `last checked`. The URL should be something like `.../network/updates/31646526`, only need the last ID portion.

**Comment by feelepxyz** [comment]
> Another weird thing - Dependabot keeps opening a new PR in that repo for updating `actions/cache` even if it's already updated on master - notice the conflict:

Will take a look! We have some rough corners on actions updating as we just launched it a week ago.

**Comment by ondrejmirtes** [comment]
I can't give you the ID because in the repo it says "last checked" 12 hours ago in all the entries and the times in the log correspond to that. So there are no more recent entries that actually showed the buggy behaviour.

And the other problem with duplicate and unnecessary PR now started happening in multiple repos. Here's an example from a public one: https://github.com/phpstan/phpstan/pull/3487/files (these files are already on cache v2). And the log also shows "last checked 12 hours ago".

**Comment by feelepxyz** [comment]
Ah ok, this is probably due to a recent change where we fixed a bug creating some actions pull requests which has meant that a bunch of previously failing (old) PRs have now been successfully retired from the failed queue. Sorry about that!

I think you can safely close these bad PRs and should not see them pop back.

We should also be able do a better job to not open PRa with merge conflicts.

**Comment by ondrejmirtes** [comment]
> We should also be able do a better job to not open PRa with merge conflicts.

It would be sufficient to always make sure that you're opening it on the latest master, which wasn't the case here.

> I think you can safely close these bad PRs 

Alright, I'll close them.

What about the v2.1.2 bug, can I close this issue? :)

Anyway, thank you very much and have a nice day :)

**Comment by feelepxyz** [comment]
> What about the v2.1.2 bug, can I close this issue? :)

Still looking into this.

**Comment by ondrejmirtes** [comment]
Thank you! Interesting to see that you manipulate YAML with regexes, a format-preserving YAML printer would come in handy, right :)
