### ISSUE TITLE
Checks not getting triggered. 

### ISSUE THREAD

**Issue by ghost** [dependabot/feedback#967]
**Package manage/ecosystem**
Elixir Mix and JS npm

**What you expected to see, versus what you actually saw**

TBH this looks like an issue with github actions and not Dependabot but I don't know where to start so I figured here. 
Long story short. https://github.com/MorphicPro/morphic.pro/pull/126 Debendabot is making PRs that have checks that never run and because I have locks on my master branch to which the PR's point, the PRs, in turn become stuck because they rely on the checks that never start.  Thus all I can do with these prs is close them or turn off the lock on my master branch :(

**Comment by feelepxyz** [comment]
@joshchernoff looks like the glob here https://github.com/MorphicPro/morphic.pro/blob/master/.github/workflows/CI.yml#L6 isn't matching the dependabot branch names `dependabot/*/*`, some details here: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet 

Changing it to `**` should work 🤞

**Comment by joshchernoff** [comment]
Ah `but does not match the / character` 
You are probably correct, thanks for the good directions. 👋
