### ISSUE TITLE
Sign off commits

### ISSUE THREAD

**Issue by vmarkovtsev** [dependabot/feedback#97]
Would be nice to have the submitted Git commits to be [signed off](https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for). Some projects require PRs to be signed off and this feature would allow Dependabot's commits to pass that check.

**Comment by greysteil** [comment]
Good idea - [done](https://github.com/dependabot/dependabot-core/commit/2f837809e431437e161c3cb86ae7ac3374fd0c85)!
