### ISSUE TITLE
Sign commits with GPG

### ISSUE THREAD

**Issue by shaneog** [dependabot/feedback#98]
I want to enforce GitHub's new [Require signed commits](https://help.github.com/articles/enabling-required-commit-signing/) but Dependabot does not sign its commits.

It would be great to implement this feature!

**Comment by greysteil** [comment]
We actually just started signing our commits! If you've had any PRs this week then they should have been signed 🎉

**Comment by shaneog** [comment]
Wow, that was fast! 👍 
Thank you, that's excellent news!
