### ISSUE TITLE
Dependabot dashboard difficulties when managing large # of repos

### ISSUE THREAD

**Issue by matthewmcgarvey** [dependabot/feedback#98]
- The button to add a repo is at the very bottom.  Could it be added to the top?  The best solution might be making the navbar fixed to the top of the screen despite scrolling so that the button could go there.
- When adding a repo, the dropdown menu to pick a repo seems to be loaded fresh.  That takes quite a while to load when working with large numbers of repos.  That menu should be cached and updated asynchronously.
- To add a repo you have to find it in a dropdown menu.  This is the biggest pain point so far.  Having a text field that provides completion options would solve this much better.
- Having to scroll through the list of all repos added so far to find the one you're looking for.  We haven't added all of our repos yet or else this would be the biggest pain point.  A search bar that filters the list is going to be almost required for us.

**Comment by simlu** [comment]
@matthewmcgarvey We hacked together a quick script that talks to the api directly for this purpose. It's very raw, but should get us through until the ui improves (and ideally we have config files inside the repos at some point!). Reverse engineering wasn't too bad, but it really depends where your pain point is :)

**Comment by greysteil** [comment]
@feelepxyz - you've probably already seen this, but relevant to the recent dashboard changes

**Comment by feelepxyz** [comment]
@matthewmcgarvey @simlu 🎉 we just launched a new view for adding repos in bulk on the
[dashboard](https://app.dependabot.com/) ("Add Repositories" in the top nav)

Let me know if you run into any issues!
