### ISSUE TITLE
Feature Request: Delete branches when closing PRs

### ISSUE THREAD

**Issue by omnibs** [dependabot/feedback#99]
Scenario:
* Dependabot opens a PR to update a dependency
* You leave it there untouched
* Dependabot finds a new update that supersedes the update in that PR
* Dependabot closes the old PR and opens a new one
* The branch for the old PR will stay open

Can we change behavior so Dependabot also deletes the branch when closing the old PR?

**Comment by omnibs** [comment]
Oh, nevermind, sorry for bothering!

My local git's view of the remote that's stale ☺️

**Comment by omnibs** [comment]
btw, such a fast response time omg =o

**Comment by greysteil** [comment]
Haha, well I was just working on another small issue so was easy to jump on this. Thanks for giving Dependabot a try! 😄

**Comment by fbartho** [comment]
I should put `git remote prune origin` into my `postinstall` script, lol
